"""Freeze first Q14 preparation output-precondition failure; preserve earlier helper GO."""
from pathlib import Path
import hashlib,json,os,stat,datetime
Q=Path(__file__).resolve().parent;G=Q.parent;D=G/'final-qualification-inputs-13';B=G/'final-qualification-inputs-11'
assert not(Q/'freeze.json').exists()
def read(p):return json.loads(Path(p).read_bytes())
def pin(p):
 p=Path(p)
 with p.open('rb')as f:h=hashlib.file_digest(f,'sha256').hexdigest()
 return {'path':str(p),'bytes':p.stat().st_size,'sha256':h,'mode':stat.S_IMODE(p.stat().st_mode)}
def put(n,v):
 with(Q/n).open('x')as f:f.write(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
helper=read(Q/'delta-preflight-readiness.json');managed=read(Q/'delta-supervisor-close.json');assert helper['workResult']=='GO_CHEAP_ROLE_AWARE_DELTA_PREFLIGHT'and helper['allNegativesRefused']and len(helper['negatives'])==9
assert managed['exitCode']==0 and managed['wait4Reaped']and managed['groupAfterWait']=='absent'and not managed['timedOut']
trace=Q/'f11/member-alias-trace.json';assert trace.exists()and trace.read_bytes()==(D/'f11/member-alias-trace.json').read_bytes()
assert (Q/'f11/member-alias-context.json').read_bytes()==(D/'f11/member-alias-context.json').read_bytes()
failure={'status':'CLOSED_FIRST_ACTUAL_PREPARATION_REFUSAL','operation':'T287_FINAL_QUALIFICATION_INPUTS_14','workResult':'NO_GO_EXTERNAL_EXISTING_BIJECTION_OUTPUT_PRECONDITION','frontier':'pure owned bijection preparation after actual helper GO, before complete binding/Product imports','owner':'prepare-bijection.py:17','predicate':'assert not (Q/f11/member-alias-trace.json).exists()','actual':'The exact reused C09 alias trace already exists in Q14; an unnecessary create-only regeneration was selected by the local preparation harness.','existingOutput':pin(trace),'copiedDonor':pin(D/'f11/member-alias-trace.json'),'existingBytesUnchanged':True,'sourceRoleAndProductDefectInferred':False,'command':['python3',str(Q/'prepare-bijection.py')],'exitCode':1,'actualStderr':'Traceback (most recent call last):\n  File "'+str(Q/'prepare-bijection.py')+'", line 17, in <module>\n    p=Q/\'f11/member-alias-trace.json\';assert not p.exists();p.write_text(json.dumps(a,indent=2,ensure_ascii=False)+\'\\n\')\nAssertionError\n','ProductImports':0,'RuntimeEffects':0,'noRepairOrRetry':True}
put('first-readiness-refusal.json',failure)
launch=read(Q/'owned-module-launch-binding.json');auth=read(Q/'f11/source-authorship-records.json');assert auth==read(B/'f11/source-authorship-records.json')
manifest=read(Q/'input-manifest.json');priorManifest=read(B/'input-manifest.json');conserved=[]
for name in ['sourceFiles','authoritySources','lawMembers','toolFiles','fixtureFiles','dependencies']:
 assert len(manifest[name])==len(priorManifest[name]);conserved.append({'role':name,'members':len(manifest[name])})
 for current,previous in zip(manifest[name],priorManifest[name]):
  assert {k:v for k,v in current.items()if k!='memberRef'}=={k:v for k,v in previous.items()if k!='memberRef'}
accounting={'cheapActualHelper':managed,'cheapActualHelperPositiveChanges':9,'cheapActualHelperNegativeRefusals':9,'syntaxChecks':launch['syntaxChecks'],'syntaxChecksProductImports':0,'purePreparationFirstFailureExitCode':1,'purePreparationProcessClosure':'exec_command completed, no child/owner payload launched','completeTaskPayloads':0,'packetPayloads':0,'ProductImports':0,'resourceSerializationBytes':None,'assertionSerializationBytes':None,'canonicalEnvelopeBytes':None,'requestOrPromptBytes':None,'qualificationCommandsExecuted':0,'nativeTaskRunJHelperProviderCalls':0,'SourceChanges':0,'builds':0,'candidateChanges':0,'GitEffects':0,'networkEffects':0,'retries':0,'defaultHeap':True,'ordinaryHOME':True}
put('accounting.json',accounting)
result={'status':'CLOSED','role':'Worker','actor':'/root/q03_input_review','operation':failure['operation'],'workResult':failure['workResult'],'ProductFrame':'F-EndToEndInterfaceIntegration; fixed15/GOAL035/T287/F11/F15, STDO2.5.1RC2, unchanged Product/runtime/accepted C09/Setup09; local realization_refactor only','grant':pin(Q/'request.txt'),'currentC09Acceptance':pin(G/'rc1-c09-construction-acceptance-01/acceptance.json'),'actualSetup09Acceptance':pin(G/'rc1-setup09-acceptance-01/acceptance.json'),'donorQ13Freeze':pin(D/'freeze.json'),'donorQ11Freeze':pin(B/'freeze.json'),'actualOwnedModuleCreationAndLaunch':pin(Q/'owned-module-launch-binding.json'),'actualCheapHelper':helper,'actualCheapHelperReceipt':pin(Q/'delta-preflight-readiness.json'),'actualSourceDelta':pin(Q/'f11/current-source-delta.json'),'retainedNineProducerJoin':pin(D/'current-source-delta-correspondence.json'),'firstActualRefusal':failure,'retainedOriginalSourceAuth':{'body':pin(Q/'f11/source-authorship-records.json'),'originalQ11BodyUnchanged':True,'records':174,'chains':23,'spans':90,'retainedQ09':[121,12,46],'sourceAuthorshipTransfer':False,'sufficiency':'unknown','independence':'unknown'},'originalNonRecipeInputConservation':conserved,'completeActualInputIdentityCone':'NOT_REBOUND before first failure; no GO claim','retainedStrictCaller':pin(Q/'f11/ordinary-caller.mjs'),'retainedParentChildDriver':pin(Q/'f11/flow-driver.mjs'),'accounting':accounting,'notReached':['Complete current inventory/protected/recipe/self/Task identity binding','Current prepayload envelope accounting','Actual complete published command Task','Full actual resource/reference-owner preparation and current request/prompt rendering'],'outsideCurrentCandidate':'Root current AGENTS/CLAUDE/integration-frame/HOW notes are external current constraints, outside immutable C09 source bodies; no retroqualification','proofScope':'Absolute helper entry/dependency/argv/cwd/output joins, two syntax checks, actual nine source/copy-role positives and nine nearest negatives passed. Later local output precondition stopped preparation. No owner preparation, semantic assessment or Runtime qualification.','unknowns':['Current complete input/resource/task/request/prompt/envelope readiness','Material/context/applicability/grouping/source attribution/independence','Installed Result/J/foldback/F11/cold/QUAL056/scenarios/AF22/release'],'independentAssuranceClaim':False,'allWritesStopAfterFreeze':True,'consumer':'Root Executive'}
put('worker-result.json',result)
put('closure.json',{'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'closedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'allWritesStopAfterFreeze':True,'noRepairOrRetry':True,'returnsTo':'Root Executive'})
with(Q/'return.md').open('x')as f:f.write('CLOSED Q14: '+result['workResult']+'.\n\nAbsolute owned entry/dependency/argv/cwd/output binding and two actual syntax checks passed. Actual managed cut-specific helper passed9source/role positives and9nearest negatives; exit0, '+str(round(managed['elapsedMs'],3))+'ms, peakRSS'+str(managed['maxRSSBytesMacOS'])+'B, wait4reaped/groupabsent/no timeout.\n\nThe next pure preparation step unnecessarily invoked the inherited create-only bijection writer over the already copied f11/member-alias-trace.json; its absence assertion at line17 refused. Existing trace/context bytes remain unchanged. Input body/source/tool/fixture/law populations and174originalrecords/23chains/90spans are preserved; the complete current recipe/inventory/Task cone was not rebound. No Product import, full materialization/rendering, owner payload, nativeTask/Run/J/helper/provider/Source/build/Git/network/18qualification command. No repair or retry; Root alone selects continuation.\n')
rows=[];directories=[]
for p in sorted(Q.rglob('*')):
 if p.is_symlink():rows.append({'path':str(p.relative_to(Q)),'kind':'symlink','target':os.readlink(p),'mode':stat.S_IMODE(p.lstat().st_mode)})
 elif p.is_file():row=pin(p);row['path']=str(p.relative_to(Q));rows.append(row)
 elif p.is_dir():directories.append({'path':str(p.relative_to(Q)),'mode':stat.S_IMODE(p.stat().st_mode)})
freeze={'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'records':rows,'recordCount':len(rows),'bodyBytes':sum(r.get('bytes',0)for r in rows),'directories':directories,'directoryCount':len(directories),'linkCount':sum(r.get('kind')=='symlink'for r in rows),'noProductOrRuntimeEffects':True,'allWritesStopped':True}
put('freeze.json',freeze);os.chmod(Q/'freeze.json',0o444)
print(json.dumps({'status':'CLOSED','workResult':result['workResult'],'freeze':pin(Q/'freeze.json'),'records':len(rows),'bodyBytes':freeze['bodyBytes'],'directories':len(directories),'links':freeze['linkCount']}))
