"""Bind current external caller inputs; no attribution/native task or worksite."""
import pathlib,json,hashlib,collections
E=pathlib.Path(__file__).resolve().parent;G=E.parent;R=G.parents[3];Q=G/'final-qualification-inputs-01';C=G/'final-candidate-construction-02';T='build_tenants/abiogenesis/typescript/'
read=lambda p:json.loads(p.read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
def record(p):
 b=p.read_bytes();return {'path':str(p.relative_to(R)),'bytes':len(b),'sha256':sha(b)}
def write(n,v):
 with (E/n).open('x') as f:json.dump(v,f,indent=2);f.write('\n')
old=read(Q/'qualification-inventory.json');new=read(E/'qualification-inventory.json');members={r['path']:r for r in new['members']};sources={r['path']:r for r in read(E/'source-inventory.json')};mapping=[]
oldq=str(Q.relative_to(R));newq=str(E.relative_to(R));oldc=str((G/'final-candidate-construction-01').relative_to(R));newc=str(C.relative_to(R))
for before in old['members']:
 oldpath=before['path'];p=oldpath.replace(oldq+'/',newq+'/').replace(oldc+'/',newc+'/');after=members[p]
 if p in sources:origin=pathlib.Path(sources[p]['origin']);kind=sources[p]['role']
 else:origin=R/p;kind='external_control' if p.startswith(newq+'/') else 'supplier_observation_manifest'
 b=origin.read_bytes();assert len(b)==after['byteCount'] and 'sha256:'+sha(b)==after['digest']
 assert before['surfaceRoles']==after['surfaceRoles']
 mapping.append({'kind':kind,'original':before,'successor':after,'successorPhysicalOrigin':str(origin),'byteIdentityPreserved':before['digest']==after['digest'],'logicalPathPreserved':oldpath==p,'scope':'exact member correspondence; not attribution or semantic applicability'})
assert len(mapping)==len(members)==1950 and len({r['successor']['ref'] for r in mapping})==1950
counts=collections.Counter(r['kind'] for r in mapping);assert dict(counts)=={'selected_source':1103,'generated_output':828,'external_control':15,'supplier_observation_manifest':4}
sourcechanges=[r for r in mapping if r['kind'] in ['selected_source','generated_output'] and not r['byteIdentityPreserved']]
expected={T+p for p in ['code/src/gtl/default_library.ts','test_env/tests/t287-default-library.test.mjs','test_env/support/root-installed-environment.mjs','build/code/src/gtl/default_library.js','contracts/capabilities/capability-definition-graph.json','product-toolchain-manifest.json']};assert {r['successor']['path'] for r in sourcechanges}==expected
write('qualification-member-correspondence.json',{'originalInventory':{'ref':old['inventoryRef'],'digest':old['inventoryDigest'],'file':record(Q/'qualification-inventory.json')},'successorInventory':{'ref':new['inventoryRef'],'digest':new['inventoryDigest'],'file':record(E/'qualification-inventory.json')},'counts':dict(counts),'sourceGeneratedChanged':len(sourcechanges),'externalChangedBodies':sum(not r['byteIdentityPreserved'] for r in mapping if r['kind'] not in ['selected_source','generated_output']),'members':mapping,'scope':'Complete old-to-new byte/control correspondence. No original author reassignment or F11 semantic adequacy.'})
for n in ['recipe.mjs','recipe-stage.mjs','compare-generated.mjs','test-environment.mjs','test-selection.json','config.json','release-claims.json','budgets.json']:assert (E/n).read_bytes()==(Q/n).read_bytes()
recipe=read(E/'verification-recipe.json');oldrecipe=read(Q/'verification-recipe.json')
for k in ['sourceInputs','commandConfigurationDigest','predicateConfigurationDigest','writeTerritoriesDigest','lint']:assert recipe[k]==oldrecipe[k],k
cfg=read(E/'config.json');tests=read(E/'test-selection.json');assert len(tests['tests'])==5 and sum(len(t['selectedTitles']) for t in tests['tests'])==30
write('selection-conservation.json',{'status':'passed','testSelection':record(E/'test-selection.json'),'originalTestSelection':record(Q/'test-selection.json'),'config':record(E/'config.json'),'originalConfig':record(Q/'config.json'),'fiveTestCommands':5,'selectedTitles':30,'syntaxFiles':331,'comparisonMembers':925,'commands':13,'predicates':14,'capsAndGraceMs':958000,'commandConfigurationDigest':recipe['commandConfigurationDigest'],'predicateConfigurationDigest':recipe['predicateConfigurationDigest'],'writeTerritoriesDigest':recipe['writeTerritoriesDigest'],'commandsArgumentsEnvironmentBudgetsAndRecipeMeaning':'exactly preserved','scope':'Input conservation only; no test/recipe execution'})
inputs=read(E/'input-manifest.json');names=['input-manifest.json','expected-output-inventory.json','recipe-stage.mjs','compare-generated.mjs','config.json','toolchain.json','npm-toolchain-inventory.json','test-environment.mjs','verification-recipe.json']
targets=[r['target'] for r in inputs['sourceFiles']+inputs['dependencies']]+['recipe/'+n for n in names];assert len(targets)==len(set(targets))==716
staging={'status':'declaration_for_later_genuine_owner_environment_only','inputSelectionFunction':'recipe.mjs selectedFiles()','rootSource':'actual workspaceAuthorityBasis.canonicalRoot from the same genuine A/W consumed by constructObservedProducerTask','runtimeRoot':None,'requiredOrder':['Obtain the genuine existing clean workspace A/W and preserve its owner metadata.','Call selectedFiles(); read and verify ALL 716 immutable input bodies against byte counts/digests before any write.','Resolve every declared target under that same canonical root and confirm ALL 716 destinations are absent before any write; do not overwrite .abiogenesis or other owner metadata.','Only after all byte and target prechecks pass, create required declared parent directories and write each selected body exclusively (wx).','Observe every staged protected file through the actual worksite owner under the same A/W; require exact selected bytes.','Only under a separately supplied genuine current capability grant, call constructObservedProducerTask against that same canonical root and bind the ordinary installed Public producer.'],'targets':targets,'targetNamespaces':['subject/','dependency-inputs/','recipe/'],'ownerMetadataWrites':[],'counterexample':'stageSelectedInputs(root) uses exclusive fs.mkdir(root); calling it unchanged after workspace.create.clean fails EEXIST, and staging elsewhere would not match constructObservedProducerTask canonicalRoot.','retainedHelper':'stageSelectedInputs(absentRoot) remains unchanged as a new-root helper; it is not the selected existing-workspace caller operation.','failure':'Any missing byte, changed byte or existing declared target refuses before selected-input writes. Later native observation/grant failures remain the actual owner outcome.','performed':False}
write('staging-contract.json',staging)
core=read(C/'selected-core.json');I=pathlib.Path(core['packageRoot']);closure=read(E/'current-publication-closure.json');pubs=read(C/'publication-bindings.json');assert len(closure['publicationBindings'])==len(pubs['constructorPopulation'])==11
donor=read(Q/'next-setup-c2-inputs.json');route=donor['existingOrdinaryRoute']
write('next-setup-c2-inputs.json',{'status':'CLOSED_UNBOUND_INPUTS_ONLY','selectedCore':core,'verificationRequest':read(C/'product-verification-request.json'),'historicalOrdinaryRoute':route,'routeLimit':'Historical route files are donors only; Root binds genuine new actor/environment/capability/resource and ordinary supported operations. No moving native03 inputs consumed.','completePublicationInput':{'currentPureConstructorClosure':record(E/'current-publication-closure.json'),'acceptedC02Bindings':record(C/'publication-bindings.json'),'acceptedC02InstalledReview':record(G/'final-candidate-review-02/return.md'),'constructors':pubs['constructorPopulation'],'manifestEquality':True,'count':11,'limit':'Static immutable declaration input; not all-Program or Public admission.'},'producer':{**donor['producer'],'recipeModule':str(E/'recipe.mjs'),'inputStageFunction':'Later caller uses selectedFiles() under staging-contract.json; do not call stageSelectedInputs(existingCleanRoot)','inputSelectionFunction':'selectedFiles()','callerSequence':staging['requiredOrder'],'protectedFiles':716,'sourceFiles':691,'dependencies':16,'recipeFiles':9},'stagingContract':record(E/'staging-contract.json'),'remainingProducerSlots':donor['remainingProducerSlots'],'nativeBindings':{'installedProduct':None,'workspaceBinding':None,'tenantManifest':None},'executionSelectionRefState':'absent','prohibitedSubstitutes':['No physical-ready JSON as nominal permission or admitted ProductInstall','No direct/private ABG admission helper as ordinary Public setup','No old ten-publication setup array','No synthetic A/W or actor/grant in actual slots','No old native history transplanted to C02'],'currentEffects':'No staging, observations, task/grant construction, Public/native calls or recipe/test execution.'})
catalog=read(I/'contracts/qualification/rule-catalog.json');law=read(I/'contracts/qualification/law-basis.json');coverage=read(I/'contracts/qualification/coverage.json');assert len(catalog['rules'])==2137 and len(catalog['sources'])==95 and len(coverage['claims'])==16 and sum(len(r['behaviors']) for r in coverage['claims'])==66
part=read(Q/'qualification-partition-inputs.json');part['inventory']={'ref':new['inventoryRef'],'digest':new['inventoryDigest'],'file':record(E/'qualification-inventory.json'),'members':1950};part['ruleCatalog']={**record(I/'contracts/qualification/rule-catalog.json'),'catalogRef':catalog['catalogRef'],'rules':2137,'sources':95};part['lawBasis']={'ref':law['lawBasisRef'],'digest':law['lawBasisDigest'],'file':record(I/'contracts/qualification/law-basis.json')};part['roleCounts']=dict(collections.Counter(role for m in new['members'] for role in m['surfaceRoles']))
for key,n in [('contracts','validator/qualification_contracts.ts'),('judgment','validator/qualification.ts'),('implementation','implementation/qualification.ts')]:part['existingOwners'][key]=record(C/'source-freeze/repo'/T/'code/src'/n)
part['scopeLimit']='No partitions, role material, scope adequacy, attribution chain, native task or J constructed. Prior authored F11 scope grouping/material adequacy is excluded.';write('qualification-partition-inputs.json',part)
previous=read(Q/'conserved-component-evidence.json');componentjoins=[]
for claim in previous['claims']:
 for row in claim.get('currentSourceJoins',[]):
  assert sources[row['path']]['sha256']==row['candidateSha256'];componentjoins.append({'path':row['path'],'digest':'sha256:'+sources[row['path']]['sha256'],'currentOrigin':sources[row['path']]['origin'],'priorClaim':claim['claim'],'meaning':'Source byte premise conserved; original producing native/resource identity unchanged.'})
write('conserved-component-evidence.json',{'donor':record(Q/'conserved-component-evidence.json'),'coverageSelection':record(G/'final-candidate-coverage-selection-01.md'),'currentSourceJoins':componentjoins,'currentSubject':core['basis'],'reuse':'Closed component evidence may serve only its unchanged exact source premises; retained C01 installed/historical workload outcomes do not become C02 native proof.','C2selection':'Same five command groups/thirty titles; no whole native/private test file added.','nativeCredit':'No new claim; owner-specific applicability remains separate.'})
write('native-obligations.json',{'donorInventory':record(Q/'native-obligations.json'),'coverageSelection':record(G/'final-candidate-coverage-selection-01.md'),'newImmutableSubject':core['basis'],'status':'unexecuted_and_unbound_in_this_cut','preserved':'Existing selected S01/S02/S03/S06/control, actual C2, complete F11/seven seeds and sole AF22 obligations remain. No widened or waived claim.','routes':'Historical caller/oracle inventories are retained at their actual identities; later Root binds actual current producers.','movingNative03':'excluded and not consumed'})
write('external-construction-context.json',{'status':'attribution_not_constructed','qualificationInventory':{'ref':new['inventoryRef'],'digest':new['inventoryDigest']},'constructionRecords':[record(C/n) for n in ['activation.json','source-delta.json','source-overlay.json','source-freeze-manifest.json','operation-attribution.json','return.md','freeze.json']],'Q02operation':record(E/'activation.json'),'originalQ01Context':record(Q/'external-construction-context.json'),'scope':'This Worker authors new external input controls only; copies do not assign inherited semantic authorship. Root work grant is not the Product-owner qualification slot.','pending':['Authentic per-scope author/actor/authority correspondence','Adequate exact assessment Context','Actual admitted independent assessor and peer joins'],'optionalLaterRootCoordinate':{'freezeSHA256':'df4ff0bfe902a52b306565c5766d7042f73e0c94270dadb8369c4808b58daeac','consumed':False,'meaning':'Root-routed future external correspondence; eight C01 endpoints plus three D endpoints are not asserted here as an eleven-member successor attribution union.'},'nativeJudgments':0,'attributionChains':0})
write('classification-evidence.json',{'ref':'selection://abiogenesis/rc1/final-qualification-inputs-02/source-and-material','selectedAuthority':record(G/'final-candidate-coverage-selection-01.md'),'population':record(E/'population-binding.json'),'donor':record(Q/'classification-evidence.json'),'roleRule':read(Q/'classification-evidence.json')['roleRule'],'limit':'Unchanged finite classification claim rebound to exact bytes; no F11 applicability or scope-material adequacy assessment.'})
write('unbound-readiness.json',{'status':'valid_exact_unbound_input_cut','inventory':{'ref':new['inventoryRef'],'digest':new['inventoryDigest']},'recipe':read(E/'verification-selection-binding.json')['recipe']['digest'],'ProductToolchainManifest':read(E/'basis-template.json')['body']['toolchain'],'auxiliaryBuildConfiguration':read(E/'basis-template.json')['auxiliaryBuildConfiguration'],'nativeSlots':{'installedProduct':None,'workspaceBinding':None,'tenantManifest':None},'executionSelectionRef':'absent','isQualificationBasisReady':False,'missing':'Genuine current native environment/producer, attribution and independent semantic/native assessment','stagingPerformed':False,'recipeExecuted':False,'testsExecuted':False,'nativeCalls':0})
print(json.dumps({'status':'passed_conservation_and_unbound_routes','members':1950,'sourceGeneratedChanged':6,'externalControlsAndManifests':19,'stagingTargets':716,'publicationBindings':11,'nativeCalls':0,'attributionChains':0}))
