"""Assemble final control provenance, cost evidence and freeze; no further
constructor, validation group, test, staging or runtime operation is invoked.
"""
import pathlib,json,hashlib,datetime,difflib
E=pathlib.Path(__file__).resolve().parent;G=E.parent;Q=G/'final-qualification-inputs-01';C=G/'final-candidate-construction-02';read=lambda p:json.loads(p.read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
def record(p,relative=False):
 b=p.read_bytes();return {'path':str(p.relative_to(E) if relative else p),'bytes':len(b),'sha256':sha(b)}
def save(n,v):
 with (E/n).open('x') as f:json.dump(v,f,indent=2);f.write('\n')
groups=[read(p) for p in sorted(E.glob('??-*.execution.json'))]
save('cost-and-processes.json',{'status':'CLOSED','groups':groups,'actualSerialCommandGroups':len(groups),'maximumGroups':5,'perGroupCapMs':120000,'perGroupGraceMs':1000,'aggregateMaximumMs':605000,'actualOwnedExecutionMs':sum(r['elapsedMs'] for r in groups),'allOwnedExitsObserved':all(r['ownedExitObserved'] for r in groups),'allExitZero':all(r['exitCode']==0 and not r['timedOut'] and r['signal'] is None for r in groups),'streamBytes':[{n:(E/(r['label']+'.'+n)).stat().st_size for n in ['stdout','stderr']} for r in groups],'operation':'External input construction and pure owner/source/schema/constructor checks only','forbiddenEffectsPerformed':[],'HOME_home_CODEX_HOME':'unchanged','recordAssembly':'Final report/control provenance/freeze assembly is separate from the five closed pure command groups; no further checks or execution invoked.'})
# Complete the donor mapping after late control/report metadata is available.
# Its own coordinate is supplied by the enclosing freeze, preventing self-hash.
prior={r['path']:r for r in read(Q/'freeze.json')['records']};rows=[];patch=[]
excluded={'external-control-correspondence.json','freeze.json'}
for p in sorted(E.iterdir()):
 if not p.is_file() or p.name in excluded or p.suffix not in ['.json','.py','.mjs','.md'] or any(s in p.name for s in ['.started.','.process.','.execution.']):continue
 old=prior.get(p.name);op=Q/p.name;after=record(p)
 rows.append({'successor':after,'original':({**old,'path':str(op)} if old else None),'relation':'exact copy' if old and old['sha256']==after['sha256'] else 'current external input/control realization','actualConstructionActor':'/root/s03_independent_review','grant':'T287_FINAL_QUALIFICATION_INPUTS_02','scope':'Current external input or closure evidence only; no inherited Product semantic authorship or qualification-owner authority assigned'})
 if old and old['sha256']!=after['sha256']:patch.extend(difflib.unified_diff(op.read_text().splitlines(keepends=True),p.read_text().splitlines(keepends=True),fromfile=str(op),tofile=str(p)))
mapping={'status':'complete_at_final_record_assembly','controls':rows,'completeQualificationMemberMap':record(E/'qualification-member-correspondence.json'),'retainedOriginalCut':record(Q/'freeze.json'),'currentGrant':record(G/'final-qualification-input-controls-02/request.txt'),'originalsNotReissued':[{'path':str(Q/n),'sha256':r['sha256'],'disposition':'Retained immutable Q01 historical record; not reissued as current Q02 input'} for n,r in prior.items() if not (E/n).exists() and n!='freeze.json'],'acyclicLimit':'This metadata map and its diff have enclosing freeze identities; neither enters its own digest, protected recipe or qualification inventory. Final record assembly replaces the earlier pre-report capture with complete current closure metadata.'}
(E/'external-control-correspondence.json').write_text(json.dumps(mapping,indent=2)+'\n');(E/'external-control-delta.patch').write_text(''.join(patch))
records=[record(p,True) for p in sorted(E.rglob('*')) if p.is_file() and p.name!='freeze.json']
result={'status':'CLOSED','work_result':'exact_successor_unbound_qualification_inputs','activation':'T287_FINAL_QUALIFICATION_INPUTS_02','role':'external-input Worker CLOSED','actor':'/root/s03_independent_review','separateSessionIdentity':'not separately available','frozenAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'return':next(r for r in records if r['path']=='return.md'),'records':records,'externalInputs':next(r for r in records if r['path']=='external-input-freeze.json'),'candidateFreeze':record(C/'freeze.json'),'donorFreeze':record(Q/'freeze.json'),'request':record(G/'final-qualification-input-controls-02/request.txt'),'inventory':{'ref':read(E/'qualification-inventory.json')['inventoryRef'],'digest':read(E/'qualification-inventory.json')['inventoryDigest']},'recipe':read(E/'verification-selection-binding.json')['recipe']['digest'],'toolchain':read(E/'basis-template.json')['body']['toolchain'],'nativeBindings':{'installedProduct':None,'workspaceBinding':None,'tenantManifest':None},'executionSelectionRef':'absent','effects':'Only this new external input territory; no source/build/package/install/npm, protected staging, recipe/tests/native/provider/qualification/Git effect.','limits':['Structural input construction only; not independent assurance or native readiness','Own prior F11 scope grouping/material adequacy and attribution/independence judgments excluded','Moving native03/resource excluded; no automatic runtime rebind'],'stop':'Worker CLOSED; Root selects assurance applicability, genuine native bindings and every next effect. No actor or native operation activated.'}
save('freeze.json',result)
print(json.dumps({'status':'CLOSED','return':result['return'],'freeze':record(E/'freeze.json',True),'records':len(records),'externalInputRecords':len(read(E/'external-input-freeze.json')['records']),'inventory':result['inventory']['digest'],'recipe':result['recipe'],'ownedExecutionMs':sum(r['elapsedMs'] for r in groups)},indent=2))
