"""Close Q13 first managed cheap-preflight harness failure without retry."""
from pathlib import Path
import hashlib,json,stat,datetime,os
Q=Path(__file__).resolve().parent;G=Q.parent
assert not(Q/'freeze.json').exists()
def read(p):return json.loads(Path(p).read_bytes())
def pin(p):
 p=Path(p)
 with p.open('rb')as f:h=hashlib.file_digest(f,'sha256').hexdigest()
 return {'path':str(p),'bytes':p.stat().st_size,'sha256':h,'mode':stat.S_IMODE(p.stat().st_mode)}
def put(n,v):
 with(Q/n).open('x')as f:f.write(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
close=read(Q/'delta-supervisor-close.json');assert close['exitCode']==1 and close['wait4Reaped']and close['groupAfterWait']=='absent'and not close['timedOut']
stderr=(Q/'delta-preflight.stderr').read_text();assert 'MODULE_NOT_FOUND'in stderr and not(Q/'f11/delta-preflight.mjs').exists()and not(Q/'f11/source-delta-contract.mjs').exists()
joined=read(Q/'current-source-delta-correspondence.json');assert joined['allNineUniqueFullTuplesJoined']and joined['inheritedCallbackExcluded'];delta=read(Q/'f11/current-source-delta.json');assert len(delta['sourceChanges'])==9
failure={'status':'CLOSED_FIRST_ACTUAL_MANAGED_PREFLIGHT_REFUSAL','operation':'T287_FINAL_QUALIFICATION_INPUTS_13','workResult':'NO_GO_EXTERNAL_HARNESS_ENTRY_MODULE_ABSENT','frontier':'managed cheap external delta discriminator before Product imports','failedRelation':'Owned module write paths must resolve under the actual execution cwd before launching the discriminator','cause':'The shell used .ai-workspace/comments/.../final-qualification-inputs-13/... relative output paths while cwd was already final-qualification-inputs-13. Both module writes failed; a later preparation block still launched the absent entry.','shellWriteErrors':['zsh:1: no such file or directory: .ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE/final-qualification-inputs-13/f11/source-delta-contract.mjs','zsh:50: no such file or directory: .ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE/final-qualification-inputs-13/f11/delta-preflight.mjs'],'actualCwd':str(Q),'missingEntry':str(Q/'f11/delta-preflight.mjs'),'missingImportedContract':str(Q/'f11/source-delta-contract.mjs'),'actualNodeError':stderr,'managedReceipt':close,'producerNineTupleJoinPassed':True,'roleAwareJoinReceipt':pin(Q/'current-source-delta-correspondence.json'),'sourceDelta':pin(Q/'f11/current-source-delta.json'),'cheapActualHelperNegatives':'NOT_EXECUTED','completeTaskPayloads':0,'packetPayloads':0,'ProductImports':0,'fullMaterializationCalls':0,'RuntimeEffects':0,'noProductDefectInferred':True,'noRepairOrRetry':True}
put('first-readiness-refusal.json',failure)
auth=read(Q/'f11/source-authorship-records.json');prior=read(G/'final-qualification-inputs-11/f11/source-authorship-records.json');assert auth==prior
copies=[{'path':row['path'],'historicalFields':row['copyRoles']['selectedOrigin']['fields'],'currentFields':row['copyRoles']['currentSupplier']['fields'],'historicalAnchor':row['copyRoles']['selectedOrigin']['producer'],'currentAnchor':row['copyRoles']['currentSupplier']['producer']}for row in delta['sourceChanges']]
put('actual-copy-role-correspondence.json',{'status':'CLOSED_PASSED_PRODUCER_PREPARATION_ONLY','sourceDelta':pin(Q/'f11/current-source-delta.json'),'changes':9,'replacements':7,'additions':2,'roles':copies,'noCrossRoleEquality':True,'legitimateAdditionsHistoricalCopyAbsence':True,'actualHelperCounterexamples':'NOT_EXECUTED','fullOwnerReadiness':'NOT_EXECUTED'})
accounting={'managedPurePreflight':close,'preflightStderr':pin(Q/'delta-preflight.stderr'),'managedPurePreflightLaunches':1,'completeTaskPayloads':0,'packetPayloads':0,'publishedProductImports':0,'fullResourceBodyMaterialization':0,'resourceSerializationBytes':None,'assertionSerializationBytes':None,'requestOrPromptBytes':None,'qualificationCommandsExecuted':0,'nativeTaskRunJHelperProviderCalls':0,'SourceChanges':0,'builds':0,'candidateChanges':0,'GitEffects':0,'networkEffects':0,'retries':0,'defaultHeap':True,'ordinaryHOME':True}
put('accounting.json',accounting)
result={'status':'CLOSED','role':'Worker','actor':'/root/q03_input_review','operation':failure['operation'],'workResult':failure['workResult'],'ProductFrame':'F-EndToEndInterfaceIntegration; fixed15/GOAL035/T287/F11/F15, unchanged Product WHAT/runtime; role-aware owning HOW4.1 UML is agent guidance only','grant':pin(Q/'request.txt'),'currentC09Acceptance':pin(G/'rc1-c09-construction-acceptance-01/acceptance.json'),'actualSetup09Acceptance':pin(G/'rc1-setup09-acceptance-01/acceptance.json'),'donorQ12Freeze':pin(G/'final-qualification-inputs-12/freeze.json'),'donorQ11Freeze':pin(G/'final-qualification-inputs-11/freeze.json'),'firstActualRefusal':failure,'actualProducerJoin':joined,'distinctCopyRoleEvidence':pin(Q/'actual-copy-role-correspondence.json'),'retainedOriginalSourceAuth':{'body':pin(Q/'f11/source-authorship-records.json'),'records':174,'chains':23,'spans':90,'entireQ11BodyUnchanged':True,'sufficiency':'unknown','independence':'unknown'},'retainedStrictCaller':pin(Q/'f11/ordinary-caller.mjs'),'retainedParentChildDriver':pin(Q/'f11/flow-driver.mjs'),'accounting':accounting,'notReached':['Actual external helper cheap positive/negative discriminator','Complete current inventory/protected/recipe/task identities','Prepayload envelope checks','Complete published command Task','Full resource/reference-owner preparation and current request/prompt rendering'],'proofScope':'All nine frozen producer source/body/author/preimage/postimage tuples and own historical/current copy roles were checked. The intended actual consumer/helper guard did not execute because its module was absent. No end-to-end preparation or qualification is claimed.','unknowns':['Current complete consumer correspondence, negative and Task/resource/request readiness','Context/material/applicability/grouping/attribution/independence','Installed Result/J/foldback/F11/cold/QUAL056/scenarios/AF22/release'],'independentAssuranceClaim':False,'noFurtherWritesAfterFreeze':True,'returnsTo':'Root Executive'}
put('worker-result.json',result)
put('closure.json',{'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'closedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'allWritesStopAfterFreeze':True,'noRepairOrRetry':True,'consumer':'Root Executive'})
with(Q/'return.md').open('x')as f:f.write('CLOSED Q13: '+result['workResult']+'.\n\nActual role-aware producer preflight passed all nine selected C09 changes (7 replacements/2 additions), immutable body/preimage/postimage/source-author/original-row joins and distinct own producer copy roles. Inherited callback excluded; legitimate additions retain absent historical copy fields. Original174records/23chains/90spans remain exact Q11 bytes.\n\nThe first managed cheap discriminator failed before imports because its entry module was never created: module-write commands used repo-relative paths from Q13 cwd. Actual pinned Node MODULE_NOT_FOUND/exit1; '+str(round(close['elapsedMs'],3))+'ms, peakRSS'+str(close['maxRSSBytesMacOS'])+'B, wait4 reaped/group absent/no timeout. The actual helper negatives, complete inventory/Task/resource/reference-owner/request/prompt readiness did not run. No Product/Runtime/provider/source/build/Git/network/qualification-command effect. No repair or retry; Root receives this failed harness cut.\n')
rows=[];directories=[]
for p in sorted(Q.rglob('*')):
 if p.is_symlink():rows.append({'path':str(p.relative_to(Q)),'kind':'symlink','target':os.readlink(p),'mode':stat.S_IMODE(p.lstat().st_mode)})
 elif p.is_file():row=pin(p);row['path']=str(p.relative_to(Q));rows.append(row)
 elif p.is_dir():directories.append({'path':str(p.relative_to(Q)),'mode':stat.S_IMODE(p.stat().st_mode)})
freeze={'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'records':rows,'recordCount':len(rows),'bodyBytes':sum(r.get('bytes',0)for r in rows),'directories':directories,'directoryCount':len(directories),'linkCount':sum(r.get('kind')=='symlink'for r in rows),'noProductOrRuntimeEffects':True,'allWritesStopped':True}
put('freeze.json',freeze);os.chmod(Q/'freeze.json',0o444)
print(json.dumps({'status':'CLOSED','workResult':result['workResult'],'freeze':pin(Q/'freeze.json'),'records':len(rows),'bodyBytes':freeze['bodyBytes'],'directories':len(directories),'links':freeze['linkCount']}))
