// Addressable M01 contract entrypoint. Every symbol is projected from the
// direct GTL family; this entrypoint owns no alternate carrier or admission.
export {
  C,
  COMPUTE_REGIME_VALUES,
  C_TERM_KIND_VALUES,
  cCarrier,
  cGraphFunctionRef,
  cLeafTerms,
  cTermResultCardinality,
  isExecutableCLeaf,
  isInteractionCLeaf,
  isNativeCProgramTerm,
  workflow,
  type CBatchNode,
  type CCarrier,
  type CComposeNode,
  type CEdgeNode,
  type CGraphFunctionRef,
  type CIdentityNode,
  type CLeafRequirement,
  type COfNode,
  type COfTerm,
  type CProgramNode,
  type CProgramTerm,
  type CResultCardinality,
  type CRetryNode,
  type CTermKind,
  type CWorkflowNode,
  type ComputeRegime,
  type ExecutableLeafRequirement,
  type InteractionLeafRequirement,
} from "./c_algebra.js";
export {
  GTL_C_ADMISSION_DIAGNOSTIC_ID_VALUES,
  admitCProgramSyntax,
  admitGraphFunction,
  admitProgram,
  type CProgramAdmission,
  type CProgramAdmissionDiagnostic,
} from "./admission.js";
export {
  admitIJsonText,
  admitIJsonValue,
  serializeIJsonCanonical,
  type IJsonValue,
} from "./canonical_ingest.js";
export {
  constructGraphFunction,
  type GraphFunctionInit,
} from "./graph_function.js";
export {
  composeGraphFunctions,
  identityGraphFunction,
  promoteGraphFunction,
  substituteGraphFunction,
  type ComposeGraphFunctionsInput,
  type IdentityGraphFunctionInput,
  type PromoteGraphFunctionInput,
  type SubstituteGraphFunctionInput,
} from "./graph_construction.js";
export {
  composeApplication,
  fanInApplication,
  fanOutApplication,
  foldbackRef,
  gateApplication,
  graphEdge,
  graphEdgeRef,
  graphFunctionApplicationRef,
  identityApplication,
  promoteApplication,
  reenterApplication,
  recurseApplication,
  recursionTerminationDecision,
  sameObjectApplication,
  sameObjectWitnessRef,
  substituteApplication,
  type RecurseApplicationInput,
} from "./graph_applications.js";
export {
  serializeCProgramCanonical,
  serializeCProgramNode,
  serializeGraphFunction,
  serializeGraphTemplate,
  serializeProgram,
  serializeProgramCanonical,
} from "./serialization.js";
export type {
  ComposeApplication,
  FanInApplication,
  FanOutApplication,
  FoldbackDeclaration,
  GateApplication,
  GraphFunction,
  GraphFunctionApplication,
  GraphTemplate,
  GtlEdge,
  GtlEnvironment,
  GtlNode,
  GtlProgram,
  IdentityApplication,
  PromoteApplication,
  ReenterApplication,
  RecurseApplication,
  SameObjectApplication,
  SubstituteApplication,
} from "./contracts.js";
export type {
  GtlProgramAdmissibleRepair,
  GtlProgramConformanceIssue,
  GtlProgramDiagnosticId,
  GtlProgramRepairEditClass,
} from "../validator/conformance.js";
