import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),read=async n=>JSON.parse(await readFile(join(here,n),'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),setup=await read('setup.json'),load=p=>import(pathToFileURL(join(setup.installedRoots[0],'build/code/src',p+'.js')).href);
const [store,product]=await Promise.all(['abg/event_store','product/index'].map(load));
const handoff=await read('handoff.json'),allEvents=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),dispatch=await read('dispatch-start.json'),events=allEvents.filter(e=>e.admissionOrdinal>dispatch.beforeEventCount),results=events.filter(e=>e.kind==='c_call_result_admitted'),byId=new Map(events.map(e=>[e.eventId,e])),brief=e=>e?{ordinal:e.admissionOrdinal,eventId:e.eventId,kind:e.kind,graphFunctionRef:e.graphFunctionRef,cCallRef:e.aggregateId,resultRef:e.payload.resultRef??null}:null;
const input=await read('input.json'),effects=await read('effects.json'),timing=await read('timing.json'),syntheses=await read('synthesis-chain.json'),execution=await read('execution.json'),assessment=results.findLast(e=>e.graphFunctionRef===product.NATIVE_WORKSPACE_WORK_IDS.assessmentGraphFunctionRef&&e.payload.resultClass==='success'),parents=results.filter(e=>e.graphFunctionRef==='graph-function://default-library-witness/executive@5'&&e.payload.value?.kind==='governance_work_state'),commands=results.filter(e=>e.graphFunctionRef===product.WORKSITE_COMMAND_EXECUTION_IDS.graphFunctionRef&&e.payload.resultClass==='success'),authors=results.filter(e=>e.graphFunctionRef===product.NATIVE_WORKSPACE_WORK_IDS.graphFunctionRef&&e.payload.resultClass==='success');
const chain=syntheses.map(s=>({...s,choice:brief(byId.get(s.choiceEvent)),child:brief(byId.get(s.childEvent)),fold:brief(byId.get(s.foldEvent)),parent:brief(byId.get(s.parentEvent))}));await save('admitted-chain.json',chain);
const tools=[],actorEvidence=[];
for(const a of timing.actors){
 const file=a.retained.find(r=>['stdout','stdoutPath'].includes(r.role))?.path;if(!file)continue;
 const rows=(await readFile(join(here,file),'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse),final=rows.findLast(r=>r.type==='result'),binding=byId.get(a.bindingEvent);
 actorEvidence.push({actor:a.actor,binding:brief(binding),actorInvocationRef:binding.parentAggregateId,graphFunctionRef:binding.graphFunctionRef,nativeIntervalMs:a.nativeIntervalMs,promptBytes:a.promptBytes,models:a.reportedModels,costUsd:a.reportedUsage.reduce((n,r)=>n+(r.totalCostUsd??0),0),outputTokens:a.reportedUsage.reduce((n,r)=>n+(r.usage?.output_tokens??0),0),structuredOutput:final?.structured_output??null});
 for(const [rowIndex,row]of rows.entries())for(const c of row.message?.content??[])if(c.type==='tool_use'){
  const selected={...c.input};for(const key of ['content','new_string','old_string'])if(typeof selected[key]==='string')selected[key]={bytes:Buffer.byteLength(selected[key]),sha256:product.sha256Bytes(Buffer.from(selected[key]))};
  tools.push({actor:a.actor,graphFunctionRef:binding.graphFunctionRef,rawStdout:file,rowIndex,toolUseRef:c.id,name:c.name,input:selected});
 }
 if(assessment&&binding.parentAggregateId===assessment.payload.value.provenance.actorInvocationRef){
  assert.deepEqual(final.structured_output,assessment.payload.value.assessment);
  await save('assessment-raw-correspondence.json',{actor:a.actor,rawStdout:file,rawStructuredOutputDigest:product.sha256Canonical(final.structured_output),admittedAssessmentDigest:product.sha256Canonical(assessment.payload.value.assessment),equal:true,assessment:brief(assessment),providerIsError:final.is_error,subtype:final.subtype,sourceResultRef:assessment.payload.resultRef});
  await save('actual-assessment.json',assessment.payload.value.assessment);
 }
}
await save('native-tools.json',{scope:'Read-only projection of retained native tool calls for effect review; no global host audit or deterministic semantic verdict. Content strings are represented by byte identities; raw stdout retains exact content.',calls:tools});
const intervals=events.filter(e=>e.kind==='actor_invocation_started').map(e=>{const end=events.find(x=>['actor_invocation_closed','actor_invocation_failed'].includes(x.kind)&&x.parentAggregateId===e.parentAggregateId);return [Date.parse(e.eventTime),end?Date.parse(end.eventTime):Infinity];});
const gaps=events.slice(1).flatMap((e,i)=>{const a=Date.parse(events[i].eventTime),b=Date.parse(e.eventTime);return intervals.some(([s,t])=>a<t&&b>s)?[]:[{ms:b-a,from:brief(events[i]),to:brief(e)}];}).sort((a,b)=>b.ms-a.ms);
const protectedChecks=input.original.sources.map(s=>({path:s.path,expected:s.digest,actual:effects[s.path]?.sha256??null,equal:s.digest===effects[s.path]?.sha256}));for(const p of parents)assert.deepEqual(p.payload.value.original,input.original);
const finalParent=parents.at(-1),finalState=finalParent?.payload.value,assessmentFold=assessment?results.find(e=>e.payload.value?.kind==='governance_work_state'&&e.payload.value.observations.at(-1)?.resultRef===assessment.payload.resultRef):null;
const failed=results.filter(e=>e.payload.resultClass!=='success'),failureEvidence=events.filter(e=>e.kind==='evidence_admitted'&&JSON.stringify(e.payload).includes('diagnostic://'));
const outcome={publicOwnerOutput:execution.output.receipt.ownerOutput,assessment:brief(assessment),assessmentMeaning:assessment?.payload.value.assessment?.disposition??null,assessmentActor:assessment?.payload.value.provenance.actorInvocationRef??null,producer:assessment?.payload.value.task.assessment.producer??null,independentActor:assessment?assessment.payload.value.provenance.actorInvocationRef!==assessment.payload.value.task.assessment.producer.actorInvocationRef:null,assessmentChangedPaths:assessment?.payload.value.changedPaths??null,assessmentFold:brief(assessmentFold),coverageAccepted:!!assessmentFold,runClosureEvents:events.filter(e=>e.kind==='run_closed').map(brief),parentCount:parents.length,lastParent:brief(finalParent),lastParentTerminal:finalState?.terminal??null,lastCoverage:finalState?.fulfillment.coverage??null,additions:finalState?.fulfillment.additions??null,originalConserved:true,protectedFiles:protectedChecks,effects,commands:commands.map(e=>({...brief(e),sourceObservedInput:!!e.payload.value.task.sourceObservedInput,nativeSourceArm:product.isNativeWorksiteCommandExecutionObservation(e.payload.value),actorInvocationRef:e.payload.value.provenance.actorInvocationRef,dependencies:e.payload.value.task.protectedObservations.map(p=>({path:p.subject.relativePath,digest:p.observation.fileDigest})),results:e.payload.value.commandResults.map(c=>({commandId:c.commandId,exitStatus:c.exitStatus,timedOut:c.timedOut,stdout:Buffer.from(c.stdout.payload,'base64').toString(),stderr:Buffer.from(c.stderr.payload,'base64').toString()}))})),authors:authors.map(e=>({...brief(e),actorInvocationRef:e.payload.value.provenance.actorInvocationRef,changedPaths:e.payload.value.changedPaths,beforeAbsent:e.payload.value.before.entries.filter(r=>r.state==='absent').map(r=>r.relativePath),report:e.payload.value.report})),failedResults:failed.map(e=>({...brief(e),value:e.payload.value,diagnosticRef:e.payload.diagnosticRef??null})),firstDiagnosticEvidence:brief(failureEvidence[0]),actorEvidence,timing:{executionMs:timing.executionMs,nativeMs:timing.nativeMs,frameworkOutsideNativeMs:timing.frameworkOutsideNativeMs,actors:timing.actors.length,promptBytes:timing.actors.reduce((n,a)=>n+a.promptBytes,0),events:timing.eventCount,totalReportedUsd:actorEvidence.reduce((n,a)=>n+a.costUsd,0),outputTokens:actorEvidence.reduce((n,a)=>n+a.outputTokens,0),maxAdjacentDeterministicInterval:gaps[0],deterministicIntervalsOver10s:gaps.filter(x=>x.ms>10000)},readback:await read('readback-timing.json')};await save('outcome-evidence.json',outcome);
console.log(JSON.stringify({chain:chain.map(c=>({synthesis:c.synthesisOrdinal,next:c.judgment.nextGraphFunctionRef,choice:c.choice?.ordinal,child:c.child?.ordinal,fold:c.fold?.ordinal,parent:c.parent?.ordinal})),timing:outcome.timing,assessment:outcome.assessment,assessmentMeaning:outcome.assessmentMeaning,assessmentFold:outcome.assessmentFold,parentTerminal:outcome.lastParentTerminal,coverage:outcome.lastCoverage,failed:failed.map(brief),effects},null,2));
