import json,pathlib,hashlib,datetime,collections,base64
root=pathlib.Path(__file__).resolve().parent;read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();D=lambda s:datetime.datetime.fromisoformat(s.replace('Z','+00:00')).timestamp()*1000
report={}
for name in ['companion-01','faulty-01']:
 p=root/name
 if not (p/'asserted-outcome.json').exists():continue
 es=read(p/'events.json');timing=read(p/'timing.json');execution=read(p/'execution.json');result=execution['output']['receipt']['ownerOutput'];assert result['value']['disposition']=='completed';rows=read(p/'synthesis-correspondence.json');events={e['eventId']:e for e in es};initial=read(p/'input.json');case=read(p/'case-input-files.json')
 selection=read(p/'selection.json');protected=selection['protectedSeedPaths']+(['generated/hello-world.mjs'] if name.startswith('companion') else []);assert all(sha(p/'worksite-result'/path)==case[path]['sha256'] for path in protected)
 intervals=[]
 for e in es:
  if e['kind']=='actor_invocation_started':
   end=next(r for r in es if r['kind'] in ['actor_invocation_closed','actor_invocation_failed'] and r['aggregateId']==e['aggregateId']);intervals.append((e,end))
 gaps=[]
 for a,b in zip(es,es[1:]):
  if not any(lo['admissionOrdinal']<=a['admissionOrdinal']<hi['admissionOrdinal'] for lo,hi in intervals):gaps.append({'wallMs':D(b['eventTime'])-D(a['eventTime']),'fromOrdinal':a['admissionOrdinal'],'fromKind':a['kind'],'toOrdinal':b['admissionOrdinal'],'toKind':b['kind']})
 commandResults=[e for e in es if e['kind']=='c_call_result_admitted' and e.get('graphFunctionRef')=='graph-function://abiogenesis/worksite/command-execution@5'];authors=[e for e in es if e['kind']=='c_call_result_admitted' and e.get('graphFunctionRef')=='graph-function://abiogenesis/worksite/native-work@5'];assessments=[e for e in es if e['kind']=='c_call_result_admitted' and e.get('graphFunctionRef')=='graph-function://abiogenesis/worksite/native-work/assessment@5']
 def coord(e):return {'ordinal':e['admissionOrdinal'],'eventId':e['eventId'],'resultRef':e['payload'].get('resultRef')}
 commands=[{'result':coord(e),'sourceObservedInput':bool(e['payload']['value']['task'].get('sourceObservedInput')),'observations':[{'exit':c['exitStatus'],'stdout':base64.b64decode(c['stdout']['payload']).decode(),'stderr':base64.b64decode(c['stderr']['payload']).decode()} for c in e['payload']['value']['commandResults']]}for e in commandResults]
 reads={}
 for member in ['run_result','run_replay']:
  r=read(p/f'read-{member}.json');receipt=r['output']['receipt'];assert receipt['ownerOutput']['outcomeKind']=='result';assert receipt['resources']['eventResource']['closeHandoff']['prefix']==read(p/'handoff.json')['prefix'];reads[member]={'wallMs':r['wallMs'],'outcomeKind':receipt['ownerOutput']['outcomeKind'],'requestBytes':pathlib.Path(r['requestPath']).stat().st_size,'receiptSha256':sha(p/f'read-{member}.json')}
 report[name]={'status':'completed; assertions and fresh Public reads passed','asserted':read(p/'asserted-outcome.json'),'coreArchiveSha256':sha(p/'core.tgz'),'consumerArchiveSha256':sha(p/'consumer.tgz'),'eventLogSha256':sha(p/'events.jsonl'),'mapping':[{'synthesisOrdinal':r['synthesisOrdinal'],'contributions':[{'graphFunctionRef':c['graphFunctionRef'],'dependsOn':c['dependsOn']} for c in r['judgment']['contributions']],'next':r['judgment']['nextGraphFunctionRef'],'choiceOrdinal':r['choiceOrdinal'],'childResultOrdinal':r['childResultOrdinal'],'childGraphFunction':r['childGraphFunction'],'foldOrdinal':r['foldOrdinal'],'parentOrdinal':events[r['parentEvent']]['admissionOrdinal'],'exactRowsFile':'synthesis-correspondence.json'}for r in rows],'commands':commands,'authors':[{'result':coord(e),'changedPaths':e['payload']['value']['changedPaths']}for e in authors],'assessments':[{'result':coord(e),'producer':e['payload']['value']['task']['assessment']['producer'],'actor':e['payload']['value']['provenance']['actorInvocationRef'],'verdict':e['payload']['value']['assessment']}for e in assessments],'runClosure':[coord(e)for e in es if e['kind']=='run_closed'],'unchangedProtectedFiles':protected,'timing':{'setupMs':sum(timing['setup']['wallMs'].values()),'executionMs':timing['executionMs'],'nativeMs':sum(t['nativeIntervalMs'] for t in timing['native']),'frameworkOutsideNativeMs':timing['frameworkOutsideNativeIntervalsMs'],'largestOutsideActorGaps':sorted(gaps,key=lambda r:r['wallMs'],reverse=True)[:8]},'reads':reads,'volumes':{'publicRequestBytes':timing['publicRequestBytes'],'readinessBytes':len(json.dumps(read(pathlib.Path(execution['requestPath']))['invocation']['resources']['catalog']['readinessBasis'],separators=(',',':')).encode()),'promptBytes':[t['promptBytes'] for t in timing['native']],'eventCount':len(es),'eventLogBytes':(p/'events.jsonl').stat().st_size,'eventKinds':dict(collections.Counter(e['kind'] for e in es)),'setup':timing['setup'].get('volumes',{})}}
(root/'outcome.json').write_text(json.dumps(report,indent=2)+'\n');print({k:{'nativeMs':v['timing']['nativeMs'],'frameworkMs':v['timing']['frameworkOutsideNativeMs'],'choices':[r['next'].split('/')[-1]for r in v['mapping']]}for k,v in report.items()})
