from pathlib import Path
import json,hashlib,stat,datetime,collections
R=Path('/Users/jim/src/apps/abiogenesis');G=R/'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE';N=G/'final-observed-c2-01';P=G/'final-native-setup-03';B=G/'final-native-continuation-04';C=G/'final-candidate-construction-02';Q=G/'final-qualification-inputs-02';S=C/'source-freeze/repo'
def read(p):return json.loads(p.read_text())
def sha(b):return hashlib.sha256(b).hexdigest()
def row(p,base=N):
 s=p.lstat()
 if p.is_symlink():return {'path':str(p.relative_to(base)),'kind':'symlink','target':str(p.readlink())}
 b=p.read_bytes();return {'path':str(p.relative_to(base)),'kind':'file','mode':stat.S_IMODE(s.st_mode),'bytes':len(b),'sha256':sha(b)}
def save(n,v):
 with(N/n).open('x')as f:json.dump(v,f,indent=2);f.write('\n')
def verify(p,x):
 observed=row(p,p.parent)
 for k in ['kind','mode','target','bytes','sha256']:
  if k in x:assert observed[k]==x[k],(str(p),k)
verified=[]
for cut in [C,Q,B]:
 rows=read(cut/'freeze.json')['records']
 for x in rows:verify(cut/x['path'],x)
 verified.append({'cut':str(cut.relative_to(R)),'freeze':row(cut/'freeze.json',R),'records':len(rows)})
oldRecords=read(P/'freeze.json')['records'];eventRel='resources/events/runtime.events.jsonl'
for x in oldRecords:
 if x['path']!=eventRel:verify(P/x['path'],x)
for x in read(N/'pre-effect-input-freeze.json')['records']:verify(N/x['path'],x)
for x in read(N/'donor-preimages.json'):verify(R/x['original']['path'],x['original']);verify(R/x['preserved']['path'],x['preserved'])
files=read(N/'all716-pre-effect-checks.json')['files'];root=P/'resources/worksite'
for f in files:
 b=(root/f['target']).read_bytes();assert len(b)==f['bytes'] and sha(b)==f['sha256'],f['target']
assert not(root/'verification').exists()
oldPaths={x['path']for x in oldRecords}|{'freeze.json'};currentPaths={str(p.relative_to(P))for p in P.rglob('*')if p.is_file()or p.is_symlink()};newPaths=sorted(currentPaths-oldPaths)
stagedPaths={'resources/worksite/'+x['target']for x in files}
for name in newPaths:assert name in stagedPaths or any(name.startswith(prefix)for prefix in ['resources/archives/','resources/runtime/','resources/projections/','tmp/']),name
assert stagedPaths.issubset(set(newPaths));newRows=[row(P/name,P)for name in newPaths];save('N03-new-resource-inventory.json',{'scope':'All newly created N03 files; original preserved files are joined through N03 freeze; original event log has separate physical snapshot','records':newRows,'recordCount':len(newRows)})
resource=P/eventRel;a=resource.stat();body=resource.read_bytes();z=resource.stat();assert (a.st_dev,a.st_ino,a.st_size,a.st_mtime_ns)==(z.st_dev,z.st_ino,z.st_size,z.st_mtime_ns);assert z.st_dev==16777230 and z.st_ino==464012478
old=(B/'failure-native-prefix.jsonl').read_bytes();assert body[:len(old)]==old;assert body==(N/'failure-native-prefix.jsonl').read_bytes();assert body[:(P/'failure-native-prefix.jsonl').stat().st_size]==(P/'failure-native-prefix.jsonl').read_bytes()
lock=P/'tmp/abiogenesis-event-store-locks-v5/16777230-464012478.lock';assert not lock.exists();handoff=read(N/'final-handoff.json');assert handoff['prefix']['prefixLength']==len(body) and handoff['prefix']['prefixDigest']=='sha256:'+sha(body)
failure=read(N/'failure.json');assert len(failure['calls'])==1 and failure['staged']==716;events=[json.loads(l)for l in body.splitlines()];added=events[33:];assert len(events)==84
physical={'path':str(resource.relative_to(R)),'device':z.st_dev,'inode':z.st_ino,'bytes':len(body),'sha256':sha(body),'eventCount':len(events),'initialBytes':len(old),'initialSHA256':sha(old),'prefixConserved':True,'snapshotIdentical':True,'stable':True,'lockPath':str(lock),'lockPresent':False,'coordinateDigest':handoff['prefix']['coordinateDigest']}
save('conservation.json',{'status':'passed','frozenCuts':verified,'N03ImmutableRecordsVerified':len(oldRecords)-1,'N03EventException':physical,'newN03Files':len(newRows),'protectedStagedInputs':716,'protectedBytesUnchanged':True,'verificationSubtreeAbsent':True,'newOwnerFiles':len(newRows)-716,'controlsAndDonors':'all exact frozen records unchanged','candidateAndQ02':'unchanged','oldSetupS01ReceiptsAndPrefixes':'unchanged','scopeLimit':'Only selected cuts and original native resource territory; no host-wide filesystem claim'})
selectedKinds=['actor_transport_binding_admitted','actor_invocation_started','actor_process_started','actor_process_exited','actor_result_artifact_observed','actor_invocation_failed','c_call_evidenced','c_call_result_admitted','c_call_judged','traversal_route_admitted','run_stopped'];selected=[e for e in added if e['kind']in selectedKinds];save('actual-native-causal-events.json',{'initialEvents':33,'addedEvents':51,'kindCounts':dict(collections.Counter(e['kind']for e in added)),'events':selected,'fullPrefix':'failure-native-prefix.jsonl'})
binding=next(e['payload']for e in added if e['kind']=='actor_transport_binding_admitted');actor=next(e['payload']for e in added if e['kind']=='actor_result_artifact_observed');proc=next(e['payload']for e in added if e['kind']=='actor_process_exited');native=read(N/'c2-observed-c2-native-process.json');timing=read(N/'c2-observed-c2-timing.json');driver=read(N/'driver-process.json')
assert actor['toolCallCount']==0 and actor['apiRetryCount']==10 and actor['failureClass']=='transport_failure' and actor['exitObserved']and actor['terminationConfirmed']and not actor['timedOut'];assert proc['status']==1 and proc['signal']is None;assert native['exitCode']==0 and native['signal']is None;assert driver['exitCode']==1 and driver['exitObserved']and not driver['timedOut'];assert timing['terminal']['code']==0 and not timing['terminal']['timedOut']
assert binding['command']=='/Users/jim/.local/share/claude/versions/2.1.280';assert binding['args'][-4:]==['--model','claude-opus-5-5','--effort','xhigh'];assert binding['timeoutMs']==1083000 and binding['absoluteTimeoutMs']==1263000 and binding['terminationGraceMs']==1000
archive=P/'resources/archives';stdoutPath=next(archive.glob('fp-*-stdout.log'));stdoutRows=[json.loads(l)for l in stdoutPath.read_text().splitlines()];providerResult=[d for d in stdoutRows if d.get('type')=='result'];assert len(providerResult)==1;providerResult=providerResult[0];assert providerResult['is_error']is True and 'ENOTFOUND'in providerResult['result'];assert providerResult['total_cost_usd']==0;assert providerResult['usage']['input_tokens']==0 and providerResult['usage']['output_tokens']==0
init=next(d for d in stdoutRows if d.get('type')=='system'and d.get('subtype')=='init');assert init['model']=='claude-opus-5-5';save('provider-observation.json',{'nativeSource':row(stdoutPath,R),'actualBinding':binding,'reportedInit':{k:init[k]for k in ['type','subtype','model','permissionMode','apiKeySource','session_id']if k in init},'apiRetryNotices':[{k:d[k]for k in ['type','subtype','attempt','max_retries','retry_delay_ms','error']if k in d}for d in stdoutRows if d.get('subtype')=='api_retry'],'providerResult':{k:providerResult[k]for k in ['type','subtype','is_error','result','num_turns','duration_ms','duration_api_ms','total_cost_usd','usage','modelUsage','session_id']if k in providerResult},'nativeActorObservation':actor,'limits':'Provider reports ENOTFOUND but does not expose the failed hostname or establish whether ambient DNS, sandbox networking, proxy/endpoint configuration or upstream infrastructure caused resolution failure. No network/config/credential probe or repair was run.'})
save('cost-and-quiescence.json',{'preflightElapsedMs':read(N/'pure-preflight.json')['elapsedMs'],'driver':driver,'nativeCLI':native,'nativeWrapper':timing['terminal'],'nativeCallElapsedMs':timing['elapsedMs'],'providerDurationMs':providerResult['duration_ms'],'providerReportedCostUSD':providerResult['total_cost_usd'],'providerUsage':providerResult['usage'],'actorNativeProcessExit':proc,'actorTransport':{'exitObserved':actor['exitObserved'],'terminationConfirmed':actor['terminationConfirmed'],'processStatus':actor['processStatus'],'processSignal':actor['processSignal'],'timedOut':actor['timedOut'],'signalSequence':actor['signalSequence'],'apiRetryCount':actor['apiRetryCount'],'toolCallCount':actor['toolCallCount']},'actualCalls':1,'freshReads':0,'helperInvocations':0,'commandsExecuted':0,'declaredCommands':13,'providerEpisodes':1,'retries':'No Public/Run/provider episode retry by Worker; existing provider internally emitted10 API retry notices within the same process','quiescence':'ABG admitted actual provider exit1, termination confirmed; wait4 reaped native CLI exit0; wrapper closed; supervisor waited driver exit1. Same original resource stable and lock absent. No host-wide process absence claimed.'})
save('assertion-frontier.json',{'firstFailure':{'phase':failure['phase'],'expression':"assert.equal(value.disposition,'completed')",'location':'output-checks.mjs:19','actual':'runtime_failed','message':failure['message']},'reachedAndPassed':failure['reached'],'notReached':['Typed terminal producer/task/source-set success checks because terminalResult is null','Successful helper artifact and protected before/after observation material','13 command ordered exits/streams/reports','14 predicate value comparisons','5 strict reports and30titles','Syntax lint report population','925 generated output comparisons','Two fresh run_result/run_replay processes and zero-append/output joins','Normal success runtime-slot/material output'],'closureObservations':['Physical716 staged bytes unchanged and verification subtree absent','Actual native toolCallCount0 plus no helper artifact prove no declared command execution','51 event append, genuine latest handoff, source-linked transport failure and failure Result/J/route preserved','Original N03/N04 prefixes and all immutable records conserved'],'limit':'Prepared consumer contracts remain unexecuted on a successful C2 output. First assertion correctly exposes runtime failure; no proof-consumer carrier typo established.'})
sourceRelations=[]
for path,ranges in [('build_tenants/abiogenesis/typescript/code/src/abg/transport_contracts.ts',[[64,89],[240,270]]),('build_tenants/abiogenesis/typescript/code/src/abg/worker_transport.ts',[[748,777]]),('build_tenants/abiogenesis/typescript/code/src/abg/actor_process.ts',[[1286,1340]]),('build_tenants/abiogenesis/typescript/code/src/implementation/worksite_command_execution.ts',[[250,275],[699,706]])]:
 p=S/path;ls=p.read_text().splitlines();sourceRelations.append({'logicalRepositoryPath':path,'source':row(p,R),'ranges':[{'lines':[a,b],'excerpt':'\n'.join(f'{i+1}: {ls[i]}'for i in range(a-1,min(b,len(ls))))}for a,b in ranges]})
save('failure-source-relations.json',sourceRelations)
value=read(N/'actual-c2-owner-value.json');save('retained-runtime-coordinates.json',{'subject':read(N/'selected-core.json')['basis'],'workspaceBinding':read(B/'runtime-slots.json')['workspaceBinding'],'actualRun':value['run'],'actualGraphCall':value['graphCall'],'actualStop':value['stop'],'actualReplay':value['replay'],'terminalResult':None,'cCallRef':actor['cCallRef'],'actorInvocationRef':actor['actorInvocationRef'],'transportBindingRef':actor['transportBindingRef'],'finalHandoff':row(N/'final-handoff.json'),'physical':physical,'task':{'ref':read(N/'actual-observed-task.json')['taskRef'],'digest':read(N/'actual-observed-task.json')['taskDigest']},'executionSelectionRef':None,'tenantManifest':None,'qualificationBasis':None,'nextAuthority':'Root selects any recovery/new execution. Present genuine resource and staged current inputs are retained; any subsequent call must use current owner projection, actual last handoff and applicable lifecycle/source law, not replay the original absence-stage or reuse old prefix authority.'})
save('causal-triage.json',{'status':'CLOSED_FIRST_MATERIAL_NATIVE_FAILURE','origin':'Selected provider process could not reach its API server and reports DNS ENOTFOUND; no helper dispatch occurred','firstCallerSymptom':'Supported Public start returned result carrier with disposition runtime_failed, null terminalResult/result, actual run/stop/replay. Current completed-outcome assertion failed and ended driver. Native CLI exit0 means successful projection of that failure, not successful C2.','causalChain':['Actual C02 Product/input/grant/context preparation passed and ABG admitted current invocation/basis/C-call/actor transport','Provider emitted10 internal API retry notices, then is_error:true ENOTFOUND; process exited1, zero tools/tokens/cost','Existing transport owner classifies nonzero process/API-retry/no result as transport_failure','C2 exactExchange also requires successful transport and one exact Bash call; this false relation projects generic transport_identity_mismatch, not evidence that immutable input identities differ','ABG admitted failure Result, blocked judgment, failure route and run_stopped; Public projects runtime_failed; caller success assertion refuses advancement'],
'frames':{'ProductRequirements':'REQ-P-QUAL056/057 require actual native commands/reports tied to exact source selection. No successful helper or commands exist, so prepared recipe/component evidence cannot substitute. C02 and Q02 remain immutable; no qualification or release claim.','Design':'Existing observed-root C2 and packaged renderer environment are sufficient and reached. Native owner assembled exact context and helper launch manifests. This attempt does not indicate a missing declaration or revised architecture.','Integration':'Complete selected request/resource/authority/context joins passed actual Product preparation before native dispatch. The break is between actual Claude process and its API endpoint, before Bash/helper. Generic downstream transport_identity_mismatch must not be mistaken for a supplied carrier defect. Output/oracle success checks and cold reads remain pending.','Identity':'Same actual N03 A/W/install/catalog/actor; exact C02 artifact and Q02 config, actual direct grant/task/source set and admitted C-call/transport retained. Executable hash/model/effort match current grant. Public source Run has authentic failure lifecycle, not a successful verification producer.','Lifecycle':'One actual new C2 Run stopped failed, one actor invocation terminated, original33-event prefix conserved within84events. No root/child/actor retry or new Run by Worker. Genuine latest handoff retained; any future operation requires Root selection and current owner lifecycle/source inputs.','Authority':'Worker current author/session/grant distinct from native actor and Product-owned ABG authority. Root confirmed create-only context path within granted archive territory. Only read_context for current renderer dependency; no new Product/qualification authority.','Effect':'716 exclusive stage writes and one new archive/context preparation;7 owner archive files;51 event append. Protected716 and installed/canonical/frozen inputs unchanged. Verification subtree absent, helper tool count0, commands0, cold reads0. Existing provider internally retried10 API calls, one bounded process; no Worker retry.','Proof':'First actual runtime failure was preserved; assertion correctly refused completed status. No successful command/report/predicate/output comparison is claimed. Independent component/input/package checks and nominal verification did not probe ambient provider reachability; grant explicitly prohibited a paid probe.'},
'alternativesAndUncertainty':{'supported':'Execution environment/provider reachability failure, specifically reported ENOTFOUND, before semantic/helper work. Exact lower network owner unresolved.','notEstablished':'Which hostname failed or whether sandbox DNS, local/proxy configuration or upstream endpoint infrastructure caused it. No extra network probe or configuration inspection performed.','callerOrProductFault':'No positive evidence; owner preparation and actual dispatch reached intended provider with requested args. Generic identity diagnostic is downstream of non-success/zero-tool exchange. Latent unexecuted successful output consumer issues remain possible but are not this cause.','oracleFailure':'No evidence; completed assertion truthfully rejects runtime_failed, and original Q02 recipe/oracles were unchanged.'},
'recurrenceAndEscape':'Unlike N1/N03 stale resource carriers and N04 producer-field typo, this is an observed provider-network failure. Prior preparation and bounded component proofs could not prove network availability. Missing Hello donor runEnvironmentResources was explicitly constructed using existing owner before staging, without a failed native attempt or source change. No recurrence of that caller omission reached native.',
'smallestReentry':'Root-owned execution-environment intake to establish a usable network/provider route for the exact existing executable/profile, followed by separately granted lawful current-resource execution/recovery and pending success/cold proof. Present evidence selects no C02/Product/Q02/source/recipe change. Worker performs no continuation.','requiredReproof':'One actual successful native C2,13 ordered commands,14 predicates,716 observations,strict5/30 test/lint reports,925 comparisons and two fresh reads remain open; preserve this failed attempt and accepted prior setup/S01.'})
save('closed-state.json',{'status':'CLOSED_FIRST_MATERIAL_NATIVE_FAILURE','activation':'T287_FINAL_OBSERVED_C2_01','actor':'/root/s03_phase_b','sessionId':'01a0f036-c7b5-7f40-b1d8-e53a1fcf24f4','actualNativeCalls':1,'providerEpisodes':1,'helperInvocations':0,'commandCount':0,'freshReads':0,'physical':physical,'finalHandoff':'final-handoff.json','snapshot':'failure-native-prefix.jsonl','remaining':'Root network/environment disposition and selected current lifecycle continuation; no autonomous retry','Worker':'CLOSED'})
print(json.dumps({'status':'closure_evidence_ready','nativeCalls':1,'newN03Files':len(newRows),'frozenCutsVerified':verified,'finalPrefix':physical,'handoffSHA256':sha((N/'final-handoff.json').read_bytes())}))
