// Bounded caller evidence consumer. Source-linked current owner protocol;
// this does not construct F11 material or confer qualification authority.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {join} from 'node:path';
import {createRequire} from 'node:module';
const keys=x=>Object.keys(x).sort();
export function makeOutputChecks({product,installedRoot}){
 const v=createRequire(join(installedRoot,'package.json'))('valibot'),count=v.pipe(v.number(),v.integer(),v.minValue(0)),text=v.pipe(v.string(),v.minLength(1));
 const testRow=v.variant('type',[
  v.strictObject({ordinal:count,type:v.literal('begin'),format:v.literal('node-test-events-jsonl@1'),nodeVersion:text}),
  v.strictObject({ordinal:count,type:v.literal('end')}),
  v.strictObject({ordinal:count,type:v.literal('case'),passed:v.boolean(),name:text,file:v.nullable(text),nesting:count,testNumber:count,suite:v.boolean(),skip:v.union([v.boolean(),v.string()]),todo:v.union([v.boolean(),v.string()]),error:v.nullable(v.unknown())}),
  v.strictObject({ordinal:count,type:v.literal('summary'),file:v.nullable(text),counts:v.object({tests:count,passed:count,failed:count,cancelled:count,skipped:count,todo:count,suites:count,topLevel:count}),success:v.boolean(),durationMs:v.pipe(v.number(),v.minValue(0))})]);
 const lintSchema=v.strictObject({kind:v.literal('qualification_syntax_lint'),schemaVersion:v.literal('1'),passed:v.boolean(),files:v.array(v.strictObject({path:text,kind:v.picklist(['mjs','json']),disposition:v.picklist(['passed','failed']),diagnostic:v.nullable(text)}))});
 const stream=s=>{const b=Buffer.from(s.payload,'base64');assert.equal(b.toString('base64'),s.payload);assert.equal(b.length,s.byteLength);assert.equal(product.sha256Bytes(b),s.digest);return new TextDecoder('utf-8',{fatal:true}).decode(b);};
 const processPassed=c=>{assert.equal(c.exitStatus,0,c.commandId);assert.equal(c.timedOut,false);assert.equal(c.processSignal,null);assert.deepEqual(c.signalSequence,[]);assert.equal(c.terminationConfirmed,true);};
 async function consume({value,task,recipe,selection,expected,workspaceRoot,write,mark}){
  assert.equal(value.disposition,'completed');assert.equal(value.stop,null);const terminal=value.terminalResult;assert.equal(terminal.kind,'abg_typed_terminal_result');assert.equal(terminal.producer.runRef,value.run.ref);assert.equal(terminal.valueDigest,product.sha256Canonical(terminal.value));const o=terminal.value;
  assert.equal(product.isObservedWorksiteCommandExecutionObservation(o),true,'actual installed observed-result predicate');assert.deepEqual(o.task,task);assert.equal(o.task.sourceObservedInput.sourceSetDigest,product.sha256Canonical(task.protectedObservations));mark('typed terminal/current producer/task/source-set');
  const helperBytes=await fs.readFile(o.provenance.helperArtifactPath),helper=JSON.parse(helperBytes);assert.equal(product.isWorksiteExecutionHelperArtifact(task,helper),true);assert.equal(helperBytes.length,o.provenance.helperArtifactByteLength);assert.equal(helper.artifactDigest,o.helperArtifactDigest);assert.equal(helper.artifactRef,o.helperArtifactRef);assert.equal(helper.disposition,'success');assert.deepEqual(helper.commandResults,o.commandResults);assert.deepEqual(helper.predicateObservations,o.predicateObservations);assert.deepEqual(helper.protectedBefore,task.protectedObservations.map(x=>x.observation));assert.deepEqual(helper.protectedAfter,helper.protectedBefore);assert.equal(helper.protectedBefore.length,716);assert.deepEqual(o.productDelta,[]);assert.ok(o.worksiteDelta.every(d=>d.matchedTerritoryRef!==null));await write('helper-observation.json',helper);mark('actual helper/protected716 before-after/product conservation');
  assert.equal(o.commandResults.length,13);assert.equal(o.predicateObservations.length,14);const commands=[];
  for(let i=0;i<13;i++){const c=o.commandResults[i],d=task.commands[i];for(const k of ['ordinal','commandId','executable','args','relativeCwd','environment','timeoutMs','terminationGraceMs'])assert.deepEqual(c[k],d[k]);processPassed(c);const stdout=stream(c.stdout),stderr=stream(c.stderr);await write('command-'+String(i).padStart(2,'0')+'-streams.json',{commandId:c.commandId,stdout,stderr,stdoutObservation:c.stdout,stderrObservation:c.stderr});for(const r of c.reports){assert.equal(r.state,'file');const bytes=await fs.readFile(join(workspaceRoot,r.relativePath));assert.equal(bytes.length,r.byteLength);assert.equal(product.sha256Bytes(bytes),r.digest);}commands.push({commandId:c.commandId,exitStatus:c.exitStatus,stdoutDigest:c.stdout.digest,stderrDigest:c.stderr.digest,reports:c.reports});mark('command '+i+' '+c.commandId);}
  for(let i=0;i<14;i++){const p=task.outcomePredicates[i],actual=o.predicateObservations[i];assert.equal(actual.ordinal,i);assert.equal(actual.predicateId,p.predicateId);assert.equal(actual.predicateKind,p.predicateKind);assert.ok(['process_exit','stdout_exact'].includes(p.predicateKind));assert.deepEqual(actual.observedValue,p.declaration.equals);mark('predicate '+i);}
  const tests=[];for(const t of recipe.tests){const c=o.commandResults.find(x=>x.commandId===t.commandId),s=selection.tests.find(x=>x.commandId===t.commandId);assert.ok(c&&s);const raw=stream(c.stdout);assert.ok(raw.endsWith('\n'));const rows=raw.slice(0,-1).split('\n').map(l=>v.parse(testRow,JSON.parse(l)));assert.ok(rows.length>=3);assert.equal(rows[0].type,'begin');assert.equal(rows.at(-1).type,'end');rows.forEach((r,i)=>{assert.equal(r.ordinal,i);if(r.type==='begin')assert.equal(i,0);if(r.type==='end')assert.equal(i,rows.length-1);});const summaries=rows.filter(r=>r.type==='summary'),global=summaries.filter(r=>r.file===null),perFile=summaries.filter(r=>r.file!==null),cases=rows.filter(r=>r.type==='case'),leaves=cases.filter(r=>!r.suite);assert.equal(global.length,1);assert.strictEqual(rows.at(-2),global[0]);assert.equal(new Set(perFile.map(s=>s.file)).size,perFile.length);assert.deepEqual(perFile.map(s=>s.file).sort(),[...t.files].sort());assert.deepEqual([...new Set(cases.flatMap(c=>c.file===null?[]:[c.file]))].sort(),[...t.files].sort());assert.deepEqual(leaves.map(c=>c.name).sort(),[...s.selectedTitles].sort());assert.equal(leaves.length,s.expectedTestCount);assert.ok(leaves.every(c=>c.passed&&!c.skip&&!c.todo&&c.error===null));assert.ok(summaries.every(s=>s.success));const n=global[0].counts;assert.equal(n.tests,leaves.length);assert.equal(n.passed,leaves.length);for(const k of ['failed','cancelled','skipped','todo'])assert.equal(n[k],0);assert.equal(n.suites,cases.filter(c=>c.suite).length);for(const k of ['tests','passed','failed','cancelled','skipped','todo','suites'])assert.equal(perFile.reduce((sum,s)=>sum+s.counts[k],0),n[k]);tests.push({commandId:t.commandId,counts:n,files:t.files,cases,summaries});mark('strict test report '+t.commandId);}
  assert.equal(tests.reduce((n,t)=>n+t.counts.tests,0),30);
  const lintCommand=o.commandResults.find(c=>c.commandId===recipe.lint.commandId),lint=v.parse(lintSchema,JSON.parse(stream(lintCommand.stdout)));assert.deepEqual(lint.files.map(({path,kind})=>({path,kind})),recipe.lint.files);assert.equal(new Set(lint.files.map(f=>f.path)).size,lint.files.length);assert.equal(lint.passed,true);assert.ok(lint.files.every(f=>f.disposition==='passed'&&f.diagnostic===null));mark('strict syntax lint full population');
  const comparison=JSON.parse(await fs.readFile(join(workspaceRoot,'verification/reports/generated-comparison.json'),'utf8'));assert.deepEqual(keys(comparison),['actualCount','basisInventorySha256','changed','equal','expectedCount','extra','kind','missing']);assert.equal(comparison.kind,'exact_generated_comparison');assert.equal(comparison.basisInventorySha256,expected.basisInventorySha256);assert.equal(comparison.expectedCount,925);assert.equal(comparison.actualCount,925);assert.deepEqual(comparison.missing,[]);assert.deepEqual(comparison.extra,[]);assert.deepEqual(comparison.changed,[]);assert.equal(comparison.equal,true);for(const r of expected.paths){const bytes=await fs.readFile(join(workspaceRoot,'verification',r.path));assert.equal(bytes.length,r.bytes);assert.equal(product.sha256Bytes(bytes),'sha256:'+r.sha256);}mark('925 output comparisons');
  const result={status:'passed',actualRun:value.run,actualProducer:terminal.producer,task:{ref:task.taskRef,digest:task.taskDigest},sourceObservedInput:task.sourceObservedInput,commands,predicates:o.predicateObservations,tests,lint,comparison,protectedObservations:716,qualification:'not constructed; no executionSelectionRef/tenant basis invented'};await write('observed-output-checks.json',result);return {observation:o,checks:result};
 }
 function cold(value,reads){const rp=reads.run_result.ownerOutput.value,re=reads.run_replay.ownerOutput.value;assert.deepEqual(rp.source,value.run);assert.deepEqual(re.source,value.run);assert.deepEqual(rp.projection.terminalResult,value.terminalResult);assert.deepEqual(re.projection.terminalResult,value.terminalResult);assert.deepEqual(rp.projection.result,value.result);assert.deepEqual(rp.projection.replay,value.replay);assert.deepEqual(re.projection.replay,value.replay);assert.equal(re.projection.status,'closed');assert.equal(rp.projection.terminalResult.producer.runRef,value.run.ref);return {status:'passed',source:value.run,producer:value.terminalResult.producer,typedTerminalResultEqual:true,resultEqual:true,replayEqual:true,closed:true};}
 return {consume,cold};
}
