import assert from 'node:assert/strict';
const keys=x=>Object.keys(x).sort(),sort=xs=>[...xs].sort((a,b)=>a.ref.localeCompare(b.ref)||a.digest.localeCompare(b.digest));
function definitionJoin(call,verified){const k=call.invocation.definitionKey,m=verified.definitionContractCoordinates.operations.find(x=>x.operationId===k.operationId)?.members.find(x=>x.memberKey===k.memberKey);assert.ok(m);assert.deepEqual(call.invocation.requestContract,m.slots.request);assert.deepEqual(call.invocation.contractCatalog,m.slots.request.contractCatalog);}
export async function checkStart(c,prepared){
 const {product,abg,state,verified,hash}=c,{call,resolution}=prepared;definitionJoin(call,verified);assert.equal(product.isRunInvocationResourceAssertion(call.resources),true,'actual native wrapper resource predicate');assert.deepEqual(keys(call.resources),['applicationResources','applications','catalog','catalogView','eventResource','kind','runEnvironmentResources','schemaVersion','source']);assert.deepEqual(call.resources.applications,[]);assert.deepEqual(call.resources.applicationResources,[]);assert.deepEqual(call.resources.source,{kind:'none'});assert.deepEqual(call.resources.catalog,state.catalog);assert.deepEqual(call.resources.catalogView,state.catalogView);assert.deepEqual(call.resources.eventResource,c.reopen());assert.deepEqual(call.invocation.request.sourceBasis,{kind:'none'});assert.equal(call.invocation.request.rootMode,'direct');assert.equal(call.invocation.request.until,'converged');assert.equal(call.invocation.request.program.ref,'program://abiogenesis/worksite/command-execution@5');
 assert.ok(Object.hasOwn(resolution.program.policies,c.gtl.RUN_ENVIRONMENT_POLICY));
 const inner={catalog:call.resources.catalog,catalogView:call.resources.catalogView,applications:call.resources.applications,source:call.resources.source,runEnvironmentResources:call.resources.runEnvironmentResources};
 const owner=await product.ProductRunInvocationPort.prepare({memberKey:'start',invocation:call.invocation,resources:inner,admittedInstalls:state.environment.productInstalls,workspaceBinding:state.environment.workspaceBinding,verifyInstallAdmission:i=>abg.hasAdmittedProductInstall(state.environment.artifactTruth,i),transportResourceAssertion:call.resources.eventResource});assert.equal(owner.kind,'prepared_product_run_invocation',JSON.stringify(owner));assert.ok(owner.runEnvironment);assert.deepEqual(owner.runEnvironment,prepared.environmentObservation.evidence);assert.deepEqual(owner.admittedInput,call.invocation.request.input.value);assert.equal(call.invocation.request.input.valueDigest,hash(owner.admittedInput));
 return {actualCall:call,nativeWrapperPredicate:true,ownerConsumedInnerResources:inner,transportResourceAssertion:call.resources.eventResource,existingProductPreparation:{kind:owner.kind,programRef:owner.resolution.program.programRef,admittedInput:owner.admittedInput,policy:owner.policy,grants:owner.grants,authority:owner.authority,runEnvironment:owner.runEnvironment},claim:'Native wrapper and actual Product owner preparation use real current A/W/grants/input and observed installed renderer environment; no Run/event/provider dispatch yet'};
}
export async function checkReadCall({product,abg,call,state,verified,run,closed,grants,write,label}){
 definitionJoin(call,verified);const r=call.resources,q=call.invocation.request,slots=call.invocation.invocationAuthority.slots,k=call.invocation.definitionKey.memberKey;assert.ok(['run_result','run_replay'].includes(k));assert.deepEqual(keys(r),['eventResource','kind','schemaVersion']);assert.equal(r.kind,'abg_project_read_resource_assertion');assert.equal(r.schemaVersion,'5.0.0');assert.deepEqual(r.eventResource,{kind:'reopen_abg_event_resource',schemaVersion:'5.0.0',closeHandoff:state.closeHandoff,handoffDigest:product.sha256Canonical(state.closeHandoff)});assert.deepEqual(state.closeHandoff.prefix,closed.prefix);assert.equal(q.caseKey,k);assert.deepEqual(q.source,{sourceKind:'run',sourceRef:run.ref,sourceDigest:run.digest});assert.deepEqual(q.projectionBasis,{projectionBasisRef:closed.prefix.eventLogRef,projectionBasisDigest:closed.prefix.coordinateDigest});assert.deepEqual(q.selector,k==='run_result'?{kind:'none'}:{kind:'ordinal_page',fromOrdinal:0,limit:1000});
 const environment=abg.projectExactPrefixWorkspaceEnvironment(state.closeHandoff.prefix,state.binding);assert.equal(environment.kind,'exact_prefix_workspace_environment');const packet=abg.ABG_PROJECT_READ_CONTRACTS[k],expectedGrants=packet.metadata.capabilityRefs.map(cap=>product.constructCapabilityGrant(environment.workspaceAuthorityBasis,environment.workspaceBinding.authorizedActorRef,packet.definitionKey.operationId,cap,{admittedInstalls:environment.productInstalls,workspaceBinding:environment.workspaceBinding,fixedPacket:packet}));assert.deepEqual(grants,expectedGrants);
 const expected=Object.fromEntries(Object.keys(slots).map(n=>[n,null]));Object.assign(expected,{workspace_binding:{ref:environment.workspaceBinding.bindingId,digest:environment.workspaceBinding.bindingDigest},product_set:environment.productInstalls.map(i=>({ref:i.installId,digest:i.productContentDigest})),dependency_lock:{ref:environment.resolvedProductLock.lockId,digest:environment.resolvedProductLock.lockDigest},capability_grants:{requiredCapabilityRefs:[...packet.metadata.capabilityRefs],grants:expectedGrants.map(g=>({ref:g.grantRef,digest:g.grantDigest}))}});assert.deepEqual(slots,expected);
 await write(label+'-owner-precondition.json',{actualCall:call,currentEnvironment:environment,actualProducedRun:run,expectedGrants,ownerResourceKeys:keys(r),claim:'Actual genuine Run/latest handoff, exact three-key resource, current reader metadata and owner-derived authority; runtime read projection still performed by separate installed CLI'});
}
