import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const D=path.dirname(fileURLToPath(import.meta.url)),G=path.dirname(D),S=path.join(G,'final-f11-scope-inputs-01'),I=path.join(G,'final-candidate-construction-01/install/node_modules/@abiogenesis/typescript-tenant');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex'),need=(x,m)=>{if(!x)throw new Error(m);};
const index=read(path.join(S,'material-index.json')), bodyIndex=read(path.join(S,'body-input-index.json')), scope=read(path.join(S,'scope-body.json')),cat=read(path.join(I,'contracts/qualification/rule-catalog.json'));
let count=0,originalBytes=0;const decodedCoordinates=[];
for(const m of [...index.materials,...index.authorityMaterials]){const a=read(path.join(S,m.file)),b=Buffer.from(a.contentBase64,'base64');need(b.toString('base64')===a.contentBase64&&b.length===m.byteCount&&sha(b)===m.digest&&['ref','path','digest','byteCount'].every(k=>m[k]===a[k]),'material '+m.ref);count++;originalBytes+=b.length;decodedCoordinates.push({ref:m.ref,digest:m.digest,byteCount:m.byteCount});}
const byRef=new Map(index.materials.map(m=>[m.ref,m]));for(const m of index.authorityMaterials)byRef.set(m.ref,m);
let spans=0;for(const r of cat.rules){const s=cat.sources.find(s=>s.ref===r.sourceRef),b=fs.readFileSync(path.join(I,s.path));need(sha(b)===r.sourceDigest&&b.length===s.byteCount&&r.startByte>=0&&r.endByte<=b.length&&r.startByte<r.endByte&&sha(b.subarray(r.startByte,r.endByte))===r.spanDigest,'rule span '+r.ruleRef);spans++;}
const memberByRef=new Map(scope.inventory.members.map(m=>[m.ref,m])),criteria=new Map(),roleTotals={};let declaredMembers=0;
for(const row of bodyIndex.packets){const p=read(path.join(S,row.file)),refs=new Set(p.materialRefs);need(refs.size===p.materialRefs.length&&p.materialRefs.every(r=>byRef.has(r)), 'selected material refs '+p.label);need(p.subjectMembers.every(m=>{const s=memberByRef.get(m.ref);return s&&['ref','path','digest','byteCount'].every(k=>s[k]===m[k]);}),'selected subject '+p.label);need(p.contextMembers.length===refs.size&&p.contextMembers.every(m=>{const s=byRef.get(m.memberRef);return s&&['path','digest','byteCount'].every(k=>s[k]===m[k]);}), 'context correspondence '+p.label);need(p.materialRefs.reduce((n,r)=>n+byRef.get(r).byteCount,0)===row.providedBodyBytes,'body count '+p.label);declaredMembers+=p.subjectMembers.length;roleTotals[p.roleName]??={packets:0,criteria:0,rawSelectedBytes:0};roleTotals[p.roleName].packets++;roleTotals[p.roleName].criteria+=p.coverage.length;roleTotals[p.roleName].rawSelectedBytes+=row.providedBodyBytes;for(const c of p.coverage){need(!criteria.has(c.criterionRef),'duplicate criterion in primitive selections');criteria.set(c.criterionRef,c);}}
const proofMembers=scope.surfaceGroups.find(g=>g.groupRef.endsWith('/proof_historical_records')).memberRefs;
const fixtureStructure=proofMembers.map(ref=>{const m=byRef.get(ref),body=read(path.join(S,m.file)),b=Buffer.from(body.contentBase64,'base64');let shape;try{const j=JSON.parse(b.toString('utf8'));shape=Array.isArray(j)?{type:'array',length:j.length}:typeof j==='object'&&j!==null?{type:'object',keys:Object.keys(j),shortScalars:Object.fromEntries(Object.entries(j).filter(([k,v])=>v===null||['string','number','boolean'].includes(typeof v)).map(([k,v])=>[k,typeof v==='string'?v.slice(0,200):v]))}:{type:typeof j};}catch{shape={type:'non-single-JSON retained fixture body'};}return {ref,bytes:b.length,digest:sha(b),shape};});
const result={materialRecords:count,originalBytesChecked:originalBytes,catalogSpansChecked:spans,bodySelectionsChecked:bodyIndex.packets.length,declaredMemberOccurrences:declaredMembers,criterionCount:criteria.size,roleTotals,fixtureStructure,limits:'Mechanical complete material/selection correspondence. Fixture structure is candidate data, not source-session transcripts, not acquired native resources, and not semantic or current execution credit. No complete assessment task fabricated or renderer dispatch invoked.'};
fs.writeFileSync(path.join(D,'observations-02.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
