import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,readdir,copyFile,symlink} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const repository='/Users/jim/src/apps/abiogenesis',tenant=join(repository,'build_tenants/abiogenesis/typescript'),records=join(repository,'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE'),evidence=join(records,'s6-declared-source-projection-01/installed-live-03');
const load=path=>import(pathToFileURL(join(tenant,path)).href),save=(name,value)=>writeFile(join(evidence,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
const {setupInstalledRootCatalog}=await load('test_env/support/root-installed-environment.mjs');
const {prepareRegisteredSelectionProduct,constructInstalledStartCall}=await load('test_env/support/registered-graph-selection.mjs');
const {libraryEnvironment,witnessRef,schemaPath}=await load('test_env/support/default-library.mjs');
const {prepareFulfillmentSeed,fulfillmentWitnessInput,fulfillmentAssessmentSchema,fulfillmentConsumerDeclaration,freshLifecyclePaths}=await load('test_env/support/default-library-fulfillment.mjs');
const accounting={wallMs:{}};let selectedEnvironment;const started=performance.now();
const constructors=['constructDefaultGovernanceLibraryModulePublication','constructNativeWorkspaceWorkModulePublication','constructWorksiteCommandExecutionModulePublication'];
const env=await setupInstalledRootCatalog({after:()=>{}},tenant,{frozenArtifact:{artifactPath:join(records,'s6-declared-source-projection-01/core.tgz'),artifactSha256:'sha256:08d95ee6fc816e413f8f6deaf43c1f106d1c202c942eead9af47bb962cd30110',installHost:join(evidence,'bootstrap-host')},candidateBasisSource:'packed_artifact',workspaceProductIndex:1,setupAccounting:accounting,additionalCorePublicationConstructors:constructors,
 prepareAdditionalProducts:async setup=>{
  selectedEnvironment=await libraryEnvironment(setup);
  const archive=join(records,'s6-declared-source-projection-01/core.tgz'),p=setup.abiPublication;
  const library=setup.gtl.constructDefaultGovernanceLibraryModulePublication({productId:p.owningProductId,packageName:p.productSemanticsBinding.packageName,packageVersion:p.productSemanticsBinding.packageVersion,artifactDigest:p.artifactDigest,productContentDigest:p.productContentDigest,productManifestDigest:p.productManifestDigest});
  const schema=join(setup.scratch,'assessment.schema.json');await writeFile(schema,JSON.stringify(fulfillmentAssessmentSchema(setup.product))+'\n');
  return [await prepareRegisteredSelectionProduct({...setup,abiPackageArchivePath:archive,declarationFactory:gtl=>fulfillmentConsumerDeclaration({gtl,product:setup.product,library,runEnvironment:selectedEnvironment.declaration}),fixtureFiles:[{path:'build/index.mjs',source:join(tenant,'test_env/fixtures/default-library-product/index.mjs')}],schemaAssets:[{path:schemaPath,source:schema,contractId:witnessRef('contract','assessment'),requirementAuthorityRefs:[witnessRef('obligation','complete-original')]}]})];
 }});
await save('setup.json',{scratch:env.scratch,installedRoots:env.installedRoots,artifactPaths:env.artifactPaths,accounting});
await symlink('../core.tgz',join(evidence,'core.tgz'));await copyFile(env.additionalProducts[0].artifactPath,join(evidence,'consumer.tgz'));
const host=join(evidence,'frozen-host');await mkdir(join(host,'node_modules/@abiogenesis'),{recursive:true});await symlink(env.installedRoot,join(host,'node_modules/@abiogenesis/typescript-tenant'));
await save('frozen-artifact.json',{artifactPath:join(evidence,'core.tgz'),artifactSha256:await env.product.sha256File(env.artifactPath),installHost:host});
await save('archive.json',{core:{path:join(evidence,'core.tgz'),sha256:await env.product.sha256File(env.artifactPath)},consumer:{path:join(evidence,'consumer.tgz'),sha256:await env.product.sha256File(env.additionalProducts[0].artifactPath),basis:env.additionalProducts[0].basis}});
await save('publication.json',env.additionalPublications[0]);await save('run-environment.json',selectedEnvironment.declaration);
const worksite=env.workspaceBinding.canonicalRoot??env.workspaceAuthority.canonicalRoot;
const files=await prepareFulfillmentSeed({seedRoot:join(records,'default-library-witness/seed'),caseContractPath:join(records,'s6-witness-contract.md'),destination:worksite}),input=fulfillmentWitnessInput({product:env.product,files});
await save('input.json',input);await save('fulfillment-policy.json',input.original.fulfillment);
await writeFile(join(evidence,'assessment.schema.json'),Buffer.from(input.original.assessment.schemaAsset.bytesBase64,'base64'),{flag:'wx'});
await save('input-files.json',Object.fromEntries(Object.entries(files).map(([path,bytes])=>[path,{bytes:bytes.length,sha256:env.product.sha256Bytes(bytes)}])));
const refs=env.additionalPublications[0].programs[0].callableMembership;env.catalogView=env.product.narrowGraphFunctionCatalog(env.catalog,refs);assert.equal(env.catalogView.kind,'graph_function_catalog_view');
const publicApi=await import(pathToFileURL(join(env.installedRoot,'build/code/src/public/index.js')).href),physical=await import(pathToFileURL(join(env.installedRoot,'build/code/src/product/worksite_operations.js')).href);
const handoff=env.store.projectReopenAuthorityAndClose();await save('handoff-before-start.json',handoff);
const start=await constructInstalledStartCall({environment:env,publicApi,eventResource:{kind:'reopen_abg_event_resource',schemaVersion:'5.0.0',closeHandoff:handoff,handoffDigest:env.product.sha256Canonical(handoff)},input,identity:'s6-fulfillment',runEnvironmentResourceFactory:selectedEnvironment.resources});
const closure=env.product.resolveProgramDeclarationClosure(env.catalog,env.catalogView,start.resolution.program.programRef);assert.equal(closure.kind,'resolved_program_declaration_closure',JSON.stringify(closure));
const lookup=ref=>{const rows=env.publications.flatMap(p=>p.contracts).filter(c=>c.contractRef===ref);return rows.length===1?rows[0]:null;};
assert.ok(env.product.governanceFulfillmentContractsMatch(input.original.fulfillment,lookup));
const context=await physical.observeWorksiteContext({workspaceAuthorityBasis:env.workspaceAuthority,workspaceBinding:env.workspaceBinding,capabilityGrant:start.capabilityBasis.capabilityGrants[0],protectedInstallRoots:env.installedRoots,readRoots:input.original.readRoots,maxFiles:input.original.maxContextFiles,maxBytes:input.original.maxContextBytes});
assert.equal(context.kind,'worksite_context_observation');assert.ok(env.product.governanceFulfillmentSourceMatches(input.original.fulfillment,context));
for(const path of freshLifecyclePaths)assert.equal(context.entries.find(e=>e.relativePath===path)?.state,'absent');
for(const [path,bytes]of Object.entries(files))assert.equal(context.entries.find(e=>e.relativePath===path)?.digest,env.product.sha256Bytes(bytes));
const schemaInstalled=join(env.installedRoots[1],schemaPath);assert.deepEqual(await readFile(schemaInstalled),Buffer.from(input.original.assessment.schemaAsset.bytesBase64,'base64'));
await save('context.json',context);await save('start-prepared.json',start);await save('contract-owners.json',closure.contractOwners);
await save('readiness.json',{ready:true,launchAuthorized:false,providerCalls:0,setupMs:performance.now()-started,accounting,sourceCaseSha256:await env.product.sha256File(join(records,'s6-witness-contract.md')),inputSha256:env.product.sha256Canonical(input),publicCallBytes:Buffer.byteLength(JSON.stringify(start.call)),contextBytes:context.entries.filter(e=>e.state==='file').reduce((n,e)=>n+e.byteLength,0),initialFiles:Object.keys(files).length,absentAssets:freshLifecyclePaths,initialObligations:input.fulfillment.coverage.length,schemaInstalled,worksite,callableMembership:refs,checks:['actual core/consumer verify/install/catalog','imported exact pair contract owners','Program profile selection','exact original source/span binding','four assets absent','installed immutable schema equals input','prepared Public start only; no run or actor']});
console.log(JSON.stringify({ready:true,setupMs:performance.now()-started,archiveSha256:await env.product.sha256File(env.artifactPath)}));

const prior=join(records,'s6-fulfillment-implementation');
for(const name of ['input.json','input-files.json','assessment.schema.json','fulfillment-policy.json']) assert.deepEqual(await readFile(join(evidence,name)),await readFile(join(prior,name)),name+' changed');
await save('unchanged-case.json',{exactFiles:['input.json','input-files.json','assessment.schema.json','fulfillment-policy.json'],caseContractSha256:await env.product.sha256File(join(records,'s6-witness-contract.md')),providerCalls:0,oldInstallationReused:false,oldRunModified:false});
