import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {assertScenario} from './scenario-oracles.mjs';
const deepFreeze=x=>{if(x&&typeof x==='object'&&!Object.isFrozen(x)){for(const v of Object.values(x))deepFreeze(v);Object.freeze(x);}return x;};
export async function verifyCase(c,row,input,started,reads,before,after){
 const {product,hash,abg}=c,v=started.receipt.ownerOutput?.value;
 assert.deepEqual(started.issues,[],JSON.stringify(started.issues));assert.equal(started.receipt.ownerOutput.outcomeKind,'result');assert.ok(v.run&&v.graphCall);
 const bytes=await readFile(new URL(after.prefix.eventLogRef));assert.equal(bytes.length,after.prefix.prefixLength);assert.equal(product.sha256Bytes(bytes),after.prefix.prefixDigest);assert.equal(product.sha256Bytes(bytes.subarray(0,before.prefix.prefixLength)),before.prefix.prefixDigest);assert.deepEqual(before.prefix.storeIdentity,after.prefix.storeIdentity);
 const delta=bytes.subarray(before.prefix.prefixLength).toString('utf8');assert.ok(delta.endsWith('\n'));const events=delta.trimEnd().split('\n').map(JSON.parse),all=k=>events.filter(e=>e.kind===k),byId=id=>{const xs=events.filter(e=>e.eventId===id);assert.equal(xs.length,1,id);return xs[0];};
 assert.ok(events.every(e=>e.runId===null||e.runId===undefined||e.runId===v.run.ref));assert.equal(all('run_segment_opened').length,1);assert.equal(all('actor_invocation_started').length,0);assert.equal(all('actor_result_artifact_observed').length,0);assert.ok(all('c_call_fibre_selected').every(e=>e.payload.regime==='F_D'));assert.equal(events.filter(e=>e.kind.startsWith('worksite_')||e.kind==='work_committed').length,0);
 const replay=reads.run_replay.ownerOutput;assert.equal(replay.outcomeKind,'result');assert.deepEqual(replay.value.source,v.run);assert.deepEqual(replay.value.projection.replay,v.replay);assert.deepEqual(replay.value.projection.terminalResult,v.terminalResult??null);assert.deepEqual(c.state.closeHandoff.prefix,after.prefix);
 let expected=null;
 if(row.expected==='completed'){
  assert.equal(v.disposition,'completed');assert.equal(v.stop,null);assert.ok(abg.isAbgTypedTerminalResult(v.terminalResult));assert.equal(replay.value.projection.status,'closed');
  const result=reads.run_result.ownerOutput;assert.equal(result.outcomeKind,'result');assert.deepEqual(result.value.source,v.run);assert.deepEqual(result.value.projection.terminalResult,v.terminalResult);assert.deepEqual(result.value.projection.result,v.result);assert.deepEqual(result.value.projection.replay,v.replay);
  expected=row.case==='recursive-foldback'?{...input,remaining:0,terminal:true,trace:[2,1,0]}:row.case==='ordered-vector'?{kind:'fan_out_hello_summary',schemaVersion:'5.0.0',count:3,messages:['Hello Alpha','Hello Beta','Hello Gamma']}:{kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello World'};
  assert.deepEqual(v.terminalResult.value,expected);assert.equal(v.terminalResult.valueDigest,hash(expected));assert.deepEqual(v.result,v.terminalResult.result);
  const p=v.terminalResult.producer;assert.equal(p.runRef,v.run.ref);assert.equal(p.graphCallRef,v.graphCall.ref);assert.deepEqual(p.program,started.call.invocation.request.program);assert.equal(p.graphFunction.ref,row.graphFunctionRef);assert.deepEqual(p.graphFunction,started.call.invocation.invocationAuthority.slots.graph_function.graphFunction);assert.deepEqual(v.terminalResult.projectionBasis,{ref:after.prefix.eventLogRef,digest:after.prefix.coordinateDigest});
  const r=byId(p.resultAdmissionEventRef),j=byId(p.judgmentAdmissionEventRef);assert.equal(r.kind,'c_call_result_admitted');assert.equal(j.kind,'c_call_judged');assert.equal(r.payload.cCallRef,p.cCallRef);assert.equal(j.payload.cCallRef,p.cCallRef);assert.equal(j.payload.resultRef,r.payload.resultRef);assert.equal(j.payload.resultDigest,r.payload.resultDigest);assert.equal(j.payload.judgmentRef,p.judgmentRef);assert.deepEqual(r.payload.value,expected);
  const routes=all('traversal_route_admitted').filter(e=>e.payload.routeRef===p.terminalRoute.ref&&e.payload.routeDigest===p.terminalRoute.digest);assert.equal(routes.length,1);assert.equal(routes[0].payload.routeKind,'terminal');assert.equal(routes[0].payload.targetCursorRef,null);
  const reached=all('terminal_reached').find(e=>e.graphCallId===v.graphCall.ref),frameClosed=all('frame_closed').find(e=>e.graphCallId===v.graphCall.ref),graphClosed=all('graph_call_closed').find(e=>e.graphCallId===v.graphCall.ref);assert.ok(reached&&frameClosed&&graphClosed);assert.equal(all('run_closed').length,1);const closed=all('run_closed')[0];assert.ok(reached.causationEventRefs.includes(routes[0].eventId));assert.equal(frameClosed.payload.terminalReachedEventRef,reached.eventId);assert.ok(frameClosed.causationEventRefs.includes(reached.eventId));assert.equal(graphClosed.payload.frameClosedEventRef,frameClosed.eventId);assert.ok(graphClosed.causationEventRefs.includes(frameClosed.eventId));assert.equal(closed.payload.graphCallClosedEventRef,graphClosed.eventId);assert.ok(closed.causationEventRefs.includes(graphClosed.eventId));assert.equal(events.at(-1).eventId,closed.eventId);
 }else{
  assert.equal(v.disposition,'blocked');assert.equal(v.terminalResult??null,null);assert.equal(replay.value.projection.status,'blocked');assert.equal(all('run_closed').length,0);assert.equal(all('run_stopped').length,1);assert.equal(events.at(-1).kind,'run_stopped');assert.equal(reads.run_result.ownerOutput.outcomeKind,'refusal');assert.equal(reads.run_result.ownerOutput.value.code,'not_found');
 }
 const calls=all('c_call_opened'),spines=calls.map(call=>{
  const same=k=>{const xs=all(k).filter(e=>e.payload.cCallRef===call.payload.cCallRef);assert.equal(xs.length,1,k+':'+call.payload.cCallRef);return xs[0];};const fibre=same('c_call_fibre_selected'),evidence=same('c_call_evidenced'),result=same('c_call_result_admitted'),judgment=same('c_call_judged');assert.ok(fibre.causationEventRefs.includes(call.eventId));assert.ok(evidence.causationEventRefs.includes(fibre.eventId));assert.ok(result.causationEventRefs.includes(evidence.eventId));assert.ok(judgment.causationEventRefs.includes(result.eventId));assert.ok(result.payload.evidenceRefs.includes(evidence.payload.evidenceRef));assert.equal(judgment.payload.resultRef,result.payload.resultRef);assert.equal(judgment.payload.resultDigest,result.payload.resultDigest);assert.ok(['deterministic','sub_traversal'].includes(evidence.payload.evidenceClass));const routes=all('traversal_route_admitted').filter(e=>e.payload.judgmentRef===judgment.payload.judgmentRef);assert.ok(routes.length>0,'actual J has admitted route');assert.ok(routes.some(e=>e.causationEventRefs.includes(judgment.eventId)||e.payload.consumedAvailabilityRefs.includes(judgment.payload.judgmentRef)));
  return {cCallRef:call.payload.cCallRef,graphFunctionRef:call.graphFunctionRef,locus:call.payload.programLocusRef,callClass:call.payload.callClass,attempt:call.payload.attempt,taskOrdinal:call.payload.taskOrdinal,stageRole:call.payload.stageRole,evidenceClass:evidence.payload.evidenceClass,resultClass:result.payload.resultClass,judgment:judgment.payload.judgment,eventRefs:[call,fibre,evidence,result,judgment].map(e=>e.eventId),routes:routes.map(e=>({eventId:e.eventId,routeRef:e.payload.routeRef,routeKind:e.payload.routeKind}))};
 });
 assertScenario(row,started,events,input);
 const prefix=abg.selectValidatedRuntimeEventPrefix(deepFreeze(bytes.toString('utf8').trimEnd().split('\n').map(JSON.parse)));const holds=abg.deriveRuntimeEventCalculusProjection(prefix).holds.map(abg.runtimeFluentKey);const active=holds.filter(x=>['run_active(','graph_call_active(','frame_active(','frame_blocked(','frame_failed(','locus_active(','c_call_active(','parent_waiting_on_child(','child_foldback_available(','terminal_route_available('].some(p=>x.startsWith(p)));assert.deepEqual(active,[],'closed or stopped resource has no active runtime lifecycle');
 return {status:'passed',case:row.case,sourceFixedExpectedDisposition:row.expected,input,expectedOutput:expected,observedDisposition:v.disposition,run:v.run,graphCall:v.graphCall,terminalResult:v.terminalResult??null,stop:v.stop??null,spines,eventCount:events.length,eventKinds:events.map(e=>e.kind),before:before.prefix,after:after.prefix,coldResultOutcome:reads.run_result.ownerOutput.outcomeKind,coldResultRefusal:reads.run_result.ownerOutput.outcomeKind==='refusal'?reads.run_result.ownerOutput.value:null,coldReplayStatus:replay.value.projection.status,coldReadAgreement:true,coldReadAppends:0,activeLifecycleFluents:active,providerCalls:0,modelCalls:0,claim:'Bounded selected C02 native S02 relation; caller proof only, no complete S02/F11/AF22/RC1 claim.'};
}
