import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),read=async n=>JSON.parse(await readFile(join(here,n),'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),setup=await read('setup.json'),load=p=>import(pathToFileURL(join(setup.installedRoots[0],'build/code/src',p+'.js')).href);
const [store,product]=await Promise.all(['abg/event_store','product/index'].map(load));
const handoff=await read('handoff.json'),events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),results=events.filter(e=>e.kind==='c_call_result_admitted'),byId=new Map(events.map(e=>[e.eventId,e])),brief=e=>e?{ordinal:e.admissionOrdinal,eventId:e.eventId,kind:e.kind,graphFunctionRef:e.graphFunctionRef,cCallRef:e.aggregateId,resultRef:e.payload.resultRef??null}:null;
const input=await read('input.json'),effects=await read('effects.json'),timing=await read('timing.json'),syntheses=await read('synthesis-chain.json'),assessment=events.find(e=>e.admissionOrdinal===26469),parents=results.filter(e=>e.graphFunctionRef==='graph-function://default-library-witness/executive@5'&&e.payload.value?.kind==='governance_work_state'),commands=results.filter(e=>e.graphFunctionRef===product.WORKSITE_COMMAND_EXECUTION_IDS.graphFunctionRef&&e.payload.resultClass==='success'),authors=results.filter(e=>e.graphFunctionRef===product.NATIVE_WORKSPACE_WORK_IDS.graphFunctionRef&&e.payload.resultClass==='success');
const chain=syntheses.map(s=>({...s,choice:brief(byId.get(s.choiceEvent)),child:brief(byId.get(s.childEvent)),fold:brief(byId.get(s.foldEvent)),parent:brief(byId.get(s.parentEvent))}));await save('admitted-chain.json',chain);
const scopes=[],actorEvidence=[];
for(const a of timing.actors){const file=a.retained.find(r=>['stdout','stdoutPath'].includes(r.role))?.path;if(!file)continue;const rows=(await readFile(join(here,file),'utf8')).trim().split('\n').map(JSON.parse),final=rows.findLast(r=>r.type==='result'),tools=rows.flatMap(r=>(r.message?.content??[]).filter(c=>c.type==='tool_use').map(c=>({id:c.id,name:c.name,input:c.input}))),outside=tools.filter(t=>t.name==='Bash'&&/\/tmp\//.test(t.input.command??'')||t.name==='Bash'&&/cd \/tmp/.test(t.input.command??''));
 const binding=byId.get(a.bindingEvent);actorEvidence.push({actor:a.actor,binding:brief(binding),actorInvocationRef:binding.parentAggregateId,graphFunctionRef:binding.graphFunctionRef,nativeIntervalMs:a.nativeIntervalMs,promptBytes:a.promptBytes,models:a.reportedModels,costUsd:a.reportedUsage.reduce((n,r)=>n+(r.totalCostUsd??0),0),outputTokens:a.reportedUsage.reduce((n,r)=>n+(r.usage?.output_tokens??0),0)});
 if(outside.length)scopes.push({actor:a.actor,binding:brief(binding),actorInvocationRef:binding.parentAggregateId,rawStdout:file,toolCalls:outside,structuredReport:final?.structured_output??null});
 if(a.actor===12){assert.deepEqual(final.structured_output,assessment.payload.value.assessment);await save('assessment-raw-correspondence.json',{actor:a.actor,rawStdout:file,rawStructuredOutputDigest:product.sha256Canonical(final.structured_output),admittedAssessmentDigest:product.sha256Canonical(assessment.payload.value.assessment),equal:true,assessment:brief(assessment),providerIsError:final.is_error,subtype:final.subtype,sourceResultRef:assessment.payload.resultRef});}
}
await save('native-scope-evidence.json',{scope:'Exact raw tool calls and reports from retained actors containing observed /tmp use; not a global host filesystem audit. Original logs remain authoritative.',actors:scopes,findings:[{actor:4,paths:['/tmp/hw.out','/tmp/hw.err'],operation:'write stdout/stderr scratch then delete',disclosedInReport:true},{actor:10,paths:['/tmp/<mktemp>/sub/cwd.test.mjs'],operation:'create temporary cwd probe then recursively delete its directory',disclosedInReport:false,reportClaim:'I wrote the three assets in my write scope ... I wrote nothing else.'},{actor:12,paths:['/tmp'],operation:'change working directory and attempt unsupported off-root CLI invocation; no write shown in this retained command'}],effectComplianceClaim:false});
const intervals=events.filter(e=>e.kind==='actor_invocation_started').map(e=>{const end=events.find(x=>['actor_invocation_closed','actor_invocation_failed'].includes(x.kind)&&x.parentAggregateId===e.parentAggregateId);return [Date.parse(e.eventTime),end?Date.parse(end.eventTime):Infinity];});
const gaps=events.slice(1).flatMap((e,i)=>{const a=Date.parse(events[i].eventTime),b=Date.parse(e.eventTime);return intervals.some(([s,t])=>a<t&&b>s)?[]:[{ms:b-a,from:brief(events[i]),to:brief(e)}];}).sort((a,b)=>b.ms-a.ms);
const protectedChecks=input.original.sources.map(s=>({path:s.path,expected:s.digest,actual:effects[s.path].sha256,equal:s.digest===effects[s.path].sha256}));assert.ok(protectedChecks.every(x=>x.equal));for(const p of parents)assert.deepEqual(p.payload.value.original,input.original);
const outcome={disposition:'runtime_failed',assessment:brief(assessment),assessmentMeaning:assessment.payload.value.assessment.disposition,assessmentActor:assessment.payload.value.provenance.actorInvocationRef,producer:assessment.payload.value.task.assessment.producer,independentActor:assessment.payload.value.provenance.actorInvocationRef!==assessment.payload.value.task.assessment.producer.actorInvocationRef,assessmentChangedPaths:assessment.payload.value.changedPaths,assessmentFoldAccepted:false,coverageAccepted:false,runClosureEvents:events.filter(e=>e.kind==='run_closed').map(brief),parentCount:parents.length,lastParent:brief(parents.at(-1)),lastParentTerminal:parents.at(-1).payload.value.terminal,lastCoverage:parents.at(-1).payload.value.fulfillment.coverage,additions:parents.at(-1).payload.value.fulfillment.additions,originalConserved:true,protectedFiles:protectedChecks,effects,commands:commands.map(e=>({...brief(e),sourceObservedInput:!!e.payload.value.task.sourceObservedInput,sourceNativeResult:!!e.payload.value.task.sourceNativeResult,actorInvocationRef:e.payload.value.provenance.actorInvocationRef,dependencies:e.payload.value.task.protectedObservations.map(p=>({path:p.subject.relativePath,digest:p.observation.fileDigest})),results:e.payload.value.commandResults.map(c=>({commandId:c.commandId,exitStatus:c.exitStatus,timedOut:c.timedOut,stdout:Buffer.from(c.stdout.payload,'base64').toString(),stderr:Buffer.from(c.stderr.payload,'base64').toString()}))})),authors:authors.map(e=>({...brief(e),actorInvocationRef:e.payload.value.provenance.actorInvocationRef,changedPaths:e.payload.value.changedPaths,beforeAbsent:e.payload.value.before.entries.filter(r=>r.state==='absent').map(r=>r.relativePath),report:e.payload.value.report})),actorEvidence,timing:{executionMs:timing.executionMs,nativeMs:timing.nativeMs,frameworkOutsideNativeMs:timing.frameworkOutsideNativeMs,actors:timing.actors.length,promptBytes:timing.actors.reduce((n,a)=>n+a.promptBytes,0),events:timing.eventCount,totalReportedUsd:actorEvidence.reduce((n,a)=>n+a.costUsd,0),outputTokens:actorEvidence.reduce((n,a)=>n+a.outputTokens,0),maxAdjacentDeterministicInterval:gaps[0],deterministicIntervalsOver10s:gaps.filter(x=>x.ms>10000)},readback:await read('readback-timing.json')};await save('outcome-evidence.json',outcome);
await save('first-failure.json',{stage:'uat-retained-fold',firstEvidence:brief(events.find(e=>e.admissionOrdinal===26497)),firstResult:brief(events.find(e=>e.admissionOrdinal===26499)),diagnosticRef:'diagnostic://abiogenesis/default-library/missing-owned-fold@5',exactCause:'Nine artifact-support rows have nonnull commandId; first complete-original.support[0] violates profile binder. Raw structural schema permits it; role applicability omitted from presentation.',downstreamRuntime:brief(events.find(e=>e.admissionOrdinal===26522)),downstreamLauncher:'Both cold read receipts saved before readback expected-result assertion on actual not_found; assertion did not cause the Run failure.',noRetry:true});
console.log(JSON.stringify({chain:chain.map(c=>({synthesis:c.synthesisOrdinal,next:c.judgment.nextGraphFunctionRef,choice:c.choice?.ordinal,child:c.child?.ordinal,fold:c.fold?.ordinal,parent:c.parent?.ordinal})),timing:outcome.timing,assessment:outcome.assessment,assessmentMeaning:outcome.assessmentMeaning,effects,scope:scopes.map(s=>({actor:s.actor,commands:s.toolCalls.length}))},null,2));
