import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {join} from 'node:path';
const proof=new URL('.',import.meta.url).pathname,repo=process.cwd(),prior=JSON.parse(await readFile(join(proof,'../selected-action-03/environment.json'),'utf8'));
const load=p=>import(pathToFileURL(join(prior.installedRoot,`build/code/src/${p}.js`)).href);
const product=await load('product/index'),gtl=await load('gtl/index'),validator=await load('validator/index'),traversal=await load('hog/traversal'),cursorOwner=await load('abg/traversal_cursor'),sourcePath=await load('gtl/source_path');
const f=await import(pathToFileURL(join(repo,'build_tenants/abiogenesis/typescript/test_env/fixtures/t287-selected-action-product/index.mjs')).href);
const {rawProgramInput,requireRawAdmission}=await import(pathToFileURL(join(repo,'build_tenants/abiogenesis/typescript/test_env/support/root-installed-environment.mjs')).href);
const d=f.declarations(gtl),digest=product.sha256Canonical({scope:'fixture construction preflight'}),pub=gtl.modulePublication({kind:'module_publication',moduleVersion:'5.0.0',...d,artifactDigest:digest,productContentDigest:digest,productManifestDigest:digest,contributions:d.contributions.map(c=>({...c,provenanceRefs:[digest]}))});
const raw=requireRawAdmission(validator,pub,'module_publication','contract://abiogenesis/gtl/module-publication@5'),program=raw.value.programs.find(p=>p.programRef===f.ref('program','root')),graphFunction=raw.value.graphFunctions.find(g=>g.name===f.ref('graph-function','root'));
const validation=validator.validateProgram(rawProgramInput(validator,raw,program));assert.equal(validation.kind,'program_validation',JSON.stringify(validation));
const input=f.fixtureInput({workspaceBinding:prior.workspaceBinding,program}),materializationBasis={invocationAdmissionRef:'invocation-admission://preflight/structural',admittedInputRef:'input://preflight/structural',admittedInputDigest:product.sha256Canonical(input),admittedInput:input},graph=gtl.materializeGraph(graphFunction,materializationBasis),graphValidation=validator.validateGraph(graph,validation,graphFunction,materializationBasis);assert.equal(graphValidation.kind,'graph_validation',JSON.stringify(graphValidation));
const terms=graphFunction.template.nodes[0].term.terms,composition=program.constructionComposition,app=graph.template.applications[0];assert.equal(terms.length,8);assert.equal(app.relationKind,'re_enter');assert.equal(app.maxApplications,1);assert.equal(terms[5].compositionRef,composition.compositionRef);assert.notEqual(terms[5].compositionRef,app.applicationRef,'construction composition identity is preserved; reentry owner binds application by source/target');assert.equal(terms[5].resultBearing,false);assert.equal(terms[5].outputCarrierRef,app.inputContractRef);assert.equal(terms[0].inputCarrierRef,app.outputContractRef);assert.equal(terms[5].programLocusRef,app.sourceProgramLocusRef);assert.equal(terms[0].programLocusRef,app.targetProgramLocusRef);assert.equal(terms[7].programLocusRef,composition.authorities[2].refreshProgramLocusRef);
const expected=['model','gap','next','child','evaluate','refreshModel','refreshGap','finish'];assert.deepEqual(terms.map(t=>t.kind==='c_workflow'?t.graphFunctionRef:t.programLocusRef),expected.map((n,i)=>f.ref(i===3?'graph-function':'locus',n)));
const checkContract=(name,value)=>{const binding=pub.implementationBindings.find(b=>b.namedSymbol===name),contract=pub.contracts.find(c=>c.contractRef===binding.outputContractRef);assert.equal(value.kind,contract.valueKind);assert.equal(value.schemaVersion,'5.0.0');assert.equal(Boolean(f.SEMANTICS.validateContractValue(contract.valueKind,value)),true);return {contractRef:contract.contractRef,valueKind:contract.valueKind};};
const sourceLocus=sourcePath.resolveCProgramLocus(graph.template,app.sourceProgramLocusRef),targetLocus=sourcePath.resolveCProgramLocus(graph.template,app.targetProgramLocusRef);assert.equal(sourceLocus.kind,'c_program_locus');assert.equal(targetLocus.kind,'c_program_locus');
const checks=[];
for(const phase of [0,1]){
 const observation={...input,phase,task:{...input.task,payload:phase===0?'first action':'selected second action'}},basis=f.gap(f.model(observation).resultCandidate).resultCandidate,choice=f.next(basis).resultCandidate;
 assert.deepEqual(basis.admittedActionCatalog,program.actionCatalog);assert.deepEqual(basis.declaredPolicy,composition.closurePolicy);assert.equal(choice.selectedActionRef,f.ref('action',phase===0?'initial':'consumer'));checkContract('model',f.model(observation).resultCandidate);checkContract('gap',basis);checkContract('next',choice);
 // Controlled candidate-only evaluation data: no event or admission is fabricated.
 const evaluation={kind:'action_evaluation_projection',schemaVersion:'5.0.0',observationSnapshot:observation,constructionIntentRef:'construction-intent://preflight/structural',targetOutcomeRef:f.ref('outcome','echo'),edgeClosureDecision:{decisionRef:'edge-closure-decision://preflight/structural'}};
 const refresh=f.refreshModel(evaluation).resultCandidate,refreshContract=checkContract('refreshModel',refresh);
 if(phase===0){assert.equal(refresh.disposition,'re_enter');assert.deepEqual(refresh.targetInput.priorRefreshedModel.evaluation,evaluation);assert.deepEqual(refresh.targetInput.priorRefreshedModel.observationSnapshot,observation);assert.deepEqual(refresh.targetInput.workspaceBinding,input.workspaceBinding);assert.deepEqual(refresh.targetInput.actionCatalog,program.actionCatalog);assert.deepEqual(refresh.targetInput.constructionPolicy,composition.closurePolicy);assert.equal(refresh.targetInput.phase,1);assert.equal(refresh.targetInput.task.payload,'selected second action');assert.equal(refresh.targetInputDigest,product.sha256Canonical(refresh.targetInput));const {projectionRef,projectionDigest,...body}=refresh;assert.equal(projectionDigest,product.sha256Canonical(body));assert.equal(projectionRef,`graph-span-reentry-projection://product/${projectionDigest.slice(7)}`);assert.deepEqual(Object.keys(refresh).sort(),['applicationRef','disposition','graphFunctionRef','kind','projectionDigest','projectionRef','schemaVersion','sourceProgramLocusRef','targetInput','targetInputDigest','targetInputRef','targetProgramLocusRef'].sort());
  const cursor=cursorOwner.constructTraversalCursorCandidate({programRef:program.programRef,executionBasisRef:'execution-basis://preflight/structural',traversalScopeRef:'scope://preflight/structural',runId:'run://preflight/structural',graphCallId:'graph-call://preflight/structural',frameId:'frame://preflight/structural',graphRef:graph.materializationRef,inputRef:'result://preflight/structural',inputDigest:product.sha256Canonical(evaluation),currentNodeRef:sourceLocus.nodeRef,position:'at_term',termPath:sourceLocus.termPath,taskOrdinal:null,attempt:1,retryPath:[]});
  const derived=traversal.deriveGraphSpanReentryCursor(graph,cursor,app,{inputRef:refresh.targetInputRef,inputDigest:refresh.targetInputDigest});assert.equal(derived.kind,'traversal_cursor',JSON.stringify(derived));assert.deepEqual(derived.termPath,targetLocus.termPath);assert.equal(derived.attempt,2);assert.equal(derived.inputDigest,refresh.targetInputDigest);assert.equal(f.next(f.gap(f.model(refresh.targetInput).resultCandidate).resultCandidate).resultCandidate.selectedActionRef,f.ref('action','consumer'));checks.push({phase,refreshContract,disposition:refresh.disposition,targetCursor:derived,targetInputDigest:refresh.targetInputDigest});
 }else{assert.equal(refresh.disposition,'continue');assert.deepEqual(refresh.state.evaluation,evaluation);assert.deepEqual(refresh.state.observationSnapshot,observation);const refreshed=f.refreshGap(refresh).resultCandidate;checkContract('refreshGap',refreshed);assert.deepEqual(refreshed.admittedActionCatalog,program.actionCatalog);assert.deepEqual(refreshed.evaluation,evaluation);assert.equal(refreshed.runtimeFrontier.phase,'post_evidence');const terminal=f.finish(refreshed).resultCandidate,terminalContract=checkContract('finish',terminal);assert.equal(terminal.kind,'next_action_projection');assert.equal(terminal.disposition,'converged');assert.equal(terminal.constructionIntentRef,evaluation.constructionIntentRef);assert.equal(terminal.edgeClosureDecisionRef,evaluation.edgeClosureDecision.decisionRef);assert.equal(terminal.nextActionBasisDigest,refreshed.basisDigest);checks.push({phase,refreshContract,disposition:refresh.disposition,terminalContract,terminal});}
}
const result={status:'passed',scope:'construction preflight only; controlled cursor/evaluation candidates, no runtime event or traversal admission',coreArchiveSha256:await product.sha256File(prior.artifactPaths[0]),programDigest:product.sha256Canonical(program),validation:{kind:validation.kind,diagnostics:validation.diagnostics},graphValidation:{kind:graphValidation.kind,diagnostics:graphValidation.diagnostics},termCount:terms.length,authorityOrder:expected,compositionRef:terms[5].compositionRef,application:app,checks,terminalRuntimeLimit:'Actual current intent/delta lineage and parent closure require installed execution; structural/candidate preflight cannot establish them'};await writeFile(join(proof,'preflight.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,termCount:result.termCount,compositionRef:result.compositionRef,applicationRef:app.applicationRef,phases:checks.map(c=>({phase:c.phase,disposition:c.disposition,kind:c.refreshContract.valueKind,terminal:c.terminal?.kind})),validation:result.validation,graphValidation:result.graphValidation}));
