import {readFile,writeFile,stat}from'node:fs/promises';import{join,dirname}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const p=dirname(fileURLToPath(import.meta.url)),read=async n=>JSON.parse(await readFile(join(p,n),'utf8')),save=async(n,v)=>writeFile(join(p,n),JSON.stringify(v,null,2)+'\n');
const result=await read('composition-result.json'),handoff=await read('latest-handoff.json'),equal=await read('equal-selection-relation.json'),covered=await read('covered/result.json'),cold=await read('covered/semantic-cold-oracle.json'),setup=JSON.parse(await readFile(join(p,'../selected-action-09/same-basis/setup.json'),'utf8'));
const load=m=>import(pathToFileURL(join(setup.installedRoot,'build/code/src',m+'.js')).href);await load('product/index');const eventOwner=await load('abg/event_store'),abg=await load('abg/index'),owner=await load('abg/construction_continuation');
const nativePath=fileURLToPath(handoff.prefix.eventLogRef),bytes=await readFile(nativePath),physical=await stat(nativePath),events=eventOwner.readRuntimeEventsAtDurablePrefix(handoff.prefix),prefix=abg.selectValidatedRuntimeEventPrefix(events),original330=await readFile(join(p,'../selected-action-10/failed-native-prefix.jsonl')),original328=await readFile(join(p,'../selected-action-10/predecessor-328.jsonl'));
await writeFile(join(p,'final-prefix.jsonl'),bytes);
const hosts=[];for(const name of['covered-source','prior-current','fresh-current']){const h=await read(`${name}/host-termination.json`),i=await read(`${name}/interruption.json`),r=await read(`${name}/recovery.json`);let live=true;try{process.kill(h.pid,0);}catch(e){if(e.code==='ESRCH')live=false;else throw e;}hosts.push({name,pid:h.pid,live,signal:h.signal,wallMs:h.wallMs,initialTraversalMs:i.initialTraversalMs,selectedEvent:i.selectedEvent.eventId,logicalEventCount:i.eventCount,recoveryKind:r.kind,recoveredCount:r.validatedEventCount,prefix:r.closeHandoff.prefix});}
const lockPath=join(p,'../selected-action-09/disposable/abiogenesis-event-store-locks-v5',`${physical.dev}-${physical.ino}.lock`);let lock;try{lock=await stat(lockPath);}catch(e){if(e.code!=='ENOENT')throw e;lock=null;}
const supersessions=events.filter(e=>e.kind==='continuation_superseded'&&e.payload.continuationRef===equal.source.continuationRef),operations=events.filter(e=>e.kind==='public_operation_admitted'&&e.payload.continuationKind==='selected_action'&&e.payload.currentContinuationRef===equal.fresh.occurrence.continuationRef);
const receipts={};for(const name of['cover','stop-prior-current']){const r=await read(`${name}-receipt.json`);receipts[name]={wallMs:r.wallMs,ownerOutput:r.output.receipt.ownerOutput};}for(const name of['continue','run_result','run_replay']){const r=await read(`covered/${name}-receipt.json`);receipts[name]={wallMs:r.wallMs,outcomeKind:r.output.receipt.ownerOutput.outcomeKind,boundary:r.output.receipt.resources.eventResource.closeHandoff.prefix};}
await save('closed-summary.json',{status:'passed_bounded_installed_population',eventCount:events.length,physicalBytes:bytes.length,nativeSha256:createHash('sha256').update(bytes).digest('hex'),physicalIdentity:{device:physical.dev,inode:physical.ino},retained330ExactPrefix:bytes.subarray(0,original330.length).equals(original330),retained328ExactPrefix:bytes.subarray(0,original328.length).equals(original328),handoff,hosts,lockPath,lockAbsent:lock===null,coverEvent:equal.coverEvent,selectedOperation:operations,supersessions,finalOccurrences:{source:owner.projectSelectedActionContinuations(prefix,result.sourceRun),prior:owner.projectSelectedActionContinuations(prefix,result.priorCurrentRun),fresh:owner.projectSelectedActionContinuations(prefix,result.currentRun)},equalSelectionDigest:equal.fresh.occurrence.selectedActionDigest,distinctBasis:{prior:equal.prior.basis,current:equal.fresh.basis},actualCurrentChildInput:{basisRef:cold.childInputBasis.payload.basisRef,basisEvent:cold.childInputBasis.eventId,parentCCallRef:cold.childInputBasis.payload.parentCCallRef,parentExecutionBasisRef:cold.childInputBasis.payload.parentExecutionBasisRef,invocationAdmissionRef:cold.childInputBasis.payload.invocationAdmissionRef,run:cold.childInputBasis.runId,value:cold.childInputBasis.payload.rawInputValue,digest:cold.childInputBasis.payload.rawInputDigest,childCCalls:cold.childCalls.map(e=>({eventRef:e.eventId,cCallRef:e.payload.cCallRef,locus:e.payload.programLocusRef}))},receipts,refusals:covered.results,totalMs:result.wallMs,newBuilds:0,newPackages:0,newInstalls:0,sameBasisEffectsRerun:0});
console.log(JSON.stringify({events:events.length,bytes:bytes.length,digest:handoff.prefix.prefixDigest,hosts:hosts.map(h=>({name:h.name,pid:h.pid,live:h.live,selectedCount:h.logicalEventCount,recoveredCount:h.recoveredCount})),lockAbsent:lock===null,operationOrdinals:operations.map(e=>e.admissionOrdinal),supersessionOrdinals:supersessions.map(e=>e.admissionOrdinal),coverOrdinal:equal.coverEvent.admissionOrdinal,receiptCosts:Object.fromEntries(Object.entries(receipts).map(([k,v])=>[k,v.wallMs]))}));
