import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp,cp,copyFile,realpath,symlink,readdir} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const here=dirname(fileURLToPath(import.meta.url)),records=resolve(here,'../..'),repository=resolve(records,'../../../..'),tenant=join(repository,'build_tenants/abiogenesis/typescript');
const save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex'),load=p=>import(pathToFileURL(join(tenant,p)).href);
const frozen=JSON.parse(await readFile(join(here,'../source-use-01/source-generated.json'),'utf8'));
for(const row of [...frozen.source,...frozen.generated])assert.equal(hash(await readFile(join(repository,row.path))),'sha256:'+row.sha256,row.path);
const privateRoot=await realpath(await mkdtemp('/private/tmp/abi5-s7-retained-work-'));await save('private-root.json',{privateRoot,canonicalSubjectReadOnly:true});process.env.TMPDIR=privateRoot;process.env.npm_config_cache=join(privateRoot,'npm-cache');
const {setupInstalledRootCatalog}=await load('test_env/support/root-installed-environment.mjs');
const {prepareRegisteredSelectionProduct,constructInstalledStartCall}=await load('test_env/support/registered-graph-selection.mjs');
const {libraryEnvironment,libraryConsumerDeclaration,witnessInput,witnessRef,schemaPath,assessmentSchema}=await load('test_env/support/default-library.mjs');
const accounting={wallMs:{}};let selectedEnvironment;const started=performance.now();
const env=await setupInstalledRootCatalog({after:()=>{}},tenant,{candidateBasisSource:'packed_artifact',workspaceProductIndex:1,setupAccounting:accounting,
additionalCorePublicationConstructors:['constructDefaultGovernanceLibraryModulePublication','constructNativeWorkspaceWorkModulePublication','constructWorksiteCommandExecutionModulePublication'],prepareAdditionalProducts:async setup=>{
 selectedEnvironment=await libraryEnvironment(setup);const p=setup.abiPublication,library=setup.gtl.constructDefaultGovernanceLibraryModulePublication({productId:p.owningProductId,packageName:p.productSemanticsBinding.packageName,packageVersion:p.productSemanticsBinding.packageVersion,artifactDigest:p.artifactDigest,productContentDigest:p.productContentDigest,productManifestDigest:p.productManifestDigest});
 const schema=join(setup.scratch,'assessment.schema.json');await writeFile(schema,JSON.stringify(assessmentSchema)+'\n');
 const archives=(await readdir(join(setup.scratch,'artifacts'))).filter(p=>p.endsWith('.tgz'));assert.equal(archives.length,1);
 return [await prepareRegisteredSelectionProduct({...setup,abiPackageArchivePath:join(setup.scratch,'artifacts',archives[0]),declarationFactory:gtl=>libraryConsumerDeclaration(gtl,library,selectedEnvironment.declaration,{purposes:['testing','uat'],bound:4}),fixtureFiles:[{path:'build/index.mjs',source:join(tenant,'test_env/fixtures/default-library-product/index.mjs')}],schemaAssets:[{path:schemaPath,source:schema,contractId:witnessRef('contract','assessment'),requirementAuthorityRefs:[witnessRef('obligation','complete-original')]}]})];
}});
await save('setup.json',{scratch:env.scratch,privateRoot,installedRoots:env.installedRoots,artifactPaths:env.artifactPaths,accounting});
await copyFile(env.artifactPath,join(here,'core.tgz'));await copyFile(env.additionalProducts[0].artifactPath,join(here,'consumer.tgz'));
await save('archive.json',{core:{path:join(here,'core.tgz'),sha256:await env.product.sha256File(env.artifactPath)},consumer:{path:join(here,'consumer.tgz'),sha256:await env.product.sha256File(env.additionalProducts[0].artifactPath),basis:env.additionalProducts[0].basis}});
const worksite=env.workspaceBinding.canonicalRoot??env.workspaceAuthority.canonicalRoot,seed=join(records,'default-library-witness/seed');await cp(seed,worksite,{recursive:true});
await copyFile(join(here,'case-contract.md'),join(worksite,'source/witness-contract.md'));
const candidate=join(records,'default-library-implementation/framed-synthesis/correction-02/companion-01/worksite-result/generated/hello-world.mjs');await copyFile(candidate,join(worksite,'generated/hello-world.mjs'));
const selection=JSON.parse(await readFile(join(records,'default-library-witness/selection.json'),'utf8'));
for(const path of Object.keys(selection.seedFiles)){const bytes=await readFile(join(worksite,path));selection.seedFiles[path]={sha256:hash(bytes).slice(7),bytes:bytes.length};}
selection.applicationWriteRoots=[];
const initial=await witnessInput({product:env.product,selection,seedRoot:worksite}),original=structuredClone(initial.original),missing='assessment/consumer-context.md';
original.taskRef=witnessRef('task','retained-supplied-work');delete original.workOrders.construction;
original.readRoots=[...original.readRoots,missing].sort();original.assessment.sources=[...original.assessment.sources,missing];original.workOrders.uat.readFirst=[...original.workOrders.uat.readFirst,missing];
const input=env.product.constructGovernanceWorkState(original);
await save('input.json',input);await save('selection.json',{purposes:['testing','uat'],bound:4,missingAssessmentInput:missing,onlyBetweenRunWrite:missing,originalSourceSha256:selection.seedFiles['source/original-basic-cli.txt'].sha256,oracleSha256:selection.seedFiles['source/basic-cli.oracle.json'].sha256,suppliedCandidate:{path:candidate,sha256:selection.seedFiles['generated/hello-world.mjs'].sha256},claim:'ordinary fresh invocation source use, not exact execution recovery'});
await save('input-files.json',selection.seedFiles);await writeFile(join(here,'assessment.schema.json'),Buffer.from(input.original.assessment.schemaAsset.bytesBase64,'base64'),{flag:'wx'});
await save('publication.json',env.additionalPublications[0]);await save('run-environment.json',selectedEnvironment.declaration);
const refs=env.additionalPublications[0].programs[0].callableMembership;env.catalogView=env.product.narrowGraphFunctionCatalog(env.catalog,refs);assert.equal(env.catalogView.kind,'graph_function_catalog_view');
const publicApi=await import(pathToFileURL(join(env.installedRoot,'build/code/src/public/index.js')).href),physical=await import(pathToFileURL(join(env.installedRoot,'build/code/src/product/worksite_operations.js')).href);
const handoff=env.store.projectReopenAuthorityAndClose();await save('handoff-before-start.json',handoff);
const start=await constructInstalledStartCall({environment:env,publicApi,eventResource:{kind:'reopen_abg_event_resource',schemaVersion:'5.0.0',closeHandoff:handoff,handoffDigest:env.product.sha256Canonical(handoff)},input,identity:'s7-retained-first',runEnvironmentResourceFactory:selectedEnvironment.resources});
const context=await physical.observeWorksiteContext({workspaceAuthorityBasis:env.workspaceAuthority,workspaceBinding:env.workspaceBinding,capabilityGrant:start.capabilityBasis.capabilityGrants[0],protectedInstallRoots:env.installedRoots,readRoots:original.readRoots,maxFiles:original.maxContextFiles,maxBytes:original.maxContextBytes});assert.equal(context.kind,'worksite_context_observation');assert.equal(context.entries.find(e=>e.relativePath===missing)?.state,'absent');
assert.ok(!original.testing.selectedPaths.includes(missing)&&original.assessment.sources.includes(missing)&&!original.sources.some(s=>s.path===missing));
for(const row of original.sources)assert.equal(context.entries.find(e=>e.relativePath===row.path)?.digest,row.digest);
for(const path of ['source/original-basic-cli.txt','source/basic-cli.oracle.json'])assert.deepEqual(await readFile(join(worksite,path)),await readFile(join(seed,path)));
await save('context.json',context);await save('start-prepared.json',start);await save('reader-environment.json',{verified:env.verified,workspaceAuthority:env.workspaceAuthority});
await save('readiness.json',{ready:true,dispatchAuthorized:false,providerCalls:0,setupMs:performance.now()-started,accounting,worksite,privateRoot,inputDigest:env.product.sha256Canonical(input),publicCallBytes:Buffer.byteLength(JSON.stringify(start.call)),initialFiles:Object.keys(selection.seedFiles).length,missingAssessmentInput:missing,contextFileBytes:context.entries.filter(e=>e.state==='file').reduce((s,e)=>s+e.byteLength,0),callableMembership:refs,checks:['exact frozen source/output before packaging','actual core/consumer verification/install/catalog','ordinary Program/input resolution','initial source/oracle exact','assessment-only input absent and excluded from producer dependencies','no Run/actor dispatched']});
for(const row of [...frozen.source,...frozen.generated])assert.equal(hash(await readFile(join(repository,row.path))),'sha256:'+row.sha256,row.path+' mutated');
console.log(JSON.stringify({ready:true,setupMs:performance.now()-started,privateRoot,worksite}));
