import json,pathlib,hashlib,datetime,collections
root=pathlib.Path(__file__).resolve().parent;p=root/'attempt-02';read=lambda f:json.loads(f.read_text());es=read(p/'events.json');times=read(p/'timing.json');execution=read(p/'execution.json');initial=read(p/'input.json');D=lambda s:datetime.datetime.fromisoformat(s.replace('Z','+00:00')).timestamp()*1000
ref=lambda e:{'ordinal':e['admissionOrdinal'],'eventId':e['eventId'],'resultRef':e['payload'].get('resultRef'),'graphFunctionRef':e.get('graphFunctionRef'),'cCallRef':e.get('aggregateId')}
results=[e for e in es if e['kind']=='c_call_result_admitted'];synth=[e for e in results if e['payload']['value'].get('kind')=='framed_synthesis_result'];choices=[e for e in results if e['payload']['value'].get('kind')=='registered_graph_choice'];parents=[e for e in results if e['graphFunctionRef'].endswith('/executive@5')]
correspondence=[]
for index,e in enumerate(synth):
 value=e['payload']['value'];choice=choices[index];assert choice['payload']['value']['graphFunctionRef']==value['judgment']['nextGraphFunctionRef'];assert choice['payload']['value']['input']['value']['synthesis']['judgment']==value['judgment'];assert value['state']['original']==initial['original'];assert value['basis']['previousResultRef']==(None if index==0 else synth[index-1]['payload']['resultRef'])
 fold=next(r for r in results if r['payload']['value'].get('kind')=='governance_work_state' and r['payload']['value']['observations'] and r['payload']['value']['observations'][-1]['synthesisResultRef']==e['payload']['resultRef']);obs=fold['payload']['value']['observations'][-1];source=next(r for r in results if r['payload']['resultRef']==obs['resultRef'] and r['aggregateId']==obs['cCallRef']);parent=next(r for r in parents if r['admissionOrdinal']>fold['admissionOrdinal']);fixed=source;binding=next(r for r in es if r['kind']=='actor_transport_binding_admitted' and r['parentAggregateId']==e['aggregateId']);
 correspondence.append({'assembly':ref(binding),'synthesis':ref(e),'boundBasis':value['basis'],'contributions':value['judgment']['contributions'],'revisionReason':value['judgment']['revisionReason'],'revisionEvidenceRefs':value['judgment']['revisionEvidenceRefs'],'choice':ref(choice),'choiceReason':choice['payload']['value']['reason'],'fixedChildResult':ref(fixed),'retainedSourceResult':ref(source),'fold':ref(fold),'parentReevaluation':ref(parent),'parentTerminal':parent['payload']['value']['terminal']})
for e in parents:
 v=e['payload']['value'];assert v['original']==initial['original'];assert not v['terminal'];assert v['unresolvedSupportRefs']==initial['unresolvedSupportRefs']
actors=[];intervals=[]
for i,a in enumerate(e for e in es if e['kind']=='actor_invocation_started'):
 b=next(e for e in es if e['kind'] in ['actor_invocation_closed','actor_invocation_failed'] and e['aggregateId']==a['aggregateId']);ms=D(b['eventTime'])-D(a['eventTime']);intervals.append((a,b));actors.append({'actor':i+1,'start':ref(a),'end':ref(b),'endKind':b['kind'],'wallMs':ms,'promptBytes':times['native'][i]['promptBytes'],'reportedModels':times['native'][i]['reportedModels']})
outside=[]
for a,b in zip(es,es[1:]):
 if not any(lo['admissionOrdinal']<=a['admissionOrdinal']<hi['admissionOrdinal'] for lo,hi in intervals):outside.append({'wallMs':D(b['eventTime'])-D(a['eventTime']),'fromOrdinal':a['admissionOrdinal'],'fromKind':a['kind'],'toOrdinal':b['admissionOrdinal'],'toKind':b['kind']})
raw_event=[e for e in es if e['kind']=='actor_result_artifact_observed'][-1];raw=json.loads(raw_event['payload']['finalOutput']);members={c['graphFunctionRef'] for c in raw['contributions']};dangling=[{'member':c['graphFunctionRef'],'dependency':d} for c in raw['contributions'] for d in c['dependsOn'] if d not in members]
commands=[e for e in results if e['graphFunctionRef']=='graph-function://abiogenesis/worksite/command-execution@5'];native=[e for e in results if e['graphFunctionRef']=='graph-function://abiogenesis/worksite/native-work@5'];selection=read(p/'selection.json')
protected={path:hashlib.sha256((p/'worksite-result'/path).read_bytes()).hexdigest()==selection['seedFiles'][path]['sha256'] for path in selection['protectedSeedPaths']};assert all(protected.values())
report={'status':'first paid attempt failed; no retry or companion','publicOutcome':execution['output']['receipt']['ownerOutput'],'correspondence':correspondence,'failedRaw':{'artifact':ref(raw_event),'disposition':raw_event['payload']['disposition'],'failureClass':raw_event['payload']['failureClass'],'nextGraphFunctionRef':raw['nextGraphFunctionRef'],'contributionMembers':sorted(members),'outOfMappingDependencies':dangling,'bytes':len(raw_event['payload']['finalOutput'].encode()),'sha256':hashlib.sha256(raw_event['payload']['finalOutput'].encode()).hexdigest()},'assemblyReplayOmission':{'missingField':'manifest.runEnvironment.invocationAdmissionRef','observedBindings':[ref(e) for e in es if e['kind']=='actor_transport_binding_admitted' and e['payload']['instructionAssembly']['plan'].get('variant')=='framed-synthesis']},'observedCommands':[{'result':ref(e),'sourceObservedInput':bool(e['payload']['value']['task'].get('sourceObservedInput')),'observations':[{'exitStatus':r['exitStatus'],'stdout':__import__('base64').b64decode(r['stdout']['payload']).decode(),'stderr':__import__('base64').b64decode(r['stderr']['payload']).decode()} for r in e['payload']['value']['commandResults']]} for e in commands],'nativeWork':[{'result':ref(e),'changedPaths':e['payload']['value']['changedPaths'],'report':e['payload']['value']['report']} for e in native],'protectedSeedBytesUnchanged':protected,'actors':actors,'timing':{'setupMs':sum(times['setup']['wallMs'].values()),'executionMs':times['executionMs'],'actorMs':sum(a['wallMs'] for a in actors),'outsideActorMs':times['executionMs']-sum(a['wallMs'] for a in actors),'largestOutsideActorEventGaps':sorted(outside,key=lambda r:r['wallMs'],reverse=True)[:12]},'volumes':{'publicRequestBytes':times['publicRequestBytes'],'readinessBytes':len(json.dumps(read(pathlib.Path(execution['requestPath']))['invocation']['resources']['catalog']['readinessBasis'],separators=(',',':')).encode()),'promptBytes':[a['promptBytes'] for a in actors],'eventCount':len(es),'eventLogBytes':(p/'events.jsonl').stat().st_size,'eventKinds':dict(collections.Counter(e['kind'] for e in es)),'setup':times['setup']['volumes']}}
(root/'outcome.json').write_text(json.dumps(report,indent=2)+'\n');print({'actorMs':report['timing']['actorMs'],'outsideActorMs':report['timing']['outsideActorMs'],'setupMs':report['timing']['setupMs'],'mappingRows':len(correspondence),'dangling':len(dangling),'preservedProtected':len(protected)})
