import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {SourceTextModule,SyntheticModule} from 'node:vm';
const here=dirname(fileURLToPath(import.meta.url)),live=resolve(here,'../s6-declared-source-projection-01/installed-live-03'),repo=resolve(here,'../../../../..'),tenant=join(repo,'build_tenants/abiogenesis/typescript'),read=async n=>JSON.parse(await readFile(join(live,n),'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),setup=await read('setup.json'),load=p=>import(pathToFileURL(join(tenant,'build/code/src',p+'.js')).href);
const [store,prefixOwner,executionOwner,calls,cursors,gtl,product,truth,native]=await Promise.all(['abg/event_store','abg/event_prefix','abg/execution_basis','abg/c_call','abg/traversal_cursor','gtl/index','product/index','abg/invocation_execution_truth','abg/native_worksite_execution'].map(load));
const handoff=await read('handoff.json'),events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),at=n=>events.find(e=>e.admissionOrdinal===n),cut=store.durableRuntimeEventPrefixThroughEvent(handoff.prefix,at(21041).eventId),prefix=prefixOwner.selectValidatedRuntimeEventPrefix(store.readRuntimeEventsAtDurablePrefix(cut)),execution=executionOwner.rehydrateExecutionBasisAtPrefix(prefix,at(21037).basisId),start=await read('start-prepared.json'),publication=await read('publication.json'),definitions=start.call.resources.catalog.readinessBasis.publications.flatMap(p=>p.graphFunctions),graphFunction=definitions.find(g=>g.name===execution.graphFunctionRef),graph=gtl.materializeGraph(graphFunction,{invocationAdmissionRef:execution.invocationAdmissionRef,admittedInputRef:execution.rawInputAdmissionRef,admittedInputDigest:execution.rawInputDigest,admittedInput:execution.rawInputValue}),call=calls.projectOpenedCCallCarrierAtPrefix(prefix,graph,at(21037).aggregateId),ce=at(21036),cp=ce.payload;
const cursor=cursors.constructTraversalCursorCandidate({programRef:cp.programRef,executionBasisRef:cp.executionBasisRef,traversalScopeRef:cp.traversalScopeRef,runId:ce.runId,graphCallId:ce.graphCallId,frameId:ce.frameId,graphRef:cp.materializationRef,inputRef:cp.inputRef,inputDigest:cp.inputDigest,currentNodeRef:call.programLocusRef,position:'at_term',termPath:cp.termPath,taskOrdinal:cp.taskOrdinal,attempt:cp.attempt,retryPath:cp.retryPath});
assert.equal(cursor.cursorRef,cp.cursorRef);assert.equal(cursor.cursorDigest,cp.cursorDigest);
const basis=executionOwner.constructNativeInstructionAssemblyBasis({publication,graph,graphFunction,declarationGraphFunctions:definitions,executionBasis:execution,cCall:call,cursor,predecessorPrefix:cut});assert.ok(basis,'actual admitted preparation basis authenticates');const owned=executionOwner.authenticateNativeInstructionAssemblyBasis(basis);assert.ok(owned);

const libraryOwner=await load('abg/default_library'),nativeProduct=await load('product/native_workspace_work'),input=owned.inputValue,task=await libraryOwner.projectGovernanceNativeTask(basis,input);assert.ok(task,'actual failed CCall now prepares');assert.equal(libraryOwner.governanceResultMatches(basis,input,task),true,'actual preparation admission relation');
const selected=events.find(e=>e.kind==='c_call_result_admitted'&&e.payload.resultRef===input.synthesis.judgment.subjectEvidenceRef);assert.equal(selected.admissionOrdinal,4711);assert.equal(task.assessment.producer.resultRef,selected.payload.resultRef);assert.equal(task.assessment.producer.cCallRef,selected.aggregateId);assert.equal(task.assessment.producer.actorInvocationRef,selected.payload.value.provenance.actorInvocationRef);
const dependencies=selected.payload.value.task.protectedObservations.map(r=>r.subject.relativePath),assessmentPaths=[...task.assessment.sources.map(r=>r.path),task.assessment.candidate.path,task.assessment.rubric.path];assert.equal(native.worksiteCommandSourcesInvalidatedAfter(prefix,4711,task.workspaceAuthorityBasis.canonicalRoot,dependencies),false);assert.equal(native.worksiteCommandSourcesInvalidatedAfter(prefix,4711,task.workspaceAuthorityBasis.canonicalRoot,assessmentPaths),true);
const currentSelectorTask=events.findLast(e=>e.kind==='c_call_result_admitted'&&e.payload.value?.kind==='framed_synthesis_task').payload.value;assert.deepEqual(task.context,currentSelectorTask.context);for(const p of input.original.assessment.sources)assert.ok(task.assessment.sources.some(s=>s.path===p&&s.digest===task.context.entries.find(e=>e.relativePath===p).digest));
// The future child has not been admitted. Only its occurrence is controlled;
// frame, installed schema, raw contract, task and admitted producer are actual.
const assessmentGraph=definitions.find(g=>g.name===product.NATIVE_WORKSPACE_WORK_IDS.assessmentGraphFunctionRef),role=publication.runEnvironments[0].roles.find(r=>r.role==='assessor'),stdo=await load('abg/stdo_environment'),roleEvidence=stdo.projectRunEnvironmentRoleEvidence(events,execution.invocationAdmissionRef,publication,owned.program.programRef,assessmentGraph.name,role.programLocusRef,'assessor');assert.ok(roleEvidence&&roleEvidence.role==='assessor');
const taskDigest=product.sha256Canonical(task),futureCall={cCallRef:'controlled:prospective-assessment-call',cCallDigest:product.sha256Canonical({premise:'future assessment',taskDigest}),regime:'F_P',graphFunctionRef:assessmentGraph.name,programLocusRef:role.programLocusRef,implementationRef:product.NATIVE_WORKSPACE_WORK_IDS.implementationRef,inputContractRef:product.NATIVE_WORKSPACE_WORK_IDS.taskContractRef,outputContractRef:product.NATIVE_WORKSPACE_WORK_IDS.observationContractRef,runId:call.runId};
let occurrence={...owned,inputValue:task,inputRef:'controlled:prospective-assessment-task',inputDigest:taskDigest,call:futureCall};
async function controlledModule(path){const file=join(tenant,'build/code/src',path+'.js'),m=new SourceTextModule(await readFile(file,'utf8'),{identifier:file});await m.link(async specifier=>{const actual=await import(specifier.startsWith('node:')?specifier:pathToFileURL(resolve(dirname(file),specifier)).href),values={...actual,...(specifier==='./execution_basis.js'?{authenticateNativeInstructionAssemblyBasis:()=>occurrence}:{})};return new SyntheticModule(Object.keys(values),function(){for(const[k,v]of Object.entries(values))this.setExport(k,v);});});await m.evaluate();return m.namespace;}
const assemblyOwner=await controlledModule('abg/instruction_assembly'),futureBasis={...basis,graphFunction:assessmentGraph,assessmentPublication:publication,cCall:futureCall,cursor:{...cursor,currentNodeRef:role.programLocusRef,termPath:gtl.rootCSourcePath(role.programLocusRef)}},assembly=assemblyOwner.constructWorksiteNativeInstructionAssembly(futureBasis,task);assert.ok(assembly,'owned assessment assembly for actual C2 producer');assert.equal(assembly.request.inputDigest,taskDigest);assert.equal(assembly.request.transportLane,'worker_executes');
await writeFile(join(here,'assessment-prompt.txt'),assembly.request.prompt,{flag:'wx'});
const active=product.governanceFulfillmentActive(input.original.fulfillment,input.fulfillment),raw={kind:'consumer_outcome_assessment',disposition:'indeterminate',reason:'Controlled structural response, no native semantic judgment',unresolvedCriteria:active.map(a=>a.binding.obligationRef),fulfillment:{obligations:active.map(a=>({obligationRef:a.binding.obligationRef,policyRef:a.binding.proofPolicyRef,shapeRef:a.binding.proofShapeRef,judgment:'indeterminate',reason:'Not independently assessed',support:[],adverseEvidenceRefs:[],criteria:a.completeness.semanticCriteria.map(criterionRef=>({criterionRef,judgment:'indeterminate',reason:'No semantic judgment'})),depth:a.completeness.depthClasses.map(c=>({classRef:c.classRef,judgment:'indeterminate',reason:'No semantic judgment',evidenceRefs:[]}))})),discoveries:input.original.fulfillment.discoveryClasses.map(c=>({classRef:c.classRef,judgment:'indeterminate',reason:'No semantic judgment',evidenceRefs:[]}))}};
const p={cCallRef:futureCall.cCallRef,actorInvocationRef:'actor:controlled-independent-assessor',executionAuthorityRef:'authority:controlled',executionAuthorityDigest:product.sha256Canonical('authority'),transportBindingRef:'transport:controlled',transportBindingDigest:product.sha256Canonical('transport'),promptDigest:product.sha256Canonical(assembly.request.prompt),transportDigest:product.sha256Canonical('transport')};
const result=nativeProduct.constructNativeWorkspaceWorkObservation(task,task.context,null,p,raw),transport={...p,implementationRef:product.NATIVE_WORKSPACE_WORK_IDS.implementationRef,inputDigest:taskDigest,transportLane:'worker_executes',disposition:'success',finalOutput:JSON.stringify(raw)};assert.ok(nativeProduct.isNativeWorkspaceWorkObservation(result));assert.equal(nativeProduct.nativeWorkspaceWorkResultMatches(task,result,p.cCallRef,transport),true,'same result/producer matcher used by ABG outcome admission');
const judgment=nativeProduct.resolveNativeWorkspaceWorkJudgmentRelation(product.NATIVE_WORKSPACE_WORK_IDS.judgmentPredicateRef);assert.equal(judgment.evaluate(task,result),true);
const self=nativeProduct.constructNativeWorkspaceWorkObservation(task,task.context,null,{...p,actorInvocationRef:task.assessment.producer.actorInvocationRef},raw);assert.equal(nativeProduct.nativeWorkspaceWorkResultMatches(task,self,p.cCallRef,{...transport,actorInvocationRef:task.assessment.producer.actorInvocationRef}),false);
// Complete the existing retained fold without admitting a fabricated event.
const retained=product.constructRetainedGraphInput(input,result),ref='result:controlled-assessment',event={kind:'c_call_result_admitted',runId:call.runId,basisId:'basis:controlled-assessment',aggregateId:futureCall.cCallRef,payload:{resultRef:ref,resultDigest:product.sha256Canonical(result),contractRef:product.NATIVE_WORKSPACE_WORK_IDS.observationContractRef,resultClass:'success',value:result}};
occurrence={...owned,inputValue:retained,inputRef:'controlled:retained-assessment',call:{...owned.call,implementationRef:product.governanceRef('implementation','fold')},inputOrigin:{retainedProjection:{entryBasis:execution,input:{admissionRef:'controlled:retained-assessment',value:retained},sourceResult:event}}};const foldOwner=await controlledModule('abg/default_library'),fold=foldOwner.projectGovernanceFold(basis,retained);assert.ok(fold,'existing C2-producer assessment fold');assert.ok(fold.fulfillment.coverage.every(r=>r.assessmentResultRef===ref&&r.disposition==='open'));assert.equal(fold.observations.at(-1).fulfillmentEvidence.producerResultRef,selected.payload.resultRef);
const render={kind:assembly.kind,promptBytes:Buffer.byteLength(assembly.request.prompt),contextBytes:task.context.entries.filter(e=>e.state==='file').reduce((n,e)=>n+e.byteLength,0),contextBound:task.context.maxBytes,selectorBound:input.original.maxPromptBytes,separateNumericNativePromptBound:null,role:roleEvidence.role,frameRefs:roleEvidence.frameRefs,manifest:assembly.manifest,taskDigest,producer:task.assessment.producer,assessmentAdmitted:false};await save('assessment-render.json',render);
await save('checks.json',{passed:true,providerCalls:0,installation:false,actualAdmittedPrepare:{callRef:call.cCallRef,basisRef:execution.basisRef,inputRef:owned.inputRef,inputDigest:owned.inputDigest,authenticated:true,preparationAccepted:true,admissionGuardAccepted:true,producerOrdinal:4711,producerOwnDependenciesCurrent:true,laterAssessmentSourcesChanged:true,contextConserved:true,taskDigest},actualProducer:task.assessment.producer,dependencies,assessmentPaths,render,downstream:{ownedAssemblyRendered:true,rawSchemaValidated:true,abgNativeResultMatchingGuard:true,observationJudgment:true,independenceRefused:true,retainedFold:true,openCoverage:fold.fulfillment.coverage.length,actualAdmittedUat:false},limits:'Actual retained failed preparation CCall/authentication/input/currentness. Future assessor occurrence, raw indeterminate response and fold-result admission are controlled premises only; no UAT admission, provider, semantic success, installed successor or Run closure.'});console.log(JSON.stringify({passed:true,render,downstream:true},null,2));
