import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {join,dirname,resolve} from 'node:path';
import {here,read,write,caller,verificationRequest,schemaVersion} from './ordinary-caller.mjs';
import {loadRuntime} from './public-support.mjs';
import {preflight} from './preflight.mjs';
const {identity,prospect,r,items,publications:preparedPublications}=await preflight(),{product}=r;
const budgets=await read(join(here,'budgets.json'));const driverStart=performance.now(),driverDeadline=driverStart+budgets.driverBudgetMs;await write('driver-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgetMs:budgets.driverBudgetMs,operationCount:12});
const c=await caller('setup',items[0].verification,driverDeadline),{abg,gtl,hash,actor,state,authorized,invoke,coord}=c;
try{
 const workspaceRoot=join(here,'resources/worksite');await mkdir(join(here,'resources/events'),{recursive:true});
 const created=await invoke('workspace',await authorized(product.WORKSPACE_OPERATION_SOURCE_DECLARATIONS.create.clean,{targetRoot:workspaceRoot,createPolicy:'clean',scaffoldPolicy:'none'},{kind:'workspace_resource_assertion',schemaVersion,targetRoot:workspaceRoot,targetRootDigest:hash({kind:'workspace_target',targetRoot:workspaceRoot})},{actor}));
 const workspaceManifest=await read(created.receipt.resources.manifest.locator);
 for(const item of items){
  const v=item.verified;item.packed={kind:'product_verification_artifact_resource',schemaVersion,artifactPath:item.artifactPath,artifact:{ref:v.artifactRef,digest:v.artifactDigest},productContent:{ref:'product-content://abiogenesis/'+v.productContentDigest.slice(7),digest:v.productContentDigest},descriptor:item.verification.coordinates.descriptor,contributionManifest:{ref:v.contributionManifestRef,digest:v.contributionManifestDigest},manifestDigest:v.manifestDigest,productId:v.productId,packageName:v.packageName,packageVersion:v.packageVersion};
  const result=await invoke('verify-'+item.name,await authorized(product.PRODUCT_VERIFICATION_SOURCE_DECLARATIONS.verify,{targetKind:'packed_artifact',artifact:item.packed.artifact,productContent:item.packed.productContent,descriptor:item.packed.descriptor,contributionManifest:item.packed.contributionManifest,declaredDependencies:v.declaredDependencies,compatibilityInputs:v.compatibilityRefs.map(compatibilityRef=>({compatibilityRef,subjectRef:item.packed.productContent.ref}))},{kind:'product_verification_resources',schemaVersion,targetKind:'packed_artifact',packedArtifact:item.packed}));
  item.verificationRef={invocation:{ref:result.call.invocation.invocationRef,digest:result.call.invocation.invocationDigest},outcome:result.receipt.ownerOutput.value.verifiedArtifact};item.verificationOutput=result.receipt.ownerOutput;
 }
 const resolvedLock=product.ProductEnvironmentPort.resolve({kind:'product_resolution_packet',schemaVersion,memberKey:'resolve',verifiedArtifacts:items.map(x=>x.verified)});assert.equal(resolvedLock.kind,'resolved_product_lock',JSON.stringify(resolvedLock));state.resolvedLock=resolvedLock;
 const lock={ref:resolvedLock.lockId,digest:resolvedLock.lockDigest};
 await invoke('resolve',await authorized(product.PRODUCT_ENVIRONMENT_SOURCE_DECLARATIONS.resolve,{requirements:items.map(i=>({productId:i.verified.productId,packageVersion:i.verified.packageVersion,requiredContractRefs:[],requiredCapabilityRefs:[]})),verifiedCandidates:items.map(i=>i.verificationRef)},{kind:'product_resolution_resource_assertion',schemaVersion,verifiedPreimages:items.map(i=>({verification:i.verificationRef,verifiedArtifact:i.verified,verificationOutput:i.verificationOutput})),nativeContractClosure:{selectorDispositions:[],occurrences:[],nativeBindings:[]}},{verification_references:items.map(i=>i.verificationRef)}));
 const resourcesRoot=join(here,'resources'),eventLogPath=join(resourcesRoot,'events/runtime.events.jsonl'),installRoot=join(resourcesRoot,'installed');
 for(const item of items){
  const eventResource=state.closeHandoff?c.reopen():{kind:'new_abg_event_resource',schemaVersion,eventLogPath,locatorDigest:hash({kind:'abg_event_log_locator',eventLogPath:resolve(eventLogPath)})};
  const installed=await invoke('install-'+item.name,await authorized(product.PRODUCT_INSTALL_SOURCE_DECLARATIONS.install,{verifiedArtifact:item.verification.coordinates.verifiedArtifact,descriptor:item.packed.descriptor,contributionManifest:item.packed.contributionManifest,resolvedLock:lock,targetRoot:join(installRoot,item.name),installPolicy:'clean'},{kind:'product_install_resource_assertion',schemaVersion,eventResource,packedArtifact:item.packed,verifiedArtifact:item.verified,resolvedLock},{dependency_lock:lock,verification_references:[item.verificationRef],actor}));
  const row=abg.projectAdmittedProductInstallByInvocationRef(abg.projectExactPrefixArtifactTruth(state.closeHandoff.prefix),installed.call.invocation.invocationRef);assert.ok(row);item.install=row.install;
 }
 const authorityManifest={workspaceId:workspaceManifest.workspaceRef,canonicalRoot:workspaceManifest.canonicalRoot,authorityMode:'trusted_developer',authorizedActorRef:c.op.actorRef};
 const workspaceAuthority=product.constructWorkspaceAuthorityBasis({...authorityManifest,authorityManifestRef:c.op.authorityRef+'/workspace-manifest',authorityManifestDigest:hash(authorityManifest)});
 const roots={toolchainRoot:installRoot,productRoot:items[0].install.installedRoot,eventLogRoot:dirname(eventLogPath),runtimeStateRoot:join(resourcesRoot,'runtime'),projectionRoot:join(resourcesRoot,'projections'),archiveRoot:join(resourcesRoot,'archives')};
 const rootFields={toolchain:'toolchainRoot',product:'productRoot',event_log:'eventLogRoot',runtime_state:'runtimeStateRoot',projection:'projectionRoot',archive:'archiveRoot'},coordinates=items.map(i=>product.productInstallCoordinate(i.install));
 const bound=await invoke('bind',await authorized(product.PRODUCT_ENVIRONMENT_SOURCE_DECLARATIONS.bind,{workspaceAuthority:{ref:workspaceAuthority.authorityBasisId,digest:workspaceAuthority.authorityBasisDigest},installedSet:coordinates,resolvedLock:lock,declaredRoots:Object.entries(rootFields).map(([rootKind,field])=>({rootKind,path:roots[field]}))},{kind:'product_workspace_binding_resource_assertion',schemaVersion,eventResource:c.reopen(),workspaceAuthority,workspaceManifest,admittedInstalls:items.map(i=>i.install),resolvedLock,declaredRoots:roots},{product_set:coordinates,dependency_lock:lock,actor}));
 state.binding=bound.receipt.ownerOutput.value.binding;c.refresh();
 const coreBasis={...items[0].verified,productManifestDigest:items[0].verified.manifestDigest};
 const publications=preparedPublications;
 assert.deepEqual(publications.map(p=>[p.owningProductId,p.moduleRef,product.modulePublicationSemanticDigest(p)].join('\0')).sort(),items.flatMap(i=>i.verified.contributionManifest.publicationBindings.map(p=>[i.verified.productId,p.moduleRef,p.publicationDigest].join('\0'))).sort(),'complete exact installed publication inventories');
 const publicationInputs={workspaceBinding:state.binding,descriptors:items.map(i=>i.packed.descriptor),verifiedProducts:items.map(i=>i.verified),modulePublications:publications};await write('publication-inputs.json',publicationInputs);
 const catalogResult=await invoke('catalog',await authorized(product.CATALOG_OPERATION_SOURCE_DECLARATIONS.admit,{workspaceBinding:state.binding,descriptors:publicationInputs.descriptors,contributionManifests:items.map(i=>({ref:i.verified.contributionManifestRef,digest:i.verified.contributionManifestDigest})),resolvedLock:lock},{kind:'catalog_admission_resource_assertion',schemaVersion,eventResource:c.reopen(),workspaceBinding:state.environment.workspaceBinding,resolvedLock,verifiedProducts:publicationInputs.verifiedProducts,admittedInstalls:state.environment.productInstalls,publications},c.boundSlots()));
 const installed=state.environment.productInstalls.map(i=>abg.projectAdmittedProductInstallByAdmissionEventRef(state.environment.artifactTruth,i.admissionEventRef));assert.ok(installed.every(Boolean));
 state.catalog=product.CatalogOperationPort.admit({kind:'catalog_admit_packet',schemaVersion,memberKey:'admit',readinessBasis:{workspaceBinding:state.environment.workspaceBindingCandidate,resolvedLock,verifiedProducts:publicationInputs.verifiedProducts,installedProducts:installed.map(i=>i.candidate),publications}});assert.equal(state.catalog.kind,'graph_function_catalog',JSON.stringify(state.catalog));
 const programs=publications.flatMap(p=>p.programs).filter(p=>[gtl.HELLO_WORLD_IDS.programRef,'program://abiogenesis/worksite/command-execution@5'].includes(p.programRef));assert.equal(programs.length,2);
 const allowlist=[...new Set(programs.flatMap(p=>p.callableMembership))].sort();
 await invoke('catalog-view',await authorized(product.CATALOG_OPERATION_SOURCE_DECLARATIONS.view.allowlist,{catalog:catalogResult.receipt.ownerOutput.value.catalog,allowlist},{kind:'catalog_view_resource_assertion',schemaVersion,catalog:state.catalog},c.boundSlots()));state.catalogView=product.narrowGraphFunctionCatalog(state.catalog,allowlist);
 for(const p of programs)await c.conformance(p.programRef,'conformance-'+p.programRef.split('/').at(-1).split('@')[0],publicationInputs);
 await write('setup-state.json',{...state,items,workspaceAuthority,workspaceManifest,roots,contractCatalog:c.contractCatalog});console.log(JSON.stringify({phase:'ordinary_setup_complete',calls:state.calls.length,install:items[0].install.installId,workspaceBinding:state.binding,prefix:state.closeHandoff.prefix}));
 const helloInput=c.gtl.constructHelloWorldInput('prospective 5.0.0-rc.1 qualification');
 const started=await c.start(c.gtl.HELLO_WORLD_IDS.programRef,c.gtl.HELLO_WORLD_IDS.graphFunctionRef,helloInput,'hello-root','hello');
 console.log(JSON.stringify({phase:'hello_completed',run:started.receipt.ownerOutput.value.run}));
 const reads=await c.freshReads('hello-root',started),value=started.receipt.ownerOutput.value,resultProjection=reads.run_result.ownerOutput.value.projection,replayProjection=reads.run_replay.ownerOutput.value.projection;
 assert.equal(value.disposition,'completed');assert.equal(value.stop,null);assert.equal(value.terminalResult.kind,'abg_typed_terminal_result');
 assert.deepEqual(value.terminalResult.value,{kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello prospective 5.0.0-rc.1 qualification'});
 assert.deepEqual(value.terminalResult,resultProjection.terminalResult);assert.deepEqual(resultProjection.terminalResult,replayProjection.terminalResult);assert.deepEqual(value.result,resultProjection.result);assert.deepEqual(value.replay,resultProjection.replay);assert.deepEqual(value.replay,replayProjection.replay);assert.equal(replayProjection.status,'closed');
 assert.deepEqual(reads.run_result.ownerOutput.value.source,value.run);assert.deepEqual(reads.run_replay.ownerOutput.value.source,value.run);assert.equal(value.terminalResult.provenance.runRef,value.run.ref);
 assert.equal(state.calls.length,12);assert.ok(performance.now()<driverDeadline);
 await write('hello-result.json',{status:'passed',input:helloInput,startCall:started.call,rootReceipt:started.receipt,reads,comparison:{expectedOutput:'Hello prospective 5.0.0-rc.1 qualification',typedTerminalEqual:true,resultEqual:true,replayEqual:true,replayClosed:true,actualRun:value.run},closeHandoff:state.closeHandoff,calls:state.calls});
 const finalPhysical=await c.physical('final');const finalBytes=await readFile(eventLogPath);await (await import('node:fs/promises')).writeFile(join(here,'final-native-prefix.jsonl'),finalBytes,{flag:'wx'});await write('final-handoff.json',state.closeHandoff);
 await write('environment.json',{...state.environment,verified:items[0].verified,admittedInstalls:state.environment.productInstalls,workspaceAuthority,workspaceManifest,catalog:state.catalog,catalogView:state.catalogView,installedRoot:identity.installedRoot,productSet:coordinates,roots,contractCatalog:c.contractCatalog,definitionContractCoordinates:items[0].verified.definitionContractCoordinates,closeHandoff:state.closeHandoff});
 await write('runtime-slots.json',{installedProduct:{ref:items[0].install.installId,digest:hash(items[0].install)},workspaceBinding:state.binding,tenantManifest:null,executionSelectionRef:'absent; no C2 executed',remainingC2Join:'Q stageSelectedInputs requires an absent destination; ordinary setup created and bound '+workspaceAuthority.canonicalRoot+'. Root selected later use of exported selectedFiles(): validate every immutable input and absence of declared targets before exclusive writes, preserve .abiogenesis metadata, then constructObservedProducerTask under this same real A/W root. No second setup, staging or C2 performed here; do not call stageSelectedInputs unchanged.',noQualificationBasisMinted:true});
 await write('native-result.json',{status:'passed',candidate:identity.basis,setupCalls:9,helloCalls:1,coldReadCalls:2,providerCalls:0,C2Calls:0,finalPhysical,finalPrefix:state.closeHandoff.prefix,installedProduct:items[0].install.installId,workspaceBinding:state.binding,helloRun:value.run,elapsedMs:performance.now()-driverStart,budgetMs:budgets.driverBudgetMs,ownedDriverPid:process.pid,claim:'First exact-final candidate ordinary setup and bounded S01 Hello/cold proof; not qualification'});console.log(JSON.stringify({phase:'CLOSED_native_success',calls:state.calls.length,elapsedMs:performance.now()-driverStart}));
}catch(error){try{await c.physical('failure-final');const fs=await import('node:fs/promises');const p=join(here,'resources/events/runtime.events.jsonl');await fs.writeFile(join(here,'failure-native-prefix.jsonl'),await fs.readFile(p),{flag:'wx'});}catch(observationError){await write('failure-observation.json',{message:String(observationError)});}await write('setup-failure.json',{status:'CLOSED_first_failure',message:String(error),stack:error.stack,closeHandoff:state.closeHandoff,calls:state.calls});throw error;}
