import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {join} from 'node:path';
import {here,read,write,verificationRequest,schemaVersion} from './ordinary-caller.mjs';import {loadRuntime} from './public-support.mjs';
export async function preflight(){
 const identity=await read(join(here,'selected-core.json')),prospect=await read(join(here,'prospective-cases.json')),r=await loadRuntime(identity.installedRoot),{product,gtl}=r,items=[{name:'core',...prospect.core}];
 const begin=performance.now();const item=items[0];const packet={kind:'product_verification_packet',schemaVersion,memberKey:'verify',targetKind:'packed_artifact',request:verificationRequest(item)};
 const result=await product.ProductVerificationPort.verify(packet);await write('bootstrap-core.json',result);await write('bootstrap-core-timing.json',{elapsedMs:performance.now()-begin});assert.equal(result.kind,'product_verification_success',JSON.stringify(result));item.verification=result;item.verified=result.verifiedArtifact;assert.strictEqual(product.selectOwnedProductVerification(packet.request,item.verified),item.verified);
 const constructors=['constructDefaultGovernanceLibraryModulePublication','constructHelloWorldModulePublication','constructConsensusModulePublication','constructWorksiteConstructionModulePublication','constructWorksiteCommandExecutionModulePublication','constructWorksiteCommandForwardModulePublication','constructRequirementHandoffModulePublication','constructSemanticStageModulePublication','constructSemanticRevisionModulePublication','constructSelfConformanceModulePublication','constructNativeWorkspaceWorkModulePublication'];
 const coreBasis={...item.verified,productManifestDigest:item.verified.manifestDigest};const publications=constructors.map(n=>{assert.equal(typeof gtl[n],'function');return gtl[n](coreBasis);});
 const rows=publications.map((p,i)=>({constructor:constructors[i],productId:p.owningProductId,moduleRef:p.moduleRef,publicationDigest:product.modulePublicationSemanticDigest(p)}));const observed=rows.map(p=>[p.productId,p.moduleRef,p.publicationDigest].join('\0')).sort(),expected=item.verified.contributionManifest.publicationBindings.map(p=>[item.verified.productId,p.moduleRef,p.publicationDigest].join('\0')).sort();assert.equal(rows.length,11);assert.deepEqual(observed,expected);
 const archived=await read(join(here,'../final-candidate-construction-01/archive-members.json')),manifest=await read(join(identity.installedRoot,'product-toolchain-manifest.json'));assert.equal(product.sha256Canonical(manifest),identity.basis.manifestDigest);
 const contextChecks=[];for(const publication of publications){for(const declaration of publication.runEnvironments??[]){
  for(const dependency of declaration.dependencies){const matches=archived.filter(x=>'sha256:'+x.sha256===dependency.recordDigest);assert.ok(matches.length>0,'packaged dependency record '+dependency.recordRef);for(const match of matches){const bytes=await readFile(join(identity.installedRoot,match.path));assert.equal(product.sha256Bytes(bytes),dependency.recordDigest);const data=JSON.parse(bytes);assert.deepEqual(data.members,dependency.members);contextChecks.push({moduleRef:publication.moduleRef,declarationRef:declaration.declarationRef,recordRef:dependency.recordRef,path:match.path,digest:dependency.recordDigest});}}
  for(const context of declaration.contexts){for(const member of context.members){const matches=archived.filter(x=>'sha256:'+x.sha256===member.digest&&x.bytes===member.byteCount);assert.ok(matches.length>0,'packaged context '+member.memberRef);const bytes=await readFile(join(identity.installedRoot,matches[0].path));assert.equal(product.sha256Bytes(bytes),member.digest);for(const role of declaration.roles)for(const span of role.sourceBindings.filter(s=>s.memberRef===member.memberRef)){assert.equal(product.sha256Bytes(bytes.subarray(span.startByte,span.endByte)),span.spanDigest);}contextChecks.push({moduleRef:publication.moduleRef,declarationRef:declaration.declarationRef,memberRef:member.memberRef,digest:member.digest,packagedEqualContentPaths:matches.map(x=>x.path),roleSpansChecked:true});}}
 }}
 const c2=publications.find(p=>p.programs.some(x=>x.programRef==='program://abiogenesis/worksite/command-execution@5'));assert.ok(c2.runEnvironments.length);assert.ok(c2.programs.find(p=>p.programRef==='program://abiogenesis/worksite/command-execution@5').policies[gtl.RUN_ENVIRONMENT_POLICY]);
 await write('pure-preflight.json',{status:'passed',fullPublicationCount:rows.length,publicationBindings:rows,contextChecks,actualVerification:{productId:item.verified.productId,productContentDigest:item.verified.productContentDigest,manifestDigest:item.verified.manifestDigest,catalogDigest:item.verified.catalogDigest},declarations:'Complete semantic publication bindings authenticate full declarations/run environments; package inventory and source spans checked before effects',nativeEffects:0});await write('prepared-publications.json',publications);console.log(JSON.stringify({phase:'pure_preflight_passed',publications:11,contexts:contextChecks.length,nativeEffects:0}));
 return {identity,prospect,r,items,publications};
}
