import pathlib,json,hashlib,shutil,difflib
R=pathlib.Path('/Users/jim/src/apps/abiogenesis');G=R/'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE';N=G/'final-native-setup-01';C=G/'final-candidate-construction-01';Q=G/'final-qualification-inputs-01';D=R/'.ai-workspace/comments/codex/20260923_RC1_QUALIFICATION_RECIPE/native-material-01'
def r(p):return json.loads(p.read_text())
def wr(n,x):(N/n).write_text(json.dumps(x,indent=2)+'\n')
def row(p):return {'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['tmp','config','cache','preimages']: (N/name).mkdir()
for name in ['user.npmrc','global.npmrc','global.gitconfig','system.gitconfig']:(N/'config'/name).write_text('')
wr('worker-activation.json',{'role':'Worker','worker':'T287_FINAL_NATIVE_SETUP_01','grant':row(G/'final-native-setup-controls-01/request.txt'),'frame':'stdo://releases/v2.5.1-rc.1/standards/STDO_REFERENCE_FRAME_BASELINE.md#derived-worker-frame','territory':str(N),'selected':'one current ordinary Public setup and one Hello/cold proof','changeClass':'realization_refactor of external setup publication inputs','budget':'budgets.json','prohibited':'C2/recipe/test/provider/source/Git effects; no retry','author':'/root/s03_phase_b; activation by Root Executive'})
assert row(C/'freeze.json')['sha256']=='f6199e3f9ce72f99ecd16307eabc9ca92cc2ecdbc320c70bdd075962eb09650f';assert row(Q/'freeze.json')['sha256']=='0a386fd10e1067abb3f09ba4d7f115b56593045ca0d0d1aa272fb7fcc0a46bbe'
for x in r(Q/'freeze.json')['records']:
 p=Q/x['path'];assert p.stat().st_size==x['bytes'] and hashlib.sha256(p.read_bytes()).hexdigest()==x['sha256']
core=r(C/'selected-core.json');wr('selected-core.json',{'installedRoot':core['packageRoot'],**core});wr('prospective-cases.json',{'core':{'artifactPath':core['artifactPath'],'artifactRef':core['artifactRef'],'basis':core['basis']},'cases':[],'claim':'Full11 ordinary setup, selected Hello+C2 catalog view/conformance, exactly one Hello; C2 unexecuted'})
wr('input-joins.json',[row(p) for p in [G/'final-native-setup-controls-01/request.txt',G/'final-native-setup-controls-01/request-sections.json',C/'freeze.json',C/'selected-core.json',Q/'freeze.json',Q/'return.md',Q/'causal-triage.json',Q/'missing-publication-owner.json',Q/'next-setup-c2-inputs.json']])
wr('budgets.json',{'stages':{'setup':600000,'conformance':600000,'hello':300000,'read':600000},'operationPlan':['workspace','verify-core','resolve','install-core','bind','catalog','catalog-view','conformance-hello-world','conformance-command-execution','hello-root','hello-root-run_result','hello-root-run_replay'],'setupAndConformanceCalls':9,'helloCalls':1,'readCalls':2,'nativeCapSumMs':6900000,'terminationGraceMs':1000,'allCommandGraceMs':12000,'driverBudgetMs':6912000,'driverScope':'starts after pure nominal verification/full11/context/syntax preflight;12 finite ordinary CLI calls, each own cap, group termination, genuine receipt conservation','retry':'none','basis':row(Q/'budgets.json')})
wr('runtime-environment.json',{'TMPDIR':str(N/'tmp'),'npm_config_cache':str(N/'cache/npm'),'npm_config_prefix':str(N/'cache/npm-prefix'),'npm_config_userconfig':str(N/'config/user.npmrc'),'npm_config_globalconfig':str(N/'config/global.npmrc'),'GIT_CONFIG_GLOBAL':str(N/'config/global.gitconfig'),'GIT_CONFIG_SYSTEM':str(N/'config/system.gitconfig'),'GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','NODE_OPTIONS':''})
wr('resource-plan.json',{'workspaceRoot':str(N/'resources/worksite'),'installRoot':str(N/'resources/installed'),'eventLogPath':str(N/'resources/events/runtime.events.jsonl'),'lockNamespace':str(N/'tmp/abiogenesis-event-store-locks-v5'),'lockFileRule':'<actual-device>-<actual-inode>.lock; original namespace maintained for every call','history':'brand new; no historical resource accessed','HOME':'unchanged','permittedWrites':str(N),'nativeCalls':12})
for name in ['ordinary-caller.mjs','public-support.mjs','observe-process.py','setup.mjs','hello.mjs']:shutil.copyfile(D/name,N/'preimages'/name)
shutil.copyfile(D/'public-support.mjs',N/'public-support.mjs');shutil.copyfile(D/'observe-process.py',N/'observe-process.py')
s=(D/'ordinary-caller.mjs').read_text().replace("export const predecessor=join(here,'../d5-a01-case-01');\n",'').replace('export async function caller(mode){','export async function caller(mode, nominalVerification, driverDeadline){').replace("verification=await read(join(here,'bootstrap-core.json'))","verification=nominalVerification").replace("const budgets=await read(join(here,'budgets.json')),awaitPolicy=await read(join(here,'launch-policy.json'));","const budgets=await read(join(here,'budgets.json')),taskEnvironment=await read(join(here,'runtime-environment.json'));\n const physicalLog=[];\n async function physical(label){const f=join(here,'resources/events/runtime.events.jsonl');try{const fs=await import('node:fs/promises'),crypto=await import('node:crypto'),before=await fs.stat(f),b=await fs.readFile(f),after=await fs.stat(f);const lock=join(taskEnvironment.TMPDIR,'abiogenesis-event-store-locks-v5',String(after.dev)+'-'+String(after.ino)+'.lock');let lockPresent=false;try{await fs.stat(lock);lockPresent=true;}catch(e){if(e.code!=='ENOENT')throw e;}const row={label,path:f,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex'),device:after.dev,inode:after.ino,stable:before.dev===after.dev&&before.ino===after.ino&&before.size===after.size&&before.mtimeMs===after.mtimeMs,lockPath:lock,lockPresent,prefix:state.closeHandoff?.prefix??null};physicalLog.push(row);await write(mode+'-'+label+'-physical.json',row);assert.equal(row.stable,true);assert.equal(lockPresent,false);return row;}catch(e){if(e.code==='ENOENT')return null;throw e;}}")
s=s.replace("base='abiogenesis/t287/rc1-native-material-01'","base='abiogenesis/t287/final-native-setup-01'")
s=s.replace("const started=performance.now();let processFailure=null,terminal;","const started=performance.now();let processFailure=null,terminal;const remaining=driverDeadline-performance.now();assert.ok(remaining>0,'finite driver deadline');const capMs=Math.min(budgets.stages[stage],remaining);await write(mode+'-'+label+'-command.json',{command:[process.execPath,cli,'--jsonl',stem+'.jsonl'],cwd:packageIdentity.installedRoot,environment:taskEnvironment,budgetMs:capMs,driverRemainingMs:remaining});")
s=s.replace("env:{...process.env,...(stage==='c2'?(awaitPolicy.environment):{}),NODE_OPTIONS:''}","env:{...process.env,...taskEnvironment}").replace('budgets.stages[stage]);','capMs);')
s=s.replace("const stdout=await readFile(stem+'-stdout.json','utf8');","const stdout=await readFile(stem+'-stdout.json','utf8');")
s=s.replace("assert.equal(receipt.ownerOutput?.outcomeKind,'result',JSON.stringify(receipt));assert.equal(receipt.exitCode,0,JSON.stringify(receipt));return {call,receipt};","await physical(label);assert.equal(processFailure,null,JSON.stringify(processFailure));assert.equal(receipt.ownerOutput?.outcomeKind,'result',JSON.stringify(receipt));assert.equal(receipt.exitCode,0,JSON.stringify(receipt));return {call,receipt};")
s=s.replace('authorized,invoke,conformance,start,freshReads,reopen,refresh,boundSlots};','authorized,invoke,conformance,start,freshReads,reopen,refresh,boundSlots,physical,physicalLog};')
(N/'ordinary-caller.mjs').write_text(s)
wr('donor-preimages.json',[{'donor':row(D/n),'preserved':row(N/'preimages'/n)} for n in ['ordinary-caller.mjs','public-support.mjs','observe-process.py','setup.mjs','hello.mjs']])
print('Worker activation,12-call resource/budget plan and external caller inputs bound; no native effect.')
