import pathlib,json,hashlib,shutil,difflib
R=pathlib.Path('/Users/jim/src/apps/abiogenesis');G=R/'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE';N=G/'final-native-setup-03';C=G/'final-candidate-construction-02';N1=G/'final-native-setup-01';N2=G/'final-native-setup-02'
def read(p):return json.loads(p.read_text())
def row(p):b=p.read_bytes();return {'path':str(p.relative_to(R)),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def save(n,v):
 with (N/n).open('x') as f:json.dump(v,f,indent=2);f.write('\n')
for d in ['tmp','cache','config','preimages']:(N/d).mkdir()
for name in ['user.npmrc','global.npmrc','global.gitconfig','system.gitconfig']:(N/'config'/name).touch(exist_ok=False)
core=read(C/'selected-core.json');save('selected-core.json',{'installedRoot':core['packageRoot'],**core});save('prospective-cases.json',{'core':{k:core[k] for k in ['artifactPath','artifactRef','basis']},'cases':[],'claim':'New C02 full11 ordinary setup and Hello/C2 conformance; exactly one original S01 Hello; no C2 execution'})
b=read(N1/'budgets.json');b.pop('basis',None);b.update({'purePreflightAllowanceMs':120000,'totalCeilingMs':7032000,'driverScope':'6912000ms after preflight; exact12 calls, no retry; original setup/Hello/cold-read caps','basis':row(G/'final-native-setup-controls-03/request.txt')});save('budgets.json',b)
overlay={'TMPDIR':str(N/'tmp'),'npm_config_cache':str(N/'cache/npm'),'npm_config_prefix':str(N/'cache/npm-prefix'),'npm_config_userconfig':str(N/'config/user.npmrc'),'npm_config_globalconfig':str(N/'config/global.npmrc'),'GIT_CONFIG_GLOBAL':str(N/'config/global.gitconfig'),'GIT_CONFIG_SYSTEM':str(N/'config/system.gitconfig'),'GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','NODE_OPTIONS':''};save('runtime-environment.json',overlay)
save('resource-plan.json',{'workspaceRoot':str(N/'resources/worksite'),'installRoot':str(N/'resources/installed'),'eventLogPath':str(N/'resources/events/runtime.events.jsonl'),'lockNamespace':str(N/'tmp/abiogenesis-event-store-locks-v5'),'lockFileRule':'<actual-device>-<actual-inode>.lock; same original N03 namespace all calls','history':'Genuinely new subject/resource, no old native resource accessed','HOME':'unchanged','permittedWrites':str(N),'nativeCalls':12,'actualActorRef':'actor://abiogenesis/t287/final-native-setup-03/operator'})
donors={'driver.mjs':N1/'driver.mjs','preflight.mjs':N1/'preflight.mjs','ordinary-caller.mjs':N2/'ordinary-caller.mjs','public-support.mjs':N2/'public-support.mjs','observe-process.py':N2/'observe-process.py','launch-once.py':N2/'launch-once.py','strict-publication-donor.mjs':C/'validate-installed-publications.mjs'}
for n,p in donors.items():shutil.copyfile(p,N/'preimages'/n)
for n in ['public-support.mjs','observe-process.py']:shutil.copyfile(donors[n],N/n)
s=donors['ordinary-caller.mjs'].read_text().replace("base='abiogenesis/t287/final-native-setup-02',actorRef='actor://abiogenesis/t287/final-native-setup-01/operator'","base='abiogenesis/t287/final-native-setup-03',actorRef='actor://abiogenesis/t287/final-native-setup-03/operator'")
(N/'ordinary-caller.mjs').write_text(s)
s=donors['preflight.mjs'].read_text().replace('../final-candidate-construction-01/archive-members.json','../final-candidate-construction-02/archive-members.json')
anchor=" const archived=await read("
addition=""" const validationRows=publications.map((p,i)=>{const raw=r.validator.rawAdmitValue(p,'module_publication','contract://abiogenesis/gtl/module-publication@5'),contributions=p.contributions.map(c=>r.validator.rawAdmitValue(c,'catalog_contribution','contract://abiogenesis/gtl/catalog-contribution@5'));const result=raw.kind!=='raw_admitted_value'?raw:contributions.find(c=>c.kind!=='raw_admitted_value')??r.validator.validatePublication(raw,contributions);return {constructor:constructors[i],moduleRef:p.moduleRef,publicationDigest:product.modulePublicationSemanticDigest(p),result};});
 await write('strict-publication-preflight.json',{status:validationRows.every(x=>x.result.kind==='publication_validation')?'passed':'failed',rows:validationRows,installedRoot:identity.installedRoot,actualVerifiedBasis:identity.basis,nativeEffects:0});assert.ok(validationRows.every(x=>x.result.kind==='publication_validation'),'all eleven strict raw/static publications must pass');
 const carrierDefinitions=[];for(const [operationId,memberKey] of [['abg.operation.run.invoke','start'],['abg.operation.project.read','run_result'],['abg.operation.project.read','run_replay']]){const d=r.public.PUBLIC_FUNCTION_DEFINITION_FAMILY.definitions.find(x=>x.definitionKey.operationId===operationId&&x.definitionKey.memberKey===memberKey),coordinate=item.verified.definitionContractCoordinates.operations.find(x=>x.operationId===operationId)?.members.find(x=>x.memberKey===memberKey);assert.ok(d&&coordinate?.slots.request&&coordinate?.slots.result);carrierDefinitions.push({definitionKey:d.definitionKey,definitionRef:d.definitionRef,definitionDigest:d.definitionDigest,slots:coordinate.slots});}assert.equal(typeof product.admissionEnvironmentSelection,'function');assert.equal(typeof product.admissionAuthorityScope,'function');
 await write('current-caller-contracts.json',{status:'source_and_constructor_compatible',carrierDefinitions,admissionBranch:'N2 retained admissionEnvironmentSelection(real current prefix, real WB), current scope/approval/grant and installed DefinitionCall owners. Real downstream inputs await ordinary predecessor outputs; no fabricated future owner coordinates.',start:'N2 declared ProductExecutionResolution/RootInvocationPolicy/InvocationAuthority/current installed DefinitionCall; unchanged original Hello input and F_D-only guard',coldReads:'Actual admitted Run, original start authority slots, latest owner handoff for each fresh process; no read append'});
"""
assert anchor in s;s=s.replace(anchor,addition+anchor,1);s=s.replace("fullPublicationCount:rows.length,publicationBindings", "fullPublicationCount:rows.length,strictRawStaticFull11:true,publicationBindings")
(N/'preflight.mjs').write_text(s)
s=donors['driver.mjs'].read_text()
old="const {identity,prospect,r,items,publications:preparedPublications}=await preflight(),{product}=r;"
new="""const preflightBegin=performance.now();let prepared;
const preflightTimer=setTimeout(()=>{console.error('Pure preflight120000ms exhausted');process.exit(1);},120000);
try{prepared=await preflight();assert.ok(performance.now()-preflightBegin<120000);await write('preflight-budget-result.json',{status:'passed',elapsedMs:performance.now()-preflightBegin,capMs:120000});}catch(error){await write('preflight-failure.json',{message:String(error),stack:error.stack,nativeCalls:0});throw error;}finally{clearTimeout(preflightTimer);}
const {identity,prospect,r,items,publications:preparedPublications}=prepared,{product}=r;"""
assert old in s;s=s.replace(old,new)
old="assert.equal(state.catalog.kind,'graph_function_catalog',JSON.stringify(state.catalog));"
s=s.replace(old,old+"assert.equal(catalogResult.receipt.ownerOutput.value.catalog.digest,state.catalog.basisDigest);")
s=s.replace(" await write('setup-state.json'", " c.refresh();await write('setup-state.json'",1)
s=s.replace(" await write('environment.json'", " c.refresh();await write('environment.json'",1)
s=s.replace("installedProduct:{ref:items[0].install.installId,digest:hash(items[0].install)},workspaceBinding:state.binding,tenantManifest:null,executionSelectionRef:'absent; no C2 executed'", "installedProduct:product.productInstallCoordinate(items[0].install),workspaceBinding:state.binding,workspaceAuthority,canonicalRoot:workspaceAuthority.canonicalRoot,installedRoots:roots,resolvedLock:lock,catalog:{ref:'graph-function-catalog://abiogenesis/'+state.catalog.basisDigest.slice(7),digest:state.catalog.basisDigest},catalogView:{ref:'graph-function-catalog-view://abiogenesis/'+state.catalogView.viewDigest.slice(7),digest:state.catalogView.viewDigest},closeHandoff:state.closeHandoff,tenantManifest:null,executionSelectionRef:null")
s=s.replace('First exact-final candidate ordinary setup and bounded S01 Hello/cold proof','New C02 ordinary setup and bounded original S01 Hello/cold proof')
(N/'driver.mjs').write_text(s)
s=donors['launch-once.py'].read_text().replace("assert budget['driverBudgetMs']==4027000","assert budget['driverBudgetMs']==6912000 and budget['totalCeilingMs']==7032000 and budget['purePreflightAllowanceMs']==120000").replace('4027000','7032000').replace('4026000','7031000').replace("N.glob('continue-*-process-start.json')","N.glob('setup-*-process-start.json')")
(N/'launch-once.py').write_text(s)
save('donor-preimages.json',[{'logicalSourcePath':str(p.relative_to(R)),'source':row(p),'preserved':row(N/'preimages'/n)} for n,p in donors.items()])
patch=''
for n,p in donors.items():
 if (N/n).exists():patch+=''.join(difflib.unified_diff((N/'preimages'/n).read_text().splitlines(True),(N/n).read_text().splitlines(True),fromfile=str(p.relative_to(R)),tofile=str((N/n).relative_to(R))))
(N/'control-deltas.patch').write_text(patch)
save('control-authorship.json',{'actualActor':'/root/s03_phase_b','role':'T287_FINAL_NATIVE_SETUP_03','profile':'Astra/xhigh as assigned','sessionIdentifier':None,'sessionIdentifierAvailability':'unavailable','grant':row(G/'final-native-setup-controls-03/request.txt'),'donors':'donor-preimages.json','reconstructablePatch':row(N/'control-deltas.patch'),'authoredControlPostimages':[row(N/n) for n in donors if (N/n).exists()],'claim':'Current operation control author and executor, not inherited semantic authorship or native ABG attribution. Product-owner qualification authority is unbound.','changedRelations':['N1 sequence and preflight retargeted to exact C02 archive/export/root','N2 complete corrected shared selection/scope/approval/grant branch retained','New N03 actor/resource/TMPDIR namespace, original oracle preserved','Full11 strict raw/static validation from actual existing installed owners before native calls','Real final environment refreshed and actual runtime owner coordinates returned','Exact pure120000/native6912000/total7032000 finite budgets'],'unchanged':'No canonical source, donor, Product or old native resource write'})
save('input-joins.json',[row(p) for p in [G/'final-native-setup-controls-03/request.txt',G/'final-native-setup-controls-03/request-sections.json',C/'freeze.json',C/'selected-core.json',C/'archive-members.json',C/'construction-readiness.json',G/'final-candidate-review-02/return.md',G/'final-candidate-review-02/freeze.json',N1/'freeze.json',N2/'freeze.json']])
print('Bound new C02/N03 controls, full11 precondition, donor preimages/patches,12-call budget; no native effect')
