import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {writeFileSync} from 'node:fs';import {join} from 'node:path';import {createRequire} from 'node:module';
import {here,read,write,caller,verificationRequest,schemaVersion} from './ordinary-caller.mjs';import {loadRuntime} from './public-support.mjs';import {checkConformance,checkStart} from './owner-checks.mjs';
const P=join(here,'../final-native-setup-03'),startedAt=performance.now(),budgets=await read(join(here,'budgets.json')),window={deadline:null};let c=null,phase='preflight',nativeStartedAt=null;
await write('driver-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgets,exactCalls:5});
let preflightTimer=setTimeout(()=>{writeFileSync(join(here,'preflight-timeout.json'),JSON.stringify({phase,capMs:120000,nativeCalls:0})+'\n',{flag:'wx'});process.exit(1);},120000);
try{
 const identity=await read(join(here,'selected-core.json')),prospect=await read(join(here,'prospective-cases.json')),r=await loadRuntime(identity.installedRoot),{product,abg,gtl}=r;
 const request=verificationRequest(prospect.core),verification=await product.ProductVerificationPort.verify({kind:'product_verification_packet',schemaVersion,memberKey:'verify',targetKind:'packed_artifact',request});await write('bootstrap-core.json',verification);assert.equal(verification.kind,'product_verification_success');assert.strictEqual(product.selectOwnedProductVerification(request,verification.verifiedArtifact),verification.verifiedArtifact);
 c=await caller('continue',verification,window);const {state,hash}=c,retained=await read(join(P,'retained-environment.json')),slots=await read(join(P,'runtime-slots.json')),initial=await read(join(P,'final-handoff.json')),originalBytes=await fs.readFile(join(P,'failure-native-prefix.jsonl'));state.closeHandoff=initial;state.binding=slots.workspaceBinding;state.resolvedLock=retained.projection.resolvedProductLock;state.catalog=retained.catalog;state.catalogView=retained.catalogView;c.refresh();assert.deepEqual(state.environment,retained.projection);assert.equal(c.op.actorRef,slots.workspaceAuthority.authorizedActorRef);
 const physical=await c.physical('initial');assert.equal(physical.device,16777230);assert.equal(physical.inode,464012478);assert.equal(physical.bytes,2475382);assert.equal(physical.sha256,'cb30f7630f276feab31ea3b34a432ef85c19a6ec16d5985d1beb574687cf51d8');assert.equal(initial.prefix.coordinateDigest,'sha256:7cb5efb8e5a16babfeb0c51dbb943913be21281e0e64f3bc8f6e94dcc6dd4757');assert.deepEqual(state.catalog.basisDigest,slots.catalog.digest);assert.deepEqual(state.catalogView.viewDigest,slots.catalogView.digest);
 const publicationInputs=await read(join(P,'publication-inputs.json'));assert.deepEqual(state.binding,publicationInputs.workspaceBinding);assert.equal(publicationInputs.modulePublications.length,11);assert.deepEqual(publicationInputs.modulePublications.map(p=>[p.moduleRef,product.modulePublicationSemanticDigest(p)].join('\0')).sort(),verification.verifiedArtifact.contributionManifest.publicationBindings.map(p=>[p.moduleRef,p.publicationDigest].join('\0')).sort());
 const preparations=[];for(const [programRef,label]of [[gtl.HELLO_WORLD_IDS.programRef,'conformance-hello-world'],['program://abiogenesis/worksite/command-execution@5','conformance-command-execution']]){const prepared=await c.prepareConformance(programRef,label,publicationInputs);preparations.push(prepared);}
 const v=createRequire(join(identity.installedRoot,'package.json'))('valibot'),checks=[];for(const p of preparations){v.parse(product.ADMISSION_CAPABILITY_DATA_SCHEMA,p.call.resources.admissionAuthority.basis);v.parse(product.RESOLVED_ADMISSION_AUTHORITY_SCHEMA,p.call.resources.admissionAuthority.authority);const check=checkConformance(c,p);await write(p.label+'-owner-precondition.json',check);checks.push({label:p.label,resourceKeys:Object.keys(check.ownerConsumedResources).sort(),closure:{ref:check.ownerDeclarationClosure.closureRef,digest:check.ownerDeclarationClosure.closureDigest},callRef:p.call.invocation.invocationRef});}
 const input=gtl.constructHelloWorldInput('prospective 5.0.0-rc.1 qualification'),preparedStart=await c.prepareStart(gtl.HELLO_WORLD_IDS.programRef,gtl.HELLO_WORLD_IDS.graphFunctionRef,input,'hello-root'),startCheck=await checkStart(c,preparedStart);await write('hello-root-owner-precondition.json',startCheck);
 const readContracts=['run_result','run_replay'].map(memberKey=>{const packet=abg.ABG_PROJECT_READ_CONTRACTS[memberKey],m=verification.verifiedArtifact.definitionContractCoordinates.operations.find(x=>x.operationId===packet.definitionKey.operationId).members.find(x=>x.memberKey===memberKey);assert.ok(m.slots.request&&m.slots.result);return {memberKey,packet,coordinates:m,consumedResourceKeys:['eventResource','kind','schemaVersion'],futureDependencies:'Actual started.receipt.ownerOutput.value.run and current genuine closeHandoff; checked by checkReadCall immediately before each real native read. No fake Run/execution/handoff is constructed.'};});
 assert.ok(performance.now()-startedAt<120000);clearTimeout(preflightTimer);preflightTimer=null;await write('pure-preflight.json',{status:'passed',elapsedMs:performance.now()-startedAt,nativeCalls:0,actualNominalVerification:true,retainedPrefix:initial.prefix,physical,bothConformanceChecks:checks,actualStartResourcePredicate:true,actualPureStartOwnerPreparation:true,readContracts,conservedCatalog:slots.catalog,conservedView:slots.catalogView,limits:'Current actual value/owner construction checks, not native semantics. No full unchanged publication static proof or seven successful Public calls rerun.'});console.log(JSON.stringify({phase:'complete_remaining_owner_preflight_passed',conformances:2,actualStartPrepared:true,readSourceDeferredUntilRealRun:true,nativeCalls:0}));
 nativeStartedAt=performance.now();window.deadline=nativeStartedAt+budgets.driverBudgetMs;await write('native-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgetMs:budgets.driverBudgetMs,operationPlan:budgets.operationPlan});
 for(const p of preparations){phase=p.label;assert.deepEqual(state.closeHandoff,initial);const result=await c.invoke(p.label,p.call,'conformance');assert.equal(result.receipt.ownerOutput.value.disposition,'passed',JSON.stringify(result.receipt));assert.deepEqual(state.closeHandoff,initial);await write(p.label+'-semantic-result.json',{status:'passed',receipt:result.receipt,preparedCallRef:p.call.invocation.invocationRef,closedPrefixConserved:true});}
 console.log(JSON.stringify({phase:'both_native_conformances_passed',newCalls:state.calls.length,prefix:state.closeHandoff.prefix}));
 phase='hello-root';c.refresh();assert.deepEqual(preparedStart.call.resources.eventResource,c.reopen());assert.equal(product.isRunInvocationResourceAssertion(preparedStart.call.resources),true);const started=await c.invoke('hello-root',preparedStart.call,'hello');console.log(JSON.stringify({phase:'hello_owner_returned',run:started.receipt.ownerOutput.value.run,disposition:started.receipt.ownerOutput.value.disposition}));
 const value=started.receipt.ownerOutput.value;assert.equal(value.disposition,'completed');assert.equal(value.stop,null);assert.equal(value.terminalResult.kind,'abg_typed_terminal_result');assert.deepEqual(value.terminalResult.value,{kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello prospective 5.0.0-rc.1 qualification'});
 phase='cold-reads';const reads=await c.freshReads('hello-root',started),rp=reads.run_result.ownerOutput.value.projection,replay=reads.run_replay.ownerOutput.value.projection;assert.deepEqual(value.terminalResult,rp.terminalResult);assert.deepEqual(rp.terminalResult,replay.terminalResult);assert.deepEqual(value.result,rp.result);assert.deepEqual(value.replay,rp.replay);assert.deepEqual(value.replay,replay.replay);assert.equal(replay.status,'closed');assert.deepEqual(reads.run_result.ownerOutput.value.source,value.run);assert.deepEqual(reads.run_replay.ownerOutput.value.source,value.run);assert.equal(value.terminalResult.provenance.runRef,value.run.ref);assert.equal(state.calls.length,5);assert.ok(performance.now()<window.deadline);
 await write('hello-result.json',{status:'passed',input,startCall:started.call,rootReceipt:started.receipt,reads,comparison:{typedTerminalEqual:true,resultEqual:true,replayEqual:true,replayClosed:true,originalExpectedMessage:'Hello prospective 5.0.0-rc.1 qualification',actualRun:value.run},closeHandoff:state.closeHandoff,calls:state.calls});
 phase='final-conservation';const finalPhysical=await c.physical('final'),finalBytes=await fs.readFile(initial.reopenAuthority.eventLogPath);assert.equal(finalPhysical.device,physical.device);assert.equal(finalPhysical.inode,physical.inode);assert.deepEqual(finalBytes.subarray(0,originalBytes.length),originalBytes);await fs.writeFile(join(here,'final-native-prefix.jsonl'),finalBytes,{flag:'wx'});await write('final-handoff.json',state.closeHandoff);c.refresh();
 await write('environment.json',{projection:state.environment,catalog:state.catalog,catalogView:state.catalogView,verified:verification.verifiedArtifact,definitionContractCoordinates:verification.verifiedArtifact.definitionContractCoordinates,readerInstalledRoot:identity.installedRoot,closeHandoff:state.closeHandoff});await write('runtime-slots.json',{...slots,closeHandoff:state.closeHandoff,HelloRun:value.run,tenantManifest:null,executionSelectionRef:null,remaining:[],reuse:'Seven N03 successes plus five N04 calls on same original resource; later effect requires separate Root grant'});
 await write('native-result.json',{status:'passed',candidate:identity.basis,initialPrefix:initial.prefix,initialPrefixConserved:true,finalPrefix:state.closeHandoff.prefix,finalPhysical,priorSuccessesReexecuted:0,newCalls:5,HelloRuns:1,providerCalls:0,C2Calls:0,qualificationCalls:0,elapsedMs:performance.now()-startedAt,nativeElapsedMs:performance.now()-nativeStartedAt,driverPid:process.pid,claim:'Original bounded S01 plus two supported fresh reads completed on C02 with genuine preserved setup; not broader qualification'});console.log(JSON.stringify({phase:'CLOSED_native_success',newCalls:5,elapsedMs:performance.now()-startedAt}));
}catch(error){if(preflightTimer)clearTimeout(preflightTimer);let finalPhysical=null;try{if(c)finalPhysical=await c.physical('failure-final');const plan=await read(join(here,'resource-plan.json'));await fs.writeFile(join(here,'failure-native-prefix.jsonl'),await fs.readFile(plan.eventLogPath),{flag:'wx'});if(c?.state.closeHandoff)await write('final-handoff.json',c.state.closeHandoff);}catch(observationError){await write('failure-observation.json',{message:String(observationError)});}await write('failure.json',{phase,message:String(error),stack:error.stack,finalPhysical,closeHandoff:c?.state.closeHandoff??null,calls:c?.state.calls??[],elapsedMs:performance.now()-startedAt,driverPid:process.pid});console.error(error.stack);process.exitCode=1;}
