import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {originalGraphLawPackets} from './inputs.mjs';
import {executeInstalledGraphProof} from './driver.mjs';
const phase=fileURLToPath(new URL('.',import.meta.url)),tenant=fileURLToPath(new URL('../../../../../build_tenants/abiogenesis/typescript/',import.meta.url));
const [gtl,product,validator,publicApi,slots]=await Promise.all(['gtl/index.js','product/index.js','validator/index.js','public/index.js','shared/public_function_contracts.js'].map(path=>import(pathToFileURL(join(tenant,'build/code/src',path)).href)));
assert.equal(typeof executeInstalledGraphProof,'function');assert.equal(typeof publicApi.constructInstalledPublicDefinitionCall,'function');assert.equal(typeof product.constructCapabilityGrant,'function');assert.equal(typeof product.admissionEnvironmentSelection,'function');assert.ok(Array.isArray(slots.PUBLIC_AUTHORITY_SLOTS));assert.equal(validator.CONFORMANCE_OPERATION_CONTRACTS.evaluate.gtl_program.definitionKey.memberKey,'gtl_program');
const corpusPath=join(tenant,'contracts/conformance/gtl-language-conformance-corpus.json'),corpusBytes=await readFile(corpusPath),corpus=JSON.parse(corpusBytes);const rows=[];
for(const {id,packet} of originalGraphLawPackets(gtl,corpus)){assert.deepEqual(packet.program,corpus.programs[0].packet.program);assert.deepEqual(packet.publication.programs,corpus.programs[0].packet.publication.programs);const text=product.canonicalJson(packet)+'\n';const path=join(phase,id+'.json');await writeFile(path,text,{flag:'wx'});rows.push({id,path,bytes:Buffer.byteLength(text),fileDigest:product.sha256Bytes(Buffer.from(text)),packetDigest:product.sha256Canonical(packet),program:{ref:packet.program.programRef,digest:product.sha256Canonical(packet.program)},classification:'supplied malformed static packet, not installed/admitted producer proof'});}
const result={status:'PREPARATION_ONLY',syntaxImportOnly:true,sourceCorpus:{path:corpusPath,bytes:corpusBytes.length,digest:product.sha256Bytes(corpusBytes)},original63InputControls:rows,programValueUnchangedAcrossMutants:true,graphTemplatesDifferInPacketPublication:true,noSetupInstallCliRunProviderOrValidationExecuted:true};await writeFile(join(phase,'input-pins.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({status:result.status,controls:rows.length,corpusBytes:corpusBytes.length,driverImport:true,ownerImports:true,invocations:0,installs:0})+'\n');
