import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
const D=path.dirname(fileURLToPath(import.meta.url)),G=path.dirname(D),C=path.join(G,'final-candidate-construction-02'),Q=path.join(G,'final-qualification-inputs-02'),N=path.join(G,'final-observed-c2-01'),I=path.join(C,'install/node_modules/@abiogenesis/typescript-tenant');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),need=(x,m)=>{if(!x)throw Error(m);};
const expected={
 'final-end-to-end-forward-review-controls-01/request.txt':'e621447eb1179ae7fe90ca10e15cc0a7a1758a8337d9b9b3046932bac2927495',
 'final-candidate-construction-02/freeze.json':'7256ca2e716e73912f4937fdddc6d8a980a217ecf965cac1512ba5162dac4469',
 'final-qualification-inputs-02/freeze.json':'a4c2b5afd94fd7402b6bbfc732e691eb345dbcf4334a0300de490f607b9aad79',
 'final-observed-c2-01/return.md':'313c36287336b3c067f3bbc00776a8f2e0c5b7dde14c8daae13691b99ba8eabe',
 'final-observed-c2-01/freeze.json':'9949f56817f7f1f4bfca2a564e6de81146b9afedfde5698f573519500227efb8',
 'final-f11-material-scope-review-01/return.md':'e60b6a846a1d4776ded01f3ab247bc5d8eab2f5db6e6c9a48f0183a81808112e'
};
const subjects=Object.entries(expected).map(([p,h])=>{const b=fs.readFileSync(path.join(G,p));need(sha(b)===h,'subject '+p);return {path:p,bytes:b.length,sha256:h};});
const nfreeze=read(path.join(N,'freeze.json'));let bytes=0;for(const m of nfreeze.records){const p=path.resolve(N,m.path);need(p.startsWith(N+'/'),'outside frozen C2 territory');const b=fs.readFileSync(p);need(b.length===m.bytes&&sha(b)===m.sha256,'C2 frozen record '+m.path);bytes+=b.length;}
const digests=await import(pathToFileURL(path.join(I,'build/code/src/shared/digests.js'))),contracts=await import(pathToFileURL(path.join(I,'build/code/src/validator/qualification_contracts.js'))),worksite=await import(pathToFileURL(path.join(I,'build/code/src/product/worksite_command_execution.js'))),v=createRequire(path.join(I,'package.json'))('valibot'),hash=digests.sha256Canonical;
const task=read(path.join(N,'actual-observed-task.json')),recipe=read(path.join(Q,'verification-recipe.json')),selection=read(path.join(Q,'verification-selection-binding.json')),inventory=read(path.join(Q,'qualification-inventory.json'));
need(worksite.isObservedWorksiteCommandExecutionTask(task),'actual observed task');v.parse(contracts.QUALIFICATION_VERIFICATION_RECIPE_SCHEMA,recipe);need(task.commands.length===13&&task.outcomePredicates.length===14&&task.protectedObservations.length===716,'actual task population');
const recipeBytes=fs.readFileSync(path.join(Q,'verification-recipe.json'));need(selection.recipe.digest==='sha256:'+sha(recipeBytes)&&selection.recipe.byteCount===recipeBytes.length&&Buffer.from(selection.recipe.contentBase64,'base64').equals(recipeBytes),'recipe exact body');
const members=new Map(inventory.members.map(m=>[m.ref,m]));const declared=[...recipe.sourceInputs.map(s=>{const m=members.get(s.memberRef);need(m,'recipe member');return {relativePath:s.relativePath,digest:m.digest,byteCount:m.byteCount};}),...recipe.auxiliaryInputs,{relativePath:selection.recipePath,digest:selection.recipe.digest,byteCount:selection.recipe.byteCount}];
const protectedInputs=task.protectedObservations.map(p=>({relativePath:p.subject.relativePath,digest:p.observation.fileDigest,byteCount:p.observation.byteLength}));const sort=x=>[...x].sort((a,b)=>a.relativePath.localeCompare(b.relativePath));need(hash(sort(declared))===hash(sort(protectedInputs)),'actual task recipe protected input join');need(hash(task.commands)===recipe.commandConfigurationDigest&&hash(task.outcomePredicates)===recipe.predicateConfigurationDigest&&hash(task.allowedWriteTerritories)===recipe.writeTerritoriesDigest,'actual task exact recipe configurations');need(hash(task.protectedObservations)===task.sourceObservedInput.sourceSetDigest,'source set');need(!('executionSelectionRef' in selection),'unbound selected producer unexpectedly filled');
const value=read(path.join(N,'actual-c2-owner-value.json')),events=fs.readFileSync(path.join(N,'failure-native-prefix.jsonl'),'utf8').trimEnd().split('\n').map(JSON.parse);need(events.length===84,'frozen event population');need(value.disposition==='runtime_failed'&&value.result===null&&value.terminalResult===null,'actual failed Public output');
const actualResult=events.find(e=>e.admissionOrdinal===78),judgment=events.find(e=>e.admissionOrdinal===80),stop=events.find(e=>e.admissionOrdinal===84);need(actualResult.kind==='c_call_result_admitted'&&actualResult.payload.resultClass==='failure','failure Result');need(judgment.kind==='c_call_judged'&&judgment.payload.judgment==='blocked'&&judgment.payload.resultRef===actualResult.payload.resultRef,'blocked J');need(stop.kind==='run_stopped'&&stop.aggregateId===value.run.ref&&stop.payload.judgmentRef===judgment.payload.judgmentRef,'stopped actual Run');
const provider=read(path.join(N,'provider-observation.json')),selectedEvents=events.filter(e=>e.admissionOrdinal>=34&&['invocation_admitted','run_opened','c_call_opened','fp_dispatch_requested','c_call_result_admitted','c_call_judged','run_stopped'].includes(e.kind));
const compactEvents=selectedEvents.map(e=>({ordinal:e.admissionOrdinal,kind:e.kind,eventId:e.eventId,basisId:e.basisId,aggregateId:e.aggregateId,payload:e.kind==='fp_dispatch_requested'?{keys:Object.keys(e.payload),actorRef:e.payload.actorRef,inputDigest:e.payload.inputDigest}:e.kind==='c_call_opened'?Object.fromEntries(Object.entries(e.payload).filter(([k])=>['cCallRef','cCallDigest','programLocusRef','implementationRef','regime','graphCallId','contractRef'].includes(k))):e.kind==='invocation_admitted'||e.kind==='run_opened'?Object.fromEntries(Object.entries(e.payload).filter(([k])=>/Ref$|Digest$|Id$/.test(k)&&typeof e.payload[k]==='string')):e.payload}));
const inputFiles=['driver.mjs','output-checks.mjs','ordinary-caller.mjs','public-support.mjs','current-owner-source-relations.json','failure-source-relations.json','assertion-frontier.json','actual-observed-task.json','actual-c2-owner-value.json','provider-observation.json','failure-native-prefix.jsonl','final-handoff.json'].map(p=>{const b=fs.readFileSync(path.join(N,p));return {path:'final-observed-c2-01/'+p,bytes:b.length,sha256:sha(b)};});
const result={claim:'Exact frozen C2 task/recipe/failed-output and forward-contract checks, without native acquisition or fabricated success',subjects,c2Freeze:{records:nfreeze.records.length,bytes},recipeTask:{taskRef:task.taskRef,taskDigest:task.taskDigest,sourceObservedInput:task.sourceObservedInput,commands:13,predicates:14,protectedInputs:716,sourceInputs:recipe.sourceInputs.length,auxiliaryInputs:recipe.auxiliaryInputs.length,recipe:selection.recipe.ref,recipeDigest:selection.recipe.digest,recipePath:selection.recipePath,configurationDigests:[recipe.commandConfigurationDigest,recipe.predicateConfigurationDigest,recipe.writeTerritoriesDigest],join:true},actualEnvironment:{workspaceAuthorityBasis:task.workspaceAuthorityBasis,workspaceBinding:task.workspaceBinding,capabilityGrant:task.capabilityGrant},actualOutcome:{run:value.run,graphCall:value.graphCall,replay:value.replay,stop:value.stop,disposition:value.disposition,result:value.result,terminalResult:value.terminalResult,admittedResult:actualResult.payload,judgment:judgment.payload,stopPayload:stop.payload},events:compactEvents,inputFiles,unfinishedCaller:{executionSelectionRef:'absent in Q02 selection; no successful producer currently exists',successDriverOutputs:'runtime-slots.json would retain executionSelectionRef/tenantManifest/qualificationBasis null after successful cold reads; success branch not reached',nativeClaim:'No successful helper,13 commands,14 predicates,cold reads or qualification material executed by this check'},limits:['All reads use closed snapshots or immutable C02/Q02 files','No original native resource/current worksite read','No synthetic Result/task/basis/tenant authority/execution selection','No suite/provider/network/native/build/install effects']};
fs.writeFileSync(path.join(D,'observations.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({subjects:subjects.length,c2Records:nfreeze.records.length,c2Bytes:bytes,recipeTaskJoin:true,actualTask:task.taskRef,actualRun:value.run,actualFailure:actualResult.payload.resultRef,judgment:judgment.payload.judgment,executionSelectionRef:'absent',nativeCalls:0},null,2));
