"""Q05-only external caller adaptation; no imports or invocations of Product owners."""
from pathlib import Path
import json
G=Path('/Users/jim/src/apps/abiogenesis/.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE')
Q=G/'final-qualification-inputs-05';F=G/'f11-carrier-installed-input-preparation-01'
def write(n,v):
 p=Q/n;assert not p.exists();p.write_text(v)
def once(s,a,b):assert s.count(a)==1,(a,s.count(a));return s.replace(a,b)
s=(F/'ordinary-caller.mjs').read_text()
s=once(s,"import {loadRuntime,declaredCli,constructStart} from './public-support.mjs';", "import {loadRuntime,declaredCli,constructStart} from './public-support.mjs';\nimport {declaredInventoryConformanceResources} from './conformance-resources.mjs';\nimport {classifyInstalledOutcome,requirePublicResult} from './public-outcomes.mjs';\nimport {createHash} from 'node:crypto';\nimport {fileURLToPath} from 'node:url';")
s=once(s,"assert.equal(activation.operation,'T287_F11_CARRIER_INSTALLED_DISCRIMINATOR_01');", "assert.equal(typeof activation.operation,'string');\n const preparationFreeze=await readFile(join(dirname(dirname(fileURLToPath(import.meta.url))),'freeze.json'));\n assert.equal(activation.preparationFreezeSHA256,createHash('sha256').update(preparationFreeze).digest('hex'),'Root must bind this exact independently assured Q05 preparation');\n assert.equal(typeof activation.actorRef,'string');")
s=once(s,"base='abiogenesis/t287/f11-carrier-installed-discriminator-01',actorRef='actor://abiogenesis/t287/f11-carrier-installed-discriminator-01/operator'", "base='abiogenesis/t287/q05-selected-runtime',actorRef=activation.actorRef")
s=once(s,"if(terminal.code!==0||terminal.signal!==null||terminal.timedOut||terminal.spawnError)processFailure=terminal;", "if(terminal.signal!==null||terminal.timedOut||terminal.spawnError)processFailure=terminal;")
s=once(s,"assert.equal(transport.kind,'installed_definition_call_transport_result');const receipt=transport.receipt;", "const disposition=classifyInstalledOutcome({transport,terminal,call,installedPublic});\n  const receipt=disposition.receipt;\n  await write(mode+'-'+label+'-public-disposition.json',{kind:disposition.kind,proceed:disposition.proceed,exitCode:terminal.code});\n  if(receipt===null)return {call,receipt,disposition};")
s=once(s,"assert.equal(processFailure,null,JSON.stringify(processFailure));assert.equal(receipt.ownerOutput?.outcomeKind,'result',JSON.stringify(receipt));assert.equal(receipt.exitCode,0,JSON.stringify(receipt));return {call,receipt};", "assert.equal(processFailure,null,JSON.stringify(processFailure));return {call,receipt,disposition};")
a="{kind:'conformance_evaluation_resource_assertion',schemaVersion,packet:{kind:'conformance_evaluate_packet',schemaVersion,memberKey:'gtl_program',publication,program},conformanceLaw:law,artifactTruth:state.environment.artifactTruth,declaredInventory:state.catalog.boundPublications,declarationCatalog:{catalog:state.catalog,catalogView:state.catalogView}}"
b="declaredInventoryConformanceResources({publication,program,conformanceLaw:law,declaredInventory:state.catalog.boundPublications,catalog:state.catalog,catalogView:state.catalogView})"
s=once(s,a,b)
s=once(s,"assert.equal(res.receipt.ownerOutput.value.disposition,'passed'", "assert.equal(requirePublicResult(res).disposition,'passed'")
s=once(s,"reads[memberKey]=(await invoke(label+'-'+memberKey,call,'read')).receipt;", "const projected=await invoke(label+'-'+memberKey,call,'read');requirePublicResult(projected);reads[memberKey]=projected.receipt;")
write('f11/ordinary-caller.mjs',s)
s=(F/'flow-driver.mjs').read_text().replace('independently accepted C03','independently accepted C04 and Q05')
s=once(s,"import {actualOwnerContext,assessmentProof,", "import {actualOwnerContext,parentAssessmentProof,")
s=once(s,"import {createHash} from 'node:crypto';", "import {createHash} from 'node:crypto';\nimport {requirePublicResult} from './public-outcomes.mjs';")
s=once(s,"export async function runBoundExistingPrograms(c,packet,executionRoot){", "export async function runBoundExistingPrograms(c,packet,executionRoot,{parentSelection}){\n assert.ok(parentSelection,'actual selected wrapper Program/GraphFunction required');\n assert.notEqual(parentSelection.programRef,'program://abiogenesis/qualification/assess@5','no root-only assessment fallback');\n assert.equal(parentSelection.childGraphFunctionRef,c.gtl.QUALIFICATION_IDS.assessGraph);\n assert.equal(parentSelection.inputContractRef,c.gtl.QUALIFICATION_IDS.assessmentInput);")
s=once(s," const assessment=await c.prepareStart('program://abiogenesis/qualification/assess@5',gtl.QUALIFICATION_IDS.assessGraph,packet.assessmentInput,'assess',archive);", " // Only prepare the published core view for its exported renderer; never dispatch this root.\n const promptPreparation=await c.prepareStart('program://abiogenesis/qualification/assess@5',gtl.QUALIFICATION_IDS.assessGraph,packet.assessmentInput,'child-prompt-preparation-only',archive);\n const assessment=await c.prepareStart(parentSelection.programRef,parentSelection.graphFunctionRef,packet.assessmentInput,'parent',archive);")
s=once(s,"const assessmentOwner=await actualOwnerContext(c,assessment);", "const assessmentOwner=await actualOwnerContext(c,promptPreparation);")
s=once(s,"const started=await c.invoke('assess',assessment.call,'assessment'),value=started.receipt.ownerOutput.value;", "const started=await c.invoke('parent',assessment.call,'assessment');\n if(started.disposition.kind!=='result'){await write('selected-flow-stop.json',{boundary:'wrapper_parent',disposition:started.disposition.kind,exitCode:started.receipt?.exitCode??2,qualification:false,noFallback:true});return {status:'stopped',disposition:started.disposition.kind};}\n const value=requirePublicResult(started);")
s=once(s,"const observation=assessmentProof(c,value,packet.assessmentInput);", "const observation=parentAssessmentProof(c,value,packet.assessmentInput,parentSelection);")
s=once(s,"const selfStarted=await c.invoke('f11',self.call,'selfConformance'),selfValue=selfStarted.receipt.ownerOutput.value;", "const selfStarted=await c.invoke('f11',self.call,'selfConformance');\n if(selfStarted.disposition.kind!=='result'){await write('selected-flow-stop.json',{boundary:'F11',disposition:selfStarted.disposition.kind,qualification:false,noFallback:true});return {status:'stopped',disposition:selfStarted.disposition.kind};}\n const selfValue=requirePublicResult(selfStarted);")
s=once(s,"const verdictStarted=await c.invoke('af22',verdict.call,'verdict'),verdictValue=verdictStarted.receipt.ownerOutput.value;", "const verdictStarted=await c.invoke('af22',verdict.call,'verdict');\n if(verdictStarted.disposition.kind!=='result'){await write('selected-flow-stop.json',{boundary:'AF22',disposition:verdictStarted.disposition.kind,qualification:false,noFallback:true});return {status:'stopped',disposition:verdictStarted.disposition.kind};}\n const verdictValue=requirePublicResult(verdictStarted);")
s=once(s,"childGraphFoldback:'pending_separately_bound_wrapper'", "childGraphFoldback:observation.childFoldback")
write('f11/flow-driver.mjs',s)
print(json.dumps({'adapted':['ordinary-caller.mjs','flow-driver.mjs'],'invocationsExecuted':0}))
