import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),base=join(here,'..'),read=async p=>JSON.parse(await readFile(p,'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const setup=await read(join(base,'setup.json')),handoff=await read(join(here,'handoff.json')),timing=await read(join(here,'timing.json')),execution=await read(join(here,'execution.json')),input=await read(join(base,'input.json')),effects=await read(join(here,'effects.json')),files=await read(join(base,'input-files.json'));
const load=p=>import(pathToFileURL(join(setup.installedRoots[0],'build/code/src',p+'.js')).href),[store,prefixOwner,admission,product,replayOwner]=await Promise.all(['abg/event_store','abg/event_prefix','abg/invocation_admission','product/index','abg/replay'].map(load));
const events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),prefix=prefixOwner.selectValidatedRuntimeEventPrefix(events),runId=execution.output.receipt.resources.run.ref,runPrefix=prefixOwner.selectValidatedRuntimeEventPrefix(events,{runId}),replay=replayOwner.replayValidatedRuntimeEventPrefix(runPrefix,prefix),results=events.filter(e=>e.kind==='c_call_result_admitted'&&e.runId===runId),states=results.filter(e=>e.payload.resultClass==='success'&&product.isGovernanceWorkState(e.payload.value)),last=states.findLast(e=>e.payload.value.observations.length>0),commands=results.filter(e=>e.graphFunctionRef===product.WORKSITE_COMMAND_EXECUTION_IDS.graphFunctionRef&&e.payload.resultClass==='success'),syntheses=results.filter(e=>e.payload.value?.kind==='framed_synthesis_result'),choices=results.filter(e=>e.payload.value?.kind==='registered_graph_choice');
assert.ok(last);const root=events.find(e=>e.kind==='basis_admitted'&&e.payload.basisRef===last.basisId),invocation=admission.rehydrateInvocationAdmissionAtPrefix(prefix,root.payload.invocationAdmissionRef),request={publicAuthorityDigest:invocation.publicRequestDigest,runtimeInvocationRef:invocation.invocationRef,invocationAdmissionRef:invocation.invocationAdmissionRef,runId,resultRef:last.payload.resultRef};
const started=performance.now(),source=admission.deriveInvocationSourceResultBasisAtPrefix(prefix,request),sourceMs=performance.now()-started;await save('source-candidate.json',{request,source,sourceMs,meaning:'read-only candidate projection, not a new invocation admission or current workspace truth'});
const ref=e=>e?{ordinal:e.admissionOrdinal,eventRef:e.eventId,resultRef:e.payload.resultRef??null,graphFunctionRef:e.graphFunctionRef??null,cCallRef:e.aggregateId}:null;
for(const [path,v]of Object.entries(files))assert.equal(effects[path].sha256,'sha256:'+v.sha256,path);assert.equal(effects['assessment/consumer-context.md'].absent,true);
const reads=await Promise.all(['run_result','run_replay'].map(async member=>{const r=await read(join(here,'read-'+member+'.json'));const o=r.output.receipt.ownerOutput;return {member,outcomeKind:o.outcomeKind,code:o.refusal?.code??o.code??null,valueKind:o.value?.kind??null,keys:Object.keys(o),refusal:o.outcomeKind==='refusal'?o:null};}));
const toolUses=[];for(const a of timing.actors){const stdout=a.retained.find(r=>r.role==='stdout'&&!r.absent);if(!stdout)continue;for(const line of (await readFile(join(here,stdout.path),'utf8')).trim().split('\n')){let row;try{row=JSON.parse(line);}catch{continue;}for(const c of row.message?.content??[])if(c.type==='tool_use')toolUses.push({actor:a.actor,id:c.id,name:c.name,input:c.input});}}
await save('observed-tools.json',toolUses);
const summary={runId,ownerOutcome:{outcomeKind:execution.output.receipt.ownerOutput.outcomeKind,disposition:execution.output.receipt.ownerOutput.value?.disposition},replay:{runtimeStatus:replay.runtimeStatus,runtimeFailureEventRef:replay.runtimeFailureEventRef,runStoppedEventRef:replay.runStoppedEventRef,runClosedEventRef:replay.runClosedEventRef,actorProcesses:replay.actorProcesses.map(a=>({status:a.status,terminationConfirmed:a.terminationConfirmed}))},chain:syntheses.map(s=>({synthesis:ref(s),next:s.payload.value.judgment.nextGraphFunctionRef,reason:s.payload.value.judgment.nextReason,choice:ref(choices.find(c=>c.admissionOrdinal>s.admissionOrdinal&&(c.payload.value.input?.value?.synthesis?.resultRef===s.payload.resultRef||c.payload.value.disposition==='gap')))})),measurement:commands.map(e=>({event:ref(e),actorRef:e.payload.value.provenance.actorInvocationRef,commands:e.payload.value.commandResults.map(c=>({commandId:c.commandId,exitStatus:c.exitStatus,stdout:Buffer.from(c.stdout.payload,'base64').toString(),stderr:Buffer.from(c.stderr.payload,'base64').toString()}))})),stateCandidate:{...ref(last),sourceApplicable:source!==null,inputDigest:last.payload.valueDigest,producerResultRefs:last.payload.value.observations.map(o=>o.resultRef),unresolvedSupportRefs:last.payload.value.unresolvedSupportRefs},failedResults:results.filter(e=>e.payload.resultClass!=='success').map(ref),runClosures:events.filter(e=>e.runId===runId&&['run_closed','run_stopped','runtime_failed','gap_stop_admitted'].includes(e.kind)).map(e=>({kind:e.kind,...ref(e)})),reads,timing:{executionMs:timing.executionMs,nativeMs:timing.nativeMs,frameworkMs:timing.frameworkOutsideNativeMs,actors:timing.actors.map(a=>({actor:a.actor,ms:a.nativeIntervalMs,promptBytes:a.promptBytes,models:a.reportedModels,costUsd:a.reportedUsage.reduce((n,x)=>n+(x.totalCostUsd??0),0)})),readback:await read(join(here,'readback-timing.json')),eventCount:events.length,eventBytes:(await readFile(join(here,'events.jsonl'))).length},effects:{allTenInputFilesUnchanged:true,assessmentInputStillAbsent:true,observedToolUses:toolUses.length},classification:{runtime:'truthful declared F_P gap for missing user input after successful measurement; no failed CCall Result',harness:'final assertion expected an attempted prepare-native failure and rejected the permitted gap; preserved unchanged',claim:'retained producer exists; fresh source-use invocation and independent assessment remain unexecuted'}};
await save('closed-outcome.json',summary);console.log(JSON.stringify(summary,null,2));
