import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {performance} from 'node:perf_hooks';
import {SourceTextModule,SyntheticModule} from 'node:vm';
const here=dirname(fileURLToPath(import.meta.url)),records=resolve(here,'../..'),repo=resolve(records,'../../../..'),tenant=join(repo,'build_tenants/abiogenesis/typescript');
const load=p=>import(pathToFileURL(join(tenant,'build/code/src',p+'.js')).href);
const [store,prefixOwner,admission,product,truth]=await Promise.all(['abg/event_store','abg/event_prefix','abg/invocation_admission','product/index','abg/invocation_execution_truth'].map(load));
const suffix=process.argv[2] ? '-'+process.argv[2] : '';
const times={},find=async(name,relative)=>{const t=performance.now(),dir=join(records,relative),handoff=JSON.parse(await readFile(join(dir,'handoff.json'),'utf8')),events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),prefix=prefixOwner.selectValidatedRuntimeEventPrefix(events),states=events.filter(e=>e.kind==='c_call_result_admitted'&&e.payload.resultClass==='success'&&product.isGovernanceWorkState(e.payload.value));times[name]={readMs:performance.now()-t,eventCount:events.length,historyBytes:Buffer.byteLength(await readFile(join(dir,'events.jsonl'),'utf8'))};return {dir,handoff,events,prefix,states};};
const f=await find('failedBaseline','s6-fulfillment-implementation/live-01'),event=f.states.at(-1);assert.ok(event);
const basisEvent=f.events.find(e=>e.kind==='basis_admitted'&&e.payload.basisRef===event.basisId),invocation=f.events.find(e=>e.kind==='invocation_admitted'&&e.payload.invocationAdmissionRef===basisEvent.payload.invocationAdmissionRef);
const request={publicAuthorityDigest:invocation.payload.publicRequestDigest,runtimeInvocationRef:invocation.payload.invocationRef,invocationAdmissionRef:invocation.payload.invocationAdmissionRef,runId:event.runId,resultRef:event.payload.resultRef};
let t=performance.now();const source=admission.deriveInvocationSourceResultBasisAtPrefix(f.prefix,request);times.failedBaseline.sourceMs=performance.now()-t;assert.ok(source,'actual successful intermediate state of failed Run is admitted as source');
assert.equal(source.sourceResultRef,event.payload.resultRef);assert.equal(source.sourceCCallRef,event.aggregateId);assert.deepEqual(source.sourceResultValue,event.payload.value);
t=performance.now();assert.deepEqual(admission.rehydrateInvocationSourceResultBasisAtDurablePrefix(f.handoff.prefix,JSON.parse(JSON.stringify(source))),source,'cold durable rederivation conserves exact source basis');times.failedBaseline.coldMs=performance.now()-t;
assert.equal(admission.deriveInvocationSourceResultBasisAtPrefix(f.prefix,{...request,resultRef:'result:foreign'}),null);
assert.equal(admission.deriveInvocationSourceResultBasisAtPrefix(f.prefix,{...request,runtimeInvocationRef:'invocation:foreign'}),null);
assert.equal(admission.rehydrateInvocationSourceResultBasisAtDurablePrefix(f.handoff.prefix,{...source,sourceResultDigest:product.sha256Canonical('wrong')}),null);
const input=product.retainedGovernanceWorkInput(source.sourceResultValue),semantics=product.ABI5_DEFAULT_LIBRARY_PRODUCT_SEMANTICS,entry={input,workspaceBindingId:source.workspaceBindingId,workspaceBindingDigest:source.workspaceBindingDigest,workspaceId:source.sourceWorkspaceId,sourceResultBasis:source};
assert.equal(semantics.validateInvocationBasis(entry),true);assert.equal(semantics.validateInvocationBasis({...entry,input:{...input,original:{...input.original,task:'changed'}}}),false);assert.equal(semantics.validateInvocationBasis({...entry,sourceResultBasis:null}),false);
const producer=f.events.find(e=>e.kind==='c_call_result_admitted'&&e.payload.resultRef===input.observations[0].resultRef),current={...invocation.payload,sourceResultBasis:source};assert.ok(producer);assert.equal(truth.hasAdmittedGovernanceSourceUse(current,producer),true);assert.equal(truth.hasAdmittedGovernanceSourceUse(current,{...producer,aggregateId:'call:foreign'}),false);assert.equal(truth.hasAdmittedGovernanceSourceUse(current,{...producer,payload:{...producer.payload,resultDigest:product.sha256Canonical('foreign')}}),false);
const next=await find('laterWork','s6-context-projection-01/live-02');assert.ok(next.states.length>1);
const earlier=next.states.find(e=>e.payload.value.observations.length>0),later=next.states.at(-1),ib=next.events.find(e=>e.kind==='basis_admitted'&&e.payload.basisRef===earlier.basisId),iv=next.events.find(e=>e.kind==='invocation_admitted'&&e.payload.invocationAdmissionRef===ib.payload.invocationAdmissionRef),rq={publicAuthorityDigest:iv.payload.publicRequestDigest,runtimeInvocationRef:iv.payload.invocationRef,invocationAdmissionRef:iv.payload.invocationAdmissionRef,runId:earlier.runId,resultRef:earlier.payload.resultRef};
assert.equal(admission.deriveInvocationSourceResultBasisAtPrefix(next.prefix,rq),null,'later admitted work cannot be erased by choosing an earlier snapshot');assert.ok(admission.deriveInvocationSourceResultBasisAtPrefix(next.prefix,{...rq,resultRef:later.payload.resultRef}),'latest applicable actual native-work state is available');
// The new invocation admission itself is a controlled premise here. Exercise
// the actual cold external-owner projector against actual predecessor history;
// no invented event is admitted and no old events enter a new Run.
const file=join(tenant,'build/code/src/abg/replay.js'),currentPrefix={},newEvent={kind:'invocation_admitted',eventId:'controlled:new-admission',payload:{invocationAdmissionRef:'controlled:new-invocation',sourceResultBasis:source}},currentInvocation={admissionEventRef:newEvent.eventId,publicOperationEventRef:'controlled:new-public'};
const module=new SourceTextModule((await readFile(file,'utf8'))+'\nexport { projectOwnerFacts as sourceUseOwnerFacts };\n',{identifier:file});
await module.link(async specifier=>{const actual=await import(specifier.startsWith('node:')?specifier:pathToFileURL(resolve(dirname(file),specifier)).href),overrides=specifier==='./event_prefix.js'?{
  runtimeEventsFromValidatedPrefix:p=>p===currentPrefix?[newEvent]:actual.runtimeEventsFromValidatedPrefix(p),
  validatedRuntimeEventPrefixThroughEvent:(p,ref)=>ref===newEvent.eventId?f.prefix:actual.validatedRuntimeEventPrefixThroughEvent(p,ref),
  validatedRuntimeEventPrefixBeforeEvent:(p,ref)=>ref===currentInvocation.publicOperationEventRef?f.prefix:actual.validatedRuntimeEventPrefixBeforeEvent(p,ref)
}:specifier==='./invocation_admission.js'?{rehydrateInvocationAdmissionAtPrefix:(p,ref)=>ref==='controlled:new-invocation'?currentInvocation:actual.rehydrateInvocationAdmissionAtPrefix(p,ref)}:{};
  const values={...actual,...overrides};return new SyntheticModule(Object.keys(values),function(){for(const [k,v]of Object.entries(values))this.setExport(k,v);});});await module.evaluate();
const project=()=>module.namespace.sourceUseOwnerFacts(currentPrefix,f.prefix,{cCalls:[],routes:[],fanOutCompletions:[],constructionDeltas:[]},[],new Map([[newEvent.eventId,'current-owner-atom']]));
const external=project();assert.equal(external.length,1);assert.equal(external[0].owner,'invocation_source_result');assert.deepEqual(external[0].sourceResultBasis,source);
newEvent.payload.sourceResultBasis={...source,sourceResultDigest:product.sha256Canonical('crossed')};assert.throws(project,/exact admitted external source-result basis/);newEvent.payload.sourceResultBasis=source;
const result={passed:true,providerCalls:0,installed:false,controlledNewInvocationExternalOwnerFact:true,actualSource:{runId:source.sourceRunId,stateResultRef:source.sourceResultRef,stateCCallRef:source.sourceCCallRef,producerResultRef:producer.payload.resultRef,producerCCallRef:producer.aggregateId,producerActorRef:producer.payload.value.provenance.actorInvocationRef,sourceReplayRef:source.sourceReplayRef,sourceReplayDigest:source.sourceReplayDigest},laterWork:{olderResultRef:earlier.payload.resultRef,latestResultRef:later.payload.resultRef},timings:times,limits:'Actual immutable failed histories and cold source owner; Product input correspondence and internal use identity. Actual cold replay external-owner projection uses a controlled new-invocation admission premise. No new invocation/actor, effect or installed-success claim.'};
await writeFile(join(here,'actual-source-check'+suffix+'.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});await writeFile(join(here,'selected-source-basis'+suffix+'.json'),JSON.stringify(source,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result,null,2));
