from pathlib import Path
import json,hashlib,stat,os,time,datetime,signal,difflib
signal.alarm(60);started=time.monotonic();R=Path('/Users/jim/src/apps/abiogenesis');N=Path(__file__).resolve().parent;G=N.parent
sha=lambda b:hashlib.sha256(b).hexdigest()
def read(p):return json.loads(p.read_text())
def save(name,value):
 with (N/name).open('x') as f:json.dump(value,f,indent=2);f.write('\n')
def record(p,root):
 s=p.lstat()
 if p.is_symlink():return {'path':str(p.relative_to(root)),'kind':'symlink','target':os.readlink(p)}
 b=p.read_bytes();return {'path':str(p.relative_to(root)),'kind':'file','mode':stat.S_IMODE(s.st_mode),'bytes':len(b),'sha256':sha(b)}
def verify(p,e):
 if e.get('kind')=='symlink':assert p.is_symlink() and os.readlink(p)==e['target'];return
 assert p.is_file() and not p.is_symlink(),str(p)
 b=p.read_bytes();assert len(b)==e['bytes'] and sha(b)==e['sha256'],str(p)
 if 'mode' in e:assert stat.S_IMODE(p.stat().st_mode)==e['mode'],str(p)
expected={'final-observed-c2-01':'9949f56817f7f1f4bfca2a564e6de81146b9afedfde5698f573519500227efb8','final-qualification-inputs-02':'a4c2b5afd94fd7402b6bbfc732e691eb345dbcf4334a0300de490f607b9aad79','final-c2-output-consumer-repair-01':'5b705555a5ebd9a58e0402667a0f31f9256e3e3ce643930f065d33bee34650f6','final-c2-output-consumer-review-01':'dcc50dcc635d9ac4184945afe74bffabfd9db59d4b4fa01b651a5b4487e803b5'}
verified=[]
for d,h in expected.items():
 p=G/d/'freeze.json';assert sha(p.read_bytes())==h;f=read(p)
 for e in f['records']:verify(G/d/e['path'],e)
 verified.append({'directory':str(G/d),'freezeSHA256':h,'recordsVerified':len(f['records'])})
C=G/'final-candidate-construction-02';assert sha((C/'freeze.json').read_bytes())=='7256ca2e716e73912f4937fdddc6d8a980a217ecf965cac1512ba5162dac4469'
cf={e['path']:e for e in read(C/'freeze.json')['records']};sourceprefix='source-freeze/repo/build_tenants/abiogenesis/typescript/code/src/'
sourceRelations={
'abg/environment_admission.ts':'482-528: current exact-prefix environment projection; authenticated artifact owner; same A/W/installs/lock/productSet at latest prefix',
'abg/artifact_truth.ts':'664-677,711-748: prefix/count/last admission ordinal included in projection digest/ref; rows survive lawful unrelated Run advancement',
'abg/event_store.ts':'1991-2119: current projection cold prefix acquisition is O_RDONLY/fstat/read/close plus byte/event validation; no event owner acquisition or writes',
'product/worksite_command_execution.ts':'457-495,706-780,2002-2050,2075-2166: exact observed-input task, helper plan and actual artifact-to-observation ownership',
'product/stdo_environment.ts':'191-202,218-280: future exact context resources and read_context observation against fresh invocation authority',
'product/run_invocation_operation.ts':'614-638: future Product preparation consumes actual context resource owner observation',
'owner_bindings/run_invocation.ts':'1100-1114,1303-1324: supported wrapper transports actual runEnvironmentResources into Product preparation',
'abg/terminal_result_contracts.ts':'8-29: typed terminal producer, not obsolete provenance',
'validator/qualification_contracts.ts':'212-232: future actual successful observed Result and exact producer basis relation',
'abg/qualification_proof.ts':'694-746: future genuine Result/J/Program/invocation/locus and prefix identity to qualification; no fabricated success inputs'}
sources=[]
for logical,meaning in sourceRelations.items():
 key=sourceprefix+logical;verify(C/key,cf[key]);sources.append({'logicalRepositoryPath':'build_tenants/abiogenesis/typescript/code/src/'+logical,'frozenPath':str(C/key),'sha256':cf[key]['sha256'],'relation':meaning})
# Exact N04 immutable retained values are donors; no stale handoff is selected.
P=G/'final-native-continuation-04';pf={e['path']:e for e in read(P/'freeze.json')['records']};retainedDonors=[]
for name in ['retained-environment.json','runtime-slots.json']:verify(P/name,pf[name]);retainedDonors.append(record(P/name,G))
for e in read(N/'donor-preimages.json'):
 verify(Path(e['path']),e)
 if 'preimage' in e:assert (N/e['preimage']).read_bytes()==Path(e['path']).read_bytes()
changed=read(N/'changed-paths.json')
for name in changed['modifiedDonorCopies']:
 a=(N/'preimages'/name).read_text();b=(N/name).read_text();actual=''.join(difflib.unified_diff(a.splitlines(True),b.splitlines(True),fromfile='final-observed-c2-01/'+name,tofile=N.name+'/'+name));assert (N/(name+'.patch')).read_text()==actual
old=read(P/'retained-environment.json')['projection'];current=read(N/'offline-current-projection.json');changedTop=[k for k in old if old[k]!=current[k]];assert changedTop==['prefix','artifactTruth'];changedTruth=[k for k in old['artifactTruth'] if old['artifactTruth'][k]!=current['artifactTruth'][k]];assert changedTruth==['prefix','prefixEventCount','lastAdmissionOrdinal','projectionRef','projectionDigest']
unchanged=[k for k in old if k not in changedTop];truthUnchanged=[k for k in old['artifactTruth'] if k not in changedTruth]
triage={'reentry':'realization_refactor; external current-prefix caller adaptation','cause':'Donor full projection equality conflates lifecycle-dependent prefix projection identity with conserved admitted environment values. Lawful failed-C2 history advanced33 to84 events, without changing environment admissions.','changedTopFields':changedTop,'unchangedTopFields':unchanged,'artifactTruthUnchangedFields':truthUnchanged,'artifactTruthChangedFields':{k:{'retainedN04':old['artifactTruth'][k],'actualCurrentOwner':current['artifactTruth'][k]} for k in changedTruth},'comparisonMeaning':'Current prefix must exactly match latest genuine C2 handoff; every admitted environment value and artifact row must equal retained owner values. Prefix/count/ordinal/ref/digest are the freshly authenticated owner output, fully retained in offline-current-projection.json, not discarded or forged. Owner source hashes above fix their derivation.','frames':{'Product':'Same immutable C02; no new environment, Product, result or qualification claim.','Design':'Existing exact-prefix projections derive identities from current admitted history. No HOW change.','Integration':'Replace stale full-value comparison; keep actual owner current-prefix projection and check conserved values. Future constructStart/Product preparation still owns actual catalog/program/readiness.','Identity':'Physical resource and A/W/install/lock/catalog coordinates conserved; prefix and projection identities advance. Selected task/grant semantic identity may repeat; new operation refs distinguish occurrence.','Lifecycle':'Historical N04 projection remains immutable evidence. Failed C2 is genuine history, not recovery to erase or replay.','Effect':'Read-only prefix and716-file checks; future context/native/helper effects need separate grant.','Proof':'Actual installed projection plus byte correspondence, stale/crossed counterexamples and exact retained owner values. Syntax/static successor joins do not establish native C2 success.'},'catalogScope':'Current environment projection owns A/W/install/lock; it does not itself freshly construct a catalog. Retained immutable catalog/view are bound to same A/W/lock and retained coordinates. Full actual catalog/program resolution and readiness remain required in future unchanged installed constructStart/Product preparation.'}
save('projection-triage.json',triage);save('owner-relations.json',{'sourceBindings':sources,'pastForwardTraversal':'Reused CLOSED C2 and reader analysis; no new owner/runtime repair','pureCallsExecuted':['Q02 selectedFiles reads declared origin inventory','supported installed abg.projectExactPrefixWorkspaceEnvironment reads/authenticates current prefix','external current-input checker and local counterexamples'],'futureCallsOnly':['ProductVerificationPort.verify/selectOwnedProductVerification','constructStart fresh invocation authority and DIRECT_INVOKE grants','constructRunEnvironmentResources and observeRunEnvironment','unchanged Q02 constructObservedProducerTask then actual ProductRunInvocationPort.prepare','one ordinary Public start and two fresh CLI reads','accepted output reader task/plan/helper-artifact snapshot binding for reports/comparison/925reads and cold Result/replay'],'qualificationFutureRoute':'validator qualification contracts -> ABG qualification proof -> actual Result/J/prefix -> constructQualificationVerificationMaterial. Producer slots unbound until successful genuine C2; no tenantManifest/executionSelectionRef/qualificationBasis minted.'})
plan=read(N/'resource-plan.json');p=Path(plan['eventLogPath']);s=p.stat();b=p.read_bytes();assert s.st_dev==16777230 and s.st_ino==464012478 and len(b)==5577377 and sha(b)==plan['initialPrefixSHA256'];assert not Path(plan['futureContextRoot']).exists();assert not (Path(plan['lockNamespace'])/(str(s.st_dev)+'-'+str(s.st_ino)+'.lock')).exists()
# Recheck every selected file after all pure import/check work, without restaging.
inputs=read(N/'offline-all716-inputs.json');assert len(inputs['observations'])==716
for e in inputs['observations']:
 p=Path(e['path']);st=p.lstat();assert stat.S_ISREG(st.st_mode) and p.resolve()==p and st.st_dev==e['device'] and st.st_ino==e['inode'];assert p.stat().st_size==e['bytes'] and sha(p.read_bytes())==e['sha256']
selection=read(G/'final-qualification-inputs-02/test-selection.json');assert len(selection['tests'])==5
save('conservation.json',{'status':'passed','closedDonorCuts':verified,'N04RetainedDonors':retainedDonors,'C02':'Accepted frozen16774-member candidate reused; freeze hash and ten exact causal source members freshly verified, no broad requalification','preimagesAndPatches':'Exact donor bytes and all five unified patches verified','actualResource':{'device':s.st_dev,'inode':s.st_ino,'bytes':len(b),'sha256':sha(b),'events':84,'lockAbsent':True,'futureContextAbsent':True},'original716Files':'all lengths/digests/canonical regular identities checked again after offline work','selectedGroups':len(selection['tests']),'writesOutsideTerritory':0,'nativeCalls':0,'providerCalls':0,'driverImportsOrExecutions':0})
checks=read(N/'offline-checks.json');total=read(N/'offline-processes.json')['elapsedMs']+read(N/'offline-processes02.json')['elapsedMs']+(time.monotonic()-started)*1000;assert total<180000
save('closed-state.json',{'status':'CLOSED_PREPARATION_READY_LIMITED','activation':'T287_C2_CURRENT_RESOURCE_CALLER_02','offlineCasesPassed':checks['checks'],'priorHarnessProbe':'Preserved internal-versus-public export assumption; corrected only local checker','aggregateOfflineElapsedMsThroughConservation':total,'aggregateBudgetMs':180000,'futureDriver':'Never imported or executed; syntax only','futureExecution':'Not authorized; Root assurance and later exact grant required; DNS unresolved','resource':'Same unchanged84-event C2 handoff; existing716 retained','qualification':'Success-shaped slots remain null/unbound','actualAuthor':'/root/s03_phase_b','sessionId':'01a0f036-c7b5-7f40-b1d8-e53a1fcf24f4','profile':'Root-selected Astra/xhigh, not independently attested','closedAt':datetime.datetime.now(datetime.timezone.utc).isoformat()})
returnText='''# T287_C2_CURRENT_RESOURCE_CALLER_02 — CLOSED preparation-ready/limited

The future three-call caller is prepared against the latest genuine C2 handoff and the existing716 inputs. It imports the independently accepted reader directly. No future driver import/execution, native/provider/helper operation, runtime preparation, Product verification, restaging or genuine-resource write occurred. DNS remains unresolved; this cut does not authorize execution.

`driver.mjs` now uses final-observed-c2-01/final-handoff.json (452d82338db55b5ae53406516df6186fe7a39018adbbcccd33b6ff3269c0f7ff), the original dev16777230/inode464012478 resource,5577377 bytes/84events and prefix81cefea619af712a416d8680efa40fc2bed1f3248460022e4e625eef0ed46c0c. Existing716 canonical regular targets and origins are checked before context construction, again before the unchanged observed-task constructor under fresh actual grant, and after future output/cold reads. The original final716 rereads and full prior-prefix byte conservation remain.

Five donor copies changed: driver, ordinary caller operation/provenance base, runtime report/config/cache paths, proposed budgets and resource plan. `changed-paths.json`, exact preimages and five unified patches identify the delta. Public support, complete owner checks, observer/launcher, selected C02 and prospective input copies are unchanged. New `current-inputs.mjs` contains read-only reuse/environment checks. All reports target this new directory; the accepted reader itself is unchanged.

The current installed environment projection was actually recomputed through the supported ABG export. Its admitted A/W/install/lock/productSet values and artifact owner rows equal N04. Full projection equality would incorrectly reject lawful advancement: only prefix and artifact-truth prefix/count/lastAdmissionOrdinal/ref/digest changed (33 to84 events). `projection-triage.json` accounts for every top-level and artifact-truth field across Product/Design/Integration/Identity/Lifecycle/Effect/Proof, preserving actual old/new values. Catalog/view remain retained immutable values bound to the conserved environment; actual future installed catalog/program/readiness resolution is still required. This is caller adaptation, not a Product defect or a new projection implementation.

Ten focused offline checks passed: actual prefix/environment, stale prefix, crossed authority, all716, digest mismatch, root escape, duplicate target, changed bytes, symlink alias and missing target; the tenth named check also includes static future input/output/cold-read/configuration joins. See `offline-checks.json` for the exact case population (the separate all716 case is included there). All successor modules passed syntax checks; Python launch/observer controls were parsed without running them. The first local checker probe incorrectly assumed an internal validator was a public export. Its source, failure and process evidence are preserved; `harness-correction.json` binds the correction to exact handoff bytes and the supported current-prefix owner. No owner mismatch was found. This is bounded offline evidence, not future native success.

All220 records across the CLOSED C2/Q02/reader/review cuts were reverified, together with N04 retained environment/slots, exact donor preimages, ten C02 causal source members and the unchanged original resource and716 files. Accepted C02/S01/reader dispositions are retained; this cut does not independently requalify the entire Product. `conservation.json` states the exact verification population.

The future execution plan is explicit in `resource-plan.json` and `budgets.json`: current same-process nominal Product verification; actual current prefix/environment and716 checks; fresh invocation authority, DIRECT_INVOKE grant and owner context observation; create-only original archiveRoot/observed-c2-02-context with read_context permission; one ordinary C2 start then two fresh reads, original TMPDIR/lock namespace. Only existing helper owners select an attempt archive and sandbox; reports/comparison/925 generated-body reads use the accepted authenticated helper snapshot root. No writes to the original716 or failed-Run recovery are proposed. Proposed ceilings remain120000ms preparation +3066000ms driver (3186000 total); helper963000, provider inactivity1083000/absolute1263000, one selected provider and no caller retry. Root must separately grant these effects and decide the unresolved provider condition before execution.

All13 commands/14 predicates/5 groups/30 titles/925 outputs, strict lint/test and typed terminal Result plus fresh result/replay joins remain. The accepted reader consumes actual successful observation/task/helper-plan/artifact material; no workspaceRoot override is passed. Fresh reads bind their actual new Run, current handoffs and owner source/producer projections. New operation refs identify the operation; repeated immutable semantic task/grant content is not forced to change. Existing qualification owner routes remain named in `owner-relations.json`; actual successful Result/J/prefix, tenant manifest, execution selection and qualification basis remain unbound.

Actual present author: /root/s03_phase_b, session01a0f036-c7b5-7f40-b1d8-e53a1fcf24f4; Root-selected Astra/xhigh. This attributes only this external construction delta, not original semantic authorship, Product-owner qualification authority, native admission or independent review. Root owns assurance and any later execution. Worker stops at this freeze.
'''
# Use actual check population rather than a hand-count in prose.
returnText=returnText.replace('Ten focused offline checks passed:',str(checks['checks'])+' focused offline checks passed:').replace('; the tenth named check also includes static future input/output/cold-read/configuration joins. See `offline-checks.json` for the exact case population (the separate all716 case is included there).','; plus static future input/output/cold-read/configuration joins. See `offline-checks.json` for the exact population.')
(N/'return.md').write_text(returnText)
save('closure-cost.json',{'closureElapsedMs':(time.monotonic()-started)*1000,'aggregatePriorCheckAndClosureMs':read(N/'offline-processes.json')['elapsedMs']+read(N/'offline-processes02.json')['elapsedMs']+(time.monotonic()-started)*1000,'closureProcessBudgetMs':60000,'graceMs':1000,'nativeOrProviderProcesses':0})
records=[record(p,N) for p in sorted(N.rglob('*')) if p.is_file() or p.is_symlink()]
save('freeze.json',{'status':'CLOSED','activation':'T287_C2_CURRENT_RESOURCE_CALLER_02','root':str(N),'recordCount':len(records),'records':records,'scope':'Exact current-resource external caller preparation only; no native authorization','preservedDonorCuts':verified,'noFurtherWorkerEffects':True})
for e in records:verify(N/e['path'],e)
print(json.dumps({'status':'CLOSED_PREPARATION_READY_LIMITED','recordCount':len(records),'returnSHA256':sha((N/'return.md').read_bytes()),'freezeSHA256':sha((N/'freeze.json').read_bytes()),'driverSHA256':sha((N/'driver.mjs').read_bytes()),'readerSHA256':sha((G/'final-c2-output-consumer-repair-01/output-checks.mjs').read_bytes()),'nativeCalls':0,'providerCalls':0,'elapsedMs':(time.monotonic()-started)*1000}));signal.alarm(0)
