import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {writeFileSync} from 'node:fs';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {here,read,write,caller,verificationRequest,schemaVersion} from './ordinary-caller.mjs';import {loadRuntime} from './public-support.mjs';import {checkStart} from './owner-checks.mjs';import {makeOutputChecks} from '../final-c2-output-consumer-repair-01/output-checks.mjs';import {checkExistingInputs,assertRetainedEnvironment} from './current-inputs.mjs';
import * as recipe from '../final-qualification-inputs-02/recipe.mjs';
// FUTURE EXECUTION ONLY: this preparation grant does not authorize importing or running this driver.
const P=join(here,'../final-native-continuation-04'),D=join(here,'../final-observed-c2-01'),Q=join(here,'../final-qualification-inputs-02'),startedAt=performance.now(),budgets=await read(join(here,'budgets.json')),window={deadline:null};let c=null,phase='preflight',nativeStartedAt=null,environmentObservation=null,reusedInputs=0;const reached=[];const mark=s=>reached.push(s),sha=b=>createHash('sha256').update(b).digest('hex');
await write('driver-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgets,exactCalls:3});
let preflightTimer=setTimeout(()=>{writeFileSync(join(here,'preflight-timeout.json'),JSON.stringify({phase,capMs:120000,nativeCalls:c?.state.calls.length??0,reusedInputs})+'\n',{flag:'wx'});process.exit(1);},120000);
try{
 const identity=await read(join(here,'selected-core.json')),prospect=await read(join(here,'prospective-cases.json')),r=await loadRuntime(identity.installedRoot),{product,abg,gtl}=r;assert.equal(typeof product.isObservedWorksiteCommandExecutionObservation,'function');assert.equal(typeof product.isWorksiteExecutionHelperArtifact,'function');assert.equal(typeof product.constructRunEnvironmentResources,'function');const output=makeOutputChecks({product,installedRoot:identity.installedRoot});
 const request=verificationRequest(prospect.core),verification=await product.ProductVerificationPort.verify({kind:'product_verification_packet',schemaVersion,memberKey:'verify',targetKind:'packed_artifact',request});await write('bootstrap-core.json',verification);assert.equal(verification.kind,'product_verification_success');assert.strictEqual(product.selectOwnedProductVerification(request,verification.verifiedArtifact),verification.verifiedArtifact);mark('same-process nominal Product verification and selection');
 c=await caller('c2',verification,window);const {state,hash}=c,retained=await read(join(P,'retained-environment.json')),slots=await read(join(P,'runtime-slots.json')),initial=await read(join(D,'final-handoff.json')),originalBytes=await fs.readFile(join(D,'failure-native-prefix.jsonl'));state.closeHandoff=initial;state.binding=slots.workspaceBinding;state.resolvedLock=retained.projection.resolvedProductLock;state.catalog=retained.catalog;state.catalogView=retained.catalogView;c.refresh();assertRetainedEnvironment(state.environment,retained,slots,initial.prefix);assert.equal(c.op.actorRef,state.environment.workspaceAuthorityBasis.authorizedActorRef);
 const physical=await c.physical('initial');assert.equal(physical.device,16777230);assert.equal(physical.inode,464012478);assert.equal(physical.bytes,5577377);assert.equal(originalBytes.length,5577377);assert.equal(originalBytes.toString().trim().split("\n").length,84);assert.equal(sha(originalBytes),physical.sha256);assert.equal(physical.sha256,'e2bb5df3f58b91a49f7324a487e9e79b93d05b03c368c339c82a6edc9d359ec0');assert.equal(initial.prefix.coordinateDigest,'sha256:81cefea619af712a416d8680efa40fc2bed1f3248460022e4e625eef0ed46c0c');mark('actual original resource/prefix/actor/A-W/current owner projection');
 const root=state.environment.workspaceAuthorityBasis.canonicalRoot;assert.equal(root,(await read(join(here,'resource-plan.json'))).workspaceRoot);assert.equal(await fs.realpath(root),root);const files=await recipe.selectedFiles(),staging=await read(join(Q,'staging-contract.json'));assert.equal(files.length,716);assert.deepEqual(files.map(x=>x.target),staging.targets);assert.equal(new Set(files.map(x=>x.target)).size,716);
 async function absent(p){try{await fs.lstat(p);assert.fail('declared new target already exists: '+p);}catch(e){if(e.code!=='ENOENT')throw e;}}
 const existing=await checkExistingInputs(root,files,staging.targets);assert.equal(existing.count,716);reusedInputs=existing.count;await write('all716-current-input-checks.json',existing);mark('all716 existing canonical regular inputs and origins exact; zero staging writes');
 const configBinding=await read(join(Q,'configuration-binding.json')),verificationRecipe=await read(join(Q,'verification-recipe.json')),testSelection=await read(join(Q,'test-selection.json')),expected=await read(join(Q,'expected-output-inventory.json'));assert.equal(hash(configBinding.commands),verificationRecipe.commandConfigurationDigest);assert.equal(hash(configBinding.predicates),verificationRecipe.predicateConfigurationDigest);assert.equal(hash(configBinding.allowedWriteTerritories),verificationRecipe.writeTerritoriesDigest);assert.equal(configBinding.commands.reduce((n,x)=>n+x.timeoutMs+x.terminationGraceMs,0),958000);assert.equal(expected.paths.length,925);assert.equal(testSelection.totalSelectedTitles,30);mark('unchanged exact13/14/5/30/925 configuration');
 const resourcesFactory=async({authority,resolution,declaration})=>{
  phase='environment-resources';assert.equal(declaration.dependencies.length,1);assert.equal(declaration.contexts.length,1);assert.equal(declaration.roles.length,1);assert.equal(declaration.roles[0].role,'command_executor');assert.equal(declaration.corpusAccess,null);assert.deepEqual(declaration.accesses,[]);const archiveRoot=state.environment.workspaceBinding.roots.archiveRoot,temporaryRoot=join(archiveRoot,'observed-c2-02-context');assert.equal(temporaryRoot,(await read(join(here,'resource-plan.json'))).futureContextRoot);await absent(temporaryRoot);const archiveStatus=await fs.lstat(archiveRoot);assert.ok(archiveStatus.isDirectory()&&!archiveStatus.isSymbolicLink());assert.equal(await fs.realpath(archiveRoot),archiveRoot);await write('context-resource-creation-intent.json',{archiveRoot,archiveAbsent:false,temporaryRoot,temporaryAbsent:true,operation:'exclusive new context directory; current invocation authority; read_context only',authority,authorization:'Requires separate future native grant covering this exact path; current preparation grant does not authorize execution'});await fs.mkdir(temporaryRoot);assert.equal(await fs.realpath(temporaryRoot),temporaryRoot);const productRoot=state.environment.workspaceBinding.roots.productRoot,coordinates={dependencies:[{dependencyRef:declaration.dependencies[0].dependencyRef,root:productRoot,recordPath:join(productRoot,gtl.WORKSITE_COMMAND_EXECUTION_CONTEXT_INVENTORY.path)}],temporaryRoot,pythonPath:null};
  const resources=product.constructRunEnvironmentResources({kind:'run_environment_resources',schemaVersion,...coordinates,permission:{authorityRef:authority.authorityRef,authorityDigest:authority.authorityDigest,actorRef:authority.actorRef,programRef:resolution.program.programRef,environmentRef:declaration.declarationRef,environmentDigest:hash(declaration),operations:['read_context'],...coordinates}});environmentObservation=await product.observeRunEnvironment({publication:resolution.programPublication,program:resolution.program,graphFunctions:resolution.declarationPublications.flatMap(p=>p.graphFunctions),authority:{authorityRef:authority.authorityRef,authorityDigest:authority.authorityDigest,actorRef:authority.actorRef},archiveRoot,resources});await write('current-context-owner-observation.json',{resources,authority,declaration,environmentObservation});assert.equal(environmentObservation.kind,'run_environment_observed',JSON.stringify(environmentObservation));assert.ok(environmentObservation.evidence);mark('actual invocation-authority-bound current renderer context observed before task construction');return resources;
 };
 let task;
 const inputFactory=async({grants})=>{phase='current-input-recheck';assert.equal(environmentObservation?.kind,'run_environment_observed');assert.equal(grants.length,1);await write('actual-direct-grant.json',{grants,workspaceAuthorityBasis:state.environment.workspaceAuthorityBasis,workspaceBinding:state.environment.workspaceBinding});const current=await checkExistingInputs(root,files,staging.targets);assert.equal(current.count,716);await write('all716-before-task-checks.json',current);mark('existing716 rechecked under actual current grant before unchanged task constructor');phase='observed-task-construction';task=await recipe.constructObservedProducerTask({product,workspaceAuthorityBasis:state.environment.workspaceAuthorityBasis,workspaceBinding:state.environment.workspaceBinding,capabilityGrant:grants[0]});assert.equal(product.isObservedWorksiteCommandExecutionTask(task),true);assert.deepEqual(task.commands,configBinding.commands);assert.deepEqual(task.outcomePredicates,configBinding.predicates);assert.deepEqual(task.allowedWriteTerritories,configBinding.allowedWriteTerritories);assert.equal(task.protectedObservations.length,716);await write('actual-observed-task.json',task);return task;};
 const prepared=await c.prepareStart('program://abiogenesis/worksite/command-execution@5','graph-function://abiogenesis/worksite/command-execution@5',inputFactory,'observed-c2',resourcesFactory);prepared.environmentObservation=environmentObservation;phase='complete-owner-preparation';const ownerCheck=await checkStart(c,prepared);await write('c2-owner-precondition.json',ownerCheck);mark('actual complete current Product preparation with selected F_P input/context/authority');
 const readContracts=['run_result','run_replay'].map(memberKey=>{const packet=abg.ABG_PROJECT_READ_CONTRACTS[memberKey],m=verification.verifiedArtifact.definitionContractCoordinates.operations.find(x=>x.operationId===packet.definitionKey.operationId).members.find(x=>x.memberKey===memberKey);assert.ok(m.slots.request&&m.slots.result);return {memberKey,packet,coordinates:m,ownerResourceKeys:['eventResource','kind','schemaVersion'],futureDependencies:'Actual produced Run and latest owner close handoff; current grants and three-key resource checked immediately before each read'};});
 assert.ok(performance.now()-startedAt<120000);clearTimeout(preflightTimer);preflightTimer=null;await write('pure-preflight.json',{status:'passed',elapsedMs:performance.now()-startedAt,nativeCalls:0,reusedInputs,initialPrefix:initial.prefix,physical,actualNominalVerification:true,currentEnvironmentObservedBeforeTask:true,stagingWrites:0,actualProductPreparation:true,readContracts,outputContract:'abg typed terminal producer; observed C2 task/13/14/716/strict reports/925 then fresh source ref-digest/result/replay joins',reached});console.log(JSON.stringify({phase:'complete_c2_input_and_consumer_preflight_passed',reusedInputs,nativeCalls:0}));
 nativeStartedAt=performance.now();window.deadline=nativeStartedAt+budgets.driverBudgetMs;await write('native-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgetMs:budgets.driverBudgetMs,operationPlan:budgets.operationPlan});phase='observed-c2';const started=await c.invoke('observed-c2',prepared.call,'c2');mark('native C2 receipt result exit0');const value=started.receipt.ownerOutput.value;await write('actual-c2-owner-value.json',value);phase='c2-output-consumption';const consumed=await output.consume({value,task,recipe:verificationRecipe,selection:testSelection,expected,write,mark});console.log(JSON.stringify({phase:'observed_c2_material_passed',run:value.run,commands:13,predicates:14,tests:30,outputs:925}));
 phase='cold-reads';const reads=await c.freshReads('observed-c2',started),cold=output.cold(value,reads);mark('both fresh read source/producer/result/replay values');assert.equal(state.calls.length,3);assert.ok(performance.now()<window.deadline);await write('cold-results.json',{reads,cold,closeHandoff:state.closeHandoff});
 phase='final-conservation';const finalInputs=await checkExistingInputs(root,files,staging.targets);assert.equal(finalInputs.count,716);await write('all716-final-input-checks.json',finalInputs);for(const f of files){const bytes=await fs.readFile(join(root,f.target));assert.equal(bytes.length,f.bytes);assert.equal(sha(bytes),f.sha256);}mark('physical protected716 after native and cold reads');const finalPhysical=await c.physical('final'),finalBytes=await fs.readFile(initial.reopenAuthority.eventLogPath);assert.equal(finalPhysical.device,physical.device);assert.equal(finalPhysical.inode,physical.inode);assert.deepEqual(finalBytes.subarray(0,originalBytes.length),originalBytes);await fs.writeFile(join(here,'final-native-prefix.jsonl'),finalBytes,{flag:'wx'});await write('final-handoff.json',state.closeHandoff);c.refresh();await write('retained-environment.json',{projection:state.environment,catalog:state.catalog,catalogView:state.catalogView,verified:verification.verifiedArtifact,readerInstalledRoot:identity.installedRoot,closeHandoff:state.closeHandoff});await write('runtime-slots.json',{...slots,closeHandoff:state.closeHandoff,observedC2Run:value.run,observedTask:{ref:task.taskRef,digest:task.taskDigest},observation:{ref:consumed.observation.observationRef,digest:consumed.observation.observationDigest},tenantManifest:null,executionSelectionRef:null,qualificationBasis:null,claim:'Actual observed C2 material only; later qualification owner inputs remain unbound'});await write('native-result.json',{status:'passed',candidate:identity.basis,initialPrefix:initial.prefix,initialPrefixConserved:true,finalPrefix:state.closeHandoff.prefix,finalPhysical,priorSuccessesReexecuted:0,newCalls:3,C2Calls:1,qualificationCalls:0,elapsedMs:performance.now()-startedAt,nativeElapsedMs:performance.now()-nativeStartedAt,driverPid:process.pid,reached,claim:'Observed-root C2 and two fresh reads; not qualification or release'});console.log(JSON.stringify({phase:'CLOSED_native_success',newCalls:3,elapsedMs:performance.now()-startedAt}));
}catch(error){if(preflightTimer)clearTimeout(preflightTimer);let finalPhysical=null;try{if(c)finalPhysical=await c.physical('failure-final');const plan=await read(join(here,'resource-plan.json'));await fs.writeFile(join(here,'failure-native-prefix.jsonl'),await fs.readFile(plan.eventLogPath),{flag:'wx'});if(c?.state.closeHandoff)await write('final-handoff.json',c.state.closeHandoff);}catch(observationError){await write('failure-observation.json',{message:String(observationError)});}await write('failure.json',{phase,message:String(error),stack:error.stack,finalPhysical,closeHandoff:c?.state.closeHandoff??null,calls:c?.state.calls??[],reusedInputs,reached,elapsedMs:performance.now()-startedAt,driverPid:process.pid});console.error(error.stack);process.exitCode=1;}
