from pathlib import Path
import json,hashlib,datetime,subprocess
from urllib.parse import unquote,urlparse
base=Path('/Users/jim/src/apps/abiogenesis/.ai-workspace/work/T287_SANDBOX_UAT_RUN_02');phase=base/'operator/crosscut-installed-graph-law-proof-81/terminal-contract-fixture-successor'
def read(q):return json.loads(Path(q).read_text())
def pin(q):
 q=Path(q);b=q.read_bytes();return {'path':str(q),'sha256':hashlib.sha256(b).hexdigest(),'byteCount':len(b)}
def write(q,v):
 with Path(q).open('x') as f:f.write(json.dumps(v,indent=2)+'\n')
prep=read(phase/'preparation.json');obs=read(phase/'observations.json');outer=read(phase/'commands/actual-positive-composition.result.json');setup=read(phase/'execution/setup.json');correspondence=read(phase/'execution/fixture-four-field-correspondence.json')
assert outer['exitCode']==0 and outer['signal'] is None and not outer['timedOut'] and not outer['truncated'];assert obs['native']['disposition']=='completed';assert all(obs['installationsBefore']) and all(obs['installationsAfter'])
for expected in prep['controlPins']:assert pin(expected['path'])==expected,expected['path']
source=Path(obs['sourceRoot']);artifact=next((source/'artifacts').glob('*.tgz'));artifactpin=pin(artifact);assert 'sha256:'+artifactpin['sha256']==obs['fixtureBasis']['artifactDigest']
fixturepins=[pin(q) for q in sorted(source.rglob('*')) if q.is_file() and not q.is_relative_to(source/'artifacts')]+[artifactpin]
installedsourcepin=pin(Path(obs['fixtureInstalledRoot'])/'build/program.mjs');assert installedsourcepin['sha256']==prep['transformedSourcePin']['sha256']
log=Path(unquote(urlparse(obs['closeHandoff']['prefix']['eventLogRef']).path));logpin=pin(log);assert 'sha256:'+logpin['sha256']==obs['physicalPrefix']['digest']
old=read(phase.parent/'positive-candidate21/conservation.json')['old45Store'];assert pin(old['path'])==old
pid=read(phase/'execution/process-info.json')['driverPid'];ps=subprocess.run(['/bin/ps','-p',str(pid),'-o','pid=,ppid=,command='],capture_output=True,text=True);assert not ps.stdout.strip()
conservation={'controlCount':len(prep['controlPins']),'allControlsUnchanged':True,'controlPins':prep['controlPins'],'oldFailed45Store':old,'oldFailed45StoreConserved':True,'corrected51Store':logpin,'fixturePins':fixturepins,'installedTransformedSource':installedsourcepin,'authorPackInstalledSourceMatches':True,'allOtherPublicationSemanticsEqualAtSameArtifactBasis':True,'graphsProgramsRootMembershipTopologyVectorImplementationsUnchanged':True,'allInstallBarriersTrue':True,'samePrefixBothFreshReads':True,'driverPid':pid,'driverPidAbsent':True,'allRawProcessCommandsClosed':True,'signalsSent':0,'boundedProcessObservationOnly':True,'noFrameworkSourceSupportMethodGitDataMapperOldCutEffects':True};write(phase/'conservation.json',conservation)
ready={'state':'CLOSED actual installed composition/terminal/fresh-read proof PASS; independent review/Root acceptance pending','method':prep['method'],'frame':prep['frame'],'productFrame':'Fixed15 ABI5 GOAL035/T287; original external UAT remains separate; generic fixture owner and ABG admitted runtime truth respected.','frameworkHostSelector':prep['controlPins'][-2],'fixtureOriginalSource':prep['originalFixturePin'],'fixtureTransformedSource':prep['transformedSourcePin'],'fixtureArtifact':artifactpin,'fixtureBasis':obs['fixtureBasis'],'fourChangedClosureFields':[x['path'] for x in obs['canonicalFourFieldsOnly']],'allOtherPublicationSemanticsPreserved':True,'rootOnlyProgramMembershipPreserved':True,'programDigest':obs['programDigest'],'currentRun':obs['currentRun'],'terminalResult':obs['native']['typedTerminalResult'],'prefix':obs['closeHandoff']['prefix'],'physicalPrefix':obs['physicalPrefix'],'nativeEventCount':obs['native']['eventCount'],'kinds':obs['native']['kinds'],'positiveDisposition':obs['positive']['ownerOutput']['value']['disposition'],'readKinds':[{'name':x['name'],'kind':x['kind'],'status':x['status'],'sameTypedTerminal':True} for x in obs['reads']],'conservation':pin(phase/'conservation.json'),'timingsMs':{'outer':outer['wallMs'],'conformance':read(phase/'execution/commands/81-declared-positive.result.json')['wallMs'],'M5':obs['native']['wallMs'],'freshResult':obs['reads'][0]['wallMs'],'freshReplay':obs['reads'][1]['wallMs']},'oldFailureImmutable':True,'old20StaticNegativesReusedNotRerun':True,'noP0RC1UATDataMapperRecoveryOrReleaseCredit':True};write(phase/'readiness.json',ready)
text='''CLOSED81 corrected external fixture successor — actual installed composition/terminal/fresh-read proof PASS; STOPPED for independent review.
Product Frame: fixed fifteen-family ABI5/GOAL035/T287, external original UAT; generic Product/fixture ownership and ABG-exclusive admitted truth preserved. STDO2.5.1RC2/#f-end-to-end-interface-integration.
Same accepted21 factory/94 host; original fixture6591f179666eeec55f14930ebd4b96f7c05d494b2c619be4d790207c691a1218/22919B conserved. Existing sourceTransform before manifest/pack changes only GraphEdge RUN closure evidence/judgment/refusal/rejection to terminal Project refs.
Transformedc34bf7a02cf558b7293c900c8670901fd1ab2cf73ce54f36841c28b49760683e/23856B equals authored, packaged and installed source. Distinct fixture artifactcbe23fdd7d30e080a7d57bcc64f6f770a9084c739493356b6655656aaf06b820; no framework/support Source change.
Whole-publication canonical same-basis comparison finds exactly four fields; all Programs/root-only membership/graphs/topology/vectors/implementations and remaining metadata unchanged. Program0ec7f2810f7ef39dca8b8341ea95bbe047c000e91c4bc3c6b8804abaf6b6541d unchanged.
Actual declared_inventory conformance PASS21,859.285167ms; diagnostics empty. Actual M5 two deterministic C_Call results plus Project judgment, advance→terminal, terminal/frame/graph-call/Run close PASS2,127.990125ms.
Run760e3ebcc06422a4cb54c037d97d823fc7e875c6fd478e6cb58cf978ec5c462e completed; typed Resultac6df998b71f32308994985395f9d601288876acac6b9d769ce40106c9656f13 is data_output/Qualification with exact authentic producer coordinates.
51-event/3,266,889B cut SHAa0afa32cccdf16ade933ef977ed48b5c706a81bbd4f0e959d32bc8db49b36c07; no runtime failure. Fresh Public run_result771.018125ms and run_replay773.699292ms both result/exit0, same typed terminal, replay closed, prefix unchanged.
Outer exit0/76,666.247459ms/no timeout/truncation/stderr; raw process stdout/stderr/results retained before decode. Both installed barriers true before/after; current framework physical input unchanged.
Old failed45 cut and12 selected controls conserved; original20 three static negatives reused, not rerun/imported as new native credit. Driver PID absent/commands closed; bounded process observation, no signals.
No provider/model/DataMapper/P0/RC1 qualification/recovery/release credit; Source63/89 semantics rely on independent acceptance, not this author's review. Readiness records only this genuine compound installed discriminator.
'''
with (phase/'return.md').open('x') as f:f.write(text)
files=[q for q in phase.rglob('*') if q.is_file() and q.name!='freeze.json'];ledger=[pin(q) for q in sorted(files)]+fixturepins+[installedsourcepin,logpin,old]
write(phase/'freeze.json',{'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'state':'CLOSED/STOPPED','returnPin':pin(phase/'return.md'),'readinessPin':pin(phase/'readiness.json'),'observationsPin':pin(phase/'observations.json'),'conservationPin':pin(phase/'conservation.json'),'ledger':ledger,'qualifiedCampaignOrRelease':False,'noMoreEffectsAuthorizedInThisCut':True})
print(json.dumps({'return':pin(phase/'return.md'),'readiness':pin(phase/'readiness.json'),'freeze':pin(phase/'freeze.json'),'observations':pin(phase/'observations.json'),'conservation':pin(phase/'conservation.json'),'ledgerCount':len(ledger),'fixtureArtifact':artifactpin},indent=2))
