import assert from 'node:assert/strict';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const here=dirname(fileURLToPath(import.meta.url)),base=dirname(here),read=async p=>JSON.parse(await readFile(p,'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),hash=b=>createHash('sha256').update(b).digest('hex');
const setup=await read(join(base,'setup.json')),load=p=>import(pathToFileURL(join(setup.installedRoots[0],'build/code/src',p+'.js')).href),[store,{canonicalJson}]=await Promise.all([load('abg/event_store'),load('shared/canonical_json')]);
const handoff=await read(join(here,'handoff.json')),events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),byOrdinal=n=>events.find(e=>e.admissionOrdinal===n),diagnosis=await read(join(here,'retained-diagnosis.json')),attribution=await read(join(here,'retained-attribution.json')),assembly=await read(join(here,'assembly-1.json')),timing=await read(join(here,'timing.json')),effect=await read(join(here,'effects.json')),input=await read(join(base,'input.json'));
const source=byOrdinal(1703).payload.value;
assert.deepEqual(source.commandResults.map(c=>c.exitStatus),[0,1]);assert.equal(byOrdinal(1774).payload.value.terminal,false);assert.deepEqual(byOrdinal(1774).payload.value.unresolvedSupportRefs,input.unresolvedSupportRefs);
for(const s of input.original.sources)assert.equal(effect[s.path].sha256,s.digest);assert.equal(effect['generated/hello-world.mjs'].sha256,'sha256:647697a5fb5d141a2b1163363170a7a845b61a36096ff52f7a369f1736cd4993');
for(const actor of timing.actors){assert.equal(actor.command,'/Users/jim/.local/share/claude/versions/2.1.280');assert.equal(actor.args[actor.args.indexOf('--model')+1],'claude-opus-5-5');assert.equal(actor.args[actor.args.indexOf('--effort')+1],'xhigh');assert.ok(actor.reportedModels.every(m=>m==='claude-opus-5-5'));}
const reads=Object.fromEntries(await Promise.all(['run_result','run_replay'].map(async n=>[n,(await read(join(here,'read-'+n+'.json'))).output.receipt])));
assert.equal(reads.run_result.ownerOutput.value.code,'not_found');assert.equal(reads.run_replay.ownerOutput.value.projection.status,'failed');assert.equal(reads.run_replay.ownerOutput.value.projection.terminalResult,null);assert.deepEqual(reads.run_replay.ownerOutput.value.projection.replay,(await read(join(here,'execution.json'))).output.receipt.resources.replay);
for(const receipt of Object.values(reads))assert.deepEqual(receipt.resources.eventResource.closeHandoff.prefix,handoff.prefix);
await save('first-failure.json',{stage:'second-selector-owned-preparation',runtimeOutcome:'runtime_failed',runClosed:false,providerCalls:timing.actors.length,automaticRetry:false,sourceFreeze:'sha256:3bfda7ac23bd8fd7ad5274d0875c3c13bdbf6033805370665055749e04e2d8e8',firstRejectedRelation:diagnosis.firstOwnedPreparationRefusal,declaredBound:131072,retainedRenderBytes:133945,boundInterpretation:'Retained-byte projection demonstrates overflow. Persisted generic owner exception does not retain its internal assembly refusal cause.',causalEvents:[40,1456,1469,1496,1703,1713,1733,1747,1764,1774,1794,1807,1809,1815].map(n=>{const e=byOrdinal(n);return {ordinal:n,eventId:e.eventId,kind:e.kind,graphFunctionRef:e.graphFunctionRef,resultRef:e.payload.resultRef??null,contractRef:e.payload.contractRef??null};}),baseline:{stdout:Buffer.from(source.commandResults[0].stdout.payload,'base64').toString(),commandExitStatuses:[0,1],testStdout:Buffer.from(source.commandResults[1].stdout.payload,'base64').toString(),worksiteDelta:source.worksiteDelta,productDelta:source.productDelta},initialSectionBytes:Object.fromEntries(Object.entries(assembly.envelope.sections).map(([k,v])=>[k,Buffer.byteLength(canonicalJson(v))])),successorSectionBytes:diagnosis.promptVolume.sectionBytes,attribution:attribution.retainedTaskAttribution,runtimeIntervals:attribution.runtimeGapQualification,reads:{run_result:'not_found; no terminal Result exists',run_replay:'result; status failed, terminalResult null; exact replay identity matches'},preservedOriginal:true,assetsAuthored:0,changedActualChoice:false,coverageQualified:false,reportedProviderCostUsd:timing.actors.reduce((sum,a)=>sum+a.reportedUsage.reduce((n,r)=>n+(r.totalCostUsd??0),0),0)});
// Verify old proof and accepted launcher bytes remain intact; new evidence is
// inventoried separately instead of rewriting either historical manifest.
for(const [path,id]of Object.entries(await read(join(base,'proof-manifest.json'))))assert.equal(hash(await readFile(join(base,path))),id.sha256,path);
for(const [path,id]of Object.entries(await read(join(here,'launcher-manifest.json'))))assert.equal(hash(await readFile(join(here,path))),id.sha256,path);
assert.equal(hash(await readFile(join(here,'return.md'))),'ef4b22d0736d4eb1b39fb1f853b413665699e0b3efca10b4a2b45bc2d3ea5b13');
const inventory={};async function walk(path,prefix=''){for(const name of await readdir(path)){const full=join(path,name),rel=join(prefix,name);try{const b=await readFile(full);inventory[rel]={sha256:hash(b),bytes:b.length};}catch(e){if(e.code==='EISDIR')await walk(full,rel);else throw e;}}}await walk(here);await save('run-proof-manifest.json',inventory);await save('run-freeze.json',{coreSha256:'64712d9e3f480236f3a90f7c3c124eb8140ffee5ba426dafc1c7d02767008d4d',consumerSha256:'f70349590488054f940e818628d0009c950dde6d91e513d27c6b934a54636b98',proofManifestSha256:hash(await readFile(join(here,'run-proof-manifest.json'))),proofMembers:Object.keys(inventory).length,events:inventory['events.jsonl'],firstFailure:inventory['first-failure.json'],execution:inventory['execution.json'],handoff:inventory['handoff.json'],originalProofUnchanged:true,launcherReadinessUnchanged:true,outcome:'runtime_failed',providerCalls:2,runClosed:false});
console.log(JSON.stringify(await read(join(here,'run-freeze.json')),null,2));
