import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {join} from 'node:path';import {createRequire} from 'node:module';
import {here,read,write,caller,verificationRequest,schemaVersion} from './ordinary-caller.mjs';import {loadRuntime} from './public-support.mjs';
const N1=join(here,'../final-native-setup-01'),C=join(here,'../final-candidate-construction-01');
const startedAt=performance.now(),budgets=await read(join(here,'budgets.json')),deadline=startedAt+budgets.driverBudgetMs;
let phase='preflight',c=null;
await write('driver-start.json',{pid:process.pid,startedAt:new Date().toISOString(),budgetMs:budgets.driverBudgetMs,purePreflightAllowanceMs:120000,calls:7});
try{
 const identity=await read(join(here,'selected-core.json')),prospect=await read(join(here,'prospective-cases.json')),r=await loadRuntime(identity.installedRoot),{product,abg,gtl}=r;
 const verification=await product.ProductVerificationPort.verify({kind:'product_verification_packet',schemaVersion,memberKey:'verify',targetKind:'packed_artifact',request:verificationRequest(prospect.core)});await write('bootstrap-core.json',verification);assert.equal(verification.kind,'product_verification_success');assert.strictEqual(product.selectOwnedProductVerification(verificationRequest(prospect.core),verification.verifiedArtifact),verification.verifiedArtifact);
 const verified=verification.verifiedArtifact,prior=await read(join(N1,'last-successful-bind-environment.json')),slots=await read(join(N1,'runtime-slots.json')),initialHandoff=await read(join(N1,'final-handoff.json')),originalBytes=await fs.readFile(join(N1,'failure-native-prefix.jsonl')),publicationInputs=await read(join(N1,'publication-inputs.json'));
 c=await caller('continue',verification,deadline);const {state,hash,authorized,invoke}=c;
 state.closeHandoff=initialHandoff;state.binding=slots.workspaceBinding;state.resolvedLock=prior.projection.resolvedProductLock;c.refresh();
 assert.deepEqual(state.environment,prior.projection);assert.equal(state.environment.workspaceAuthorityBasis.authorizedActorRef,'actor://abiogenesis/t287/final-native-setup-01/operator');assert.deepEqual(state.environment.workspaceAuthorityBasis,slots.workspaceAuthority);
 const initialPhysical=await c.physical('initial');assert.equal(initialPhysical.device,16777230);assert.equal(initialPhysical.inode,463939156);assert.equal(initialPhysical.sha256,'5d915fcc50e8639e7376bd33571404c060d89af798efb9f56cdd3694232d2348');assert.equal(initialPhysical.bytes,2475382);assert.equal(state.closeHandoff.prefix.coordinateDigest,'sha256:8b5e835908d985bd675e8e841b912bce468dc7a5547a5fbf475dbac9857a95fe');
 const publications=publicationInputs.modulePublications;assert.equal(publications.length,11);assert.deepEqual(publications.map(p=>[p.owningProductId,p.moduleRef,product.modulePublicationSemanticDigest(p)].join('\0')).sort(),verified.contributionManifest.publicationBindings.map(p=>[verified.productId,p.moduleRef,p.publicationDigest].join('\0')).sort());
 publicationInputs.verifiedProducts=[verified];assert.deepEqual(publicationInputs.workspaceBinding,state.binding);
 const lock={ref:state.resolvedLock.lockId,digest:state.resolvedLock.lockDigest};assert.deepEqual(lock,slots.resolvedLock);
 const catalogRequest={workspaceBinding:state.binding,descriptors:publicationInputs.descriptors,contributionManifests:[{ref:verified.contributionManifestRef,digest:verified.contributionManifestDigest}],resolvedLock:lock};
 const catalogResources={kind:'catalog_admission_resource_assertion',schemaVersion,eventResource:c.reopen(),workspaceBinding:state.environment.workspaceBinding,resolvedLock:state.resolvedLock,verifiedProducts:[verified],admittedInstalls:state.environment.productInstalls,publications};
 const catalogCall=await authorized(product.CATALOG_OPERATION_SOURCE_DECLARATIONS.admit,catalogRequest,catalogResources,c.boundSlots());
 const auth=await read(join(here,'continue-authorization-0.json'));const v=createRequire(join(identity.installedRoot,'package.json'))('valibot');v.parse(product.ADMISSION_CAPABILITY_DATA_SCHEMA,auth.basis);v.parse(product.RESOLVED_ADMISSION_AUTHORITY_SCHEMA,auth.authority);assert.equal(auth.basis.boundEnvironment.kind,'admission_environment_selection');assert.deepEqual(auth.basis.boundEnvironment.prefix,initialHandoff.prefix);assert.deepEqual(auth.basis.boundEnvironment.workspaceBinding,state.binding);assert.equal(auth.authority.approval.value.scopeDigest,product.admissionAuthorityScope(auth.basis).digest);assert.ok(auth.grants.length>0);assert.deepEqual(catalogCall.invocation.invocationAuthority.slots.capability_grants.grants,auth.grants.map(g=>({ref:g.grantRef,digest:g.grantDigest})));
 // Source-bound start/read carrier paths wait for their real catalog and Run producers; no fake future values.
 const definitions=r.public.PUBLIC_FUNCTION_DEFINITION_FAMILY.definitions;const paths=[];for(const [op,key] of [['abg.operation.run.invoke','start'],['abg.operation.project.read','run_result'],['abg.operation.project.read','run_replay']]){const d=definitions.find(x=>x.definitionKey.operationId===op&&x.definitionKey.memberKey===key);assert.ok(d);const coordinate=verified.definitionContractCoordinates.operations.find(x=>x.operationId===op).members.find(x=>x.memberKey===key);assert.ok(coordinate.slots.request);assert.ok(coordinate.slots.result);paths.push({definitionKey:d.definitionKey,definitionRef:d.definitionRef,definitionDigest:d.definitionDigest,slots:coordinate.slots});}
 assert.ok(performance.now()-startedAt<120000,'preflight120000ms');await write('pure-preflight.json',{status:'passed',fullPublicationCount:11,initialPhysical,initialHandoff,selection:auth.basis.boundEnvironment,scope:auth.scope,authority:auth.authority,grants:auth.grants,actualCatalogCall:'pre-effect-catalog-call.json',remainingCarrierDefinitions:paths,startPath:'same declared ProductExecutionResolution/RootInvocationPolicy/InvocationAuthority/installed DefinitionCall constructors; actual catalog/view required before construction',readPath:'current ABG_PROJECT_READ_CONTRACTS, actual Run source and original start slots; each actual owner handoff feeds next read; no fake Run/source slot',elapsedMs:performance.now()-startedAt,nativeCalls:0});await write('pre-effect-catalog-call.json',catalogCall);console.log(JSON.stringify({phase:'current_selection_scope_approval_grants_preflight_passed',publications:11,nativeCalls:0}));
 phase='catalog';const catalogResult=await invoke('catalog',catalogCall);
 const installed=state.environment.productInstalls.map(i=>abg.projectAdmittedProductInstallByAdmissionEventRef(state.environment.artifactTruth,i.admissionEventRef));assert.ok(installed.every(Boolean));
 state.catalog=product.CatalogOperationPort.admit({kind:'catalog_admit_packet',schemaVersion,memberKey:'admit',readinessBasis:{workspaceBinding:state.environment.workspaceBindingCandidate,resolvedLock:state.resolvedLock,verifiedProducts:[verified],installedProducts:installed.map(i=>i.candidate),publications}});assert.equal(state.catalog.kind,'graph_function_catalog');assert.equal(catalogResult.receipt.ownerOutput.value.catalog.digest,state.catalog.basisDigest);
 const programs=publications.flatMap(p=>p.programs).filter(p=>[gtl.HELLO_WORLD_IDS.programRef,'program://abiogenesis/worksite/command-execution@5'].includes(p.programRef));assert.equal(programs.length,2);const allowlist=[...new Set(programs.flatMap(p=>p.callableMembership))].sort();
 phase='catalog-view';await invoke('catalog-view',await authorized(product.CATALOG_OPERATION_SOURCE_DECLARATIONS.view.allowlist,{catalog:catalogResult.receipt.ownerOutput.value.catalog,allowlist},{kind:'catalog_view_resource_assertion',schemaVersion,catalog:state.catalog},c.boundSlots()));state.catalogView=product.narrowGraphFunctionCatalog(state.catalog,allowlist);
 for(const p of programs){phase='conformance-'+p.programRef;await c.conformance(p.programRef,'conformance-'+p.programRef.split('/').at(-1).split('@')[0],publicationInputs);}
 c.refresh();await write('setup-state.json',{...state,workspaceAuthority:slots.workspaceAuthority,workspaceManifestResource:(await read(join(N1,'setup-workspace-stdout.json'))).receipt.resources.manifest,verified,publicationInputs,contractCatalog:c.contractCatalog});console.log(JSON.stringify({phase:'ordinary_setup_complete',newCalls:state.calls.length,workspaceBinding:state.binding}));
 phase='hello';const input=gtl.constructHelloWorldInput('prospective 5.0.0-rc.1 qualification');const started=await c.start(gtl.HELLO_WORLD_IDS.programRef,gtl.HELLO_WORLD_IDS.graphFunctionRef,input,'hello-root','hello');console.log(JSON.stringify({phase:'hello_completed',run:started.receipt.ownerOutput.value.run}));
 phase='cold-reads';const reads=await c.freshReads('hello-root',started),value=started.receipt.ownerOutput.value,resultProjection=reads.run_result.ownerOutput.value.projection,replayProjection=reads.run_replay.ownerOutput.value.projection;
 assert.equal(value.disposition,'completed');assert.equal(value.stop,null);assert.equal(value.terminalResult.kind,'abg_typed_terminal_result');assert.deepEqual(value.terminalResult.value,{kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello prospective 5.0.0-rc.1 qualification'});assert.deepEqual(value.terminalResult,resultProjection.terminalResult);assert.deepEqual(resultProjection.terminalResult,replayProjection.terminalResult);assert.deepEqual(value.result,resultProjection.result);assert.deepEqual(value.replay,resultProjection.replay);assert.deepEqual(value.replay,replayProjection.replay);assert.equal(replayProjection.status,'closed');assert.deepEqual(reads.run_result.ownerOutput.value.source,value.run);assert.deepEqual(reads.run_replay.ownerOutput.value.source,value.run);assert.equal(value.terminalResult.provenance.runRef,value.run.ref);
 await write('hello-result.json',{status:'passed',input,startCall:started.call,rootReceipt:started.receipt,reads,comparison:{typedTerminalEqual:true,resultEqual:true,replayEqual:true,replayClosed:true,run:value.run},closeHandoff:state.closeHandoff,calls:state.calls});
 phase='final-conservation';const finalPhysical=await c.physical('final'),finalBytes=await fs.readFile(initialHandoff.reopenAuthority.eventLogPath);assert.equal(finalPhysical.device,16777230);assert.equal(finalPhysical.inode,463939156);assert.deepEqual(finalBytes.subarray(0,originalBytes.length),originalBytes);assert.equal(state.calls.length,7);assert.ok(performance.now()<deadline);
 await fs.writeFile(join(here,'final-native-prefix.jsonl'),finalBytes,{flag:'wx'});await write('final-handoff.json',state.closeHandoff);c.refresh();await write('environment.json',{...state.environment,verified,admittedInstalls:state.environment.productInstalls,workspaceAuthority:slots.workspaceAuthority,catalog:state.catalog,catalogView:state.catalogView,installedRoot:identity.installedRoot,contractCatalog:c.contractCatalog,definitionContractCoordinates:verified.definitionContractCoordinates,closeHandoff:state.closeHandoff});
 await write('runtime-slots.json',{installedProduct:slots.installedProduct,workspaceBinding:state.binding,workspaceAuthority:slots.workspaceAuthority,canonicalRoot:slots.canonicalRoot,installedRoots:slots.installedRoots,resolvedLock:slots.resolvedLock,catalog:{ref:'graph-function-catalog://abiogenesis/'+state.catalog.basisDigest.slice(7),digest:state.catalog.basisDigest},catalogView:{ref:'graph-function-catalog-view://abiogenesis/'+state.catalogView.viewDigest.slice(7),digest:state.catalogView.viewDigest},tenantManifest:null,executionSelectionRef:'absent; no C2 executed',laterC2Join:'Root selected Q.selectedFiles: verify all bytes and absent target paths before exclusive writes under same existing A/W canonicalRoot; preserve .abiogenesis metadata; then constructObservedProducerTask. No staging performed.',closeHandoff:state.closeHandoff});
 await write('native-result.json',{status:'passed',candidate:identity.basis,initialPrefix:initialHandoff.prefix,initialPrefixConserved:true,finalPrefix:state.closeHandoff.prefix,finalPhysical,newCalls:7,priorCallsReexecuted:0,HelloRuns:1,C2Calls:0,providerCalls:0,elapsedMs:performance.now()-startedAt,budgetMs:4027000,driverPid:process.pid,claim:'Exact final candidate ordinary setup completed and one supported Hello/cold proof; not qualification'});console.log(JSON.stringify({phase:'CLOSED_native_success',newCalls:7,elapsedMs:performance.now()-startedAt}));
}catch(error){let finalPhysical=null;try{if(c)finalPhysical=await c.physical('failure-final');const plan=await read(join(here,'resource-plan.json'));await fs.writeFile(join(here,'failure-native-prefix.jsonl'),await fs.readFile(plan.eventLogPath),{flag:'wx'});}catch(observationError){await write('failure-observation.json',{message:String(observationError)});}await write('failure.json',{phase,message:String(error),stack:error.stack,finalPhysical,closeHandoff:c?.state.closeHandoff??null,calls:c?.state.calls??[],elapsedMs:performance.now()-startedAt,driverPid:process.pid});console.error(error.stack);process.exitCode=1;}
