from pathlib import Path
import json,hashlib,shutil,difflib
R=Path('/Users/jim/src/apps/abiogenesis');G=R/'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE';N=G/'final-native-setup-02';P=G/'final-native-setup-01';C=G/'final-candidate-construction-01';Q=G/'final-qualification-inputs-01'
def rd(p):return json.loads(p.read_text())
def wr(n,x):(N/n).write_text(json.dumps(x,indent=2)+'\n')
def ref(p):return {'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
assert ref(P/'freeze.json')['sha256']=='2696a00bda621be6aedca8fd32483e810d6e48d90f546ea75c66f082af4690bb';assert ref(P/'final-handoff.json')['sha256']=='f5f94c87a2d7cb174f8423c63ca370317966fabd9fafc4af25b1dc3bdf104fbf';assert ref(P/'failure-native-prefix.jsonl')['sha256']=='5d915fcc50e8639e7376bd33571404c060d89af798efb9f56cdd3694232d2348'
for d in ['preimages','config','cache','scratch']: (N/d).mkdir()
for f in ['user.npmrc','global.npmrc','global.gitconfig','system.gitconfig']:(N/'config'/f).write_text('')
wr('worker-activation.json',{'role':'Worker','worker':'T287_FINAL_NATIVE_SETUP_02','author':'/root/s03_phase_b','request':ref(G/'final-native-setup-controls-02/request.txt'),'territory':str(N),'additionalRuntimeGrant':{'eventLog':rd(P/'resource-plan.json')['eventLogPath'],'TMPDIR':str(P/'tmp'),'lockNamespace':str(P/'tmp/abiogenesis-event-store-locks-v5'),'effect':'ordinary owner append/reopen/close and owned transient verification only'},'changeClass':'realization_refactor of shared external caller','selected':'seven remaining ordinary calls on same environment; no repeat of5 successes','prohibited':'source/package/install/recipe/test/C2/staging/provider/Git/F11/AF22; no retry'})
wr('input-joins.json',[ref(p) for p in [G/'final-native-setup-controls-02/request.txt',G/'final-native-setup-controls-02/request-sections.json',P/'freeze.json',P/'return.md',P/'causal-triage.json',P/'runtime-slots.json',P/'last-successful-bind-environment.json',P/'final-handoff.json',P/'failure-native-prefix.jsonl',P/'publication-inputs.json',P/'prepared-publications.json',C/'freeze.json',Q/'freeze.json']])
for name in ['ordinary-caller.mjs','public-support.mjs','observe-process.py','driver.mjs']:
 shutil.copyfile(P/name,N/'preimages'/name)
for name in ['public-support.mjs','observe-process.py','selected-core.json','prospective-cases.json']:shutil.copyfile(P/name,N/name)
wr('budgets.json',{'stages':{'setup':600000,'conformance':600000,'hello':300000,'read':600000},'operationPlan':['catalog','catalog-view','conformance-hello-world','conformance-command-execution','hello-root','hello-root-run_result','hello-root-run_replay'],'calls':7,'nativeCapSumMs':3900000,'allCommandGraceMs':7000,'terminationGraceMs':1000,'purePreflightAllowanceMs':120000,'driverBudgetMs':4027000,'retry':'none','source':ref(P/'budgets.json')})
wr('runtime-environment.json',{'TMPDIR':str(P/'tmp'),'npm_config_cache':str(N/'cache/npm'),'npm_config_prefix':str(N/'cache/npm-prefix'),'npm_config_userconfig':str(N/'config/user.npmrc'),'npm_config_globalconfig':str(N/'config/global.npmrc'),'GIT_CONFIG_GLOBAL':str(N/'config/global.gitconfig'),'GIT_CONFIG_SYSTEM':str(N/'config/system.gitconfig'),'GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','NODE_OPTIONS':''})
wr('resource-plan.json',{**rd(P/'resource-plan.json'),'newProofRoot':str(N),'nativeCalls':7,'history':'Continue exact original2-event prefix; preserve N1 immutable snapshot/receipts and same dev/inode/lock','initialHandoff':ref(P/'final-handoff.json'),'initialSnapshot':ref(P/'failure-native-prefix.jsonl'),'canonicalRoot':rd(P/'runtime-slots.json')['canonicalRoot']})
s=(P/'ordinary-caller.mjs').read_text();s=s.replace("base='abiogenesis/t287/final-native-setup-01',actorRef='actor://'+base+'/operator'","base='abiogenesis/t287/final-native-setup-02',actorRef='actor://abiogenesis/t287/final-native-setup-01/operator'")
s=s.replace("const f=join(here,'resources/events/runtime.events.jsonl');","const f=(await read(join(here,'resource-plan.json'))).eventLogPath;")
s=s.replace("boundEnvironment:packet.metadata.workspaceBindingRequirement==='forbidden'?null:state.environment","boundEnvironment:packet.metadata.workspaceBindingRequirement==='forbidden'?null:product.admissionEnvironmentSelection(state.closeHandoff.prefix,slots.workspace_binding)")
s=s.replace("const capMs=Math.min(budgets.stages[stage],remaining);","const capMs=Math.min(budgets.stages[stage],remaining-1000);assert.ok(capMs>0,'termination grace preserved');")
# Save exact current granted data before a native call; shared branch covers catalog/view/conformance.
s=s.replace("return installedPublic.constructInstalledPublicDefinitionCall({product,installedPublic,definitionContractCoordinates:verified.definitionContractCoordinates,contractCatalog,...packet.definitionKey,request,slots:{...slots,capability_grants:{requiredCapabilityRefs:[...definition.capabilityRefs],grants:grants.map(g=>({ref:g.grantRef,digest:g.grantDigest}))}},resources:{...resources,admissionAuthority:{basis,authority,grants}},requestRef:op.requestBaseRef+'/'+mode+'/'+state.calls.length,correlationRef:op.correlationRef,eventTime:new Date().toISOString(),provenanceRefs:op.provenanceRefs});","await write(mode+'-authorization-'+state.calls.length+'.json',{basis,authority,grants,scope:product.admissionAuthorityScope(basis),claim:'Actual current selection/scope/approval/grants before native invocation; selection is not an admitted environment'});\n  return installedPublic.constructInstalledPublicDefinitionCall({product,installedPublic,definitionContractCoordinates:verified.definitionContractCoordinates,contractCatalog,...packet.definitionKey,request,slots:{...slots,capability_grants:{requiredCapabilityRefs:[...definition.capabilityRefs],grants:grants.map(g=>({ref:g.grantRef,digest:g.grantDigest}))}},resources:{...resources,admissionAuthority:{basis,authority,grants}},requestRef:op.requestBaseRef+'/'+mode+'/'+state.calls.length,correlationRef:op.correlationRef,eventTime:new Date().toISOString(),provenanceRefs:op.provenanceRefs});")
assert "?null:state.environment" not in s
(N/'ordinary-caller.mjs').write_text(s)
changes=[]
for name in ['ordinary-caller.mjs','public-support.mjs','observe-process.py']:
 old=(P/name).read_text();new=(N/name).read_text();patch=''.join(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='N1/'+name,tofile='N2/'+name));(N/(name+'.patch')).write_text(patch);changes.append({'file':name,'donor':ref(P/name),'preimage':ref(N/'preimages'/name),'postimage':ref(N/name),'patch':name+'.patch','changed':old!=new})
wr('authored-input-chain.json',{'activation':'worker-activation.json','changes':changes,'newAuthored':['prepare.py','driver.mjs','budgets.json','resource-plan.json','runtime-environment.json','launch-once.py'],'attribution':'N2 external caller/control construction only; original actor/workspace authority is conserved, inherited Product/source authors unchanged'})
print('N2 activation and shared caller branch prepared; no native effect.')
