/** Independent pure owner checks. Never calls staging, task or native owners. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const O=path.dirname(fileURLToPath(import.meta.url)),G=path.dirname(O),Q=path.join(G,'final-qualification-inputs-02');
const C=path.join(G,'final-candidate-construction-02'),I=path.join(C,'install/node_modules/@abiogenesis/typescript-tenant');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const {sha256Bytes:sha,sha256Canonical:hash}=await import(pathToFileURL(path.join(I,'build/code/src/shared/digests.js')));
const qual=await import(pathToFileURL(path.join(I,'build/code/src/validator/qualification.js')));
const sc=await import(pathToFileURL(path.join(I,'build/code/src/validator/self_conformance.js')));
const inventory=read(path.join(Q,'qualification-inventory.json')),template=read(path.join(Q,'basis-template.json'));
const recipe=read(path.join(Q,'verification-recipe.json')),manifest=read(path.join(I,'product-toolchain-manifest.json'));
const next=read(path.join(Q,'next-setup-c2-inputs.json')),current=read(path.join(Q,'current-publication-closure.json'));
const checks=[],unknowns=[];
async function check(name,fn){try{const detail=await fn();checks.push({name,status:'pass',detail});}catch(e){checks.push({name,status:'not_established',error:String(e)});}}
await check('installed_inventory_identity',()=>{assert.equal(qual.isQualificationInventory(inventory),true);assert.equal(inventory.inventoryDigest,'sha256:107360f76fdbdfa7920d912aac2edc10ecaf80ca88406190748f28d834c40101');return {ref:inventory.inventoryRef,digest:inventory.inventoryDigest,members:inventory.members.length};});
await check('canonical_manifest_and_native_preview',()=>{const canonical=hash(manifest),file=sha(fs.readFileSync(path.join(I,'product-toolchain-manifest.json'))),aux=sha(fs.readFileSync(path.join(Q,'toolchain.json')));assert.equal(canonical,'sha256:d93ec21cf34a043822a211ba8bea46fdc1050311925d38030b430172f5464ee4');assert.equal(file,'sha256:ccae3c530199a813bc943f8d07a0cf90ee89e3201839082c2df6744ae57e9518');assert.equal(aux,'sha256:c8a694ddb749b3f8e2aa7c76afacf2e074b9b15ab12411b0dca8eb877037f8b1');assert.equal(template.body.productManifest.digest,canonical);assert.deepEqual(template.body.toolchain,template.body.productManifest);assert.notEqual(canonical,file);assert.notEqual(canonical,aux);return {canonical,file,auxiliaryConfiguration:aux};});
await check('unknown_native_slots_remain_unready',()=>{for(const k of ['installedProduct','workspaceBinding','tenantManifest'])assert.equal(template.body[k],null);assert.equal(qual.isQualificationBasisReady(template.body),false);const selection=read(path.join(Q,'verification-selection-binding.json'));assert(!('executionSelectionRef' in selection));return {nativeSlots:null,executionSelectionRefPresent:false,isQualificationBasisReady:false,limit:'Template has no ready basis identity; null-native guard is also visible directly in owner source. No future task or fabricated native tuple constructed.'};});
await check('recipe_shape_and_identity',()=>{const v=createRequire(path.join(I,'package.json'))('valibot');const possible=[['build/code/src/validator/self_conformance_contracts.js','VERIFICATION_RECIPE_SCHEMA'],['build/code/src/product/self_conformance_contracts.js','VERIFICATION_RECIPE_SCHEMA']];return (async()=>{let schema;let route;for(const [p,n]of possible){if(!fs.existsSync(path.join(I,p)))continue;const m=await import(pathToFileURL(path.join(I,p)));if(m[n]){schema=m[n];route=p+'#'+n;break;}}if(schema){assert(v.is(schema,recipe));return {schemaRoute:route,recipeByteDigest:sha(fs.readFileSync(path.join(Q,'verification-recipe.json')))};}const names=Object.keys(sc).filter(n=>/recipe/i.test(n));throw Error('Recipe schema export not selected automatically; owner exports: '+names.join(','));})();});
await check('selectedFiles_pure_input_population',async()=>{const api=await import(pathToFileURL(path.join(Q,'recipe.mjs')));const files=await api.selectedFiles();assert(Array.isArray(files));assert.equal(files.length,716);const targets=files.map(r=>r.target);assert.equal(new Set(targets).size,716);assert(targets.every(t=>typeof t==='string'&&!path.isAbsolute(t)&&!t.split('/').includes('..')&&!t.startsWith('.abiogenesis/')&&t!=='.abiogenesis'&&!t.startsWith('verification/')));const guards=[];for(const f of files){const origin=f.source??f.origin;assert.equal(typeof origin,'string','selectedFiles source field keys '+Object.keys(f));assert(origin.startsWith(C+path.sep)||origin.startsWith(Q+path.sep),origin);const bytes=fs.readFileSync(origin);const expected=f.digest??(f.sha256?'sha256:'+f.sha256:null);assert(expected,'expected digest field keys '+Object.keys(f));assert.equal(sha(bytes),expected);const length=f.byteCount??f.bytes;if(length!==undefined)assert.equal(bytes.length,length);guards.push({source:origin,target:f.target,bytes:bytes.length,digest:sha(bytes)});}const contract=read(path.join(Q,'staging-contract.json'));const declared=contract.targets.map(r=>typeof r==='string'?r:r.target);assert.deepEqual([...targets].sort(),[...declared].sort());return {files:716,uniqueTargets:true,allBodiesVerified:true,protectedOwnerMetadata:true,physicalStagingPerformed:false,sample:guards[0],sourceTargetGuards:guards};});
await check('current_publication_constructors',async()=>{const gtl=await import(pathToFileURL(path.join(I,'build/code/src/gtl/index.js')));const validator=await import(pathToFileURL(path.join(I,'build/code/src/validator/index.js')));const names=current.publicationBindings.map(x=>x.constructor);assert.equal(names.length,11);const basis=next.selectedCore.basis;const outputs=[];for(const n of names){assert.equal(typeof gtl[n],'function');const pub=gtl[n](basis);const a=validator.rawAdmitValue(pub,{subjectKind:'module_publication',contractRef:'contract://abiogenesis/gtl/module-publication@5'});assert.equal(a.kind,'raw_admission');const contributions=pub.contributions.map(c=>validator.rawAdmitValue(c,{subjectKind:'catalog_contribution',contractRef:'contract://abiogenesis/gtl/catalog-contribution@5'}));const valid=validator.validatePublication(a,contributions);assert.equal(valid.kind,'publication_validation');outputs.push({constructor:n,moduleRef:pub.moduleRef,validationKind:valid.kind});}assert.deepEqual(outputs.map(x=>x.moduleRef).sort(),current.publicationBindings.map(x=>x.moduleRef).sort());return {count:outputs.length,outputs,semanticDigestScope:'Constructor/static validity checked. Exact digest comparison follows only if the imported digest owner is selected.'};});
const result={status:'independent_pure_checks_complete',checks,qualificationExports:Object.keys(qual).filter(n=>/Inventory|Identity|BasisReady/.test(n)),selfConformanceRecipeExports:Object.keys(sc).filter(n=>/recipe/i.test(n)),nativeEffects:0,physicalStaging:0,testsBuildsRecipesExecuted:0,actualQualificationTasksConstructed:0};
fs.writeFileSync(path.join(O,'owner-checks.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({checks:checks.map(x=>({name:x.name,status:x.status,error:x.error,detail:x.detail?Object.fromEntries(Object.entries(x.detail).filter(([k])=>!['sourceTargetGuards','outputs'].includes(k))):undefined}))},null,2));
