import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {SourceTextModule,SyntheticModule} from 'node:vm';
const here=dirname(fileURLToPath(import.meta.url)),records=dirname(here),old=join(records,'s6-fulfillment-implementation'),repo=resolve(records,'../../../..'),tenant=join(repo,'build_tenants/abiogenesis/typescript'),read=async p=>JSON.parse(await readFile(p,'utf8'));
const load=p=>import(pathToFileURL(join(tenant,'build/code/src',p+'.js')).href),[product,gtl,{canonicalJson}]=await Promise.all([load('product/index'),load('gtl/index'),load('shared/canonical_json')]);
const setup=await read(join(old,'setup.json')),handoff=await read(join(old,'live-01/handoff.json')),prior=await read(join(old,'live-01/assembly-1.json')),start=await read(join(old,'start-prepared.json')),publication=await read(join(old,'publication.json')),original=await read(join(old,'input.json'));
const oldStore=await import(pathToFileURL(join(setup.installedRoots[0],'build/code/src/abg/event_store.js')).href),events=oldStore.readRuntimeEventsAtDurablePrefix(handoff.prefix),at=n=>events.find(e=>e.admissionOrdinal===n),initial=at(40).payload.value,successor=at(1794).payload.value;
const publications=start.call.resources.catalog.readinessBasis.publications,definitions=publications.flatMap(p=>p.graphFunctions),graph=publication.graphFunctions.find(g=>g.name.endsWith('/executive-step@5')),program=publication.programs[0],node=graph.template.nodes.find(n=>n.nodeRef===graph.declarations['abg.framed_synthesis_locus']);
const role=publication.runEnvironments[0].roles.find(r=>r.role==='selector'),roleEvidence={...role,...prior.manifest.runEnvironment,evidenceDigest:prior.envelope.boundBasis.frameEvidenceDigest,contextPolicyDigest:product.sha256Canonical(role.contextPolicy),sourceContent:prior.envelope.sections.role.sourceContent,accessContent:prior.envelope.sections.evidence.declaredAccess};
const invocation=events.find(e=>e.kind==='invocation_admitted').payload,root=events.find(e=>e.kind==='basis_admitted'&&e.payload.basisClass==='root'),source=at(1703),nativeTask=source.payload.value.task;
const execution=ref=>events.find(e=>e.kind==='basis_admitted'&&e.payload.basisRef===ref).payload;
let owned={program,events,prefix:{},execution:execution(at(1804).basisId),graph:{template:graph.template},environment:{kind:'exact_prefix_workspace_environment',workspaceAuthorityBasis:nativeTask.workspaceAuthorityBasis,workspaceBinding:nativeTask.workspaceBinding,productInstalls:setup.installedRoots.map(installedRoot=>({installedRoot}))},call:{},inputValue:null,inputRef:'',inputDigest:'',inputOrigin:{}};
const lookup=ref=>{const rows=publications.flatMap(p=>p.contracts).filter(c=>c.contractRef===ref);return rows.length===1?rows[0]:null;};
async function module(path,extra={}){const file=join(tenant,'build/code/src',path+'.js'),m=new SourceTextModule(await readFile(file,'utf8'),{identifier:file});await m.link(async specifier=>{const actual=await import(specifier.startsWith('node:')?specifier:pathToFileURL(resolve(dirname(file),specifier)).href),replacements=specifier==='./execution_basis.js'?{authenticateNativeInstructionAssemblyBasis:()=>owned}:specifier==='./stdo_environment.js'?{projectRunEnvironmentRoleEvidence:()=>roleEvidence}:specifier==='./invocation_execution_truth.js'?{projectExactInvocationAdmissionAtPrefix:()=>invocation}:specifier==='./event_prefix.js'?{indexedRuntimeEvents:(_p,key)=>key==='invocation:'+invocation.invocationRef?[root]:events.filter(e=>key==='payload:resultRef:'+e.payload.resultRef||key==='related:'+e.aggregateId)}:{};const values={...actual,...replacements,...extra[specifier]};return new SyntheticModule(Object.keys(values),function(){for(const[k,v]of Object.entries(values))this.setExport(k,v);});});await m.evaluate();return m.namespace;}
// Controlled authenticated occurrence/index premise, populated from actual
// admitted live-01 facts. No new runtime admission or provider is performed.
const assemblyOwner=await module('abg/instruction_assembly'),libraryOwner=await module('abg/default_library');
const candidate=taskEvent=>{const task=taskEvent.payload.value,call=events.find(e=>e.kind==='c_call_opened'&&e.basisId===taskEvent.basisId&&e.payload.programLocusRef===node.nodeRef),basis=execution(taskEvent.basisId);
 owned={...owned,execution:basis,graph:{template:graph.template},call:{...call.payload,runId:call.runId,regime:'F_P',inputContractRef:node.term.inputCarrierRef,outputContractRef:node.term.outputCarrierRef,implementationRef:product.governanceRef('implementation','select')},inputValue:task,inputRef:taskEvent.payload.resultRef,inputDigest:taskEvent.payload.valueDigest,inputOrigin:{event:taskEvent}};
 return {publication,graphFunction:graph,declarationGraphFunctions:definitions,executionBasis:basis,cCall:owned.call,cursor:{currentNodeRef:node.nodeRef,termPath:gtl.rootCSourcePath(node.nodeRef)},predecessorPrefix:prior.envelope.predecessorPrefix};};
const sectionsBytes=sections=>Object.fromEntries(Object.entries(sections).map(([k,v])=>[k,Buffer.byteLength(canonicalJson(v))]));
const measurements=[];
for(const event of [at(40),at(1794)]){
 const task=event.payload.value,before=canonicalJson(task),b=candidate(event),assembly=assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,task,lookup);assert.equal(assembly.kind,'native_instruction_assembly',JSON.stringify(assembly));assert.ok(Buffer.byteLength(assembly.request.prompt)<131072);
 const oldSections={...prior.envelope.sections,task,response:product.framedSynthesisResponseSchema(task,prior.envelope.targetBindings)},oldPrompt=prior.plan.sectionOrder.map(k=>`## ${k}\n${canonicalJson(oldSections[k])}`).join('\n\n');
 assert.deepEqual(assembly.request.responseJsonSchema,oldSections.response);assert.deepEqual(assembly.envelope.targetBindings,prior.envelope.targetBindings);assert.equal(assembly.envelope.inputRef,event.payload.resultRef);assert.equal(assembly.envelope.inputDigest,event.payload.valueDigest);assert.equal(canonicalJson(task),before);
 const projected=assembly.envelope.sections.task;assert.equal(projected.originalTask,original.original.task);assert.deepEqual(projected.authorityRefs,original.original.authorityRefs);assert.deepEqual(projected.unresolvedSupportRefs,task.state.unresolvedSupportRefs);assert.deepEqual(projected.testing,task.state.original.testing);assert.deepEqual(projected.priorJudgment,task.state.synthesis===null?null:{resultRef:task.state.synthesis.resultRef,judgment:task.state.synthesis.judgment});
 for(const file of projected.worksite.files){const entry=task.context.entries.find(e=>e.relativePath===file.path);assert.equal(file.state,entry.state);if(entry.state==='file'){const bytes=Buffer.from(entry.bytes,'base64'),text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);assert.equal(file.contentIn==='originalTask'?projected.originalTask.slice(file.startCharacter,file.endCharacter):file.content,text);}}
 for(const [purpose,order]of Object.entries(original.original.workOrders)){const row=projected.workOrders[purpose];for(const key of ['outcome','readFirst','writeRoots','checks'])assert.deepEqual(row[key],order[key]);for(const instruction of order.instructions)assert.ok(row.instructions.includes(instruction)||task.context.entries.some(e=>e.state==='file'&&Buffer.from(e.bytes,'base64').toString()===instruction&&projected.originalTask.includes(instruction)));}
 for(const active of product.governanceFulfillmentActive(original.original.fulfillment,task.state.fulfillment)){const row=projected.fulfillment.obligations.find(o=>o.obligationRef===active.binding.obligationRef);for(const key of ['scope','realizationMeaning','proofMeaning','unprovedScope','closureRule'])assert.deepEqual(row.policy[key],active.policy[key]);assert.deepEqual(row.completeness,active.completeness);assert.deepEqual(row.shape.requiredContent,active.shape.requiredContent);assert.deepEqual(row.shape.requiredEvidenceRoles,active.shape.requiredEvidenceRoles);}
 assert.equal(projected.assessment.schemaAsset,undefined);assert.equal(projected.fulfillment.bindings,undefined);assert.equal(projected.fulfillment.terms,undefined);assert.equal(projected.original,undefined);assert.equal(projected.state,undefined);assert.ok(projected.worksite.files.every(f=>!Object.hasOwn(f,'bytes')));
 for(const [i,observation]of task.state.observations.entries()){const row=projected.observations[i];assert.equal(row.resultRef,observation.resultRef);assert.equal(row.synthesisResultRef,observation.synthesisResultRef);assert.equal(row.fulfillmentEvidence,undefined);for(const [j,c]of observation.value.commandResults.entries()){assert.deepEqual(row.observed.commandResults[j].stdout,c.stdout);assert.deepEqual(row.observed.commandResults[j].stderr,c.stderr);assert.equal(row.observed.commandResults[j].exitStatus,c.exitStatus);assert.equal(row.observed.commandResults[j].environment,undefined);}}
 const other=structuredClone(task);other.state.original.task+=' altered';assert.equal(assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,other,lookup).kind,'native_instruction_assembly_refusal');assert.equal(assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,task,()=>null).kind,'native_instruction_assembly_refusal');
 const raw=at(1456).payload.value.judgment,bound=product.bindFramedSynthesisResult(task,assembly.envelope.targetBindings,assembly.envelope.boundBasis,raw);assert.ok(bound);assert.deepEqual(bound.judgment,raw);assert.equal(bound.state,task.state);
 const observation={disposition:'success',toolCallCount:0,finalOutput:JSON.stringify(raw),inputDigest:owned.inputDigest,implementationRef:owned.call.implementationRef};assert.ok(assemblyOwner.framedSynthesisInstructionResultMatches(b,task,bound,observation,lookup));assert.equal(assemblyOwner.framedSynthesisInstructionResultMatches(b,task,{...bound,basis:{...bound.basis,inputRef:'result:foreign'}},observation,lookup),false);
 measurements.push({taskOrdinal:event.admissionOrdinal,taskRef:event.payload.resultRef,inputDigest:event.payload.valueDigest,beforeBytes:Buffer.byteLength(oldPrompt),afterBytes:Buffer.byteLength(assembly.request.prompt),beforeSections:sectionsBytes(oldSections),afterSections:sectionsBytes(assembly.envelope.sections),responseSchemaDigest:product.sha256Canonical(assembly.request.responseJsonSchema)});
}
// The omitted ordinary execution join: replay the actual typed baseline fold,
// parent projection and physical next-context acquisition through their owners.
const choice=at(1469).payload.value,retained=product.constructRetainedGraphInput(choice.input.value,source.payload.value),foldBasis=execution(at(1733).basisId),wrapper=definitions.find(g=>g.name===at(1733).graphFunctionRef);
owned={...owned,execution:foldBasis,inputValue:retained,inputRef:'controlled:actual-retained-input',inputDigest:product.sha256Canonical(retained),call:{runId:source.runId,implementationRef:product.governanceRef('implementation','fold')},inputOrigin:{retainedProjection:{entryBasis:foldBasis,input:{admissionRef:'controlled:actual-retained-input',value:retained},sourceResult:source}}};
const folded=libraryOwner.projectGovernanceFold({graphFunction:wrapper},retained);assert.deepEqual(folded,at(1733).payload.value);
owned={...owned,execution:root.payload,inputValue:folded,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','evaluate-parent')},inputOrigin:{}};
const parent=libraryOwner.projectGovernanceParent({},folded);assert.deepEqual(parent,at(1774).payload.value);assert.equal(parent.terminal,false);
owned={...owned,execution:execution(at(1794).basisId),inputValue:parent,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','prepare-selection')}};
const next=await libraryOwner.projectGovernanceSelection({graphFunction:graph},parent);assert.deepEqual(next,successor);const nextBasis=candidate(at(1794));assert.equal(assemblyOwner.requireDeclaredNativeInstructionAssembly(nextBasis,next,lookup).kind,'native_instruction_assembly');
// Retain the already-computed refusal through the same exception boundary.
const oversized=structuredClone(successor);oversized.state.original.task+='x'.repeat(131072);owned.inputValue=oversized;owned.inputDigest=product.sha256Canonical(oversized);
const refused=assemblyOwner.evaluateFramedSynthesisInstructionAssembly(nextBasis,oversized,lookup);assert.equal(refused.cause,'declared_bound_overflow');assert.throws(()=>assemblyOwner.requireDeclaredNativeInstructionAssembly(nextBasis,oversized,lookup),error=>assert.deepEqual(JSON.parse(error.message),refused)===undefined);
// Finite presentation multiplicity probe only: twelve copies of the actual
// observation test carrier growth, not twelve fabricated admitted executions.
const repeated=structuredClone(successor);repeated.state.observations=Array.from({length:12},()=>successor.state.observations[0]);const repeatProjection=product.projectFramedSynthesisPromptTask(repeated),repeatBytes=Buffer.byteLength(canonicalJson(repeatProjection));assert.equal(repeatProjection.observations.length,12);assert.ok(repeatBytes+measurements[1].afterBytes-measurements[1].afterSections.task<131072);
await writeFile(join(here,'checks.json'),JSON.stringify({passed:true,providerCalls:0,retainedSource:'s6-fulfillment-implementation/live-01',componentPremise:'Existing authenticated occurrence/index relations supplied from retained admitted facts; no new admission or whole installed rerun.',measurements,ordinaryJoin:{foldOrdinal:1733,parentOrdinal:1774,nextTaskOrdinal:1794,actualC2SourceOrdinal:1703,typedFoldEqual:true,parentEqual:true,nextTaskEqual:true,ownedAssemblyAccepted:true},refusals:['changed input','missing exact contract','wrong input Result ref','declared bound overflow cause retained'],conserved:['original task/case/oracle/source text','authority','capability effects/read/write/checks','fixed command plan','active obligation policy/shape/criteria/depth/discovery','current observation streams/status/Result refs','prior judgment and unresolved obligations','unchanged dynamic response domains and raw answer','full input identity'],multiplicityProbe:{observations:12,presentationBytes:repeatBytes,totalUsingSuccessorSections:repeatBytes+measurements[1].afterBytes-measurements[1].afterSections.task,admittedRunClaim:false}},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({passed:true,measurements,multiplicityProjectionBytes:repeatBytes},null,2));
