import json,pathlib,hashlib,shutil,collections,datetime
R=pathlib.Path('/Users/jim/src/apps/abiogenesis');G=R/'.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE';E=G/'final-qualification-inputs-01';C=G/'final-candidate-construction-01';D=R/'.ai-workspace/comments/codex/20260923_RC1_QUALIFICATION_RECIPE/successor-06';T='build_tenants/abiogenesis/typescript/'
def read(p):return json.loads(p.read_text())
def write(n,d): (E/n).write_text(json.dumps(d,indent=2)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def row(p):return {'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':sha(p)}
def check(p,r):assert p.stat().st_size==r.get('bytes',r.get('byteCount')) and sha(p)==r.get('sha256',r.get('digest','').removeprefix('sha256:')),str(p)
src=read(C/'source-members.json');gen=read(C/'generated-after.json');arc=read(C/'archive-members.json');joins=read(C/'authority-joins.json');deps=read(C/'dependency-archives.json');rows=read(E/'source-inventory.json');files=read(E/'input-manifest.json')['sourceFiles'];lint=read(E/'lint-population.json')['lint']['files'];expected=read(E/'expected-output-inventory.json')['paths'];npmroot=C/'source-freeze/toolchain/npm';npmrows=read(E/'npm-toolchain-inventory.json')['files']
host=read(C/'toolchain-host.json');tool=read(D/'toolchain.json');tool.pop('reverifiedAt',None);tool['npm']['inventorySha256']=sha(E/'npm-toolchain-inventory.json');tool['npm']['frozenRoot']=str(npmroot);tool['node']['frozenPath']=str(C/'source-freeze/toolchain/bin/node');tool['hostLibraryBasis']=row(C/'toolchain-host.json');tool['dependencies']=row(C/'dependency-archives.json');tool['cache']='Only 16 frozen dependency archives; future protected recipe seeds its own cache and installs offline.'
for n in ['node','npm']:
 tool[n]['bytes']=pathlib.Path(tool[n]['invokedPath']).stat().st_size;check(pathlib.Path(tool[n]['invokedPath']),tool[n])
for r in npmrows:check(pathlib.Path('/opt/homebrew/lib/node_modules/npm')/r['path'],r)
for r in host['nodeDynamicLibraries']:
 if not r['systemSharedCache']:assert sha(pathlib.Path(r['realpath']))==r['sha256']
check(pathlib.Path(tool['git']['resolvedDeveloperTool']),{'bytes':pathlib.Path(tool['git']['resolvedDeveloperTool']).stat().st_size,'sha256':tool['git']['sha256']})
write('toolchain.json',tool)
core=read(C/'selected-core.json');basis=core['basis'];write('package-readiness.json',{'installRoot':core['packageRoot'],'archive':core['artifactPath'],'archiveSha256':basis['artifactDigest'][7:],'productId':basis['productId'],'packageVersion':basis['packageVersion'],'productContentDigest':basis['productContentDigest'],'productManifestDigest':basis['manifestDigest'],'role':'physical readiness, not admitted ProductInstall'})
write('population-binding.json',{'sourceSelected':len(src),'generatedOutputs':len(gen),'qualificationSourceMembers':len(rows),'protectedSourceInputs':len(files),'lintFiles':len(lint),'authorityJoins':len(joins),'dependencies':len(deps),'npmFiles':len(npmrows),'archiveFiles':len(arc),'expectedCompareMembers':len(expected),'archiveInventory':row(C/'archive-members.json'),'generatedInventory':row(C/'generated-after.json'),'preimageInventory':row(C/'generated-before.json') if (C/'generated-before.json').exists() else row(C/'source-freeze-manifest.json'),'realizedBuildDependencies':row(C/'realized-dependencies-before-build.json'),'sourceOverlay':row(C/'source-overlay.json'),'reason':'All 1103 selected members and 828 generated output members are qualification source inventory. Bundled supplier payload membership remains complete in archive inventory, not falsely attributed as new local authorship. Protected build/lint selects all 689 operational and proof source members plus two schema seeds. Design/original law remain qualification inputs. Five test selections unchanged.'})
write('environment-delta.json',{'donor':row(D/'config.json'),'preloaderDonor':row(D/'test-environment.mjs'),'removed':['all 13 HOME assignments','preloader HOME assignment','unused .home creation'],'added':['explicit environment array selects no ambient HOME; inherited HOME is not rewritten','task-owned npm prefix, Git global/system config and GIT_OPTIONAL_LOCKS=0','preloader absolute npm cache/prefix/config paths'],'preserved':['13 commands and 14 predicate meanings','five test argument selections and time bounds','verification subtree only writes','TMPDIR, npm offline/cache/config, LANG/LC_ALL, F16 report territory'],'execution':'none'})
print(json.dumps(read(E/'population-binding.json'),indent=2))
