// Read-only finite candidate/input and current installed constructor checks. No command/test/native execution.
import fs from 'node:fs';import assert from 'node:assert/strict';import {join,resolve,relative} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const E=import.meta.dirname,C=resolve(E,'../final-candidate-construction-01'),R='/Users/jim/src/apps/abiogenesis',T='build_tenants/abiogenesis/typescript/';const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),local=n=>read(join(E,n)),write=(n,d)=>fs.writeFileSync(join(E,n),JSON.stringify(d,null,2)+'\n',{flag:'wx'});
const I=local('package-readiness.json').installRoot;const load=async n=>import(pathToFileURL(join(I,'build/code/src',n+'.js')).href);const p=await load('product/index'),q=await load('validator/qualification_contracts'),owner=await load('validator/qualification'),gtl=await load('gtl/index');const v=createRequire(join(I,'package.json'))('valibot'),ts=createRequire(join(C,'staged-repo',T,'package.json'))('typescript');const digest=p.sha256Bytes;
const {selectedFiles}=await import('./recipe.mjs');const files=await selectedFiles(),manifest=local('input-manifest.json'),recipe=local('verification-recipe.json'),inventory=local('qualification-inventory.json');
for(const r of files){const b=fs.readFileSync(r.origin);assert.equal(b.length,r.bytes);assert.equal(digest(b),'sha256:'+r.sha256,r.origin);}
for(const r of local('source-inventory.json')){const b=fs.readFileSync(r.origin);assert.equal(b.length,r.bytes);assert.equal(digest(b),'sha256:'+r.sha256,r.path);}
const actual=[];function walk(f){for(const ent of fs.readdirSync(f,{withFileTypes:true})){const path=join(f,ent.name);if(ent.isDirectory())walk(path);else {assert.ok(ent.isFile());actual.push(relative(join(C,'staged-repo',T),path));}}}
for(const n of ['build','contracts'])walk(join(C,'staged-repo',T,n));actual.push('product-toolchain-manifest.json');const expected=local('expected-output-inventory.json').paths;assert.deepEqual(actual.sort(),expected.map(r=>r.path).sort());
for(const r of expected){const b=fs.readFileSync(join(C,'staged-repo',T,r.path));assert.equal(b.length,r.bytes);assert.equal(digest(b),'sha256:'+r.sha256);}
const cb=local('configuration-binding.json');assert.equal(p.sha256Canonical(cb.commands),recipe.commandConfigurationDigest);assert.equal(p.sha256Canonical(cb.predicates),recipe.predicateConfigurationDigest);assert.equal(p.sha256Canonical(cb.allowedWriteTerritories),recipe.writeTerritoriesDigest);
assert.deepEqual(files.filter(r=>!r.target.startsWith('subject/')&&r.target!=='recipe/verification-recipe.json').map(r=>({relativePath:r.target,digest:'sha256:'+r.sha256,byteCount:r.bytes})),recipe.auxiliaryInputs);
assert.ok(!JSON.stringify(recipe).includes(inventory.inventoryDigest));assert.ok(!recipe.auxiliaryInputs.some(r=>r.relativePath==='recipe/verification-recipe.json'));const rb=fs.readFileSync(join(E,'verification-recipe.json'));assert.equal(local('verification-selection-binding.json').recipe.digest,digest(rb));assert.ok(!('executionSelectionRef'in local('verification-selection-binding.json')));
v.parse(q.QUALIFICATION_VERIFICATION_RECIPE_SCHEMA,recipe);v.parse(q.QUALIFICATION_INVENTORY_SCHEMA,inventory);
const {inventoryRef,inventoryDigest,...ib}=inventory;assert.deepEqual(q.constructQualificationIdentity(ib,'inventoryRef','inventoryDigest','qualification-inventory://abiogenesis/'),inventory);
const template=local('basis-template.json');for(const k of template.requiredNativeBindings)assert.equal(template.body[k],null);const structural=q.constructQualificationIdentity(template.body,'basisRef','basisDigest','qualification-basis://abiogenesis/');v.parse(q.EXACT_CANDIDATE_QUALIFICATION_BASIS_SCHEMA,structural);assert.equal(owner.isQualificationBasisReady(structural),false); // ephemeral only; not persisted as a ready basis
const syntax=[];for(const row of recipe.lint.files){const src=manifest.sourceFiles.find(x=>x.path===row.path);assert.ok(src);const txt=fs.readFileSync(src.origin,'utf8');if(row.kind==='json')JSON.parse(txt);else {const sf=ts.createSourceFile(row.path,txt,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);assert.equal(sf.parseDiagnostics.length,0,row.path+JSON.stringify(sf.parseDiagnostics.map(d=>d.messageText)));}syntax.push({path:row.path,kind:row.kind,status:'syntax_valid_no_execution'});}write('syntax-selection-check.json',{files:syntax,count:syntax.length,method:'JSON.parse and TypeScript JS parser; selected test bodies never imported or executed'});
const pm=read(join(I,'product-toolchain-manifest.json')),core=read(join(C,'selected-core.json')),basis={...core.basis,productManifestDigest:core.basis.manifestDigest};assert.equal(p.sha256Canonical(pm),core.basis.manifestDigest);
const constructors=['constructHelloWorldModulePublication','constructConsensusModulePublication','constructWorksiteConstructionModulePublication','constructWorksiteCommandExecutionModulePublication','constructWorksiteCommandForwardModulePublication','constructRequirementHandoffModulePublication','constructSemanticStageModulePublication','constructSemanticRevisionModulePublication','constructSelfConformanceModulePublication','constructNativeWorkspaceWorkModulePublication'];
const publications=constructors.map(n=>{assert.equal(typeof gtl[n],'function');return gtl[n](basis);});const rows=publications.map((pub,i)=>({constructor:constructors[i],productId:pub.owningProductId,moduleRef:pub.moduleRef,publicationDigest:p.modulePublicationSemanticDigest(pub)}));
const select=r=>[r.productId,r.moduleRef,r.publicationDigest].join('\0');assert.deepEqual(rows.map(select).sort(),pm.contributionManifest.publicationBindings.map(r=>[pm.productId,r.moduleRef,r.publicationDigest].join('\0')).sort());
const pub=publications[3],program=pub.programs.find(x=>x.programRef==='program://abiogenesis/worksite/command-execution@5');assert.ok(program);assert.ok(pub.runEnvironments.length>0);assert.ok(program.policies[gtl.RUN_ENVIRONMENT_POLICY]);
write('current-publication-closure.json',{status:'exact_current_installed_constructor_to_manifest_binding',manifestDigest:core.basis.manifestDigest,productContentDigest:core.basis.productContentDigest,publicationBindings:rows,expectedCount:pm.contributionManifest.publicationBindings.length,actualCount:rows.length,C2:{programRef:program.programRef,runEnvironmentPolicy:program.policies[gtl.RUN_ENVIRONMENT_POLICY],declarations:pub.runEnvironments.map(r=>({ref:r.declarationRef,digest:r.declarationDigest}))},effect:'Pure publication construction only. Ordinary Public-native setup must still verify and admit this complete exact closure. root-installed-environment frozenArtifact supplies selection/provisioning only; its direct ABG/publicOperationBasis is not an alternate Public-native setup proof.'});
const rule=read(join(I,'contracts/qualification/rule-catalog.json'));v.parse(q.QUALIFICATION_RULE_CATALOG_SCHEMA,rule);v.parse(q.QUALIFICATION_LAW_BASIS_SCHEMA,read(join(I,'contracts/qualification/law-basis.json')));assert.equal(rule.rules.length,2137);
const record=f=>({path:relative(R,f),bytes:fs.statSync(f).size,sha256:digest(fs.readFileSync(f)).slice(7)});write('validation-result.json',{status:'PASSED_INPUT_ONLY',sourceCopyChecks:1931,protectedFiles:files.length,expectedComparePaths:expected.length,syntaxFiles:syntax.length,recipeSchema:true,inventorySchema:true,structuralNullableBasisSchema:true,isQualificationBasisReady:false,acyclic:true,actualInstalledPublicationClosure:rows.length,ruleCount:rule.rules.length,lawSourceCount:rule.sources.length,ownerFiles:['validator/qualification_contracts.js','validator/qualification.js','product/worksite_command_execution.js','product/environment.js','gtl/worksite_command_execution.js'].map(f=>record(join(I,'build/code/src',f))),runtime:'none; no recipe,test suite,native setup,provider or qualification execution'});console.log(JSON.stringify({status:'PASSED_INPUT_ONLY',protectedFiles:files.length,sourceChecks:1931,comparePaths:925,syntaxFiles:syntax.length,publications:rows.length,rules:rule.rules.length,basisReady:false}));
