"""Freeze the first Q12 actual cheap-join refusal without repair or payload."""
from pathlib import Path
import datetime,hashlib,json,os,stat
Q=Path(__file__).resolve().parent;G=Q.parent;C=G/'final-candidate-construction-09';D=G/'final-qualification-inputs-11'
assert not(Q/'freeze.json').exists()
def read(p):return json.loads(Path(p).read_bytes())
def pin(p):
 p=Path(p)
 with p.open('rb')as f:h=hashlib.file_digest(f,'sha256').hexdigest()
 return {'path':str(p),'bytes':p.stat().st_size,'sha256':h,'mode':stat.S_IMODE(p.stat().st_mode)}
def put(n,v):
 with(Q/n).open('x')as f:f.write(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
path='build_tenants/abiogenesis/typescript/code/src/abg/c_call.ts';cut=read(C/'controls/source-cut.json');supplier=read(C/'final-source-members.json');auth=read(Q/'f11/source-authorship-records.json');view=read(Q/'current-source-supplier-view.json')
i,m=next((i,m)for i,m in enumerate(cut['replacements'])if m['path']==path);j,s=next((i,m)for i,m in enumerate(supplier)if m['path']==path);a=next(m for m in auth['sourceOrigins']if m['path']==path);v=next(m for m in view['rows']if m['path']==path)
fields=['path','origin','sha256','bytes','mode','sourceAuthor','originalSource','originalAuthorship','selectedRelation','copyBuildAuthor','copyOrigin']
project=lambda row:{k:row[k]for k in fields if k in row}
assert m['copyBuildAuthor']!=s['copyBuildAuthor']
assert a['copyBuildAuthor']==m['copyBuildAuthor']and v['copyBuildAuthor']==s['copyBuildAuthor']
for k in fields[:9]:assert (k in m)==(k in s)and(k not in m or m[k]==s[k])
assert auth['records']==read(D/'f11/source-authorship-records.json')['records']and auth['chains']==read(D/'f11/source-authorship-records.json')['chains']
failure={'status':'CLOSED_FIRST_ACTUAL_PREFLIGHT_REFUSAL','operation':'T287_FINAL_QUALIFICATION_INPUTS_12','workResult':'NO_GO_EXTERNAL_COPY_ROLE_EQUALITY_PREFLIGHT','frontier':'cheap selected-cut/current-supplier tuple correspondence before materialization','owner':'external prepare-current-delta.py:28','predicate':'For each field, selected source-cut replacement == current manifest == projected Source origin == derived supplier view','firstField':'copyBuildAuthor','path':path,'actualSelectedCutValue':m['copyBuildAuthor'],'actualCurrentSupplierValue':s['copyBuildAuthor'],'projectedOriginValue':a['copyBuildAuthor'],'derivedSupplierValue':v['copyBuildAuthor'],'actualSelectedCutRow':{'manifest':pin(C/'controls/source-cut.json'),'pointer':'/replacements/'+str(i),'tuple':project(m)},'actualCurrentSupplierRow':{'manifest':pin(C/'final-source-members.json'),'pointer':'/'+str(j),'tuple':project(s)},'originalFlatViewsFaithfullyRetainTheirDistinctRoles':True,'priorFieldsMatched':fields[:9],'failingCommand':['python3',str(Q/'prepare-current-delta.py')],'processExitCode':1,'execWallTimeSeconds':0.059746166,'actualStderr':'Traceback (most recent call last):\n  File "'+str(Q/'prepare-current-delta.py')+'", line 28, in <module>\n    for other in [sm,origins[m[\'path\']],viewRows[m[\'path\']]]:assert (field in m)==(field in other)and(field not in m or other[field]==m[field]),(m[\'path\'],field)\nAssertionError: (\''+path+'\', \'copyBuildAuthor\')\n','selectedDeltaProducerCounts':{'replacements':len(cut['replacements']),'additions':len(cut['additions'])},'completeNineTupleJoin':'NOT_ESTABLISHED','notReached':['current-source-delta.json/identity/pin creation','cheap discriminator negatives','new complete inventory/protected/recipe-self binding','prepayload envelope measurement','complete published command Task payload','full resource/material/scope/embedded/reference owner/render payload'],'noProductDefectInferred':True,'noRepairOrRetry':True,'ProductImports':0,'nativeCalls':0}
put('first-readiness-refusal.json',failure)
put('accounting.json',{'purePreparationLaunches':1,'actualOwningReadinessPayloads':0,'completeTaskPayloads':0,'packetPayloads':0,'purePreparationExitCode':1,'purePreparationExecWallTimeSeconds':0.059746166,'processClosure':'exec_command completed with exit1; no managed owner payload or process group was launched','RSSBytes':None,'RSSStatus':'not measured for cheap Python preparation','materialBodiesMaterialized':0,'resourceSerializationBytes':None,'promptBytes':None,'actualResourceEnvelopeMeasurement':'not reached','nativeTaskRunJHelperProviderCalls':0,'qualificationCommandsExecuted':0,'SourceChanges':0,'builds':0,'GitEffects':0,'networkEffects':0,'retries':0})
result={'status':'CLOSED','role':'Worker','actor':'/root/q03_input_review','operation':'T287_FINAL_QUALIFICATION_INPUTS_12','workResult':failure['workResult'],'ProductFrame':'F-EndToEndInterfaceIntegration, fixed15/GOAL035/T287/F11/F15; unchanged WHAT/runtime, selected external HOW4.1 contract','currentC09Acceptance':pin(G/'rc1-c09-construction-acceptance-01/acceptance.json'),'actualSetup09Acceptance':pin(G/'rc1-setup09-acceptance-01/acceptance.json'),'donorQ11Freeze':pin(D/'freeze.json'),'pathRecord':pin(Q/'controls/q12-path-record.json'),'grant':pin(Q/'request.txt'),'firstActualRefusal':failure,'retainedStrictCaller':pin(Q/'f11/ordinary-caller.mjs'),'retainedParentChildDriver':pin(Q/'f11/flow-driver.mjs'),'retainedOriginalSourceAuth':{'body':pin(Q/'f11/source-authorship-records.json'),'records':174,'chains':23,'spans':90,'recordAndChainValuesUnchanged':True,'sourceOriginsAndSupplierViewsConserveQ11Bytes':True,'sufficiency':'unknown','independence':'unknown'},'proofScope':'This cut records a rejected cheap preparation assertion. It establishes neither the complete nine-tuple preflight nor current Q12 Task/resource/request readiness. Q11 evidence remains historical and immutable.','accounting':read(Q/'accounting.json'),'unknowns':['Correct source-cut versus current builder copy-role contract disposition','Complete current delta correspondence and counterexamples','Current Q12 inventory/task/reference-owner/request/prompt/envelope readiness','Semantic source attribution/material/context/applicability/grouping/independence','Installed Result/J/foldback/F11/readbacks/QUAL056/greenAF22/release'],'independentAssuranceClaim':False,'noFurtherWritesAfterFreeze':True,'returnsTo':'Root Executive'}
put('worker-result.json',result)
put('closure.json',{'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'closedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'noRepairOrRetry':True,'allWritesStopAfterFreeze':True,'consumer':'Root Executive'})
with(Q/'return.md').open('x')as f:f.write('CLOSED Q12: '+result['workResult']+'.\n\nThe first cheap tuple assertion at prepare-current-delta.py:28 required one copyBuildAuthor value across selected-cut and current supplier roles. Actual c_call.ts selected-cut/projected-origin value is '+repr(m['copyBuildAuthor'])+'; current manifest/derived-supplier value is '+repr(s['copyBuildAuthor'])+'. Both original flat views preserve their respective producer records. The preceding path/body/bytes/mode/sourceAuthor/originalSource/originalAuthorship/selectedRelation fields matched.\n\nThe authoritative cut supplies seven replacements and two additions, but complete nine-tuple correspondence and negatives were not reached. The pure Python preparation exited1 in0.059746166s; no Product imports, body materialization, owner payload, Task, Run, J, provider, source/build/Git/network or qualification command occurred. All174original record values/23chains/90spans remain unchanged. No repair or retry; return Root for multi-frame triangulation.\n')
rows=[];directories=[]
for p in sorted(Q.rglob('*')):
 if p.is_symlink():rows.append({'path':str(p.relative_to(Q)),'kind':'symlink','target':os.readlink(p),'mode':stat.S_IMODE(p.lstat().st_mode)})
 elif p.is_file():row=pin(p);row['path']=str(p.relative_to(Q));rows.append(row)
 elif p.is_dir():directories.append({'path':str(p.relative_to(Q)),'mode':stat.S_IMODE(p.stat().st_mode)})
freeze={'status':'CLOSED','role':'Worker','operation':result['operation'],'workResult':result['workResult'],'records':rows,'recordCount':len(rows),'bodyBytes':sum(r.get('bytes',0)for r in rows),'directories':directories,'directoryCount':len(directories),'linkCount':sum(r.get('kind')=='symlink'for r in rows),'noProductOrRuntimeEffects':True,'allWritesStopped':True}
put('freeze.json',freeze);os.chmod(Q/'freeze.json',0o444)
print(json.dumps({'status':'CLOSED','workResult':result['workResult'],'freeze':pin(Q/'freeze.json'),'records':len(rows),'bodyBytes':freeze['bodyBytes'],'directories':len(directories),'links':freeze['linkCount'],'failingSelectedCopyRole':m['copyBuildAuthor'],'failingSupplierCopyRole':s['copyBuildAuthor']}))
