import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {SourceTextModule,SyntheticModule} from 'node:vm';
const here=dirname(fileURLToPath(import.meta.url)),records=dirname(here),old=join(records,'s6-context-projection-01'),live=join(old,'live-02'),repo=resolve(records,'../../../..'),tenant=join(repo,'build_tenants/abiogenesis/typescript'),read=async p=>JSON.parse(await readFile(p,'utf8'));
const load=p=>import(pathToFileURL(join(tenant,'build/code/src',p+'.js')).href),[product,gtl,store,prefixOwner,native,{canonicalJson}]=await Promise.all([load('product/index'),load('gtl/index'),load('abg/event_store'),load('abg/event_prefix'),load('abg/native_worksite_execution'),load('shared/canonical_json')]);
const setup=await read(join(old,'setup.json')),handoff=await read(join(live,'handoff.json')),prior=await read(join(live,'assembly-1.json')),start=await read(join(old,'start-prepared.json')),publication=await read(join(old,'publication.json')),original=await read(join(old,'input.json')),attribution=await read(join(live,'prompt-attribution.json'));
const events=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),prefix=prefixOwner.selectValidatedRuntimeEventPrefix(events),at=n=>events.find(e=>e.admissionOrdinal===n),execution=ref=>events.find(e=>e.kind==='basis_admitted'&&e.payload.basisRef===ref).payload;
const publications=start.call.resources.catalog.readinessBasis.publications,definitions=publications.flatMap(p=>p.graphFunctions),graph=publication.graphFunctions.find(g=>g.name.endsWith('/executive-step@5')),program=publication.programs[0],node=graph.template.nodes.find(n=>n.nodeRef===graph.declarations['abg.framed_synthesis_locus']);
const role=publication.runEnvironments[0].roles.find(r=>r.role==='selector');let roleEvidence={...role,...prior.manifest.runEnvironment,evidenceDigest:prior.envelope.boundBasis.frameEvidenceDigest,contextPolicyDigest:product.sha256Canonical(role.contextPolicy),sourceContent:prior.envelope.sections.role.sourceContent,accessContent:prior.envelope.sections.evidence.declaredAccess};
const root=events.find(e=>e.kind==='basis_admitted'&&e.payload.basisClass==='root'),source=at(21754),nativeTask=source.payload.value.task;
let owned={program,events,prefix,execution:execution(at(21845).basisId),graph:{template:graph.template},environment:{kind:'exact_prefix_workspace_environment',workspaceAuthorityBasis:nativeTask.workspaceAuthorityBasis,workspaceBinding:nativeTask.workspaceBinding,productInstalls:setup.installedRoots.map(installedRoot=>({installedRoot}))},call:{},inputValue:null,inputRef:'',inputDigest:'',inputOrigin:{}};
const lookup=ref=>{const rows=publications.flatMap(p=>p.contracts).filter(c=>c.contractRef===ref);return rows.length===1?rows[0]:null;};
async function module(path){const file=join(tenant,'build/code/src',path+'.js'),m=new SourceTextModule(await readFile(file,'utf8'),{identifier:file});await m.link(async specifier=>{const actual=await import(specifier.startsWith('node:')?specifier:pathToFileURL(resolve(dirname(file),specifier)).href),replacements=specifier==='./execution_basis.js'?{authenticateNativeInstructionAssemblyBasis:()=>owned}:specifier==='./stdo_environment.js'?{projectRunEnvironmentRoleEvidence:()=>roleEvidence}:{};const values={...actual,...replacements};return new SyntheticModule(Object.keys(values),function(){for(const[k,v]of Object.entries(values))this.setExport(k,v);});});await m.evaluate();return m.namespace;}
// Controlled current-call authentication/role projection only. All durable
// invocation, source/currentness and indexed prefix owners consume the actual
// closed live-02 history. No new choice, call, admission or provider is made.
const assemblyOwner=await module('abg/instruction_assembly'),libraryOwner=await module('abg/default_library');
const candidate=taskEvent=>{const task=taskEvent.payload.value,call=events.find(e=>e.kind==='c_call_opened'&&e.basisId===taskEvent.basisId&&e.payload.programLocusRef===node.nodeRef),basis=execution(taskEvent.basisId);owned={...owned,execution:basis,graph:{template:graph.template},call:{...call.payload,runId:call.runId,regime:'F_P',inputContractRef:node.term.inputCarrierRef,outputContractRef:node.term.outputCarrierRef,implementationRef:product.governanceRef('implementation','select')},inputValue:task,inputRef:taskEvent.payload.resultRef,inputDigest:taskEvent.payload.valueDigest,inputOrigin:{event:taskEvent}};return {publication,graphFunction:graph,declarationGraphFunctions:definitions,executionBasis:basis,cCall:owned.call,cursor:{currentNodeRef:node.nodeRef,termPath:gtl.rootCSourcePath(node.nodeRef)},predecessorPrefix:prior.envelope.predecessorPrefix};};
const bytes=v=>Buffer.byteLength(canonicalJson(v)),fieldBytes=v=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k,bytes(x)])),measurements=[];
for(const oldMeasurement of attribution.measurements){const e=at(oldMeasurement.task.ordinal),task=e.payload.value,full=canonicalJson(task),b=candidate(e),assembly=assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,task,lookup);assert.equal(assembly.kind,'native_instruction_assembly',JSON.stringify(assembly));assert.ok(Buffer.byteLength(assembly.request.prompt)<original.original.maxPromptBytes);assert.equal(canonicalJson(task),full);assert.equal(assembly.envelope.inputRef,e.payload.resultRef);assert.equal(assembly.envelope.inputDigest,e.payload.valueDigest);assert.deepEqual(assembly.request.responseJsonSchema,product.framedSynthesisResponseSchema(task,prior.envelope.targetBindings));assert.deepEqual(assembly.envelope.targetBindings,prior.envelope.targetBindings);
 const projection=assembly.envelope.sections.task,sourcePaths=new Set([...original.original.sources.map(s=>s.path),...original.original.fulfillment.context.members.map(s=>s.path)]);assert.equal(projection.originalTask,original.original.task);assert.deepEqual(projection.observations.map(o=>o.resultRef),task.state.observations.map(o=>o.resultRef));assert.deepEqual(projection.priorJudgment,{resultRef:task.state.synthesis?.resultRef,judgment:task.state.synthesis?.judgment}.resultRef===undefined?null:{resultRef:task.state.synthesis.resultRef,judgment:task.state.synthesis.judgment});
 for(const f of projection.worksite.files){const entry=task.context.entries.find(x=>x.relativePath===f.path);if(entry.state!=='file')continue;assert.equal(f.digest,entry.digest);assert.equal(f.byteLength,entry.byteLength);if(sourcePaths.has(f.path)){assert.equal(f.contentRole,'declared_source');const content=f.contentIn==='originalTask'?projection.originalTask.slice(f.startCharacter,f.endCharacter):f.encoding==='base64'?Buffer.from(f.content,'base64').toString():f.content;assert.equal(content,Buffer.from(entry.bytes,'base64').toString());}else {assert.equal(f.contentRole,'observed_output');assert.equal(f.content,undefined);assert.equal(f.contentIn,undefined);}}
 for(const mutate of [t=>{t.state.original.task+=' changed';},t=>{t.state.original.sources[0].digest='sha256:'+'0'.repeat(64);}]){const changed=structuredClone(task);mutate(changed);assert.equal(assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,changed,lookup).kind,'native_instruction_assembly_refusal');}
 assert.equal(assemblyOwner.evaluateFramedSynthesisInstructionAssembly(b,task,()=>null).kind,'native_instruction_assembly_refusal');
 measurements.push({taskOrdinal:e.admissionOrdinal,beforeBytes:oldMeasurement.renderedBytes,afterBytes:Buffer.byteLength(assembly.request.prompt),sectionBytes:fieldBytes(assembly.envelope.sections),projectedTaskFieldBytes:fieldBytes(projection),inputRef:e.payload.resultRef,inputDigest:e.payload.valueDigest,responseSchemaDigest:product.sha256Canonical(assembly.request.responseJsonSchema)});
}
// Same actual bytes, different explicitly declared source role. Neither path
// name nor textual content decides inclusion; this is a pure projection test.
const expanded=at(21845).payload.value,asSource=structuredClone(expanded),path='design/implementation-design.md',entry=expanded.context.entries.find(e=>e.relativePath===path);asSource.state.original.sources.push({path,digest:entry.digest});const outputProjection=product.projectFramedSynthesisPromptTask(expanded),sourceProjection=product.projectFramedSynthesisPromptTask(asSource);assert.equal(outputProjection.worksite.files.find(f=>f.path===path).content,undefined);assert.equal(sourceProjection.worksite.files.find(f=>f.path===path).content,Buffer.from(entry.bytes,'base64').toString());assert.equal(sourceProjection.worksite.files.find(f=>f.path===path).digest,outputProjection.worksite.files.find(f=>f.path===path).digest);
// Actual expanded ordinary execution join, preserving the admitted producer.
const choice=at(13575).payload.value,retained=product.constructRetainedGraphInput(choice.input.value,source.payload.value),foldBasis=execution(at(21784).basisId),wrapper=definitions.find(g=>g.name===at(21784).graphFunctionRef);
owned={...owned,execution:foldBasis,inputValue:retained,inputRef:'controlled:retained-design',inputDigest:product.sha256Canonical(retained),call:{runId:source.runId,implementationRef:product.governanceRef('implementation','fold')},inputOrigin:{retainedProjection:{entryBasis:foldBasis,input:{admissionRef:'controlled:retained-design',value:retained},sourceResult:source}}};const folded=libraryOwner.projectGovernanceFold({graphFunction:wrapper},retained);assert.deepEqual(folded,at(21784).payload.value);
owned={...owned,execution:root.payload,inputValue:folded,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','evaluate-parent')},inputOrigin:{}};const parent=libraryOwner.projectGovernanceParent({},folded);assert.deepEqual(parent,at(21825).payload.value);assert.equal(parent.terminal,false);
owned={...owned,execution:execution(at(21845).basisId),inputValue:parent,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','prepare-selection')}};const next=await libraryOwner.projectGovernanceSelection({graphFunction:graph},parent);assert.deepEqual(next,expanded);const nextBasis=candidate(at(21845));assert.equal(assemblyOwner.requireDeclaredNativeInstructionAssembly(nextBasis,next,lookup).kind,'native_instruction_assembly');
// Prospective UAT choice is the controlled semantic premise only. The actual
// admitted last Design producer and all expanded files are real preserved work.
const uat=structuredClone(parent);uat.synthesis.judgment.subjectEvidenceRef=source.payload.resultRef;uat.synthesis.judgment.nextGraphFunctionRef=product.governanceRef('graph-function','uat');const actualSource=native.projectNativeWorkspaceWorkSourceAtPrefix(prefix,source.payload.value);assert.ok(actualSource);
owned={...owned,execution:foldBasis,inputValue:uat,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','prepare-native')},inputOrigin:{}};const uatGraph=definitions.find(g=>g.name===product.governanceRef('graph-function','uat')),assessment=await libraryOwner.projectGovernanceNativeTask({graphFunction:uatGraph},uat);assert.ok(assessment,'actual expanded assessment preparation');assert.ok(product.isNativeWorkspaceWorkTask(assessment));assert.deepEqual(assessment.context,expanded.context);assert.equal(assessment.assessment.producer.resultRef,source.payload.resultRef);assert.equal(assessment.assessment.producer.cCallRef,source.aggregateId);assert.deepEqual(assessment.writeRoots,[]);
for(const file of expanded.context.entries.filter(e=>e.state==='file'))assert.equal(assessment.context.entries.find(e=>e.relativePath===file.relativePath).bytes,file.bytes);
const assessmentSourcePaths=[...assessment.assessment.sources.map(s=>s.path),assessment.assessment.candidate.path,assessment.assessment.rubric.path];for(const required of original.original.assessment.sources)assert.ok(assessmentSourcePaths.includes(required));assert.ok(assessment.instructions.some(i=>i.includes('independent judgments')));assert.ok(assessment.instructions.some(i=>i.includes('AdverseEvidenceRefs')));
// Complete the existing owned native assembly with a disclosed prospective
// child-call premise. Its schema/install and role content are actual owners.
const stdoOwner=await load('abg/stdo_environment'),assessmentGraph=definitions.find(g=>g.name===product.NATIVE_WORKSPACE_WORK_IDS.assessmentGraphFunctionRef),assessorRole=publication.runEnvironments[0].roles.find(r=>r.role==='assessor');
roleEvidence=stdoOwner.projectRunEnvironmentRoleEvidence(events,foldBasis.invocationAdmissionRef,publication,program.programRef,assessmentGraph.name,assessorRole.programLocusRef,'assessor');assert.ok(roleEvidence&&roleEvidence.role==='assessor');
const nativeDigest=product.sha256Canonical(assessment),prospectiveCall={cCallRef:'controlled:prospective-assessor-call',cCallDigest:product.sha256Canonical({premise:'prospective assessor',taskDigest:nativeDigest}),regime:'F_P',graphFunctionRef:assessmentGraph.name,programLocusRef:assessorRole.programLocusRef,implementationRef:product.NATIVE_WORKSPACE_WORK_IDS.implementationRef,inputContractRef:product.NATIVE_WORKSPACE_WORK_IDS.taskContractRef,outputContractRef:product.NATIVE_WORKSPACE_WORK_IDS.observationContractRef,runId:source.runId};
owned={...owned,inputValue:assessment,inputRef:'controlled:prospective-assessment-task',inputDigest:nativeDigest,call:prospectiveCall,environment:{...owned.environment,productInstalls:start.call.resources.catalog.readinessBasis.installedProducts}};
const assessmentBasis={publication,assessmentPublication:publication,graphFunction:assessmentGraph,declarationGraphFunctions:definitions,executionBasis:owned.execution,cCall:prospectiveCall,cursor:{currentNodeRef:assessorRole.programLocusRef,termPath:gtl.rootCSourcePath(assessorRole.programLocusRef)},predecessorPrefix:handoff.prefix};
const assessmentAssembly=assemblyOwner.constructWorksiteNativeInstructionAssembly(assessmentBasis,assessment);assert.ok(assessmentAssembly,'actual owned assessment instruction assembly');assert.equal(assessmentAssembly.request.inputDigest,nativeDigest);assert.equal(assessmentAssembly.request.transportLane,'worker_executes');assert.ok(assessmentAssembly.request.prompt.includes('Declared role context:')); 
await writeFile(join(here,'assessment-prompt.txt'),assessmentAssembly.request.prompt,{flag:'wx'});
await writeFile(join(here,'assessment-render.json'),JSON.stringify({kind:assessmentAssembly.kind,manifest:assessmentAssembly.manifest,contextByteBound:assessment.context.maxBytes,promptBytes:Buffer.byteLength(assessmentAssembly.request.prompt),transportLane:assessmentAssembly.request.transportLane,role:roleEvidence.role,frameRefs:roleEvidence.frameRefs,responseSchemaDigest:product.sha256Canonical(assessmentAssembly.request.responseJsonSchema),separateNumericNativePromptBound:null,boundExplanation:'Existing native-work assembly applies the declared physical context bound, but contains no separate numeric prompt-byte rejection. Selector maxPromptBytes remains 131072 and is not applied to this distinct native-work lane.',prospectiveAuthenticatedChildPremise:true,admitted:false},null,2)+'\n',{flag:'wx'});
owned={...owned,execution:foldBasis,inputValue:uat,call:{runId:source.runId,implementationRef:product.governanceRef('implementation','prepare-native')}};
const wrongSource=structuredClone(uat);wrongSource.synthesis.judgment.subjectEvidenceRef='result:foreign';owned.inputValue=wrongSource;assert.equal(await libraryOwner.projectGovernanceNativeTask({graphFunction:uatGraph},wrongSource),null);
await writeFile(join(here,'checks.json'),JSON.stringify({passed:true,providerCalls:0,componentPremise:'Controlled current-call authentication and exact retained selector-role projection; real closed prefix/invocation/native producer/currentness owners and physical observed files. UAT choice is prospective controlled input, never admitted or assessed.',measurements,declaredRoleDiscriminator:{path,bodyDigest:entry.digest,sameObservedBytes:true,outputBodyOmitted:true,explicitSourceBodyPreserved:true},actualJoin:{sourceOrdinal:21754,foldOrdinal:21784,parentOrdinal:21825,nextTaskOrdinal:21845,foldEqual:true,parentEqual:true,nextTaskEqual:true,ownedAssemblyAccepted:true},assessment:{prepared:true,ownedAssemblyRendered:true,promptBytes:Buffer.byteLength(assessmentAssembly.request.prompt),nativeSourceActuallyProjected:true,producerResultRef:source.payload.resultRef,producerCCallRef:source.aggregateId,contextBytes:expanded.context.entries.filter(e=>e.state==='file').reduce((n,e)=>n+e.byteLength,0),contextEntries:assessment.context.entries.length,requiredSourcePaths:assessmentSourcePaths,allOriginalFileBodiesPreserved:true,writeRoots:assessment.writeRoots,admittedChoice:false,nativeUat:false},refusals:['changed original input','changed declared source identity','missing exact contract','foreign assessment source Result']},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,measurements,assessmentPrepared:true},null,2));
