export {
  ABI5_PACKAGE_NAME,
  ABI5_PACKAGE_VERSION,
  ABI5_PRODUCT_ID,
  PRODUCT_INSTALL_REFUSAL_CODES,
  PRODUCT_VERIFICATION_REFUSAL_CODES,
  type InstallProductRequest,
  type ProductAssetLocator,
  type ProductContributionKind,
  type ProductContributionManifest,
  type ProductContributionManifestRow,
  type ProductModulePublicationBinding,
  type ProductDeclaredDependency,
  type ProductInstallCandidate,
  type ProductInstallRefusal,
  type ProductInstallRefusalCode,
  type ProductInstallResult,
  type ProductNativeDeclarationInventoryRow,
  type ProductNativeTypedLocator,
  type ProductPublicContract,
  type ProductVerificationRefusal,
  type ProductVerificationRefusalCode,
  type ProductVerificationResult,
  type VerifiedProductArtifact,
  type VerifyProductRequest,
} from "./contracts.js";
export { modulePublicationSemanticDigest } from "./publication.js";
// Compatibility projection: shared primitives are not Product-owned.
export { canonicalJson, type JsonValue } from "../shared/canonical_json.js";
export {
  isSha256Digest,
  payloadInventoryDigest,
  sha256Bytes,
  sha256Canonical,
  sha256File,
  type PayloadInventoryRow,
  type Sha256Digest,
} from "../shared/digests.js";
export {
  ENVIRONMENT_REFUSAL_CODES,
  constructProductSet,
  constructResolvedProductLock,
  constructWorkspaceAuthorityBasis,
  constructWorkspaceBinding,
  isProductSet,
  isResolvedProductLock,
  verifiedArtifactMatchesResolvedLock,
  type EnvironmentRefusal,
  type EnvironmentRefusalCode,
  type ProductInstall,
  type ProductDependencyEdge,
  type ProductSet,
  type ResolvedProductLock,
  type ResolvedProductLockRow,
  type WorkspaceAuthorityBasis,
  type WorkspaceAuthorityBasisInput,
  type WorkspaceBinding,
  type WorkspaceBindingCandidate,
  type WorkspaceDeclaredRoots,
} from "./environment.js";
export { installProduct, installedProductContentMatches } from "./install_product.js";
export {
  admitInstalledProductInput,
  evaluateInstalledInteractionResponse,
  hasInstalledPublicResultProjection,
  loadInstalledProductSemantics,
  projectInstalledLeafSemantics,
  projectInstalledPublicResult,
  supportsInstalledPublicResultProjection,
  validateInstalledInvocationBasis,
  type InstalledLeafSemanticsProjection,
  type InstalledProductSemanticsBasis,
  type ProductInvocationSourceResultBasis,
  type ProductPublicResultProjection,
  type ProductSemanticsProvider,
} from "./semantics.js";
export {
  isProductContributionManifest,
  parseProductPublicContract,
  verifyProduct,
} from "./verify_product.js";
export {
  admitGraphFunctionCatalog,
  applyCatalogDeclaration,
  buildGraphFunctionCatalog,
  graphFunctionCatalogCanonicalSnapshot,
  lookupGraphFunction,
  lookupGraphFunctionDefinition,
  directSatisfiedDependencyRefs,
  narrowGraphFunctionCatalog,
  refreshGraphFunctionCatalog,
  type CatalogConstructionRefusal,
  type CatalogReadinessBasis,
  type CatalogReadinessRowDisposition,
  type DeclarationApplication,
  type DeclarationApplicationInput,
  type DeclarationApplicationRefusal,
  type DeclarationApplicationResult,
  type DeclarationCatalogEntry,
  type GraphFunctionCatalog,
  type ReadyGraphFunctionCatalog,
  type ReadyGraphFunctionCatalogResult,
  type GraphFunctionCatalogEntry,
  type GraphFunctionCatalogResult,
  type GraphFunctionCatalogView,
  type GraphFunctionCatalogViewResult,
} from "./catalog.js";
export {
  DIRECT_INVOKE_CAPABILITY,
  constructCapabilityGrant,
  constructDirectInvocation,
  constructInvocationAuthority,
  constructRootInvocationPolicy,
  constructStartInvocation,
  isCapabilityGrantValue,
  type CapabilityGrant,
  type CapabilityOperationId,
  type InvocationAuthority,
  type InvocationConstructionRefusal,
  type InvocationInteractionCapability,
  type InvocationPolicyBasis,
  type PublicInvocationCandidate,
  type RunInvocationVariant,
} from "./invocation.js";
export {
  isImplementationResolutionSetCandidate,
  isLeafImplementationResolutionCandidate,
  isPackagedLeafImplementationDescriptor,
  loadInstalledImplementationDescriptors,
  resolveImplementation,
  resolveImplementationSet,
  type ImplementationResolutionCandidate,
  type ImplementationResolutionRefusal,
  type ImplementationResolutionResult,
  type ImplementationResolutionSetCandidate,
  type ImplementationResolutionSetRefusal,
  type ImplementationResolutionSetResult,
  type LeafImplementationResolutionCandidate,
  type PackagedLeafImplementationDescriptor,
} from "./implementation_resolution.js";
export {
  RootOperationState,
  type InstallOperationState,
  type ResolveOperationState,
  type VerifiedOperationState,
  type WorkspaceOperationState,
} from "./root_operation_state.js";
