export {
  ABI5_PACKAGE_NAME,
  ABI5_PACKAGE_VERSION,
  ABI5_PRODUCT_ID,
  PRODUCT_INSTALL_REFUSAL_CODES,
  PRODUCT_VERIFICATION_REFUSAL_CODES,
  type InstallProductRequest,
  type ProductInstallCandidate,
  type ProductInstallRefusal,
  type ProductInstallRefusalCode,
  type ProductInstallResult,
  type ProductVerificationRefusal,
  type ProductVerificationRefusalCode,
  type ProductVerificationResult,
  type VerifiedProductArtifact,
  type VerifyProductRequest,
} from "./contracts.js";
// Compatibility projection: shared primitives are not Product-owned.
export { canonicalJson, type JsonValue } from "../shared/canonical_json.js";
export {
  isSha256Digest,
  payloadInventoryDigest,
  sha256Bytes,
  sha256Canonical,
  sha256File,
  type PayloadInventoryRow,
  type Sha256Digest,
} from "../shared/digests.js";
export {
  ENVIRONMENT_REFUSAL_CODES,
  constructProductSet,
  constructResolvedProductLock,
  constructWorkspaceAuthorityBasis,
  constructWorkspaceBinding,
  isProductSet,
  isResolvedProductLock,
  type EnvironmentRefusal,
  type EnvironmentRefusalCode,
  type ProductInstall,
  type ProductDependencyEdge,
  type ProductSet,
  type ResolvedProductLock,
  type ResolvedProductLockRow,
  type WorkspaceAuthorityBasis,
  type WorkspaceAuthorityBasisInput,
  type WorkspaceBinding,
  type WorkspaceBindingCandidate,
  type WorkspaceDeclaredRoots,
} from "./environment.js";
export { installProduct, installedProductContentMatches } from "./install_product.js";
export { verifyProduct } from "./verify_product.js";
export {
  constructCatalogAdmissionCandidate,
  constructCatalogViewCandidate,
  type AdmittedCatalog,
  type CatalogAdmissionCandidate,
  type CatalogAdmissionCandidateResult,
  type CatalogConstructionRefusal,
  type CatalogRowCandidate,
  type CatalogRowDisposition,
  type CatalogRowDispositionKind,
  type CatalogView,
  type CatalogViewCandidate,
  type CatalogViewCandidateResult,
} from "./catalog.js";
export {
  DIRECT_INVOKE_CAPABILITY,
  constructCapabilityGrant,
  constructDirectInvocation,
  constructInvocationAuthority,
  constructRootInvocationPolicy,
  constructStartInvocation,
  type CapabilityGrant,
  type InvocationAuthority,
  type InvocationConstructionRefusal,
  type InvocationPolicyBasis,
  type PublicInvocationCandidate,
  type RunInvocationVariant,
} from "./invocation.js";
export {
  isImplementationResolutionSetCandidate,
  isLeafImplementationResolutionCandidate,
  isPackagedLeafImplementationDescriptor,
  loadInstalledImplementationDescriptors,
  resolveImplementation,
  resolveImplementationSet,
  type ImplementationResolutionCandidate,
  type ImplementationResolutionRefusal,
  type ImplementationResolutionResult,
  type ImplementationResolutionSetCandidate,
  type ImplementationResolutionSetRefusal,
  type ImplementationResolutionSetResult,
  type LeafImplementationResolutionCandidate,
  type PackagedLeafImplementationDescriptor,
} from "./implementation_resolution.js";
export {
  RootOperationState,
  type CatalogOperationState,
  type CatalogViewOperationState,
  type InstallOperationState,
  type VerifiedOperationState,
  type WorkspaceOperationState,
} from "./root_operation_state.js";
