import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const O=import.meta.dirname,G=path.dirname(O),C=path.join(G,'final-candidate-construction-02'),N=path.join(G,'final-native-continuation-04');const read=async p=>JSON.parse(await fs.readFile(p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const core=await read(path.join(C,'selected-core.json')),P=core.packageRoot,cf=await read(path.join(C,'freeze.json')),nf=await read(path.join(N,'freeze.json'));const sources=[],inputs=[],checks=[],edges=[];
async function module(rel){const p=path.join(P,'build/code/src',rel),b=await fs.readFile(p),r=cf.records.find(r=>r.path===path.relative(C,p));assert.ok(r);assert.equal(sha(b),r.sha256);assert.equal(b.length,r.bytes);sources.push({path:p,bytes:b.length,sha256:sha(b)});return import(pathToFileURL(p).href);}
async function acquire(name,parse=true){const p=path.join(N,name),b=await fs.readFile(p),r=nf.records.find(r=>r.path===name);assert.ok(r);assert.equal(b.length,r.bytes);assert.equal(sha(b),r.sha256);inputs.push({path:p,bytes:b.length,sha256:sha(b)});return parse?JSON.parse(b):b;}
const product=await module('product/index.js'),gtl=await module('gtl/index.js'),store=await module('abg/event_store.js'),prefixOwner=await module('abg/event_prefix.js'),replayOwner=await module('abg/replay.js'),basisOwner=await module('abg/invocation_execution_truth.js'),ccOwner=await module('abg/c_call.js'),routeOwner=await module('abg/traversal_route.js');
function check(name,fn,value){fn();checks.push({name,status:'passed',value});}
function one(events,kind){const rows=events.filter(e=>e.kind===kind);assert.equal(rows.length,1,kind+' unique');return rows[0];}
function coord(ref,digest){return{ref,digest};}
let phase='historical owner decode';
try{
 const bytes=await acquire('failure-native-prefix.jsonl',false),handoff=await acquire('final-handoff.json');
 const events=store.validateHistoricalEvents(bytes,handoff.prefix.storeIdentity.eventContractDigest);const full=prefixOwner.selectValidatedRuntimeEventPrefix(events);
 check('historical bytes validate through existing owner',()=>{assert.equal(sha(bytes),'90a608b3aa811c922e305a3c930d044e23d619cb1261f6cb7a0ecde748eb6cbc');assert.equal(bytes.length,handoff.prefix.prefixLength);assert.equal('sha256:'+sha(bytes),handoff.prefix.prefixDigest);}, {events:events.length,bytes:bytes.length,profile:handoff.prefix.storeIdentity.eventContractDigest});
 const rootRaw=await acquire('continue-hello-root-stdout.json'),root=rootRaw.receipt.ownerOutput.value,t=root.terminalResult,transport=await acquire('continue-hello-root.jsonl'),publicCall=transport.invocation.invocation,request=publicCall.request;
 const ctx=replayOwner.projectRunReplayContext(full,root.run.ref);assert.ok(ctx);const replay=ctx.replay,identity=replayOwner.projectRunIdentityAtPrefix(full,root.run.ref);assert.ok(identity);
 check('pure historical owner replay equals native result',()=>{assert.equal(replay.runtimeStatus,'closed');assert.equal(replay.runId,root.run.ref);assert.deepEqual(coord(replay.replayRef,replay.replayDigest),root.replay);assert.deepEqual(identity.run,root.run);assert.deepEqual(identity.executionBasis,t.producer.executionBasis);},{run:identity.run,nativeRun:identity.nativeRun,replay:coord(replay.replayRef,replay.replayDigest),status:replay.runtimeStatus});
 const E={};for(const kind of ['public_operation_admitted','invocation_admitted','implementation_admitted','basis_admitted','run_segment_opened','graph_call_opened','frame_opened','traversal_cursor_entered','c_call_opened','c_call_fibre_selected','c_call_evidenced','c_call_result_admitted','c_call_judged','traversal_route_admitted','terminal_reached','frame_closed','graph_call_closed','run_closed'])E[kind]=one(events,kind);
 const pub=E.public_operation_admitted,inv=E.invocation_admitted,impl=E.implementation_admitted,b=E.basis_admitted,run=E.run_segment_opened,gc=E.graph_call_opened,frame=E.frame_opened,cursor=E.traversal_cursor_entered,cc=E.c_call_opened,fibre=E.c_call_fibre_selected,evidence=E.c_call_evidenced,result=E.c_call_result_admitted,judgment=E.c_call_judged,route=E.traversal_route_admitted,terminal=E.terminal_reached,fc=E.frame_closed,gcc=E.graph_call_closed,rc=E.run_closed;
 phase='original input and public/native invocation joins';const expectedInput=gtl.constructHelloWorldInput('prospective 5.0.0-rc.1 qualification');
 check('original input and oracle relation',()=>{assert.deepEqual(request.input.value,expectedInput);assert.equal(product.sha256Canonical(expectedInput),request.input.valueDigest);assert.deepEqual(b.payload.rawInputValue,expectedInput);assert.equal(b.payload.rawInputDigest,request.input.valueDigest);assert.equal(inv.payload.rawInputDigest,request.input.valueDigest);assert.equal(inv.payload.inputContractRef,request.input.contract.ref);assert.equal(inv.payload.inputContractDigest,request.input.contract.digest);assert.deepEqual(t.value,{kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello '+expectedInput.subject});},{input:expectedInput,inputContract:request.input.contract,inputValueRef:request.input.valueRef,inputDigest:request.input.valueDigest,output:t.value});
 check('outer Public request to native invocation',()=>{assert.equal(publicCall.invocationRef,rootRaw.receipt.invocationRef);assert.equal(inv.payload.publicRequestInvocationRef,publicCall.invocationRef);assert.equal(inv.payload.publicRequestAdmissionRef,publicCall.requestRef);assert.equal(inv.payload.publicRequestDigest,publicCall.requestDigest);assert.equal(product.sha256Canonical(request),publicCall.requestDigest);assert.equal(pub.payload.invocationRef,inv.payload.invocationRef);assert.equal(pub.payload.invocationDigest,inv.payload.invocationDigest);assert.equal(inv.payload.invocationAdmissionRef,t.producer.invocationAdmissionRef);assert.deepEqual(rootRaw.receipt.resources.invocationAdmission,coord(inv.payload.invocationAdmissionRef,inv.payload.invocationAdmissionDigest));},{publicInvocation:publicCall.invocationRef,nativeInvocation:inv.payload.invocationRef,requestRef:publicCall.requestRef,requestDigest:publicCall.requestDigest,admission:rootRaw.receipt.resources.invocationAdmission});
 check('Program GraphFunction catalog and terminal declaration',()=>{assert.deepEqual(request.program,t.producer.program);assert.equal(request.target.handle,t.producer.graphFunction.ref);for(const p of [inv.payload,b.payload,cursor.payload]){assert.equal(p.programRef,t.producer.program.ref);assert.equal(p.programDigest,t.producer.program.digest);assert.equal(p.graphFunctionRef,t.producer.graphFunction.ref);assert.equal(p.graphFunctionDigest,t.producer.graphFunction.digest);}assert.equal(inv.payload.outputContractRef,t.contract.ref);assert.equal(inv.payload.outputContractDigest,t.contract.digest);assert.equal(b.payload.resultContractRef,t.contract.ref);assert.equal(request.catalogView.ref,inv.payload.catalogViewId);assert.equal(request.catalogView.digest,inv.payload.catalogViewDigest);assert.equal(b.payload.catalogViewId,inv.payload.catalogViewId);assert.equal(b.payload.catalogBasisDigest,inv.payload.catalogBasisDigest);},{program:t.producer.program,graphFunction:t.producer.graphFunction,terminalContract:t.contract,catalog:coord(inv.payload.catalogBasisRef,inv.payload.catalogBasisDigest),catalogView:request.catalogView,outputContractOwner:inv.payload.outputContractOwner});
 phase='execution basis and admitted CCall owner projections';const basis=basisOwner.projectExactExecutionBasisAtPrefix(full,t.producer.executionBasis.ref);assert.ok(basis);
 check('authenticated execution basis joins native scope',()=>{assert.equal(basis.basisRef,t.producer.executionBasis.ref);assert.equal(basis.basisDigest,t.producer.executionBasis.digest);assert.equal(basis.invocationAdmissionRef,t.producer.invocationAdmissionRef);assert.equal(basis.invocationRef,inv.payload.invocationRef);assert.equal(basis.implementationSetRef,impl.payload.implementationSetRef);assert.equal(basis.implementationSetDigest,impl.payload.implementationSetDigest);for(const e of [run,gc,frame,cursor,cc,fibre,evidence,result,judgment,route,terminal,fc,gcc,rc]){assert.equal(e.basisId,basis.basisRef);if(e.runId!==undefined)assert.equal(e.runId,root.run.ref);if(e.graphCallId!==undefined)assert.equal(e.graphCallId,root.graphCall.ref);}assert.equal(gc.aggregateId,root.graphCall.ref);assert.equal(gc.payloadDigest,root.graphCall.digest);assert.equal(frame.payload.admittedInputRef,basis.rawInputAdmissionRef);assert.equal(frame.payload.admittedInputDigest,basis.rawInputDigest);assert.equal(cursor.payload.inputRef,basis.rawInputAdmissionRef);assert.equal(cursor.payload.inputDigest,basis.rawInputDigest);},{basis:t.producer.executionBasis,run:root.run,graphCall:root.graphCall,frame:frame.aggregateId,admittedInput:coord(basis.rawInputAdmissionRef,basis.rawInputDigest),implementationSet:coord(basis.implementationSetRef,basis.implementationSetDigest)});
 const o=cc.payload,f=fibre.payload;
 const outcome=ccOwner.projectAdmittedCCallStateAtPrefix(ctx.prefix,{...o,...f,kind:'c_call',schemaVersion:'5.0.0',runId:cc.runId,childGraphFunctionRef:o.childGraphFunctionRef??null,failureContractRef:o.failureContractRef??'',openedEventRef:cc.eventId,fibreSelectedEventRef:fibre.eventId},{...result.payload,kind:'admitted_c_call_result',schemaVersion:'5.0.0',disposition:'admitted',admissionEventRef:result.eventId},{...judgment.payload,kind:'admitted_c_call_judgment',schemaVersion:'5.0.0',disposition:'admitted',admissionEventRef:judgment.eventId});assert.ok(outcome);
 check('CCall owner authenticates evidence Result and judgment',()=>{assert.equal(outcome.cCall.cCallRef,t.producer.cCallRef);assert.equal(f.implementationSetRef,basis.implementationSetRef);assert.equal(f.regime,'F_D');assert.equal(evidence.payload.implementationRef,f.implementationRef);assert.equal(evidence.payload.inputDigest,request.input.valueDigest);assert.equal(evidence.payload.outputDigest,t.valueDigest);assert.equal(evidence.payload.contractRef,basis.evidenceContractRef);assert.ok(result.payload.evidenceRefs.includes(evidence.payload.evidenceRef));assert.equal(outcome.result.resultClass,'success');assert.equal(result.eventId,t.producer.resultAdmissionEventRef);assert.equal(outcome.result.resultRef,t.result.ref);assert.equal(outcome.result.resultDigest,t.result.digest);assert.deepEqual(outcome.result.value,t.value);assert.equal(outcome.result.valueDigest,t.valueDigest);assert.equal(outcome.result.contractRef,basis.resultContractRef);assert.equal(outcome.judgment.judgment,'advance');assert.equal(outcome.judgment.judgmentRef,t.producer.judgmentRef);assert.equal(outcome.judgment.resultRef,t.result.ref);assert.equal(outcome.judgment.resultDigest,t.result.digest);assert.equal(outcome.judgment.contractRef,basis.judgmentContractRef);assert.equal(judgment.eventId,t.producer.judgmentAdmissionEventRef);},{cCall:t.producer.cCallRef,regime:f.regime,implementation:f.implementationRef,evidence:coord(evidence.payload.evidenceRef,evidence.payload.evidenceDigest),result:t.result,judgment:coord(outcome.judgment.judgmentRef,outcome.judgment.judgmentDigest),resultEvent:result.eventId,judgmentEvent:judgment.eventId});
 const routeProjection=routeOwner.projectHistoricalTraversalRouteAtPrefix(ctx.prefix,route.eventId,full);assert.ok(routeProjection);
 check('historical route owner joins terminal producer',()=>{assert.equal(routeProjection.routeKind,'terminal');assert.deepEqual(coord(routeProjection.routeRef,routeProjection.routeDigest),t.producer.terminalRoute);assert.equal(routeProjection.cCallRef,t.producer.cCallRef);assert.equal(routeProjection.judgmentRef,t.producer.judgmentRef);assert.equal(routeProjection.contractRef,basis.transitionContractRef);assert.equal(routeProjection.declarationRef,basis.graphRef);assert.equal(routeProjection.declarationDigest,basis.graphDigest);assert.equal(routeProjection.sourceCursorRef,o.cursorRef);assert.equal(routeProjection.sourceCursorDigest,o.cursorDigest);},{route:t.producer.terminalRoute,routeEvent:route.eventId,judgment:t.producer.judgmentRef,sourceCursor:coord(o.cursorRef,o.cursorDigest),declaration:coord(basis.graphRef,basis.graphDigest)});
 phase='terminal and closure causation';const {closureRef,closureDigest,...closureBody}=terminal.payload;
 check('terminal closure digest and frame GraphCall Run closure',()=>{assert.equal(product.sha256Canonical(closureBody),closureDigest);assert.equal(closureRef,'closure://abiogenesis/'+closureDigest.slice(7));assert.equal(closureBody.cCallRef,t.producer.cCallRef);assert.equal(closureBody.resultRef,t.result.ref);assert.equal(closureBody.judgmentRef,t.producer.judgmentRef);assert.equal(closureBody.routeRef,t.producer.terminalRoute.ref);assert.equal(closureBody.closureContractRef,basis.closureContractRef);assert.equal(closureBody.closureContractDigest,basis.closureContractDigest);assert.equal(closureBody.terminalKind,'completed');assert.equal(fc.payload.terminalReachedEventRef,terminal.eventId);assert.equal(gcc.payload.frameClosedEventRef,fc.eventId);assert.equal(rc.payload.graphCallClosedEventRef,gcc.eventId);for(const e of [fc,gcc,rc])assert.equal(e.payload.closureContractRef,basis.closureContractRef);},{closure:coord(closureRef,closureDigest),terminalEvent:terminal.eventId,frameClosedEvent:fc.eventId,graphCallClosedEvent:gcc.eventId,runClosedEvent:rc.eventId});
 const chain=[pub,inv,impl,b,run,gc,frame,cursor,cc,fibre,evidence,result,judgment,route,terminal,fc,gcc,rc];for(let i=1;i<chain.length;i++){const from=chain[i-1],to=chain[i];assert.ok(to.causationEventRefs.includes(from.eventId),from.kind+' -> '+to.kind);assert.ok(from.admissionOrdinal<to.admissionOrdinal);edges.push({from:{kind:from.kind,eventRef:from.eventId,line:from.admissionOrdinal},to:{kind:to.kind,eventRef:to.eventId,line:to.admissionOrdinal},relation:'to.causationEventRefs includes from.eventId',actual:to.causationEventRefs,evidence:path.join(N,'failure-native-prefix.jsonl')+'#L'+to.admissionOrdinal});}
 check('complete explicit causal chain',()=>assert.equal(edges.length,17),{edges:edges.length,first:chain[0].eventId,last:chain.at(-1).eventId});
 const output={status:'passed',claim:'retained original S01 causal execution and closure, using pure historical owner derivation only',sources,inputs,checks,edges,history:{bytes:bytes.length,sha256:sha(bytes),events:events.length},ownerReplay:{runId:replay.runId,status:replay.runtimeStatus,replay:coord(replay.replayRef,replay.replayDigest),identity},noNativeResourceOpen:true};await fs.writeFile(path.join(O,'causal-checks.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({status:'passed',checks:checks.length,causalEdges:edges.length,ownerReplay:output.ownerReplay,history:output.history},null,2));
}catch(e){await fs.writeFile(path.join(O,'causal-checks-failure.json'),JSON.stringify({status:'failed probe requiring classification',phase,error:{name:e.name,message:e.message,stack:e.stack},completedChecks:checks,completedEdges:edges,sources,inputs},null,2)+'\n');throw e;}
