import fs from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const O=import.meta.dirname,G=path.dirname(O),C=path.join(G,'final-candidate-construction-02'),N=path.join(G,'final-native-continuation-04');
const read=async p=>JSON.parse(await fs.readFile(p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const core=await read(path.join(C,'selected-core.json')),P=core.packageRoot,manifest=await read(path.join(P,'package.json')),freeze=await read(path.join(C,'freeze.json'));
const sources=[];async function loadExport(name){const p=path.resolve(P,manifest.exports['./'+name].import);assert.ok(p.startsWith(C+'/'));const b=await fs.readFile(p),row=freeze.records.find(r=>r.path===path.relative(C,p));assert.ok(row);assert.equal(row.sha256,sha(b));sources.push({path:p,bytes:b.length,sha256:sha(b)});return import(pathToFileURL(p).href);}
const abg=await loadExport('abg'),product=await loadExport('product'),gtl=await loadExport('gtl');const v=createRequire(path.join(P,'package.json'))('valibot');
const schemaPath=path.join(P,'build/code/src/abg/terminal_result_contracts.js');const terminal=await import(pathToFileURL(schemaPath).href);const sb=await fs.readFile(schemaPath);assert.equal(freeze.records.find(r=>r.path===path.relative(C,schemaPath)).sha256,sha(sb));sources.push({path:schemaPath,bytes:sb.length,sha256:sha(sb)});
assert.equal(typeof abg.isAbgTypedTerminalResult,'function');assert.ok(terminal.ABG_TYPED_TERMINAL_RESULT_SCHEMA);
const names=['continue-hello-root-stdout.json','continue-hello-root-run_result-stdout.json','continue-hello-root-run_replay-stdout.json'];const raw=await Promise.all(names.map(n=>read(path.join(N,n))));const values=raw.map(r=>r.receipt.ownerOutput.value);const [root,result,replay]=values;const carriers=[root.terminalResult,result.projection.terminalResult,replay.projection.terminalResult];
const expected={kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello prospective 5.0.0-rc.1 qualification'};
const checks=[];function check(name,fn,value){fn();checks.push({name,status:'passed',value});}
for(let i=0;i<raw.length;i++){
 check(names[i]+':owner receipt',()=>{assert.equal(raw[i].kind,'installed_definition_call_transport_result');assert.equal(raw[i].receipt.exitCode,0);assert.equal(raw[i].receipt.failure,null);assert.equal(raw[i].receipt.ownerOutput.outcomeKind,'result');},raw[i].receipt.definitionKey);
 check(names[i]+':strict terminal',()=>{assert.equal(abg.isAbgTypedTerminalResult(carriers[i]),true);v.parse(terminal.ABG_TYPED_TERMINAL_RESULT_SCHEMA,carriers[i]);},Object.keys(carriers[i]));
 check(names[i]+':original value/digest',()=>{assert.deepEqual(carriers[i].value,expected);assert.equal(product.sha256Canonical(carriers[i].value),carriers[i].valueDigest);assert.equal(carriers[i].valueKind,expected.kind);},carriers[i].valueDigest);
}
check('complete three-terminal equality',()=>{assert.deepEqual(carriers[0],carriers[1]);assert.deepEqual(carriers[1],carriers[2]);},carriers[0]);
check('root completed and original Run',()=>{assert.equal(root.disposition,'completed');assert.equal(root.stop,null);assert.equal(root.run.ref,'run://abiogenesis/ad1178eacb257eb403f511d54751b84c95f4c226a47318a82269bbc96eeb0c61');assert.equal(carriers[0].producer.runRef,root.run.ref);assert.equal(carriers[0].producer.graphCallRef,root.graphCall.ref);assert.deepEqual(carriers[0].result,root.result);}, {run:root.run,graphCall:root.graphCall,result:root.result});
for(const [label,output]of [['result',result],['replay',replay]])check(label+':source, subject, replay coordinate',()=>{assert.deepEqual(output.source,root.run);assert.deepEqual(output.projection.subject,root.run);assert.deepEqual(output.projection.replay,root.replay);assert.deepEqual(output.projectionBasis,carriers[0].projectionBasis);assert.deepEqual(Object.keys(output.source).sort(),['digest','ref']);}, {source:output.source,projectionBasis:output.projectionBasis,replay:output.projection.replay});
check('result and closed replay',()=>{assert.deepEqual(result.projection.result,root.result);assert.equal(replay.projection.status,'closed');}, {result:result.projection.result,replayStatus:replay.projection.status});
check('producer is strict current field',()=>{assert.equal(Object.hasOwn(carriers[0],'provenance'),false);assert.equal(abg.isAbgTypedTerminalResult({...carriers[0],provenance:carriers[0].producer}),false);},'producer');
const transport=await read(path.join(N,'continue-hello-root.jsonl'));const expectedInput=gtl.constructHelloWorldInput('prospective 5.0.0-rc.1 qualification');
await fs.writeFile(path.join(O,'terminal-checks.json'),JSON.stringify({status:'passed',sources,checks,expectedInput,originalTransportShape:{top:Object.keys(transport),invocation:Object.keys(transport.invocation),request:transport.invocation.invocation.request},projectionShapes:{result:Object.keys(result.projection),replay:Object.keys(replay.projection)}},null,2)+'\n');
console.log(JSON.stringify({status:'passed',checkCount:checks.length,terminalCount:3,valueDigest:carriers[0].valueDigest,run:root.run,expectedInput,transportInvocationKeys:Object.keys(transport.invocation),request:transport.invocation.invocation.request,projectionShapes:{result:Object.keys(result.projection),replay:Object.keys(replay.projection)}},null,2));
