import assert from 'node:assert/strict';
import test from 'node:test';
import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile,stat} from 'node:fs/promises';
import {join,basename} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {constructInstalledStartCall,constructInstalledRunReadCall,runInstalledCliRequest} from '../support/registered-graph-selection.mjs';
import {publicOperationBasis} from '../support/root-installed-environment.mjs';
import {observePublicSelection,afterNativeFsync} from '../support/t287-selected-action-host.mjs';
import {ref,contract,fixtureInput} from '../fixtures/t287-selected-action-product/index.mjs';
const proof=process.env.ABI5_SELECTED_ACTION_EVIDENCE_ROOT;assert.ok(proof);
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const save=async(dir,name,value)=>{await mkdir(dir,{recursive:true});await writeFile(join(dir,name),JSON.stringify(value,null,2)+'\n');};
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
const digest=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const coord=b=>({ref:b.basisRef,digest:b.basisDigest});
const nativeScopeCoordinate=o=>({ref:o.scope.runId,digest:o.scope.runDigest});
function runIdentity(c,opened){const identity=c.replay.projectRunIdentityAtPrefix(prefix(c),opened.scope.runId);assert.ok(identity,'exact shared Run identity owner');assert.deepEqual(identity.nativeRun,nativeScopeCoordinate(opened));assert.equal(identity.executionBasis.ref,opened.scope.executionBasisRef);return identity;}
const resource=c=>({kind:'reopen_abg_event_resource',schemaVersion:'5.0.0',closeHandoff:c.handoff,handoffDigest:c.product.sha256Canonical(c.handoff)});
async function context(e,handoff,runtimeTmp){
 const load=p=>import(pathToFileURL(join(e.installedRoot,`build/code/src/${p}.js`)).href);
 const product=await load('product/index'),abg=await load('abg/index');
 return {e,handoff,runtimeTmp,load,product,abg,eventOwner:await load('abg/event_store'),owner:await load('abg/construction_continuation'),publicApi:await load('public/index'),scopeOwner:await load('abg/open_call'),truth:await load('abg/invocation_execution_truth'),replay:await load('abg/replay')};
}
const rows=c=>c.eventOwner.readRuntimeEventsAtDurablePrefix(c.handoff.prefix);
const prefix=c=>c.abg.selectValidatedRuntimeEventPrefix(freeze(rows(c)));
const occurrences=(c,run)=>c.owner.projectSelectedActionContinuations(prefix(c),run);
async function runHost(dir,runtimeTmp,payload=null){
 await mkdir(dir,{recursive:true});const payloadPath=join(dir,'host-payload.json');if(payload)await save(dir,'host-payload.json',payload);
 const started=performance.now(),host=spawn(process.execPath,[new URL('../support/t287-selected-action-host.mjs',import.meta.url).pathname],{env:{...process.env,TMPDIR:runtimeTmp,ABI5_SELECTED_ACTION_EVIDENCE_ROOT:dir,...(payload?{ABI5_SELECTED_ACTION_PUBLIC_START:payloadPath}:{})}});
 let stdout='',stderr='';host.stdout.on('data',b=>stdout+=b);host.stderr.on('data',b=>stderr+=b);
 const exit=await new Promise((resolve,reject)=>{host.once('error',reject);host.once('exit',(code,signal)=>resolve({code,signal,pid:host.pid}));});
 await save(dir,'host-termination.json',{...exit,stdout,stderr,wallMs:performance.now()-started});const observerFailure=await read(join(dir,'observer-failure.json')).catch(error=>{if(error.code==='ENOENT')return null;throw error;});assert.equal(observerFailure,null,JSON.stringify(observerFailure));assert.equal(exit.signal,'SIGKILL',JSON.stringify({exit,stdout,stderr}));
}
async function recover(c,dir,initial=false){
 const origin=await read(join(dir,initial?'initial-origin.json':'recovery-origin.json'));
 const eventLogPath=initial?origin.initialOrigin.newResourceRequest.eventLogPath:fileURLToPath(origin.lastCloseHandoff.prefix.eventLogRef);
 const bytes=await readFile(eventLogPath);assert.deepEqual(bytes,await readFile(join(dir,'interrupted-prefix.jsonl')));
 const physical=initial?origin.initialOrigin:origin.lastCloseHandoff.reopenAuthority;
 const lockPath=join(c.runtimeTmp,'abiogenesis-event-store-locks-v5',`${physical.device}-${physical.inode}.lock`),lock=await stat(lockPath),lockBytes=await readFile(lockPath);
 const selection={...origin,expectedCurrent:{byteLength:bytes.length,digest:digest(bytes)},abandonedLock:{path:lockPath,device:lock.dev,inode:lock.ino,bytesBase64:lockBytes.toString('base64'),digest:digest(lockBytes)}};
 await save(dir,'recovery-selection.json',selection);const result=c.eventOwner.recoverInterruptedEventStore(selection);await save(dir,'recovery.json',result);assert.equal(result.kind,'recovered',JSON.stringify(result));c.handoff=result.closeHandoff;await save(proof,'latest-handoff.json',c.handoff);
}
async function cli(c,dir,name,call){
 await save(dir,`${name}-call.json`,call);const outcome=await runInstalledCliRequest({scratch:dir,installedRoot:c.e.installedRoot,identity:name,acquisition:{kind:'reopen',closeHandoff:c.handoff},call,expectedExitCode:null,environment:{TMPDIR:c.runtimeTmp}});await save(dir,`${name}-receipt.json`,outcome);
 const receipt=outcome.output.receipt;assert.ok(receipt,JSON.stringify(outcome));if(receipt.resources?.eventResource?.closeHandoff)c.handoff=receipt.resources.eventResource.closeHandoff;await save(proof,'latest-handoff.json',c.handoff);assert.equal(receipt.failure,null,JSON.stringify(receipt));return {receipt,wallMs:outcome.wallMs};
}
async function acquisition(c,e,binding){
 const a=await c.load('product/admission_authority');const env=a.admitCapabilityEnvironment(c.product.admissionEnvironmentSelection(c.handoff.prefix,{ref:binding.bindingId,digest:binding.bindingDigest}));assert.equal(env.kind,'exact_prefix_workspace_environment',JSON.stringify(env));
 const installs=env.productInstalls.map(({kind,disposition,admissionEventRef,...body})=>({kind:'product_install_candidate',disposition:'materialized',...body}));
 for(const i of installs)assert.deepEqual(i,e.catalog.readinessBasis.installedProducts.find(p=>p.installId===i.installId),'exact admitted Install preimage');
 const {kind,admissionEventRef,...bindingBody}=env.workspaceBinding,bindingCandidate={kind:'workspace_binding_candidate',...bindingBody};
 const catalog=c.product.admitGraphFunctionCatalog({workspaceBinding:bindingCandidate,resolvedLock:env.resolvedProductLock,verifiedProducts:e.catalog.readinessBasis.verifiedProducts,installedProducts:installs,publications:e.catalog.readinessBasis.publications});assert.equal(catalog.kind,'graph_function_catalog',JSON.stringify(catalog));
 const catalogView=c.product.narrowGraphFunctionCatalog(catalog,e.catalogView.allowlist);assert.equal(catalogView.kind,'graph_function_catalog_view');
 // Only stable resource/publication identities are conserved; work attribution is produced afresh.
 return {scratch:e.scratch,installedRoot:e.installedRoot,installedRoots:e.installedRoots,artifactPaths:e.artifactPaths,verified:e.verified,workspaceAuthority:env.workspaceAuthorityBasis,workspaceBinding:env.workspaceBinding,admittedInstalls:env.productInstalls,productSet:env.productSet,lock:env.resolvedProductLock,catalog,catalogView};
}
async function prepareStart(c,e,identity,inputFactoryOrValue,dir){
 const started=performance.now(),eventResource=resource(c),artifactTruth=c.abg.projectExactPrefixArtifactTruth(c.handoff.prefix);
 const made=await constructInstalledStartCall({environment:{...e,product:c.product,abg:c.abg,artifactTruth},publicApi:c.publicApi,eventResource,identity,programRef:ref('program','root'),rootMode:'supervised',declaredStartRef:ref('start','root'),...(typeof inputFactoryOrValue==='function'?{inputFactory:inputFactoryOrValue}:{input:inputFactoryOrValue})});
 const input=made.call.invocation.request.input.value;
 const prepared=await c.product.ProductRunInvocationPort.prepare({memberKey:'start',invocation:made.call.invocation,resources:made.call.resources,admittedInstalls:e.admittedInstalls,workspaceBinding:e.workspaceBinding,verifyInstallAdmission:i=>c.abg.hasAdmittedProductInstall(artifactTruth,i),transportResourceAssertion:eventResource});
 assert.equal(prepared.kind,'prepared_product_run_invocation',JSON.stringify(prepared));const basis=await c.load('abg/execution_basis');assert.equal(basis.hasExactInvocationObservationBasis(prepared.admittedInput,e.workspaceBinding.bindingId,e.workspaceBinding.bindingDigest,prepared.resolution.program),true);
 assert.deepEqual(input.workspaceBinding,{workspaceBindingId:e.workspaceBinding.bindingId,workspaceBindingDigest:e.workspaceBinding.bindingDigest});assert.deepEqual(input.actionCatalog,prepared.resolution.program.actionCatalog);assert.deepEqual(input.constructionPolicy,prepared.resolution.program.constructionComposition.closurePolicy);
 assert.deepEqual(made.workAuthority,prepared.authority);assert.deepEqual(made.capabilityBasis.policy,prepared.policy);assert.deepEqual(made.capabilityBasis.capabilityGrants,prepared.grants);
 assert.equal(made.call.invocation.request.rootMode,'supervised');assert.equal(made.call.invocation.request.scope,'program');assert.equal(made.call.invocation.request.target.kind,'declared_start');assert.equal(made.call.invocation.request.target.start.ref,ref('start','root'));assert.equal(made.call.invocation.request.target.start.digest,c.product.sha256Canonical(prepared.resolution.resolvedProgramStart.start));assert.equal(made.call.invocation.request.until,'converged');
 const environment={...e,input,inputDigest:c.product.sha256Canonical(input),policy:prepared.policy,actorRef:prepared.authority.actorRef,invocationAuthority:prepared.authority,publication:prepared.resolution.programPublication};
 assert.deepEqual(made.call.invocation.invocationAuthority.slots.actor.attribution,{ref:environment.invocationAuthority.authorityRef,digest:environment.invocationAuthority.authorityDigest});
 await save(dir,'prospective-start.json',{status:'passed',wallMs:performance.now()-started,call:made.call,workAuthority:prepared.authority,policy:prepared.policy,grants:prepared.grants,input,resolution:prepared.resolution.resolution,observationPredicate:true,exactCandidatePreimages:true});
 return {environment,call:made.call,closeHandoff:c.handoff};
}
async function startPending(c,e,dir,identity,input,selectionCount){
 const payload={...await prepareStart(c,e,identity,input,dir),selectionCount};await runHost(dir,c.runtimeTmp,payload);await recover(c,dir);
 const current=await read(join(dir,'environment.json')),opened=await read(join(dir,'opened.json')),pending=occurrences(c,opened.scope.runId).at(-1);assert.equal(pending.status,'open');assert.equal(current.invocationAdmission.publicRequestInvocationRef,payload.call.invocation.invocationRef);assert.equal(current.invocationAdmission.authorityDigest,current.invocationAuthority.authorityDigest);assert.equal(current.invocationAdmission.rawInputDigest,current.inputDigest);
 return {environment:current,opened,pending,payload};
}
async function witnessCall(c,e,member,request,identity,dir){
 if(member==='run-stopped'){const run=c.replay.projectRunIdentityAtPrefix(prefix(c),request.subject.ref);assert.ok(run);assert.deepEqual(request.subject,run.run);assert.deepEqual(request.context.run,run.run);assert.deepEqual(request.context.basis,run.executionBasis);assert.deepEqual(request.evidence,[run.run]);}
 const wc=await c.load('abg/witness_operation_contracts'),ao=await c.load('product/admission_authority'),eo=await c.load('product/environment');const packet=wc.WITNESS_OPERATION_CONTRACTS.admit[member],definition=c.publicApi.PUBLIC_FUNCTION_DEFINITION_FAMILY.definitions.find(d=>d.definitionKey.operationId===packet.definitionKey.operationId&&d.definitionKey.memberKey===member);
 const binding={ref:e.workspaceBinding.bindingId,digest:e.workspaceBinding.bindingDigest},env=ao.admitCapabilityEnvironment(c.product.admissionEnvironmentSelection(c.handoff.prefix,binding));assert.equal(env.kind,'exact_prefix_workspace_environment');
 const actorRef=env.workspaceAuthorityBasis.authorizedActorRef,coordinate=(ref,value)=>({ref,digest:c.product.sha256Canonical(value??{ref})});
 const slots=Object.fromEntries(['workspace_binding','product_set','dependency_lock','catalog_scope','execution_program','graph_function','input_contract','session_policy','capability_grants','actor','transport_steering','verification_references','execution_basis'].map(k=>[k,null]));
 Object.assign(slots,{workspace_binding:binding,product_set:env.productInstalls.map(eo.productInstallCoordinate),dependency_lock:{ref:env.resolvedProductLock.lockId,digest:env.resolvedProductLock.lockDigest},actor:{actor:coordinate(actorRef),attribution:coordinate('attribution://selected-action/fixture')},execution_basis:member==='run-stopped'?request.context.basis:null});
 const resources={kind:member==='reprice'?'witness_reprice_resource_assertion':'witness_run_stopped_resource_assertion',schemaVersion:'5.0.0',eventResource:resource(c)};
 const ownerRequest={artifactPath:e.artifactPaths[0],artifactRef:basename(e.artifactPaths[0]),expectedArtifactDigest:e.verified.artifactDigest,expectedProductContentDigest:e.verified.productContentDigest,expectedManifestDigest:e.verified.manifestDigest,expectedProductId:e.verified.productId,expectedPackageName:'@abiogenesis/typescript-tenant',expectedPackageVersion:'5.0.0-rc.1'};
 const basis={kind:'admission_capability_data',schemaVersion:'5.0.0',definition:{definitionKey:definition.definitionKey,definitionRef:definition.definitionRef,definitionDigest:definition.definitionDigest,owner:{ref:packet.owner.authorityRef,digest:packet.owner.authorityDigest}},ownerArtifact:{request:ownerRequest,verified:e.verified},request,resourceScope:{resourcesDigest:c.product.sha256Canonical(resources),authoritySlots:c.product.admissionAuthoritySlots(slots)},boundEnvironment:c.product.admissionEnvironmentSelection(c.handoff.prefix,binding)};
 const authorityValue={actorRef,authorityMode:'trusted_developer'},approvalValue={decision:'allow',actorRef,definitionRef:definition.definitionRef,definitionDigest:definition.definitionDigest,requestDigest:c.product.sha256Canonical(request),scopeDigest:c.product.admissionAuthorityScope(basis).digest};
 const authority={kind:'resolved_admission_authority',schemaVersion:'5.0.0',actorRef,authorityMode:'trusted_developer',authority:{...coordinate('authority://selected-action/fixture',authorityValue),value:authorityValue},approval:{...coordinate(`approval://selected-action/${identity}`,approvalValue),value:approvalValue}};
 const grants=await Promise.all(definition.capabilityRefs.map(cap=>c.product.constructCapabilityGrant(authority,actorRef,packet.definitionKey.operationId,cap,{kind:'admission_capability_grant_construction_basis',fixedPacket:packet,data:basis})));slots.capability_grants={requiredCapabilityRefs:definition.capabilityRefs,grants:grants.map(g=>({ref:g.grantRef,digest:g.grantDigest}))};
 const call=c.publicApi.constructInstalledPublicDefinitionCall({product:c.product,installedPublic:c.publicApi,definitionContractCoordinates:e.verified.definitionContractCoordinates,contractCatalog:e.verified.definitionContractCoordinates.operations.find(o=>o.operationId===packet.definitionKey.operationId).members.find(m=>m.memberKey===member).slots.request.contractCatalog,...packet.definitionKey,request,slots,resources:{...resources,admissionAuthority:{basis,authority,grants}},requestRef:`public-request://selected-action/${identity}`,correlationRef:`correlation://selected-action/${identity}`,eventTime:'2026-09-30T00:02:00.000Z',provenanceRefs:[ref('provenance','fixture')]});
 await save(dir,`${identity}-precheck.json`,{slots,authority,grants,ownerEnvironment:{workspaceBinding:env.workspaceBinding,productSet:env.productSet,resolvedProductLock:env.resolvedProductLock},runCoordinates:env.productInstalls.map(i=>({ref:i.installId,digest:i.productContentDigest}))});return call;
}
async function coldOracle(c,e,dir,run,current,scope,prepared){
 const projected=c.replay.projectRunIdentityAtPrefix(prefix(c),run.ref);assert.ok(projected);assert.deepEqual(run,projected.run);assert.deepEqual(projected.executionBasis,coord(e.executionBasis));
 const boundary=c.handoff,reads={},contracts=await c.load('abg/project_read_operation_contracts');
 for(const memberKey of ['run_result','run_replay']){const{call}=constructInstalledRunReadCall({environment:{...e,product:c.product},publicApi:c.publicApi,projectReadContracts:contracts,memberKey,selector:memberKey==='run_result'?{kind:'none'}:{kind:'ordinal_page',fromOrdinal:0,limit:2048},source:run,eventResource:resource(c),identity:`${basename(dir)}-${memberKey}`});const output=await cli(c,dir,memberKey,call);assert.equal(output.receipt.ownerOutput.outcomeKind,'result');assert.deepEqual(c.handoff.prefix,boundary.prefix);reads[memberKey]=output.receipt.ownerOutput.value;}
 const result=reads.run_result,replay=reads.run_replay,r=result.projection,p=replay.projection;
 assert.deepEqual(result.projectionBasis,replay.projectionBasis);assert.equal(result.projectionBasis.digest,boundary.prefix.coordinateDigest);assert.deepEqual(r.subject,run);assert.deepEqual(p.subject,run);assert.deepEqual(r.replay,p.replay);assert.equal(p.status,'closed');assert.deepEqual(r.terminalResult,p.terminalResult);
 const terminal=r.terminalResult;assert.equal(terminal.value.kind,'next_action_projection');assert.equal(terminal.value.disposition,'converged');assert.equal(terminal.value.constructionIntentRef,current.constructionIntentRef);assert.equal(terminal.value.targetOutcomeRef,prepared.intent.targetOutcomeRef);assert.equal(terminal.valueDigest,c.product.sha256Canonical(terminal.value));assert.deepEqual(terminal.producer.executionBasis,coord(e.executionBasis));assert.equal(terminal.producer.invocationAdmissionRef,e.invocationAdmission.invocationAdmissionRef);assert.equal(terminal.producer.runRef,run.ref);assert.equal(terminal.producer.graphCallRef,scope.graphCallId);
 const all=rows(c),local=all.filter(row=>row.runId===run.ref),terminalEvent=local.find(row=>row.eventId===terminal.producer.resultAdmissionEventRef);assert.ok(terminalEvent);assert.deepEqual(terminalEvent.payload.value,terminal.value);assert.deepEqual({ref:terminalEvent.payload.resultRef,digest:terminalEvent.payload.resultDigest},terminal.result);
 const delta=local.find(row=>row.kind==='construction_delta_observed'&&row.payload.constructionIntentRef===current.constructionIntentRef);assert.ok(delta,'current evaluation/delta');
 const evaluation=delta.payload.actionEvaluation;assert.equal(evaluation.edgeClosureDecision.disposition,'close_candidate');assert.equal(evaluation.edgeClosureDecision.decisionRef,terminal.value.edgeClosureDecisionRef);assert.equal(evaluation.observationSnapshot.task.payload,'selected second action');
 const childResults=evaluation.admittedEvidenceRefs.map(r=>local.find(row=>row.kind==='c_call_result_admitted'&&row.payload.resultRef===r));assert.equal(childResults.length,1);assert.deepEqual(childResults[0].payload.value,{kind:'fixture_consumed',schemaVersion:'5.0.0',payload:'selected second action'});
 const opened=local.find(row=>row.kind==='c_call_opened'&&row.payload.cursorRef===current.heldCursorRef);assert.ok(opened);assert.equal(opened.payload.callClass,'workflow');
 const childBases=local.filter(row=>row.kind==='basis_admitted'&&row.payload.basisClass==='child'&&row.payload.parentCCallRef===opened.payload.cCallRef);assert.equal(childBases.length,1);const childBasis=childBases[0];assert.equal(childBasis.payload.parentExecutionBasisRef,e.executionBasis.basisRef);assert.equal(childBasis.payload.invocationAdmissionRef,e.invocationAdmission.invocationAdmissionRef);assert.equal(childBasis.runId,run.ref);assert.deepEqual(childBasis.payload.rawInputValue,prepared.intent.targetInput);assert.equal(childBasis.payload.rawInputDigest,c.product.sha256Canonical(prepared.intent.targetInput));
 const childCalls=local.filter(row=>row.kind==='c_call_opened'&&row.basisId===childBasis.payload.basisRef);assert.equal(childCalls.length,2);assert.deepEqual(childCalls.map(row=>row.payload.programLocusRef),[ref('locus','producer'),ref('locus','consumer')]);for(const call of childCalls){assert.equal(call.runId,run.ref);assert.equal(call.payload.graphFunctionRef,ref('graph-function','child'));}if(Object.hasOwn(prepared.intent.targetInput,'currentAuthorityMarker'))assert.equal(childBasis.payload.rawInputValue.currentAuthorityMarker,e.workspaceBinding.bindingId);
 const refreshed=local.filter(row=>row.kind==='c_call_result_admitted'&&row.payload.value?.kind==='graph_span_selection'&&row.payload.value.state?.evaluation?.constructionIntentRef===current.constructionIntentRef);assert.equal(refreshed.length,1);assert.equal(refreshed[0].payload.value.disposition,'continue');
 const closure=local.find(row=>row.kind==='run_closed');assert.ok(closure);const parent=local.find(row=>row.eventId===closure.payload.graphCallClosedEventRef);assert.equal(parent.kind,'graph_call_closed');assert.equal(parent.graphCallId,scope.graphCallId);assert.equal(occurrences(c,run.ref).find(o=>o.continuationRef===current.continuationRef).status,'resolved');
 await save(dir,'semantic-cold-oracle.json',{status:'passed',boundary:boundary.prefix,run,replay:r.replay,terminalResult:terminal,occurrence:current,workflowOpen:opened.eventId,childInputBasis:childBasis,childCalls,childResults:childResults.map(r=>({eventId:r.eventId,...r.payload})),evaluation,delta:delta.eventId,refresh:refreshed[0].eventId,parentClosure:parent.eventId,runClosure:closure.eventId});
}
async function continueSelected(c,e,sourceOpened,source,currentOpened,current,relation,dir,extraNegatives=[]){
 const sourceIdentity=runIdentity(c,sourceOpened),currentIdentity=runIdentity(c,currentOpened);assert.deepEqual(currentIdentity.executionBasis,coord(e.executionBasis));
 const selectedRequest={run:sourceIdentity.nativeRun,continuation:{ref:source.continuationRef,digest:source.continuationDigest},selectedAction:{ref:current.selectedActionRef,digest:current.selectedActionDigest},basisRelation:relation};
 const use=c.owner.selectPendingActionUse(prefix(c),selectedRequest,coord(e.executionBasis));assert.equal(use.kind,'selected_action_use',JSON.stringify(use));assert.equal(use.current.continuationRef,current.continuationRef);
 const resolve=view=>c.product.ProductExecutionResolutionPort.resolve({catalog:e.catalog,catalogView:view,admittedInstalls:e.admittedInstalls,verifyInstallAdmission:i=>c.abg.hasAdmittedProductInstall(c.abg.projectExactPrefixArtifactTruth(c.handoff.prefix),i),programRef:use.currentBasis.programRef,selection:{kind:'admitted',graphFunctionRef:use.currentBasis.graphFunctionRef}});
 const resolution=await resolve(e.catalogView);assert.equal(resolution.kind,'loaded_product_execution_resolution');const prepared=c.owner.prepareSelectedActionContinuation(prefix(c),use,resolution);assert.ok(prepared);assert.equal(prepared.intent.targetInput.payload,'selected second action');assert.equal(e.invocationAuthority.authorityDigest,use.invocation.authorityDigest);assert.equal(e.policy.policyDigest,use.invocation.policyDigest);
 const added=e.catalog.entries.map(r=>r.handle).find(h=>!e.catalogView.allowlist.includes(h));assert.ok(added);const alternate=c.product.narrowGraphFunctionCatalog(e.catalog,[...e.catalogView.allowlist,added]),alternateResolution=await resolve(alternate);assert.equal(alternateResolution.kind,'loaded_product_execution_resolution');assert.equal(alternateResolution.resolution.programDigest,resolution.resolution.programDigest);assert.equal(alternateResolution.resolution.graphFunctionDigest,resolution.resolution.graphFunctionDigest);assert.notEqual(alternateResolution.programValidation.validationRef,resolution.programValidation.validationRef);assert.equal(c.owner.prepareSelectedActionContinuation(prefix(c),use,alternateResolution),null);
 await save(dir,'prepared-relation.json',{request:selectedRequest,use,root:prepared.root,cursor:prepared.cursor,input:prepared.input,intent:prepared.intent,resolution:resolution.resolution,alternateResolution:alternateResolution.resolution});
 const packet=c.product.RUN_OPERATION_CONTRACTS.continue.selected_action,operationId=packet.definitionKey.operationId,grant=c.product.constructCapabilityGrant(e.policy,e.actorRef,operationId,packet.metadata.capabilityRefs[0],{admittedInstalls:e.admittedInstalls,workspaceBinding:e.workspaceBinding,fixedPacket:packet});
 function makeCall(name,patch={},slotPatch={},view=e.catalogView){
  const er=resource(c),r=resolution.resolution,decl=resolution.declarationPublications.flatMap(p=>p.contracts).find(d=>d.contractRef===prepared.term.inputCarrierRef),steering=c.product.sha256Canonical(er);
  const slots={workspace_binding:{ref:e.workspaceBinding.bindingId,digest:e.workspaceBinding.bindingDigest},product_set:e.admittedInstalls.map(c.product.productInstallCoordinate),dependency_lock:{ref:e.workspaceBinding.lockId,digest:e.workspaceBinding.lockDigest},catalog_scope:{catalog:{ref:`graph-function-catalog://abiogenesis/${e.catalog.basisDigest.slice(7)}`,digest:e.catalog.basisDigest},view:{ref:`graph-function-catalog-view://abiogenesis/${view.viewDigest.slice(7)}`,digest:view.viewDigest},allowlist:view.allowlist},execution_program:{ref:r.programRef,digest:r.programDigest},graph_function:{graphFunction:{ref:r.graphFunctionRef,digest:r.graphFunctionDigest},membership:r.programGraphFunctionMembership},input_contract:{contract:{ref:decl.contractRef,digest:c.product.sha256Canonical(decl)},valueRef:prepared.input.inputRef,valueDigest:prepared.input.inputDigest,value:prepared.input.value},session_policy:{ref:e.policy.policyRef,digest:e.policy.policyDigest},capability_grants:{requiredCapabilityRefs:packet.metadata.capabilityRefs,grants:[{ref:grant.grantRef,digest:grant.grantDigest}]},actor:{actor:{ref:e.actorRef,digest:c.product.sha256Canonical({actorRef:e.actorRef})},attribution:{ref:e.invocationAuthority.authorityRef,digest:e.invocationAuthority.authorityDigest}},transport_steering:{ref:`transport-steering://abiogenesis/${steering.slice(7)}`,digest:steering},verification_references:null,execution_basis:coord(e.executionBasis),...slotPatch};
  return c.publicApi.constructInstalledPublicDefinitionCall({product:c.product,installedPublic:c.publicApi,definitionContractCoordinates:e.verified.definitionContractCoordinates,contractCatalog:e.verified.definitionContractCoordinates.operations.find(o=>o.operationId===operationId).members.find(m=>m.memberKey==='selected_action').slots.request.contractCatalog,operationId,memberKey:'selected_action',request:{...selectedRequest,...patch},slots,resources:{kind:'run_invocation_resource_assertion',schemaVersion:'5.0.0',eventResource:er,catalog:e.catalog,catalogView:view,applications:[],source:{kind:'none'}},requestRef:`public-request://selected-action/${basename(dir)}-${name}`,correlationRef:`correlation://selected-action/${basename(dir)}-${name}`,eventTime:'2026-09-30T00:04:00.000Z',provenanceRefs:[ref('provenance','fixture')]});
 }
 const negatives=[['alternate-view',{}, {},'basis_mismatch','/continuation',alternate],['crossed-basis',{}, {execution_basis:{ref:e.executionBasis.basisRef,digest:'sha256:'+'0'.repeat(64)}},'stale_action','/request'],...extraNegatives];const results=[];
 for(const[name,patch,slots,code,path,view]of negatives){const before=c.handoff.prefix;const out=await cli(c,dir,name,makeCall(name,patch,slots,view));assert.equal(out.receipt.ownerOutput.outcomeKind,'refusal');assert.equal(out.receipt.ownerOutput.value.code,code);assert.deepEqual(out.receipt.ownerOutput.value.issuePaths,[path]);assert.deepEqual(c.handoff.prefix,before,'refusal has no use/admission');results.push({name,wallMs:out.wallMs,...out.receipt.ownerOutput});}
 const output=await cli(c,dir,'continue',makeCall('continue'));assert.equal(output.receipt.ownerOutput.value.disposition,'completed',JSON.stringify(output.receipt.ownerOutput));assert.deepEqual(output.receipt.resources.run,currentIdentity.run);assert.deepEqual(output.receipt.ownerOutput.value.run,currentIdentity.run);await coldOracle(c,e,dir,output.receipt.resources.run,current,currentOpened.scope,prepared);
 const completedBoundary=c.handoff.prefix;for(const[name,patch]of [['duplicate',{}],...(relation.kind==='authority_changed'?[['duplicate-current',{run:currentIdentity.nativeRun,continuation:{ref:current.continuationRef,digest:current.continuationDigest},basisRelation:{kind:'same_basis'}}]]:[])]){const out=await cli(c,dir,name,makeCall(name,patch));assert.equal(out.receipt.ownerOutput.outcomeKind,'refusal');assert.equal(out.receipt.ownerOutput.value.code,'resolved_continuation');assert.deepEqual(c.handoff.prefix,completedBoundary);results.push({name,wallMs:out.wallMs,...out.receipt.ownerOutput});}
 const operations=rows(c).filter(r=>r.kind==='public_operation_admitted'&&r.payload.continuationKind==='selected_action'&&r.payload.currentContinuationRef===current.continuationRef);assert.equal(operations.length,1);await save(dir,'result.json',{status:'passed',results,operation:operations[0],sourceFinal:occurrences(c,source.runId),currentFinal:occurrences(c,current.runId),finalPrefix:c.handoff.prefix});return prepared;
}

function resumedDuplicateCall(c,e,priorCall){
 const eventResource=resource(c),steering=c.product.sha256Canonical(eventResource),invocation=priorCall.invocation;
 const slots={...invocation.invocationAuthority.slots,transport_steering:{ref:`transport-steering://abiogenesis/${steering.slice(7)}`,digest:steering}};
 return c.publicApi.constructInstalledPublicDefinitionCall({product:c.product,installedPublic:c.publicApi,definitionContractCoordinates:e.verified.definitionContractCoordinates,contractCatalog:invocation.contractCatalog,...invocation.definitionKey,request:invocation.request,slots,resources:{...priorCall.resources,eventResource},requestRef:'public-request://selected-action/resumed-same-basis-duplicate',correlationRef:'correlation://selected-action/resumed-same-basis-duplicate',eventTime:'2026-09-30T00:04:00.000Z',provenanceRefs:invocation.provenanceRefs});
}
async function prepareResume(c,e,opened,previous){
 const relation=await read(join(previous,'same-basis/prepared-relation.json')),completed=await read(join(previous,'same-basis/continue-receipt.json')),priorCall=await read(join(previous,'same-basis/continue-call.json'));
 const bytes=await readFile(fileURLToPath(c.handoff.prefix.eventLogRef)),preserved=await readFile(join(proof,'predecessor-328.jsonl')),identity=runIdentity(c,opened),physical=await stat(fileURLToPath(c.handoff.prefix.eventLogRef));
 assert.deepEqual(bytes,preserved);assert.equal(digest(bytes),c.handoff.prefix.prefixDigest);assert.equal(bytes.length,c.handoff.prefix.prefixLength);assert.equal(physical.dev,c.handoff.reopenAuthority.device);assert.equal(physical.ino,c.handoff.reopenAuthority.inode);
 assert.deepEqual(identity.executionBasis,coord(e.executionBasis));assert.deepEqual(priorCall.invocation.request.run,identity.nativeRun);assert.deepEqual(completed.output.receipt.resources.run,identity.run);assert.deepEqual(completed.output.receipt.ownerOutput.value.run,identity.run);assert.equal(completed.output.receipt.ownerOutput.value.disposition,'completed');assert.deepEqual(completed.output.receipt.resources.eventResource.closeHandoff,c.handoff);
 const inventory=await read(join(previous,'archive-installed.json'));assert.equal(digest(await readFile(e.artifactPaths[0])),'sha256:'+inventory.archive.sha256);for(const member of inventory.members)assert.equal(digest(await readFile(join(e.installedRoot,member.path))),'sha256:'+member.sha256,`retained installed member ${member.path}`);
 const duplicate=resumedDuplicateCall(c,e,priorCall);assert.deepEqual(duplicate.invocation.request.run,identity.nativeRun);assert.equal(c.owner.selectPendingActionUse(prefix(c),duplicate.invocation.request,coord(e.executionBasis)).code,'resolved_continuation');
 const contracts=await c.load('abg/project_read_operation_contracts'),prospectiveReads=['run_result','run_replay'].map(memberKey=>constructInstalledRunReadCall({environment:{...e,product:c.product},publicApi:c.publicApi,projectReadContracts:contracts,memberKey,selector:memberKey==='run_result'?{kind:'none'}:{kind:'ordinal_page',fromOrdinal:0,limit:2048},source:identity.run,eventResource:resource(c),identity:`same-basis-${memberKey}`}));
 for(const r of prospectiveReads)assert.deepEqual({ref:r.call.invocation.request.source.sourceRef,digest:r.call.invocation.request.source.sourceDigest},identity.run);
 const current=await acquisition(c,e,e.workspaceBinding),source=await prepareStart(c,current,'prospective-covered-source',fixtureInput,join(proof,'preflight-source'));
 const witness=await c.load('abg/witness_admission_operation'),stopContract=witness.WITNESS_CONTENT_CONTRACTS['run-stopped'];
 const stopRequest={subjectKind:'run',subject:identity.run,act:'run-stopped',content:{kind:'typed_reason',contentContract:{ref:stopContract.ref,digest:stopContract.digest},value:{reasonKind:'operator_stop',reasonDetail:'Prospective Public-coordinate grant correspondence; no stop execution'}},context:{kind:'run',run:identity.run,basis:identity.executionBasis},evidence:[identity.run],provenance:[identity.executionBasis]};assert.deepEqual(stopRequest.context.basis,coord(e.executionBasis));
 const stopCall=await witnessCall(c,current,'run-stopped',stopRequest,'prospective-stop',proof);assert.deepEqual(stopCall.invocation.request,stopRequest);assert.equal(stopCall.resources.admissionAuthority.authority.approval.value.requestDigest,c.product.sha256Canonical(stopRequest));
 await save(proof,'resume-preflight.json',{status:'passed',proofClass:'pure retained owner correspondence; no Public calls or resource acquisition',predecessor:c.handoff,identity,completedReceiptPublicRun:completed.output.receipt.resources.run,continuedRequestNativeRun:priorCall.invocation.request.run,duplicateRequestNativeRun:duplicate.invocation.request.run,coldSources:prospectiveReads.map(r=>r.call.invocation.request.source),witnessCoordinateTemplate:stopRequest,witnessTemplateScope:'coordinate correspondence only; completed Run is not eligible to stop; future prior-current request uses its then-current owner identity',archiveSha256:inventory.archive.sha256,installedMemberCount:inventory.members.length,installedMembersMatch:true,sourceProspectiveInvocation:source.call.invocation.invocationRef});
 return {relation,completed,priorCall,identity};
}
async function finishRetainedSameBasis(c,e,opened,resume,dir){
 await coldOracle(c,e,dir,resume.identity.run,resume.relation.use.current,opened.scope,resume.relation);
 const before=c.handoff.prefix,duplicate=await cli(c,dir,'duplicate',resumedDuplicateCall(c,e,resume.priorCall));assert.equal(duplicate.receipt.ownerOutput.outcomeKind,'refusal');assert.equal(duplicate.receipt.ownerOutput.value.code,'resolved_continuation');assert.deepEqual(c.handoff.prefix,before);
 const operations=rows(c).filter(r=>r.kind==='public_operation_admitted'&&r.payload.continuationKind==='selected_action'&&r.payload.currentContinuationRef===resume.relation.use.current.continuationRef);assert.equal(operations.length,1);
 await save(dir,'result.json',{status:'passed',scope:'missing cold and duplicate proof from09 completed continuation; no repeated continuation or prior negatives',operation:operations[0],duplicate,finalPrefix:c.handoff.prefix});
}

async function preflightObserverAndRecovery(c,e,opened,resumeFrom,recoverFrom){
 const state=await read(join(recoverFrom,'failure-state.json')),selection=(await read(join(recoverFrom,'causal-diagnosis.json'))).safeReentryRoute.selection;
 assert.equal(selection.recoveryCase,'lock_absent');assert.deepEqual(selection.lastCloseHandoff,c.handoff);
 const bytes=await readFile(state.nativePath),frozen=await readFile(join(recoverFrom,'failed-native-prefix.jsonl')),predecessor=await readFile(join(recoverFrom,'predecessor-328.jsonl')),physical=await stat(state.nativePath);
 assert.deepEqual(bytes,frozen);assert.deepEqual(bytes.subarray(0,predecessor.length),predecessor);assert.equal(digest(bytes),selection.expectedCurrent.digest);assert.equal(bytes.length,selection.expectedCurrent.byteLength);assert.equal(physical.dev,c.handoff.reopenAuthority.device);assert.equal(physical.ino,c.handoff.reopenAuthority.inode);assert.equal(digest(predecessor),c.handoff.prefix.prefixDigest);
 const lock=await stat(selection.lockPath).catch(error=>{if(error.code==='ENOENT')return null;throw error;});assert.equal(lock,null);let dead=false;try{process.kill(selection.ownerPid,0);}catch(error){if(error.code!=='ESRCH')throw error;dead=true;}assert.equal(dead,true);
 const actual=c.eventOwner.validateHistoricalEvents(bytes,c.handoff.prefix.storeIdentity.eventContractDigest);assert.equal(actual.length,330);c.abg.selectValidatedRuntimeEventPrefix(actual);
 const retainedBytes=await readFile(join(resumeFrom,'same-basis/interrupted-prefix.jsonl')),retained=c.eventOwner.validateHistoricalEvents(retainedBytes),root=retained.find(row=>row.kind==='basis_admitted'&&row.payload.basisRef===e.executionBasis.basisRef),codec=await c.load('abg/event_body_encoding');assert.ok(root);
 // One explicitly controlled event adds a repeated physical body after a real
 // pending prefix. This is a codec/observer unit assumption, never installed history.
 const {basisRef:_basisRef,basisDigest:_basisDigest,...body}=root.payload,controlledBody={...body,invocationRef:'invocation://selected-action/observer-preflight-only'},basisDigest=c.product.sha256Canonical(controlledBody),basisRef=`execution-basis://abiogenesis/${basisDigest.slice(7)}`;
 const {eventId:_eventId,admissionOrdinal:_ordinal,payloadDigest:_payloadDigest,eventContractDigest:_profile,...candidate}=root;
 const controlled=c.eventOwner.projectRuntimeEventFromValidatedHistory(retained,{...candidate,basisId:basisRef,parentAggregateId:controlledBody.invocationRef,payload:{basisRef,basisDigest,...controlledBody}}),logical=[...retained,controlled],committed=new Map();
 const encoded=logical.map(row=>{const staged=new Map(),line=codec.encodeEventBody(row,committed,staged);for(const[k,v]of staged)committed.set(k,v);return line;}).join(''),physicalInput=Buffer.from(encoded),physicalRows=encoded.trim().split('\n').map(JSON.parse),references=physicalRows.filter(row=>row.kind==='abg_admitted_body_reference_record');assert.ok(references.length>0);assert.equal(references.at(-1).event.admissionOrdinal,logical.length);assert.equal(references.at(-1).admissionOrdinal,undefined);
 const decoded=c.eventOwner.validateHistoricalEvents(physicalInput,c.handoff.prefix.storeIdentity.eventContractDigest);assert.deepEqual(decoded,logical);c.abg.selectValidatedRuntimeEventPrefix(decoded);
 const args={bytes:physicalInput,eventOwner:c.eventOwner,expectedProfileDigest:c.handoff.prefix.storeIdentity.eventContractDigest,call:{invocation:{invocationRef:e.invocationAdmission.publicRequestInvocationRef}},environment:{...e,inputDigest:c.product.sha256Canonical(e.input)},selectionCount:2,abg:c.abg,scopeOwner:c.scopeOwner,truth:c.truth},observed=observePublicSelection(args);assert.ok(observed);assert.equal(observed.invocationAdmission.invocationAdmissionRef,e.invocationAdmission.invocationAdmissionRef);assert.equal(observed.executionBasis.basisRef,e.executionBasis.basisRef);assert.equal(observed.scope.runId,opened.scope.runId);assert.equal(observed.event.eventId,retained.at(-1).eventId);assert.equal(observePublicSelection({...args,call:{invocation:{invocationRef:'invocation://selected-action/not-submitted'}}}),null);
 const nativeError=new Error('controlled native fsync failure');let nativeFailureObserved=false;assert.throws(()=>afterNativeFsync(()=>{throw nativeError;},0,()=>{nativeFailureObserved=true;},()=>{nativeFailureObserved=true;}),error=>error===nativeError);assert.equal(nativeFailureObserved,false);
 let nativeCalls=0,observationFailure;afterNativeFsync(()=>{nativeCalls++;},0,()=>observePublicSelection({...args,bytes:physicalInput.subarray(0,-1)}),error=>{observationFailure={message:error.message,stack:error.stack};});assert.equal(nativeCalls,1);assert.ok(observationFailure);assert.match(observationFailure.message,/incomplete trailing row/);
 await writeFile(join(proof,'controlled-repeated-body.jsonl'),physicalInput);await save(proof,'observer-preflight.json',{status:'passed',proofClass:'controlled additional basis event and storage encoding after actual216 pending prefix; no Product basis admission or installed-history claim',retainedEventCount:retained.length,controlledEvent:controlled,physicalReferenceCount:references.length,physicalReference:references.at(-1),decodedEventCount:decoded.length,correlation:{invocation:e.invocationAdmission.invocationAdmissionRef,basis:e.executionBasis.basisRef,run:opened.scope.runId,selectedEvent:observed.event.eventId},wrongInvocationRefused:true,nativeErrorPropagatesUnchanged:true,observationFailureSeparated:observationFailure});
 await save(proof,'lock-absent-recovery-selection.json',selection);await save(proof,'recovery-precheck.json',{status:'passed',byteLength:bytes.length,digest:digest(bytes),eventCount:actual.length,device:physical.dev,inode:physical.ino,predecessorDigest:digest(predecessor),formerHostDead:dead,lockAbsent:true,lockPath:selection.lockPath,immutablePackageReference:join(resumeFrom,'archive-installed.json')});return selection;
}

test('complete selected-action acquisition, occurrence and cold-proof composition',async()=>{
 const started=performance.now(),resumeFrom=process.env.ABI5_SELECTED_ACTION_RESUME_FROM,recoverFrom=process.env.ABI5_SELECTED_ACTION_RECOVER_FROM,runtimeTmp=join(resumeFrom??proof,'disposable');await mkdir(runtimeTmp,{recursive:true});process.env.TMPDIR=runtimeTmp;let c;
 try {
  if(process.env.ABI5_SELECTED_ACTION_PREFLIGHT==='1'){
   const base=fileURLToPath(new URL('../../../../../.ai-workspace/comments/codex/20260928_FRAMED_GOVERNANCE/s7-pending-consumer-01',import.meta.url));
   const old=await read(join(base,'selected-action-05/current/environment.json')),handoff=await read(join(base,'selected-action-05/latest-handoff.json'));c=await context(old,handoff,runtimeTmp);
   const current=await acquisition(c,old,old.workspaceBinding),events=rows(c),sourceRun=events.find(r=>r.kind==='construction_intent_selected').runId,source=occurrences(c,sourceRun).at(-1),cover=events.find(r=>r.kind==='declaration_reprice_admitted');assert.ok(cover);
   const inputFactory=({program,workspaceBinding})=>({...fixtureInput({program,workspaceBinding}),phase:1,task:{kind:'fixture_task',schemaVersion:'5.0.0',payload:'selected second action',currentAuthorityMarker:workspaceBinding.bindingId},coveredSelectionRefs:[source.continuationRef,cover.payload.witnessedActRef]});
   const first=await prepareStart(c,current,'prospective-current-one',inputFactory,join(proof,'preflight-first'));
   const second=await prepareStart(c,current,'prospective-current-two',freeze(first.environment.input),join(proof,'preflight-second'));assert.deepEqual(first.environment.input,second.environment.input);assert.notEqual(first.call.invocation.invocationRef,second.call.invocation.invocationRef);assert.deepEqual(first.environment.invocationAuthority,second.environment.invocationAuthority);
   const e04=await read(join(base,'selected-action-04/environment.json')),bytes04=await readFile(join(base,'selected-action-04/interrupted-prefix.jsonl')),c04=await context(e04,null,runtimeTmp);
   const observed=observePublicSelection({bytes:bytes04,eventOwner:c04.eventOwner,call:{invocation:{invocationRef:e04.invocationAdmission.publicRequestInvocationRef}},environment:{...e04,inputDigest:c04.product.sha256Canonical(e04.input)},selectionCount:2,abg:c04.abg,scopeOwner:c04.scopeOwner,truth:c04.truth});assert.ok(observed);assert.equal(observed.invocationAdmission.invocationAdmissionRef,e04.invocationAdmission.invocationAdmissionRef);assert.equal(observePublicSelection({bytes:bytes04,eventOwner:c04.eventOwner,call:{invocation:{invocationRef:'invocation://not-submitted'}},environment:e04,selectionCount:2,abg:c04.abg,scopeOwner:c04.scopeOwner,truth:c04.truth}),null);
   await save(proof,'preflight-result.json',{status:'passed',wallMs:performance.now()-started,proofClass:'read-only actual-owner prospective current preparation; retained prefix observer check, not new installed qualification',currentBinding:current.workspaceBinding,catalogDigest:current.catalog.basisDigest,viewDigest:current.catalogView.viewDigest,inputDigest:first.environment.inputDigest,workAuthority:first.environment.invocationAuthority,firstInvocation:first.call.invocation.invocationRef,secondInvocation:second.call.invocation.invocationRef,observerActualInvocation:observed.invocationAdmission.invocationAdmissionRef,priorPrefixUnchanged:c.handoff.prefix});return;
  }
  const sameDir=join(proof,'same-basis');let e,opened;
  if(recoverFrom){
   assert.ok(resumeFrom);e=await read(join(resumeFrom,'same-basis/environment.json'));opened=await read(join(resumeFrom,'same-basis/opened.json'));c=await context(e,await read(join(recoverFrom,'latest-handoff.json')),runtimeTmp);
   const selection=await preflightObserverAndRecovery(c,e,opened,resumeFrom,recoverFrom);if(process.env.ABI5_SELECTED_ACTION_OBSERVER_PREFLIGHT==='1')return;
   const recovered=c.eventOwner.recoverInterruptedEventStore(selection);await save(proof,'lock-absent-recovery.json',recovered);assert.equal(recovered.kind,'recovered',JSON.stringify(recovered));c.handoff=recovered.closeHandoff;await save(proof,'latest-handoff.json',c.handoff);await save(proof,'preserved-same-basis-reference.json',{source:join(recoverFrom,'same-basis/result.json'),disposition:'passed evidence retained; no same-basis effects rerun'});
  }else if(resumeFrom){
   e=await read(join(resumeFrom,'same-basis/environment.json'));opened=await read(join(resumeFrom,'same-basis/opened.json'));c=await context(e,await read(join(resumeFrom,'latest-handoff.json')),runtimeTmp);const resume=await prepareResume(c,e,opened,resumeFrom);
   if(process.env.ABI5_SELECTED_ACTION_RESUME_PREFLIGHT==='1')return;
   await save(proof,'latest-handoff.json',c.handoff);await finishRetainedSameBasis(c,e,opened,resume,sameDir);
  }else{
   for(const key of ['ABI5_WAVE1_FROZEN_ARTIFACT_PATH','ABI5_WAVE1_FROZEN_INSTALL_HOST','ABI5_WAVE1_FROZEN_ARTIFACT_SHA256'])assert.equal(process.env[key],undefined,'fresh repaired core required');
   await runHost(sameDir,runtimeTmp);e=await read(join(sameDir,'environment.json'));c=await context(e,null,runtimeTmp);await recover(c,sameDir,true);
   opened=await read(join(sameDir,'opened.json'));const pending=occurrences(c,opened.scope.runId);assert.deepEqual(pending.map(o=>o.status),['resolved','open']);
   await continueSelected(c,e,opened,pending[1],opened,pending[1],{kind:'same_basis'},sameDir,[['crossed-selection',{selectedAction:{ref:pending[0].selectedActionRef,digest:pending[0].selectedActionDigest}}, {},'stale_action','/request'],['crossed-run',{run:{...runIdentity(c,opened).nativeRun,digest:'sha256:'+'0'.repeat(64)}},{},'basis_mismatch','/request']]);
  }
  if(!recoverFrom)await save(sameDir,'preserved-boundary.json',{handoff:c.handoff,environmentSource:resumeFrom?join(resumeFrom,'same-basis/environment.json'):join(sameDir,'environment.json')});
  // Reuse this exact install/resource; ordinary Public start creates a separate source occurrence.
  const sourceAcquisition=await acquisition(c,e,e.workspaceBinding),sourceCase=await startPending(c,sourceAcquisition,join(proof,'covered-source'),`${basename(proof)}-covered-source`,fixtureInput,2);const source=sourceCase.pending,sourceE=sourceCase.environment,oldOpened=sourceCase.opened;assert.equal(source.status,'open');
  const acquired=c.eventOwner.reopenEventStore(c.handoff.reopenAuthority);assert.ok(acquired.store);const projectionRoot=join(e.scratch,'workspace/.ai-workspace/current-projections');await mkdir(projectionRoot,{recursive:true});
  const candidate=c.product.constructWorkspaceBinding(e.workspaceAuthority,e.productSet,e.lock,{...e.workspaceBinding.roots,projectionRoot});assert.equal(candidate.kind,'workspace_binding_candidate');assert.notEqual(candidate.bindingDigest,e.workspaceBinding.bindingDigest);
  const bindingReceipt=c.abg.admitWorkspaceBinding(acquired.store,candidate,{...publicOperationBasis(c.product,'abg.operation.workspace.bind',candidate.bindingId,candidate.bindingDigest,'invocation://selected-action/current-workspace',e.admittedInstalls.map(i=>i.admissionEventRef)),predecessorPrefix:acquired.prefix},e.workspaceAuthority);assert.equal(bindingReceipt.kind,'artifact_owner_result');c.handoff=acquired.store.projectReopenAuthorityAndClose();await save(proof,'current-binding.json',{candidate,receipt:bindingReceipt,handoff:c.handoff});await save(proof,'latest-handoff.json',c.handoff);
  const current=await acquisition(c,e,bindingReceipt.value),witness=await c.load('abg/witness_admission_operation'),historical=coord(sourceE.executionBasis),before={ref:e.workspaceBinding.bindingId,digest:e.workspaceBinding.bindingDigest},after={ref:current.workspaceBinding.bindingId,digest:current.workspaceBinding.bindingDigest},content=witness.WITNESS_CONTENT_CONTRACTS.reprice;
  const request={subjectKind:'authority_basis',subject:historical,act:'reprice',content:{kind:'typed_payload',contentContract:{ref:content.ref,digest:content.digest},value:{declarationRef:before.ref,beforeDigest:before.digest,afterDigest:after.digest,changeClass:'realization_refactor',owningTicketRef:'ticket://T-287',reason:'Bounded selected-action installed WorkspaceBinding cover'}},context:{kind:'basis',basis:historical},evidence:[before,after],provenance:[historical]};
  const coverCall=await witnessCall(c,current,'reprice',request,'cover',proof),coverReceipt=await cli(c,proof,'cover',coverCall);assert.equal(coverReceipt.receipt.ownerOutput.outcomeKind,'result',JSON.stringify(coverReceipt));const coverEvent=rows(c).filter(r=>r.kind==='declaration_reprice_admitted').at(-1),coveringReprice={ref:coverEvent.payload.witnessedActRef,digest:coverEvent.payload.witnessedActDigest};
  const worksite=await c.load('abg/worksite_revision');assert.deepEqual(worksite.projectWitnessedWorkspaceBindingCover(prefix(c),e.workspaceBinding,current.workspaceBinding,[sourceE.executionBasis]),[coverEvent.eventId]);
  const phaseOne=({program,workspaceBinding})=>({...fixtureInput({program,workspaceBinding}),phase:1,task:{kind:'fixture_task',schemaVersion:'5.0.0',payload:'selected second action',currentAuthorityMarker:workspaceBinding.bindingId},coveredSelectionRefs:[source.continuationRef,coveringReprice.ref]});
  const prior=await startPending(c,current,join(proof,'prior-current'),`${basename(proof)}-prior-current`,phaseOne,1);assert.equal(occurrences(c,source.runId).at(-1).status,'open');const semanticInput=freeze(prior.environment.input);await save(proof,'frozen-current-input.json',semanticInput);
  const stopContract=witness.WITNESS_CONTENT_CONTRACTS['run-stopped'],priorIdentity=runIdentity(c,prior.opened),priorRun=priorIdentity.run,priorBasis=coord(prior.environment.executionBasis),stopRequest={subjectKind:'run',subject:priorRun,act:'run-stopped',content:{kind:'typed_reason',contentContract:{ref:stopContract.ref,digest:stopContract.digest},value:{reasonKind:'operator_stop',reasonDetail:'Retain abandoned equal-semantic selection for exact current-basis discriminator'}},context:{kind:'run',run:priorRun,basis:priorBasis},evidence:[priorRun],provenance:[priorBasis]};
  const stop=await cli(c,proof,'stop-prior-current',await witnessCall(c,current,'run-stopped',stopRequest,'stop-prior-current',proof));assert.equal(stop.receipt.ownerOutput.outcomeKind,'result',JSON.stringify(stop));assert.equal(occurrences(c,priorRun.ref).at(-1).status,'abandoned');assert.equal(rows(c).filter(r=>r.kind==='run_stopped'&&r.runId===priorRun.ref).length,1);
  const fresh=await startPending(c,current,join(proof,'fresh-current'),`${basename(proof)}-fresh-current`,semanticInput,1);assert.deepEqual(fresh.environment.input,prior.environment.input);assert.deepEqual(fresh.environment.catalog,current.catalog);assert.deepEqual(fresh.environment.catalogView,current.catalogView);assert.notEqual(fresh.environment.invocationAdmission.invocationAdmissionRef,prior.environment.invocationAdmission.invocationAdmissionRef);assert.notEqual(fresh.environment.executionBasis.basisRef,prior.environment.executionBasis.basisRef);assert.notEqual(fresh.pending.continuationRef,prior.pending.continuationRef);assert.equal(fresh.pending.selectedActionRef,prior.pending.selectedActionRef);assert.equal(fresh.pending.selectedActionDigest,prior.pending.selectedActionDigest);assert.equal(occurrences(c,source.runId).at(-1).status,'open');assert.equal(occurrences(c,priorRun.ref).at(-1).status,'abandoned');
  await save(proof,'equal-selection-relation.json',{source,coverEvent,prior:{run:priorRun,nativeRun:priorIdentity.nativeRun,basis:priorBasis,occurrence:prior.pending,invocation:prior.environment.invocationAdmission.invocationAdmissionRef,status:'abandoned'},fresh:{...runIdentity(c,fresh.opened),basis:coord(fresh.environment.executionBasis),occurrence:fresh.pending,invocation:fresh.environment.invocationAdmission.invocationAdmissionRef},inputDigest:fresh.environment.inputDigest,prefix:c.handoff.prefix});
  const coveredDir=join(proof,'covered');await mkdir(coveredDir,{recursive:true});const prepared=await continueSelected(c,fresh.environment,oldOpened,source,fresh.opened,fresh.pending,{kind:'authority_changed',coveringReprice},coveredDir,[['missing-cover',{basisRelation:{kind:'authority_changed',coveringReprice:{ref:'witnessed-act://missing',digest:coveringReprice.digest}}},{},'reprice_mismatch','/request'],['stale-cover',{basisRelation:{kind:'authority_changed',coveringReprice:{...coveringReprice,digest:'sha256:'+'0'.repeat(64)}}},{},'reprice_mismatch','/request'],['mismatched-cover',{basisRelation:{kind:'authority_changed',coveringReprice:historical}},{},'reprice_mismatch','/request'],['abandoned-current-basis',{}, {execution_basis:priorBasis},'stale_action','/request']]);
  assert.equal(prepared.intent.targetInput.currentAuthorityMarker,current.workspaceBinding.bindingId);assert.ok(prepared.input.value.lawfulBasisRefs.includes(source.continuationRef));assert.ok(prepared.input.value.lawfulBasisRefs.includes(coveringReprice.ref));assert.equal(occurrences(c,source.runId).at(-1).status,'superseded');assert.equal(occurrences(c,priorRun.ref).at(-1).status,'abandoned');
  const final=rows(c);assert.equal(final.filter(r=>r.kind==='continuation_superseded'&&r.payload.continuationRef===source.continuationRef).length,1);assert.equal(final.filter(r=>r.kind==='run_closed'&&r.runId===source.runId).length,0);
  for(const [run,n] of [[source.runId,1],[priorRun.ref,0],[fresh.opened.scope.runId,1]])for(const name of ['producer','consumer'])assert.equal(final.filter(r=>r.kind==='c_call_fibre_selected'&&r.runId===run&&r.payload.implementationRef===ref('implementation',name)).length,n);
  await save(proof,'composition-result.json',{status:'passed',wallMs:performance.now()-started,finalPrefix:c.handoff.prefix,sameBasisRun:opened.scope.runId,sourceRun:source.runId,priorCurrentRun:priorRun.ref,currentRun:fresh.opened.scope.runId,proofClass:'one exact installed model-free F_D population; supported Public current producer and covered selected-action'});
 }catch(error){await save(proof,'failure.json',{message:error.message,stack:error.stack,wallMs:performance.now()-started,lastKnownHandoff:c?.handoff??null,installedRoot:c?.e.installedRoot??null});throw error;}
});
