import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
import {root,prior,load,semantic,hash,sha256Bytes,input,stage,failed,raw,source,eventsPath,originalBytes,retainedBasis,componentAssembly,assertIdentities} from '../support/t287-predecessor-context.mjs';
const out=process.env.ABI5_PREDECESSOR_PROOF_ROOT;assert.ok(out);fs.mkdirSync(out,{recursive:true});
const report={scope:'pure and native-assembly rederivation only; no new runtime admission or actor',checks:[]};
const record=(name,details)=>{report.checks.push({name,...details});fs.writeFileSync(join(out,'result.json'),JSON.stringify(report,null,2)+'\n');};
test('empty eligibility, exact retained counterexample and unchanged consumer acceptance',async()=>{
  assert.deepEqual(semantic.semanticPredecessorStatementRefs(input),[]);
  assert.equal(semantic.isSemanticAssetCandidate(failed),true);
  assert.equal(semantic.deriveSemanticAsset(input,stage.declarationRef,failed,source('failure')),null);
  for(const link of ['statement://same-response','statement://unknown','statement://historical-only'])assert.equal(semantic.deriveSemanticAsset(input,stage.declarationRef,raw('statement://same-response',[link]),source('author')),null);
  const before=await import(pathToFileURL(join(process.env.ABI5_PREDECESSOR_OLD_PACKAGE_ROOT,'build/code/src/product/semantic_stage.js')).href);
  const good=raw('statement://pure/current');const authored=semantic.deriveSemanticAsset(input,stage.declarationRef,good,source('author'));assert.ok(authored);
  assert.deepEqual(authored,before.deriveSemanticAsset(input,stage.declarationRef,good,source('author')));
  const assessment={kind:'semantic_stage_assessment_candidate',schemaVersion:'5.0.0',criteria:stage.rubric.map(c=>({criterionRef:c.criterionRef,disposition:'indeterminate',explanation:'Structural discriminator only.',sourceQuotes:[],statementRefs:['statement://pure/current']})),pressure:[]};
  assert.ok(semantic.deriveSemanticAssessment(authored,stage.declarationRef,assessment,source('assessor')));
  assert.deepEqual(semantic.deriveSemanticAssessment(authored,stage.declarationRef,assessment,source('assessor')),before.deriveSemanticAssessment(authored,stage.declarationRef,assessment,source('assessor')));
  assert.deepEqual(semantic.semanticWorkerResultSchema('assessor',[]),before.semanticWorkerResultSchema('assessor',[]));
  const schema=structuredClone(semantic.semanticWorkerResultSchema('author',[]));assert.match(schema.properties.statements.items.properties.predecessorStatementRefs.description,/Historical|historical/);delete schema.properties.statements.items.properties.predecessorStatementRefs.description;
  assert.deepEqual(schema,before.semanticWorkerResultSchema('author',[]),'description only; schema acceptance grammar unchanged');
  record('empty and retained failure',{invalidLinks:failed.statements.flatMap(s=>s.predecessorStatementRefs).length,assessorCurrentCandidate:true});
});
test('all active assets remain eligible, not just declared predecessor stages; exact nonempty native rendering',async()=>{
  const gtl=await load('gtl/semantic_stage');
  const second=structuredClone(stage);second.declarationRef+='-second';second.graphFunctionRef+='-second';second.assembly.graphFunctionRef=second.graphFunctionRef;second.predecessorStageRefs=[];
  const third=structuredClone(second);third.declarationRef+='-third';third.graphFunctionRef+='-third';third.assembly.graphFunctionRef=third.graphFunctionRef;third.predecessorStageRefs=[stage.declarationRef];
  const lifecycle=gtl.constructSemanticLifecycleDeclaration({...input.lifecycle,stages:[stage,second,third]});
  let value={...input,lifecycle};
  value=semantic.deriveSemanticAsset(value,stage.declarationRef,raw('statement://pure/first'),source('first'));assert.ok(value);
  const assessment={kind:'semantic_stage_assessment_candidate',schemaVersion:'5.0.0',criteria:stage.rubric.map(c=>({criterionRef:c.criterionRef,disposition:'satisfied',explanation:'Pure fixture only.',sourceQuotes:[],statementRefs:['statement://pure/first']})),pressure:[]};
  value=semantic.deriveSemanticAssessment(value,stage.declarationRef,assessment,source('first-assessor'));assert.ok(value);
  value=semantic.deriveSemanticAsset(value,second.declarationRef,raw('statement://pure/second',['statement://pure/first']),source('second'));assert.ok(value);
  assert.deepEqual(semantic.semanticPredecessorStatementRefs(value),['statement://pure/first','statement://pure/second']);
  const historicalOnly=semantic.deriveSemanticAsset(input,stage.declarationRef,raw('statement://historical-only'),source('historical')).assets[0];
  assert.equal(historicalOnly.candidate.statements[0].statementRef,'statement://historical-only');
  const revisionContext={current:value,historicalContext:[historicalOnly]};
  assert.deepEqual(semantic.semanticPredecessorStatementRefs(revisionContext.current),['statement://pure/first','statement://pure/second'],'retained historical asset is not in active input domain');
  assert.ok(semantic.deriveSemanticAsset(value,third.declarationRef,raw('statement://pure/third',['statement://pure/second']),source('third')),'active asset outside declared predecessorStageRefs stays eligible');
  for(const ref of ['statement://pure/third','statement://unknown','statement://historical-only'])assert.equal(semantic.deriveSemanticAsset(value,third.declarationRef,raw('statement://pure/third',[ref]),source('third')),null);
  const {basis,authenticated}=await retainedBasis();
  const owner={...authenticated,stage:third,lifecycle,role:'author',inputDigest:hash(value),inputRef:'component-only:nonempty'};
  const assembly=await componentAssembly(owner,basis,value);assertIdentities(assembly);
  assert.match(assembly.envelope.sections.role.native,/Eligible predecessor statement refs: \["statement:\/\/pure\/first","statement:\/\/pure\/second"\]/);
  assert.deepEqual(assembly.envelope.sections.predecessors,value.assets);
  assert.deepEqual(assembly.envelope.sections.task.taskData,input.taskData);assert.deepEqual(assembly.envelope.sections.task.rubric,third.rubric);
  record('nonempty component',{lookupAndInputAuthenticationDoubled:true,eligible:semantic.semanticPredecessorStatementRefs(value),historicalOnlyRef:historicalOnly.candidate.statements[0].statementRef,historicalRevisionAdmissionNotExercised:true,promptDigest:assembly.manifest.promptDigest});
});
test('complete actual retained native owner authenticates empty author assembly; deterministic identities and old bytes conserved',async()=>{
  const {basis,authenticated,count}=await retainedBasis();
  const instructions=await load('abg/instruction_assembly');
  const assembly=instructions.evaluateNativeInstructionAssembly(basis,input);assertIdentities(assembly);
  assert.deepEqual(instructions.constructNativeInstructionAssembly(basis,input),assembly);
  const old=await import(pathToFileURL(join(process.env.ABI5_PREDECESSOR_OLD_PACKAGE_ROOT,'build/code/src/abg/instruction_assembly.js')).href);
  const previous=old.constructNativeInstructionAssembly(basis,input);assert.ok(previous);
  assert.deepEqual(assembly.plan,previous.plan);assert.equal(assembly.request.inputDigest,previous.request.inputDigest);
  assert.deepEqual(assembly.envelope.sections.role.stdo,previous.envelope.sections.role.stdo);
  for(const name of ['source','obligations','predecessors','worksite','evidence','task'])assert.deepEqual(assembly.envelope.sections[name],previous.envelope.sections[name],name);
  assert.match(assembly.envelope.sections.role.native,/Eligible predecessor statement refs: \[\]/);
  assert.match(assembly.envelope.sections.role.native,/every predecessorStatementRefs array must be \[\]/);
  assert.match(assembly.envelope.sections.role.native,/Do not reference statements introduced in this response/);
  assert.equal(assembly.envelope.inputDigest,hash(input));assert.equal(authenticated.inputDigest,hash(input));
  assert.notEqual(assembly.envelopeDigest,previous.envelopeDigest);assert.notEqual(assembly.manifestDigest,previous.manifestDigest);assert.notEqual(assembly.manifest.promptDigest,previous.manifest.promptDigest);
  const archived=fs.readFileSync(join(prior,'live-01/run/workspace/archives/fp-42c04b85e5509386-prompt.txt'));
  assert.equal(sha256Bytes(archived),'sha256:61edcb312122f359fa4db706204ba0f40f42157fae76a38d7304962bb7824fd4');
  assert.deepEqual(fs.readFileSync(eventsPath),originalBytes);
  fs.writeFileSync(join(out,'assembly-empty.json'),JSON.stringify(assembly,null,2)+'\n');
  record('actual retained native assembly',{basisDoubles:false,prefixCount:count,planDigest:assembly.planDigest,inputDigest:assembly.request.inputDigest,responseSchemaDigest:assembly.manifest.responseSchemaDigest,envelopeDigest:assembly.envelopeDigest,manifestDigest:assembly.manifestDigest,promptDigest:assembly.manifest.promptDigest,oldArchivesUnchanged:true});
});
