import json,pathlib,hashlib,datetime,collections,base64
root=pathlib.Path(__file__).resolve().parent;p=root/'companion-01';read=lambda f:json.loads(f.read_text());es=read(p/'events.json');times=read(p/'timing.json');execution=read(p/'execution.json');initial=read(p/'input.json');D=lambda s:datetime.datetime.fromisoformat(s.replace('Z','+00:00')).timestamp()*1000
ref=lambda e:None if e is None else {'ordinal':e['admissionOrdinal'],'eventId':e['eventId'],'resultRef':e['payload'].get('resultRef'),'graphFunctionRef':e.get('graphFunctionRef'),'cCallRef':e.get('aggregateId')}
results=[e for e in es if e['kind']=='c_call_result_admitted'];synth=[e for e in results if e['payload']['value'].get('kind')=='framed_synthesis_result'];choices=[e for e in results if e['payload']['value'].get('kind')=='registered_graph_choice'];parents=[e for e in results if e['graphFunctionRef'].endswith('/executive@5') and e['payload']['value'].get('kind')=='governance_work_state'];commands=[e for e in results if e['graphFunctionRef']=='graph-function://abiogenesis/worksite/command-execution@5'];native=[e for e in es if e['kind']=='c_call_opened' and e['graphFunctionRef']=='graph-function://abiogenesis/worksite/native-work@5'];assert not native
rows=[]
for i,e in enumerate(synth):
 value=e['payload']['value'];choice=choices[i];assert choice['payload']['value']['graphFunctionRef']==value['judgment']['nextGraphFunctionRef'];assert choice['payload']['value']['input']['value']['synthesis']['judgment']==value['judgment'];assert value['state']['original']==initial['original'];assert value['basis']['previousResultRef']==(None if i==0 else synth[i-1]['payload']['resultRef'])
 fold=next((r for r in results if r['payload']['value'].get('kind')=='governance_work_state' and r['payload']['value']['observations'] and r['payload']['value']['observations'][-1]['synthesisResultRef']==e['payload']['resultRef']),None)
 binding=next(r for r in es if r['kind']=='actor_transport_binding_admitted' and r['payload']['instructionAssembly']['envelope']['cCallRef']==e['aggregateId'])
 if fold:
  obs=fold['payload']['value']['observations'][-1];child=next(r for r in results if r['payload']['resultRef']==obs['resultRef'] and r['aggregateId']==obs['cCallRef']);parent=next(r for r in parents if r['admissionOrdinal']>fold['admissionOrdinal'])
 else:
  child=next(r for r in results if r['graphFunctionRef']=='graph-function://abiogenesis/worksite/native-work/assessment@5');parent=None
 rows.append({'assembly':ref(binding),'basis':value['basis'],'synthesis':ref(e),'judgment':value['judgment'],'choice':ref(choice),'childResult':ref(child),'childResultClass':child['payload']['resultClass'],'fold':ref(fold),'parentReevaluation':ref(parent)})
for e in parents:
 v=e['payload']['value'];assert v['original']==initial['original'];assert not v['terminal'];assert v['unresolvedSupportRefs']==initial['unresolvedSupportRefs']
actors=[];intervals=[]
for i,a in enumerate(e for e in es if e['kind']=='actor_invocation_started'):
 b=next(e for e in es if e['kind'] in ['actor_invocation_closed','actor_invocation_failed'] and e['aggregateId']==a['aggregateId']);ms=D(b['eventTime'])-D(a['eventTime']);intervals.append((a,b));actors.append({'actor':i+1,'start':ref(a),'end':ref(b),'endKind':b['kind'],'wallMs':ms,'promptBytes':times['native'][i]['promptBytes'],'reportedModels':times['native'][i]['reportedModels']})
outside=[]
for a,b in zip(es,es[1:]):
 if not any(lo['admissionOrdinal']<=a['admissionOrdinal']<hi['admissionOrdinal'] for lo,hi in intervals):outside.append({'wallMs':D(b['eventTime'])-D(a['eventTime']),'fromOrdinal':a['admissionOrdinal'],'fromKind':a['kind'],'toOrdinal':b['admissionOrdinal'],'toKind':b['kind']})
files=read(p/'case-input-files.json');preserved={path:hashlib.sha256((p/'worksite-result'/path).read_bytes()).hexdigest()==row['sha256'] for path,row in files.items()};assert all(preserved.values())
assert len(synth)==2 and len(commands)==1 and not any(e['kind']=='run_closed' for e in es)
observations=[{'result':ref(e),'sourceObservedInput':bool(e['payload']['value']['task'].get('sourceObservedInput')),'observations':[{'exitStatus':r['exitStatus'],'stdout':base64.b64decode(r['stdout']['payload']).decode(),'stderr':base64.b64decode(r['stderr']['payload']).decode()} for r in e['payload']['value']['commandResults']]} for e in commands]
assert all(r['exitStatus']==0 for r in observations[0]['observations']);assert observations[0]['observations'][0]['stdout']=='Hello, world!\n';assert 'pass 2' in observations[0]['observations'][1]['stdout'] and 'fail 0' in observations[0]['observations'][1]['stdout']
report={'status':'Supplied companion failed at UAT provider schema ingress; no native retry or original-case successor','publicDisposition':execution['output']['receipt']['ownerOutput']['value']['disposition'],'run':execution['output']['receipt']['resources']['run'],'terminalResult':None,'runClosed':False,'mapping':rows,'observedCommands':observations,'nativeAuthorCalls':0,'allTenSuppliedFilesUnchanged':preserved,'actors':actors,'failure':{'stderr':next(p.glob('actor-4-*stderr*')).read_text(),'actor':ref(next(e for e in es if e['kind']=='actor_invocation_failed')),'runtimeFailure':ref(next(e for e in es if e['kind']=='runtime_failure_observed'))},'timing':{'setupMs':sum(times['setup']['wallMs'].values()),'executionMs':times['executionMs'],'actorMs':sum(a['wallMs'] for a in actors),'outsideActorMs':times['executionMs']-sum(a['wallMs'] for a in actors),'largestOutsideActorEventGaps':sorted(outside,key=lambda r:r['wallMs'],reverse=True)[:12]},'volumes':{'publicRequestBytes':times['publicRequestBytes'],'readinessBytes':len(json.dumps(read(pathlib.Path(execution['requestPath']))['invocation']['resources']['catalog']['readinessBasis'],separators=(',',':')).encode()),'promptBytes':[a['promptBytes'] for a in actors],'eventCount':len(es),'eventLogBytes':(p/'events.jsonl').stat().st_size,'eventKinds':dict(collections.Counter(e['kind'] for e in es)),'setup':times['setup']['volumes']},'readback':read(p/'readback-exact.json'),'readbackDiagnosis':read(root/'cold-read-environment.json')}
(root/'outcome.json').write_text(json.dumps(report,indent=2)+'\n');print({**report['timing'],'mappingRows':len(rows),'sourceFilesUnchanged':len(preserved)})
