import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
export async function verifySubstitution(c,started,reads,before,after){
 const {state,hash,abg,product}=c,v=started.receipt.ownerOutput.value;
 assert.equal(v.disposition,'completed');assert.equal(v.stop,null);assert.ok(abg.isAbgTypedTerminalResult(v.terminalResult));
 const expected={kind:'hello_world_output',schemaVersion:'5.0.0',message:'Hello World'};
 assert.deepEqual(v.terminalResult.value,expected);assert.equal(v.terminalResult.valueDigest,hash(expected));assert.deepEqual(v.result,v.terminalResult.result);
 const result=reads.run_result.ownerOutput,replay=reads.run_replay.ownerOutput;
 assert.equal(result.outcomeKind,'result');assert.equal(replay.outcomeKind,'result');assert.deepEqual(result.value.source,v.run);assert.deepEqual(replay.value.source,v.run);
 assert.deepEqual(result.value.projection.terminalResult,v.terminalResult);assert.deepEqual(replay.value.projection.terminalResult,v.terminalResult);
 assert.deepEqual(result.value.projection.result,v.result);assert.deepEqual(result.value.projection.replay,v.replay);assert.deepEqual(replay.value.projection.replay,v.replay);assert.equal(replay.value.projection.status,'closed');
 const bytes=await readFile(new URL(after.prefix.eventLogRef));assert.equal(bytes.length,after.prefix.prefixLength);assert.equal(product.sha256Bytes(bytes),after.prefix.prefixDigest);
 assert.equal(product.sha256Bytes(bytes.subarray(0,before.prefix.prefixLength)),before.prefix.prefixDigest);assert.deepEqual(before.prefix.storeIdentity,after.prefix.storeIdentity);
 const delta=bytes.subarray(before.prefix.prefixLength).toString('utf8');assert.ok(delta.endsWith('\n'));const events=delta.trimEnd().split('\n').map(JSON.parse);const all=kind=>events.filter(e=>e.kind===kind);const one=kind=>{const xs=all(kind);assert.equal(xs.length,1,kind);return xs[0];};const byId=id=>{const xs=events.filter(e=>e.eventId===id);assert.equal(xs.length,1,id);return xs[0];};
 const calls=all('c_call_opened'),fibres=all('c_call_fibre_selected'),routes=all('traversal_route_admitted');
 assert.deepEqual(calls.map(e=>e.payload.programLocusRef),['locus://abiogenesis/conformance/hello-graph-edge/normalize@5','locus://abiogenesis/conformance/hello-substitute/normalized-pass@5','locus://abiogenesis/conformance/hello-graph-edge/render@5']);
 assert.equal(fibres.length,3);assert.ok(fibres.every(e=>e.payload.regime==='F_D'));assert.equal(fibres[0].payload.compositionRef,fibres[2].payload.compositionRef);assert.notEqual(fibres[0].payload.compositionRef,fibres[1].payload.compositionRef);assert.equal(new Set(fibres.map(e=>e.payload.compositionRef)).size,2);assert.ok(fibres.every(e=>/^graph-function-application:\/\/abiogenesis\//u.test(e.payload.compositionRef)));
 assert.deepEqual(routes.map(e=>e.payload.routeKind),['advance','advance','terminal']);assert.notEqual(routes[0].payload.targetCursorRef,null);assert.notEqual(routes[1].payload.targetCursorRef,null);assert.equal(routes[2].payload.targetCursorRef,null);
 for(const kind of ['c_call_evidenced','c_call_result_admitted','c_call_judged'])assert.equal(all(kind).length,3,kind);
 const spines=calls.map(call=>{const same=kind=>{const xs=all(kind).filter(e=>e.payload.cCallRef===call.payload.cCallRef);assert.equal(xs.length,1,kind);return xs[0];};const fibre=same('c_call_fibre_selected'),evidence=same('c_call_evidenced'),result=same('c_call_result_admitted'),judgment=same('c_call_judged'),route=same('traversal_route_admitted');assert.equal(evidence.payload.evidenceClass,'deterministic');assert.equal(result.payload.resultClass,'success');assert.equal(judgment.payload.judgment,'advance');assert.ok(fibre.causationEventRefs.includes(call.eventId));assert.ok(evidence.causationEventRefs.includes(fibre.eventId));assert.ok(result.causationEventRefs.includes(evidence.eventId));assert.ok(judgment.causationEventRefs.includes(result.eventId));assert.ok(route.causationEventRefs.includes(judgment.eventId));assert.ok(result.payload.evidenceRefs.includes(evidence.payload.evidenceRef));assert.equal(judgment.payload.resultRef,result.payload.resultRef);assert.equal(judgment.payload.resultDigest,result.payload.resultDigest);assert.equal(route.payload.judgmentRef,judgment.payload.judgmentRef);return {locus:call.payload.programLocusRef,cCallRef:call.payload.cCallRef,eventRefs:[call,fibre,evidence,result,judgment,route].map(e=>e.eventId)};});
 const t=v.terminalResult,p=t.producer;assert.equal(p.runRef,v.run.ref);assert.equal(p.graphCallRef,v.graphCall.ref);assert.deepEqual(p.program,started.call.invocation.request.program);assert.equal(p.graphFunction.ref,'graph-function://abiogenesis/conformance/hello-substitute@5');assert.deepEqual(p.graphFunction,started.call.invocation.invocationAuthority.slots.graph_function.graphFunction);assert.deepEqual(t.projectionBasis,{ref:after.prefix.eventLogRef,digest:after.prefix.coordinateDigest});
 const r=byId(p.resultAdmissionEventRef),j=byId(p.judgmentAdmissionEventRef),route=routes.at(-1);assert.equal(r.kind,'c_call_result_admitted');assert.equal(j.kind,'c_call_judged');assert.equal(r.payload.cCallRef,p.cCallRef);assert.equal(j.payload.cCallRef,p.cCallRef);assert.equal(p.cCallRef,calls.at(-1).payload.cCallRef);assert.deepEqual(t.value,r.payload.value);assert.equal(p.judgmentRef,j.payload.judgmentRef);assert.deepEqual(p.terminalRoute,{ref:route.payload.routeRef,digest:route.payload.routeDigest});
 const opened=one('graph_call_opened'),segment=one('run_segment_opened');assert.equal(opened.payload.graphCallId,p.graphCallRef);assert.equal(opened.payload.graphFunctionDigest,p.graphFunction.digest);assert.equal(segment.payload.runId,p.runRef);assert.equal(segment.payload.programRef,p.program.ref);assert.equal(segment.payload.invocationAdmissionRef,p.invocationAdmissionRef);assert.equal(segment.payload.executionBasisRef,p.executionBasis.ref);assert.equal(segment.payload.executionBasisDigest,p.executionBasis.digest);
 const reached=one('terminal_reached'),frameClosed=one('frame_closed'),graphClosed=one('graph_call_closed'),runClosed=one('run_closed');assert.ok(reached.causationEventRefs.includes(route.eventId));assert.equal(frameClosed.payload.terminalReachedEventRef,reached.eventId);assert.ok(frameClosed.causationEventRefs.includes(reached.eventId));assert.equal(graphClosed.payload.frameClosedEventRef,frameClosed.eventId);assert.ok(graphClosed.causationEventRefs.includes(frameClosed.eventId));assert.equal(runClosed.payload.graphCallClosedEventRef,graphClosed.eventId);assert.ok(runClosed.causationEventRefs.includes(graphClosed.eventId));assert.equal(events.at(-1).eventId,runClosed.eventId);
 assert.ok(events.every(e=>e.runId===null||e.runId===undefined||e.runId===v.run.ref));assert.equal(all('actor_invocation_started').length,0);assert.equal(all('run_stopped').length,0);assert.equal(all('child_foldback_admitted').length,0);assert.ok(!JSON.stringify(events).includes('CompiledCProgramPlan'));assert.ok(!JSON.stringify(events).includes('compiled_execution'));assert.deepEqual(state.closeHandoff.prefix,after.prefix);
 return {status:'passed',oracle:{input:{kind:'hello_world_input',schemaVersion:'5.0.0',subject:'World'},output:expected,loci:calls.map(e=>e.payload.programLocusRef),compositionIdentities:[...new Set(fibres.map(e=>e.payload.compositionRef))],routes:routes.map(e=>e.payload.routeKind)},run:v.run,graphCall:v.graphCall,terminalResult:t,spines,rootEventCount:events.length,eventKinds:events.map(e=>e.kind),before:before.prefix,after:after.prefix,coldReadAgreement:true,coldReadAppends:0,noProbabilisticCalls:true,claim:'One genuine C02 graph substitution case; bounded caller proof, not independent sufficiency or complete S02 qualification.'};
}
