import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),base=join(here,'..'),read=async p=>JSON.parse(await readFile(p,'utf8')),save=(n,v)=>writeFile(join(here,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const setup=await read(join(base,'setup.json')),handoff=await read(join(here,'handoff.json')),timing=await read(join(here,'timing.json')),execution=await read(join(here,'execution.json')),source=await read(join(here,'source-result-basis.json')),input=await read(join(base,'input.json')),effects=await read(join(here,'effects.json')),files=await read(join(base,'input-files.json')),prior=await read(join(base,'first/closed-outcome.json'));
const load=p=>import(pathToFileURL(join(setup.installedRoots[0],'build/code/src',p+'.js')).href),[store,product]=await Promise.all(['abg/event_store','product/index'].map(load));
const all=store.readRuntimeEventsAtDurablePrefix(handoff.prefix),runId=execution.output.receipt.resources.run.ref,events=all.filter(e=>e.runId===runId),results=events.filter(e=>e.kind==='c_call_result_admitted'),assessment=results.findLast(e=>e.graphFunctionRef===product.NATIVE_WORKSPACE_WORK_IDS.assessmentGraphFunctionRef&&e.payload.resultClass==='success'),parents=results.filter(e=>e.graphFunctionRef==='graph-function://default-library-witness/executive@5'&&e.payload.value?.kind==='governance_work_state'),terminal=parents.at(-1),admitted=all.find(e=>e.kind==='invocation_admitted'&&e.payload.sourceResultBasis?.sourceResultRef===source.sourceResultRef);
const ref=e=>e?{ordinal:e.admissionOrdinal,eventRef:e.eventId,resultRef:e.payload.resultRef??null,graphFunctionRef:e.graphFunctionRef??null,cCallRef:e.aggregateId,graphCallId:e.graphCallId,basisId:e.basisId}:null;
assert.ok(admitted&&assessment&&terminal);assert.deepEqual(admitted.payload.sourceResultBasis,source);assert.equal(terminal.payload.value.terminal,true);assert.deepEqual(terminal.payload.value.original,input.original);
const producer=assessment.payload.value.task.assessment.producer;assert.equal(producer.resultRef,prior.measurement[0].event.resultRef);assert.equal(producer.cCallRef,prior.measurement[0].event.cCallRef);assert.equal(producer.actorInvocationRef,prior.measurement[0].actorRef);assert.notEqual(assessment.payload.value.provenance.actorInvocationRef,producer.actorInvocationRef);
for(const [path,v]of Object.entries(files))assert.equal(effects[path].sha256,'sha256:'+v.sha256,path);assert.equal(effects['assessment/consumer-context.md'].sha256,product.sha256Bytes(await readFile(join(base,'consumer-context.md'))));
const reads=await Promise.all(['run_result','run_replay'].map(async member=>{const r=await read(join(here,'read-'+member+'.json'));return {member,outcomeKind:r.output.receipt.ownerOutput.outcomeKind,projection:r.output.receipt.ownerOutput.value.projection};}));
const tools=[];for(const a of timing.actors){const stdout=a.retained.find(r=>r.role==='stdout'&&!r.absent);if(!stdout)continue;for(const line of (await readFile(join(here,stdout.path),'utf8')).trim().split('\n')){let row;try{row=JSON.parse(line);}catch{continue;}for(const c of row.message?.content??[])if(c.type==='tool_use')tools.push({actor:a.actor,id:c.id,name:c.name,input:c.input});}}
await save('observed-tools.json',tools);
const out={runId,oldRunId:source.sourceRunId,ownerOutcome:{outcomeKind:execution.output.receipt.ownerOutput.outcomeKind,disposition:execution.output.receipt.ownerOutput.value.disposition,terminalResult:execution.output.receipt.ownerOutput.value.terminalResult},sourceAdmission:{ordinal:admitted.admissionOrdinal,eventRef:admitted.eventId,invocationAdmissionRef:admitted.payload.invocationAdmissionRef,sourceResultRef:source.sourceResultRef,sourceBasisRef:source.basisRef},synthesisChain:await read(join(here,'synthesis-chain.json')),assessment:{event:ref(assessment),producer,actorRef:assessment.payload.value.provenance.actorInvocationRef,meaning:assessment.payload.value.assessment,summary:assessment.payload.value.summary,gaps:assessment.payload.value.gaps},terminalParent:{event:ref(terminal),terminal:terminal.payload.value.terminal,unresolvedSupportRefs:terminal.payload.value.unresolvedSupportRefs,originalConserved:true},runClosed:events.filter(e=>e.kind==='run_closed').map(ref),currentMeasurements:results.filter(e=>e.graphFunctionRef===product.WORKSITE_COMMAND_EXECUTION_IDS.graphFunctionRef).map(ref),failedResults:results.filter(e=>e.payload.resultClass!=='success').map(ref),reads:reads.map(r=>({member:r.member,outcomeKind:r.outcomeKind,terminalResult:r.projection.terminalResult,replay:r.projection.replay})),timing:{executionMs:timing.executionMs,nativeMs:timing.nativeMs,frameworkMs:timing.frameworkOutsideNativeMs,actors:timing.actors.map(a=>({actor:a.actor,ms:a.nativeIntervalMs,promptBytes:a.promptBytes,models:a.reportedModels,costUsd:a.reportedUsage.reduce((n,x)=>n+(x.totalCostUsd??0),0)})),readback:await read(join(here,'readback-timing.json')),newEventCount:timing.eventCount,totalEventCount:all.length,historyBytes:(await readFile(join(here,'events.jsonl'))).length},effects:{tenOriginalFilesUnchanged:true,onlySuppliedInputNew:true,observedToolNames:tools.map(t=>t.name)},limits:'Same-candidate fresh ordinary source use. Prior Run remains stopped. No restored parent stack, author or C2 repetition, exact current_intent recovery, S6 coverage/requalification or release claim.'};
await save('closed-outcome.json',out);console.log(JSON.stringify({...out,synthesisChain:out.synthesisChain.map(s=>({synthesisOrdinal:s.synthesisOrdinal,synthesisEvent:s.synthesisEvent,choiceEvent:s.choiceEvent,selected:s.judgment.nextGraphFunctionRef,reason:s.judgment.nextReason,subject:s.judgment.subjectEvidenceRef,childEvent:s.childEvent,foldEvent:s.foldEvent,parentEvent:s.parentEvent})),reads:out.reads.map(r=>({member:r.member,outcomeKind:r.outcomeKind}))},null,2));
