import {readFile,writeFile} from "node:fs/promises";
import {pathToFileURL} from "node:url";
import {createHash} from "node:crypto";
const life="/Users/jim/src/apps/abiogenesis/.ai-workspace/comments/codex/20260924_WORKSPACE_RESOURCE_LIFETIME/native-d2-01";
const dir=life+"/bootstrap-preparation-03",read=async name=>JSON.parse(await readFile(dir+"/"+name,"utf8"));
const [prepared,record,transport,launch,basis,savedResolution]=await Promise.all([read("prepared.json"),read("native-prepared.json"),read("live-start.jsonl"),read("intake-start.jsonl"),read("readback-basis.json"),read("execution-resolution.json")]);
const root=prepared.core.packageRoot+"/build/code/src/",load=p=>import(pathToFileURL(root+p).href);
const [{resolveProgramDeclarationClosure},{constructCatalogProgramValidationInput},{validateProgram},{sha256Canonical},{canonicalJson},inv,{RUN_OPERATION_CONTRACTS},{productInstallCoordinate}]=await Promise.all([load("product/declaration_closure.js"),load("product/catalog_operations.js"),load("validator/validation.js"),load("shared/digests.js"),load("shared/canonical_json.js"),load("product/invocation.js"),load("product/run_operation_contracts.js"),load("product/environment.js")]);
const call=transport.invocation,i=call.invocation,r=call.resources,environment=basis.environment;
const exact=(a,b)=>canonicalJson(a)===canonicalJson(b),program=basis.publication.programs.find(p=>p.programRef===i.request.program.ref);
const closure=resolveProgramDeclarationClosure(r.catalog,r.catalogView,program.programRef);
if(closure.kind!=="resolved_program_declaration_closure")throw Error(JSON.stringify(closure));
const validationInput=constructCatalogProgramValidationInput(r.catalog,r.catalogView,closure,program);
const validation=validateProgram(validationInput);
if(validation.kind!=="program_validation")throw Error(JSON.stringify(validation));
const regimes=["F_D","F_P","F_H"].filter(f=>[...validation.executableLeafRows,...validation.interactionLeafRows].some(row=>row.fibre===f));
const policy=inv.constructRootInvocationPolicy(environment.workspaceBinding,program,validation.interactionLeafRows.map(row=>({requirementKey:row.requirementKey,requirementKeyDigest:row.requirementKeyDigest,actorCapabilityRef:row.requirement.actorCapabilityRef})),regimes,r.applications);
const grantBasis={admittedInstalls:environment.productInstalls,workspaceBinding:environment.workspaceBinding,fixedPacket:RUN_OPERATION_CONTRACTS.invoke.start};
const grants=[inv.constructCapabilityGrant(policy,basis.actorRef,"abg.operation.run.invoke",inv.DIRECT_INVOKE_CAPABILITY,grantBasis)];
const selectedCatalogEntry=r.catalogView.entries.find(row=>row.definitionRef===savedResolution.resolution.graphFunctionRef);
const authority=inv.constructInvocationAuthority(basis.actorRef,environment.workspaceBinding,r.catalogView,program.programRef,selectedCatalogEntry,policy,grants,grantBasis);
const file=root+"product/run_invocation_operation.js",source=await readFile(file,"utf8");
const start=source.indexOf("function authorityMatches("),end=source.indexOf("\nexport async function prepareProductRunInvocation",start);
if(start<0||end<0)throw Error("owner predicate boundary absent");
const predicateText=source.slice(start,end);
const authorityMatches=Function("sha256Canonical","exactJson","packet","isRecord","catalogRef","catalogViewRef","return ("+predicateText+");")(sha256Canonical,exact,key=>RUN_OPERATION_CONTRACTS.invoke[key],v=>v!==null&&typeof v==="object"&&!Array.isArray(v),d=>"graph-function-catalog://abiogenesis/"+d.slice(7),d=>"graph-function-catalog-view://abiogenesis/"+d.slice(7));
const resolution={resolution:savedResolution.resolution};
const evaluate=j=>authorityMatches(j,r,resolution,environment.workspaceBinding,environment.productInstalls,policy,grants,authority,r.eventResource);
const changed=structuredClone(i);changed.invocationAuthority.slots.product_set=environment.productInstalls.map(install=>({ref:install.installId,digest:install.productContentDigest}));
const envRef=program.policies["abg.run_environment"],selectedEnv=basis.publication.runEnvironments.find(e=>e.declarationRef===envRef)??basis.publication.runEnvironments.find(e=>e.declarationRef===r.runEnvironmentResources.permission.environmentRef);
const report={kind:"exact_installed_authority_predicate_probe",scope:"Pure retained-data diagnostic; supplied setup facts reused, no runtime admission or history acquisition",installedFile:file,installedFileSha256:createHash("sha256").update(source).digest("hex"),predicateTextSha256:createHash("sha256").update(predicateText).digest("hex"),
 preparedAndActualJsonEqual:exact(launch,transport),recordInputDigestMatches:record.inputDigest===sha256Canonical(i.request.input.value),
 programValidation:{kind:validation.kind,sourceDigest:validation.sourceDigest,equalsClosedResolution:validation.sourceDigest===savedResolution.resolution.programValidationDigest,regimes,executableLeafCount:validation.executableLeafRows.length,probabilisticLeafCount:validation.executableLeafRows.filter(r=>r.fibre==="F_P").length,interactionLeafCount:validation.interactionLeafRows.length},
 authority:{kind:authority.kind,actualPredicate:evaluate(i),onlyProductSetDigestSubstitution:evaluate(changed),changedLocators:i.invocationAuthority.slots.product_set.map((row,index)=>({path:"/invocation/invocation/invocationAuthority/slots/product_set/"+index+"/digest",ref:row.ref,actual:row.digest,expected:environment.productInstalls.find(install=>install.installId===row.ref).productContentDigest,matchesProductInstallCoordinate:exact(row,productInstallCoordinate(environment.productInstalls.find(install=>install.installId===row.ref)))})),policy:{expectedRef:policy.policyRef,expectedDigest:policy.policyDigest,actual:i.invocationAuthority.slots.session_policy},grants:{expected:grants.map(g=>({ref:g.grantRef,digest:g.grantDigest})),actual:i.invocationAuthority.slots.capability_grants.grants,requiredCapabilityRefs:i.invocationAuthority.slots.capability_grants.requiredCapabilityRefs},attribution:{expectedRef:authority.authorityRef,expectedDigest:authority.authorityDigest,actual:i.invocationAuthority.slots.actor.attribution}},
 route:{programRef:program.programRef,programDigestMatches:sha256Canonical(program)===savedResolution.resolution.programDigest,startRows:program.starts,actualTarget:i.request.target,resolvedGraph:savedResolution.resolution.graphFunctionRef,inputContract:i.request.input.contract,sourceKind:r.source.kind,inputKind:i.request.input.value.kind,historicalRunUnchanged:exact(i.request.input.value.sourceRun,prepared.sourceRun),historicalPrefixUnchanged:exact(i.request.input.value.sourcePrefix,prepared.sourcePrefix),historicalPrefixLength:i.request.input.value.sourcePrefix.prefixLength,currentPrefixLength:r.eventResource.closeHandoff.prefix.prefixLength,currentPrefixMatchesPrepared:exact(r.eventResource.closeHandoff,prepared.successorCloseHandoff),lifecycleDigest:sha256Canonical(basis.declaration)},
 environmentPermission:{authorityRefMatches:r.runEnvironmentResources.permission.authorityRef===authority.authorityRef,authorityDigestMatches:r.runEnvironmentResources.permission.authorityDigest===authority.authorityDigest,actorMatches:r.runEnvironmentResources.permission.actorRef===authority.actorRef,programMatches:r.runEnvironmentResources.permission.programRef===program.programRef,environmentRef:selectedEnv?.declarationRef,environmentDigestMatches:sha256Canonical(selectedEnv)===r.runEnvironmentResources.permission.environmentDigest,corpusAccess:selectedEnv?.corpusAccess,dependencyCount:selectedEnv?.dependencies.length,contextCount:selectedEnv?.contexts.length},
 counterexampleLimit:"The substituted object is an in-memory predicate input with intentionally unreminted outer digests, not a repaired Public request or admitted invocation. No candidate or Run was constructed."};
await writeFile(new URL("authority-probe.json",import.meta.url),JSON.stringify(report,null,2)+"\n",{flag:"wx"});console.log(JSON.stringify(report,null,2));
