import assert from 'node:assert/strict';
const keys=x=>Object.keys(x).sort(),sort=xs=>[...xs].sort((a,b)=>a.ref.localeCompare(b.ref)||a.digest.localeCompare(b.digest));
function definitionJoin(call,verified){const k=call.invocation.definitionKey,m=verified.definitionContractCoordinates.operations.find(x=>x.operationId===k.operationId)?.members.find(x=>x.memberKey===k.memberKey);assert.ok(m);assert.deepEqual(call.invocation.requestContract,m.slots.request);assert.deepEqual(call.invocation.contractCatalog,m.slots.request.contractCatalog);}
export async function checkReadCall({product,abg,call,state,verified,run,closed,grants,write,label}){
 definitionJoin(call,verified);const r=call.resources,q=call.invocation.request,slots=call.invocation.invocationAuthority.slots,k=call.invocation.definitionKey.memberKey;assert.ok(['run_result','run_replay'].includes(k));assert.deepEqual(keys(r),['eventResource','kind','schemaVersion']);assert.equal(r.kind,'abg_project_read_resource_assertion');assert.equal(r.schemaVersion,'5.0.0');assert.deepEqual(r.eventResource,{kind:'reopen_abg_event_resource',schemaVersion:'5.0.0',closeHandoff:state.closeHandoff,handoffDigest:product.sha256Canonical(state.closeHandoff)});assert.deepEqual(state.closeHandoff.prefix,closed.prefix);assert.equal(q.caseKey,k);assert.deepEqual(q.source,{sourceKind:'run',sourceRef:run.ref,sourceDigest:run.digest});assert.deepEqual(q.projectionBasis,{projectionBasisRef:closed.prefix.eventLogRef,projectionBasisDigest:closed.prefix.coordinateDigest});assert.deepEqual(q.selector,k==='run_result'?{kind:'none'}:{kind:'ordinal_page',fromOrdinal:0,limit:1000});
 const environment=abg.projectExactPrefixWorkspaceEnvironment(state.closeHandoff.prefix,state.binding);assert.equal(environment.kind,'exact_prefix_workspace_environment');const packet=abg.ABG_PROJECT_READ_CONTRACTS[k],expectedGrants=packet.metadata.capabilityRefs.map(cap=>product.constructCapabilityGrant(environment.workspaceAuthorityBasis,environment.workspaceBinding.authorizedActorRef,packet.definitionKey.operationId,cap,{admittedInstalls:environment.productInstalls,workspaceBinding:environment.workspaceBinding,fixedPacket:packet}));assert.deepEqual(grants,expectedGrants);
 const expected=Object.fromEntries(Object.keys(slots).map(n=>[n,null]));Object.assign(expected,{workspace_binding:{ref:environment.workspaceBinding.bindingId,digest:environment.workspaceBinding.bindingDigest},product_set:environment.productInstalls.map(i=>({ref:i.installId,digest:i.productContentDigest})),dependency_lock:{ref:environment.resolvedProductLock.lockId,digest:environment.resolvedProductLock.lockDigest},capability_grants:{requiredCapabilityRefs:[...packet.metadata.capabilityRefs],grants:expectedGrants.map(g=>({ref:g.grantRef,digest:g.grantDigest}))}});assert.deepEqual(slots,expected);
 await write(label+'-owner-precondition.json',{actualCall:call,currentEnvironment:environment,actualProducedRun:run,expectedGrants,ownerResourceKeys:keys(r),claim:'Actual genuine Run/latest handoff, exact three-key resource, current reader metadata and owner-derived authority; runtime read projection still performed by separate installed CLI'});
}
